label sl_rom:
    scene bg black with fade
    "Who did Naomi romance in {i}Secret Lilies of Prudence Prep{/i}?"
    menu:
        "Blanche":
            $ secret_lilies_romance = "blanche"
        "Veronika":
            $ secret_lilies_romance = "veronika"
        "Izzie":
            $ secret_lilies_romance = "izzie"
        "Randomize":
            $ secret_lilies_romance = renpy.random.choice(['blanche', 'veronika', 'izzie'])
    jump act1

label act1:
    scene bg snowy with fade
    "A warm breath puffs up through my chest and out of my lips, being born into the world as a soft whisp in the frigid February air."
    "I hadn't noticed it before, but a soft flutter of a hand through my straight flaxen blonde hair disturbs the dusting of little white flakes which had begun to collect there."
    C "And now it's snowing too. Wonderful."
    "A frown solidly on my face, I hump the duffle strap more securely over my shoulder as I continue down the long wooded path toward my new academy."
    "I'm already dressed in my new uniform, an admittedly cute but seriously annoying blouse and jumper combo in white and pink."
    "Whether because the size is wrong or because I'm undertaking this long trek while lugging my entire worldly belongings, the white tights clinging to my legs are misfitting on my body."
    C "(Drooping here, bunching there... why can't they just {b}cooperate{/b}?)"
    "I perform an inelegant half jig for a few steps, trying to correct the tights around my legs as I walk."
    "Ultimately I just give up when I sight the stately buildings of Prudence Preparatory Academy and the prominent statue of the Virgin Mary a little futher down the way."
    "Turning about to face the empty lane in the way I had just come, I stop where I stand to fix my tights again, sticking my hands under my skirt up to pinch and dig at the tght fabric to sort it out."
    g1 "Dear me, Vincenza, and the in the sight of the Virgin Mary too."
    g2 "Come now, Vittoria, the Virgin Mary {b}always{/b} watches over us."
    C "(Who is that?)"
    "From behind, unexpectedly, come a pair of voices and a titter of laughter against the quiet of the evening dust of snowfall."
    "Before my mind can process it any further, a sudden weight presses around the back of my neck and upon my shoulders."
    O "The proper young ladies of the academy do such things in the confines of their own rooms."
    "The second girl's voice is close, close enough for me to feel the warmth of her breath on the left side of my face."
    "Flipping my head suddenly to the side, I catch sight of the face of the girl in question. She wears a soft grin upon a graceful pale face, set below sharp but cheerful eyes."
    "From her head falls hair of fine silver across her face, gathering neatly down her back."
    H "Maybe she isn't a proper young lady at all?"
    "A soft touch against the small of my back announces the arrival of the first girl, and it remains as she swoops close across my other side in a flutter of golden curls more toward my front."
    "When my head flips back the other way, I find that this girl shares similar features to the first, her flowing golden tresses notwithstanding."
    "The first thought through my brain is that they must be sisters, with a common foreign accent adding to the similarity."
    C "(What... the hell is happening?)"
    "The golden-haired girl draws close to my face, reaching a hand toward my chin to guide my face in momentary inspection."
    H "A young lady, for sure, but the question of her {b}propriety{/b} remains."
    "So goes my second thought. Frozen in place with confusion, the pair continue on their back and forth with barely an ackowledgement of me besides their hands {b}all over{/b} my body."
    O "You've kept us waiting, Clover. We have a very important meeting to attend."
    "With her right arm still heavy around my shoulders, her left heedlessly picks at the leftmost strap of my jumper skirt, following it slowly all the way up my chest."
    C "...My bus was late. H-Hey, what are you—!"
    "I might have totally forgotten that I had my skirt pulled up to pick at my tights when I suddenly froze in place, but the girl on my right certainly hasn't."
    "The hand of hers which isn't on my small of my back drop from my chin and brushes against the hand I was using to fix my tights, only to go further still, picking up where I had left off."
    H "Oh my, and with your uniform so disarrayed. Please allow me to assist. You want to make a good first impression for your Vertu, is that right?"
    "She pulls at the tights bunching around my knees and slides the palm of her hand up my leg with it, smoothing the thin material across my thighs."
    "My body tingles with the smoothness of her touch, however stiff I am with the shock and confusion of someone acting so out of ordinary convention."
    O "The poor little thing's frozen solid. Can we not keep her just a little longer, Vittoria?"
    "The strap of my jumper is released from the second girl's fingers, but rather than remove them, she goes yet further to lay her hand across my chest."
    "Her fingers tease their tips slowly between the buttons of my blouse, catching just slightly on each as she trails her way up to straighten the pink necktie at the very top."
    H "We were only asked to deliver her room key, Vincenza, and we are late ourselves as you rightly pointed out."
    "The first girl's palm glides well higher than it has any right to up the inside of my thigh, flattening out with the tights out around my hip."
    O "Pity..."
    "Distracted and slowed from logical thought by the strange caresses all over my body, it's only then that I come to the heart of the matter."
    C "W-Wait, room key?"
    "With a soft giggle, the first girl's fingers clip against my stomach where the white tights meet their end, followed by the hard, cold touch of something entirely inhuman against my bare skin."
    C "H-Hyah!"
    "I quiver instinctively against the cold metal wedged between my skin and my tights and break the stupor the mysterious pair of girls had put me in."
    "The heavy duffel strap still slung over my shoulder finally drops off as I shake about trying to fish out the object from inside my tights."
    "I hold the offending item up before my face as I do, finding a plastic id card with my face on it staring back, a metal carabiner attached to it."
    C "Y-You—!"
    "For a moment I am about to let loose on the two girls beside me, only to find that they're no longer clinging to me at all, which makes sense in how easily I was able to retrieve the key."
    "Whipping around, I find them already strolling arm-in-arm back toward the academy."
    H "Le abbiamo sicuramente piegato gli spaghetti."
    O "Certamente."
    "Now that my brain has caught up, I'm half confused and half {b}fuming{/b}. I can feel the heat rising in my cheeks, and the extra puffy breaths of air emerging from my lungs."
    "But rather than chase after them, now a fair distance away, I resign myself to heaving my duffel back over my shoulder and finally read the keycard in my hand."
    C "(Macaron Dormitory, Room 28)"
    scene bg transition with fade
    pause 1.0
    jump vertu

label vertu:
    scene bg black with fade
    C "(That was definitely {b}sexual assault{/b}, right? They didn't, like... {b}stick their fingers in{/b} or anything, but...?)"
    "I find the dormitory easily enough and pass by a number of other girls in similar uniform when I get there."
    "Most look at me curiously, some call out a welcome, and others still try to engage me in friendly conversation."
    "All of them I give a half-hearted smile toward and brush past. Inside I'm still steaming hot with annoyance replaying what those two girls did to me."
    "When I find the door with my number plastered on it, I heave a big sigh to put the earlier frustration out of my mind and shove it open."
    scene bg bedroom with dissolve
    "And when I find another girl sleeping atop one of the pair of beds before me, I blurt out an apology instinctively."
    C "S-Sorry, I—"
    "I catch my words quickly, finding the girl roused neither by the door opening or my apology, and just try to close the door as quietly as I can."
    C "(I almost forgot about the whole... roommate thing.)"
    "It's certainly an adjustment from being an only child and having my own room, but if I keep my space from her it shouldn't be a problem,{b}hopefully{/b}."
    "Having been in such a tizzy thinking about the pair of girls from before, I approach my new roommate cautiously, ready for anything, but she still remains unstirred."
    C "(Just what is she up to...?)"
    "I quickly surmise that she unintentionally fell asleep, lying in uniform crossways atop her bed, in the classic pose one makes when she rests her head for \"just a moment\"."
    "A long, thin paper banner is strung across her, draped loosely between the slim pale fingers of the sleeping figure where she once held it."
    "\"Welcome Clover!\" the banner reads in sparkling glitter lettering, and I realize that she too must have gotten caught up in my late arrival."
    "It's even decorated with all sorts of cute little drawings, and tons of shamrocks."
    C "(Because of my name, of course.)"
    "I've lost count of how many people have picked a clover out of the grass and pointed between it and me with a giggle."
    "For just a second while reading the banner, I feel guilty that I might have suspected her of something terrible, but that feeling quickly passes."
    "The girl herself is sleeping soundly, lying with her head turned aside away my the edge of the bed, but by leaning in further I can see her features clearly."
    C "(Her eyelashes are so long...)"
    "I look twice, just to be sure she isn't wearing mascara, but I detect no trace of it at all."
    "That she's gorgeous is plainly evident. Long chestnut curls stream from her head down her back and side, of which I am most jealous, but it doesn't stop there."
    "Her cheeks are smooth and fair, with high cheek bones and large eyes that complete her charming profile."
    "Further below, her pale pink lips part ever so slightly with the little flickers of a dream in progress playing cross her sleeping features."
    #TODO insert bed creak here
    "The sudden creak of the bed when I shift more weight against it draws me out of my trance, and I realize quickly just how far I'm learned over her face."
    C "(W-What am I {b}doing{/b}?)"
    "Pulling myself quickly away the bed, I turn around again toward my own, but my thoughts are still elsewhere."
    "My mind lingers on the mental images of my roommate's sleeping face longer than I would like, and my chest pounds in my ears as they begin to dissipate from mental view."
    C "(It has to be those girls from earlier. They must have done... {b}something{/b} to me!)"
    rm "Clover?"
    "The words float out airily behind me, soft enough for them to tickle at my ears while my brain steams within my skull."
    "Once it worms its way into the front of my brain, I whip back around just as quickly toward my suddenly very awake roommate and propped up on one arm."
    "More awake than before, anyway. Her long lashes lay heavy over her crisp blue eyes, and a soft pout from being pulled out of her dream remains on her lips."
    C "What do you want?"
    "I just sort of... blurt it out while my brain is still churning, and immediately realize how rude that must sound."
    "Before I can say anything more, I'm caught speechless when she unexpectedly winces with her eyes cast downward and tosses her brunette curls with the back of her hand."
    rm "A better introduction than {b}this{/b}. How silly of me to have fallen asleep..."
    "My heart skips a beat as I watch her suffer my rude greeting after having gone to such lengths to welcome me into the room she lives in."
    "Struggling to find the right balance of apologizing and keeping my distance, I brush a hand through my own fair tresses in a show of casual detachment."
    C "Sorry, I was just surprised to hear you, and I'm super late, and sore from lugging my bag all the way here, and the two crazy girls touched me all over, and..."
    "I surprise even myself by beginning to stumble over my apologies, and by how sharply I am watching her pretty face for any signs of her coming around."
    "Why I care so much about her feelings, I don't know, but I rationalize that it's better to be on her good side than her bad."
    rm "You must be speaking of Vittoria and Vincenza, surely. I must doubly apologize for also being absent when you arrived."
    "The names sound familiar as I think back to the chatter they two had shared while teasing me."
    rm "Oh right, my name is Sibyl!"
    "She stills seems half asleep to me with her her thoughts are coming all at once, but her dopey face is too cheerful and happy to object against."
    C "Umm... happy to meet you, Sibyl. So we're going to be roommates, huh?"
    "It's merely a polite rhetorical question, and I turn about to begun unpacking before I get any more caught up in her delicate facial features."
    "From behind, Sibyl yawns into a reply with no intention to let the conversation drop there."
    S "Not merely roommates to one another, but {b}partners{/b}. Didn't you read about the Vertu system in the pamphlet?"
    show choice_darkness with dissolve
    menu:
        "\"Oh, right, the pamphlet... I think that's stuffed in here somewhere.\"":
            hide choice_darkness with dissolve
            C "Oh, right, the pamphlet... I think that's stuffed in here somewhere."
            "I hazard a glance back toward Sibyl, who doesn't look mad at my casual dismissal of school procedure as much as she does dissapointed."
        "\"That's French, umm, green, right?\"":
            hide choice_darkness with dissolve
            C "That's French, umm, green, right?"
            "From somewhere behind me there's a soft sigh."
            S "We're going to have to catch you up on your French skills, and quick."
            "I'm starting to really think I should have looked more closely at the pamphlet now."
        "\"My life's been pretty well shaken up and turned upside down lately, so no.\"":
            hide choice_darkness with dissolve
            C "My life's been pretty well shaken up and turned upside down lately, so no."
            S "I am so sorry, Clover."
            C "Yeah, well, it's not you who needs to apologize."
            "My tone comes out pretty dark, and Sibyl apparently chooses not to pry into it any further."
    "Correctly surmising that I had discarded the boring school literature at first glance, she launches her own explanation."
    S "Vertu partners are like... having an older sister to help you, and being the older sister as well."
    S "More than simply sharing this room, we are meant to share our triumphs with each other, and split the burden of our tribulations."
    C "That's pretty poetic sounding, huh?"
    "Honestly, I couldn't care less about any of that flowery language, and it probably shows in my flat tone of voice."
    C "(We share a room. We're roommates.)"
    "But it feels like Sibyl definitely cares, even though she holds off on lecturing me any further about it while I unpack my duffel."
    S "Do you need some help unpacking?"
    "Even though she's on the other side of the room, it still {b}feels{/b} like she's hovering around me."
    C "No."
    S "I admit to having been a little envious of my peers who all have Vertu partners."
    C "(And there she goes again.)"
    "Not to be deterred by my short reply, Sibyl continues on without my half of the conversation to keep it going."
    S "By chance I was the odd one out in our year and received no Vertu, that is, until we heard you were transferring in."
    "She keeps saying \"Vertu\" with a strangely serious tone like it is some hallowed institution akin to marriage."
    C "(Like I'd ever marry a woman!)"
    "Just thinking about it brings the pair from earlier to mind, and I can already feel my brain churning inside my skull."
    C "You mentioned those two girls before... what were their names?"
    S "Vittoria and Vincenza? They have kind of a... {b}reputation{/b} here, so to speak, but they don't usually cross too far over the line."
    "I try to commit the names to memory because I know for sure I'll be lying awake tonight replaying the scene over in my head, thinking up all sorts of awesome comebacks to use next time I run into them."
    C "Y-Yeah, I'm fine, but I still haven't decided whether I'm pressing charges or not."
    "Sibyl laughs lightly at what I say half under my breath, but finding me not laughing along with her, quiets off quickly."
    S "If they really bothered you, I can come with you to speak with them. For all their quirks, they're not such bad girls and very understanding."
    C "I don't need you to help me."
    S "I'm your {b}Vertu{/b} partner, Clover, and this is what Vertu partners do. We look out for each other."
    C "Thank you, Sibyl, but I don't need your help."
    "The room goes quiet between us as soon as I saw the words with a cold tone of annoyance rising clearly in my voice as I speak the words."
    "I continue folding the clothes I take out of my luggage while turned away from Sibyl behind me. I consider apologizing to her that instant, but decide against it."
    C "(That's honestly how I feel, and it's better that she doesn't get too attached to me anyway.)"
    S "Did I come on too strong? I know you only {b}just{/b} got here, but I have been so excited to finally meet you."
    "I can practically {b}feel{/b} the disappointment in her voice, and it's making me feel like the absolute worst person alive."
    C "Sibyl—"
    "Turning around to face Sibyl, I'm surprised that I don't find her in tears, or even with a frown on her face."
    "Instead, I find an expression of utmost seriousness on her features, like my cold demeanor is her fault for which she needs to atone."
    C "Sibyl, I'm sorry, you've been super nice and everything, really, and I didn't mean to shut you down like that."
    C "I've just been going through some personal things, and I need some space right now, okay?"
    "She smiles up hopefully to me from where she sits on her bed, her blue eyes meeting my own and lingering in the connected gaze."
    C "(She's so much cuter when she's smiling.)"
    "Tearing my gaze away finally, and swallowing my pride somewhat, throw her a bone."
    C "But I will be counting on you to show me around campus and classes, and stuff like where to find the cafteria and all that."
    S "Oh no, the cafeteria!"
    "The sudden change in mood startles me just as quickly."
    C "W-What wrong with it?"
    S "It's closed!"
    C "For how long?!"
    "Sibyl's chestnut curls sway and she turns her head aside toward a nearby alarm clock."
    S "Until tomorrow morning."
    "Relief washes over me, having thought for a moment there that I'd be starving due to a permanently closed cafeteria in addition to everything else here."
    S "I must have snoozed right through mealtime, and you must be famished too!"
    C "Well... kinda..."
    "As much as I might be thinking that I didn't want to rely on Sibyl any more than I need to, the sudden recognition of the emptiness in my stomach draws a meek acceptance."
    C "Are there, like, vending machines that we can use?"
    S "I'm afraid not... but, ah, let's go speak to Miss Woolsey, she will be able to sneak us into the cafeteria, I think."
    "Not that I am in any way unwilling to go scavenge in the academy's kitchens, but I {b}do{/b} fear drawing the wrath of some mean old teacher within hours of my arrival."
    C "I'll be fine until the morning, I promise. Don't need to go wake a teacher."
    S "Nonsense! She's our dorm mother, this is exactly what she's here for!"
    C "But won't she be mad?"
    S "Miss Woolsey? No way, she's super easygoing, I promise. She's our athletics teacher, you know."
    "I want to refuse again, but a sudden rumbling in my stomach makes it terribly difficult to turn down Sibyl's insistent plans now."
    jump woolsey_intro

scene woolsey_intro:
    scene bg black with fade
    scene bg dormitory with dissolve
    "We find Miss Woolsey's door quickly enough. As it turns out, Sibyl only has to lead me to the end of the floor to find her room."
    "She knocks, but we receive no answer."
    S "Hmmm."
    "I wait patiently beside Sibyl, observing the confused thoughts play through her head as they are shown upon her profile."
    S "She's usually here by this time."
    "It's only when she turns her head to speak back in my direction that I realize how much I've been staring and stumble to quickly reply."
    C "Maybe she's gone out? We should just go back to our room."
    S "Some people get cranky when they're hungry, Clover."
    "I can only imagine this ambiguously worded statement is directed at my earlier performance, and shut myself up as the guilty party here while I think of another way out of this."
    who "Sorry girls, I had an important meeting."
    "At the sound of another arrival behind us, I know my doom is fully sealed and that there's no escape."
    "The woman who comes up behind us I find to look like the textbook definition of a high school gym teacher, down to the ponytail, sneakers, and athletic zip-up hoodie."
    "When her eyes turn from Sibyl toward me, they light up with recognition."
    who "You must be Clover! I'm Miss Woolsey, your athletics instructor!"
    mw "I'm so sorry I couldn't meet you at the gate; time was running short and I had to make this meeting."
    "With some obvious emabrassment, Sibyl chimes in beside me."
    S "I, umm, missed her arrival too. I couldn't sleep at all last night and it caught up with me this afternoon."
    mw "Good thing I asked the royal twins to take my place in delivering the keys."
    mw "I'm sorry that things got so mixed up with your arrival, Clover, but I'm glad you found your way despite that."
    "Our dorm mother isn't as bad as old and crotchety as in the image my mind conjured up, it would seem."
    "In fact, she looks to be rather young, probably barely out of college, and altogether quite pleasant."
    C "(Wait, what did she say? So it was her who sicced those two perverts on me, and they're {b}royalty{/b}?)"
    "Perhaps my consternation may be showing on my face, because the teacher quickly hurries to the heart of the matter when she look back to me."
    mw "How are you settling in, Clover? Was there something you needed to speak with me about?"
    "Before I can shut down Miss Woolsey's good natured assitance, Sibyl jumps in ahead of me."
    S "Well actually... we both entirely missed dinner."
    mw "Is that all? C'mon, let's go raid the kitchen and see what we can find; I'm starving too."
    scene bg black with fade
    scene bg kitchen with dissolve
    "The cooks all seemed to have long ago left for the day when we arrive, but Sibyl and Miss Woolsey manage to scrounge up some peanut butter and jelly for sandwiches."
    "It might not be much of a meal, but I have to admit to myself that it does lighten my mood as well as satisfy my rumbling stomach."
    "The two others accompanying me chat amongst themselves mostly as I try to hang back, but once we're sitting down with sandwiches in hand, it's hard to keep their interest off me for long."
    mw "It is fortunate that you arrived when you did, Clover."
    mw "All the students just came back from their winter breaks so you'll be able to more or less just jump right in as we're picking up steam again!"
    S "But you missed the masquerade ball, which is a pity. It was a lot of fun."
    C "(Masquerade ball? I'm actually thankful I missed {b}that{/b}.)"
    "That I've been staring at the sandwich I'm taking small bites out of should have indicated I don't particuarly care to talk, but it seems these two won't allow that."
    C "Oh yeah?"
    "My reply starts out incredibly half-hearted and disinterested, so I try to raise my enthusiasm just a little to not leave them too dissapointed."
    C "I'm sure I will enjoy studying here, for as long as I stay."
    C "(Oops, didn't meant to say that last part!)"
    mw "I know it must be difficult to transfer in after half the year has already passed, but you'll have your Vertu, Sibyl, by your side every step of the way."
    "The teacher, Miss Woolsey, picks up on my little faux pas easily enough."
    C "(Smarter than the average gym teacher, eh?)"
    "Sibyl nods seriously at what the teacher says, giving me an encouraging smile which only make me look away out of instinct."
    C "That's what Sibyl was telling me."
    "Returning my attention to my sandwich with a chill dismissal, I try to ignore the look that passes between Sibyl and my new teacher."
    mw "Say, if you don't mind me asking, why did you choose to Prudence Prep?"
    C "I didn't {b}choose{/b} to be here. My parents {b}sent{/b} me here."
    C "(Like a loose button that you can't find the sweater it belongs to. Just tossed in a drawer for safekeeping while you go about your life.)"
    "Miss Woolsey, while friendly, is being awfully persistent at trying to get me to open up when I have no intention of doing so, and the annoyance leads me to say more than I wanted to aloud."
    "The room couldn't be getting any chillier if we had left the refrigerator door open."
    "I know I'm acting really terrible, but I have a rightful reason to be this touchy about the subject."
    C "(And it's not like either of them really cares about me anyway.)"
    "It's the teacher's {b}job{/b} to look after me just as much as it is Sibyl's responsibility to be my \"Vertu\"."
    "There's a long silence after I speak where Miss Woolsey's gears are clearly spinning in her head trying to formulate a response to my brusque reply."
    S "Clover, I'm so sorry..."
    "To my surprise, Sibyl reaches without hesitation to lay her hand on my arm and offer her condolences."
    "The soft touch from Sibyl carries a comforting warmth which shocks me for a brief moment. A multitude of emotions swirl through me, from fear to confusion, and anger."
    "I pull away suddenly from her touch reflexively, an action which clearly hurts Sibyl's feelings."
    mw "W-Well... I've long felt like the people here at the academy are a second family to me. So if you ever need anything you can—"
    C "I don't need a second family, I already {b}have{/b} one!"
    "I don't know why I am suddenly feeling this way, but the rush of emotion from the way Sibyl touched me draws you another verbal jab which I cannot take back."
    "It's shockingly ineffective on Sibyl, who only follows my outburst with a look of pity and understanding."
    S "Oh, is that what this is? I understand, Clover..."
    "It's unnerving, to see this strange reaction to me being so cold to her, and it just makes my stomach turn every time I look at Sibyl's consoling smile."
    C "(What could she possibly {b}understand{/b} about any of this? She doesn't even {b}know{/b} me!)"
    "Sibyl might have the expression of clear comprehension on her face, but my athletics teacher is still troubled by everything that's happening."
    mw "I shouldn't have pried into your personal life, Clover, I'm sorry."
    "Surprisingly, she seems mostly down about her own failings than being angry at my rude outbursts."
    C "I-It's fine..."
    "Awkwardly, I try to cool down and smooth things over with the teacher despite Sibyl's strangely calm attitude still being foremost in the jumble of my mind."
    mw "If there's anything you don't feel comfortable talking about with Sibyl, you can always call on me too."
    C "T-Thanks..."
    "I feel like an amoeba under a microscope by the way Sibyl keeps looking at me sympathetically and how Miss Woolsey is thinking through our interaction."
    "Awkwardness permeates the air around me and I just try to focus on finishing my peanut butter and jelly sandwich without thinking about the other two women fretting over my existence."
    C "(When will this day just {b}end{/b}?)"
    scene bg black with fade
    scene bg dormitory with dissolve
    "Finally, we make our way back to the dorms, say good night to the teacher, and get back to our own room."
    "There's a notable difference in the way Sibyl acts toward me now, just a few hours after meeting."
    "She barely demands my attention or says any words beyond what is required. She merely goes about her routine for the night as do I mine."
    C "(What gives? First she wants to be all buddy-buddy and now she's acting all aloof? )"
    "It's kind of infurating actually, that I don't know what she's getting at, and I find myself keep looking back at her as I make my bed and finish my nightly preparations."
    "I keep right on watching her until she starts stripping out of her uniform right in front of me, from which I suddenly jerk my head away fast enough to break my neck."
    C "(Is this normal for roommates?)"
    "Logically, there's nowhere else to change into my sleepwear, so I suffer through the self-consciousness and follow suit."
    S "Good night, Clover."
    "I startle slightly at the suddenly rare sound of her voice floating my direction, and stammer out a short but polite reply of my own."
    "I try my best to brush the half naked form of Sibyl undressing out of my mind as I clamber into my bed for the night."
    "What replaces it is the recollection of what those two girls did to me that late afternoon."
    scene bg black with dissolve
    "Much to my displeasure, I do not manage to come up with any awesome comebacks before I drift off to a restless sleep which fades in an out of the real world around me."
    "At times I'm there sleeping in my dormitory bed, listening to the quiet breathing from the next bed over."
    "Other times I'm trudging down the long tree-lined road to the academy where those two girls, the \"royal twins\", circle around me like vultures with shining gold crowns."
    "Just once, I dream vividly of what those vultures did to me out by the gates. But this time, they're both replaced by my strange new roommate, Sibyl."
    "Her silky chestnut curls flutter around me from either side as she and her double sweep their hands across my body in smooth, sensuous motions."
    "In another dreamlike moment, one of the Sibyls stands before me, her blue eyes boring deep into mine, and wearing little but what she had on under the uniform when she was changing."
    "The phantom Sibyl says nothing, merely giving me that infuriatingly knowing smile she made before."
    "All the while, the sensation of her hands continues to rise up my leg, creeping under my skirt, flattening out my tights, and yet more... daring higher until—"
    C "Hahn!"
    "Awaking with a start, the piercing blue eyes linger to haunt my vision with the fading dream, replaced quickly with the dark of the ceiling above my bed."
    C "(What... is wrong with me?)"
    jump shower_time

label shower_time:
    scene bg black with fade
    scene bg bedroom with dissolve
    "When morning comes I am anything but well rested."
    "More than anything else, I desire to remain laying in my bed pretending to be safely back in my own bed in my own room at my own house with all being well in the world."
    "Yet still, I know it will not be true not matter how much I wish for it."
    C "(When will I get to go back? Will everything be different from now on?)"
    "At some point in the early morning my restless fits of sleep must have caught up to me, because I have no recollection of the dawn coming."
    "Now I'm there, sitting up in my bed, daylight streaming through the open windows, and the big lump of my roommate conspicuously absent from the adjacent bed."
    "As if to answer the question which had yet to form, Sibyl emerges at that very moment from the bathroom, fully dressed in her uniform and pulling a brush through her hair."
    S "Good morning, Clover. The cafeteria is already open and homeroom is at eight, so you'd better hurry up."
    C "Dun wanna."
    "I squirm around under my soft covers, snuggling the sheets tighter around me in protest and shutting my eyes tightly."
    C "(So what if I skip class. What are they gonna do, send me back home? That's what I want anyway.)"
    S "If you don't get up you're going to miss breakfast."
    C "What happened to the girl who went all cold and distant on me last night? Can I have her back?"
    S "I'm the same girl as last night, Clover."
    "Sibyl responds to me in a soft, chiding voice, like I'm some kind of petulant child that she needs to instruct properly."
    S "I know very well how you're feeling, and as such I am giving you space to come to terms with your new lifestyle while also providing structure in your life."
    C "(This girl's nuts. Now I know why she didn't have a roommate before me.)"
    C "W-What the hell does that mean?"
    C "(Why does she think I need anything at all, let alone support? I'm doing just fine by myself, aren't I?)"
    S "I means that I am going to give you all the time you need to accept your current circumstances, but also ensure that you are not worsening them."
    S "So please, get up and get ready for class."
    C "No."
    "All at once a wave of cool air washes over me as the topmost layers of my bed are whipped clear off the top of me."
    C "Noooooooo...!"
    "I writhe about in my un-made bed against the chill air assaulting me, knowing full well how childish and petulant I must look in that moment."
    "Defeated, I slump off the edge, wiping my eyes, and make for the shower where I stand half asleep with the water beating down on my face."
    C "Stupid Sibyl... what does she know about how I feel?"
    "She knows nothing about my parents' bitter divorce, or how they dumped me out here all alone while they \"figure things out\"."
    C "(Aren't divorced parents supposed to be, like, spoiling their only child rotten?)"
    "It's like the only thing they agree on is abandoning me all alone in this flowery garbage dump with only a cutesy uniform and a duffel bag of personal items to my name."
    "Blindly fumbling for my shampoo as water streaks down my cheeks, I find the bottle, squeeze it, and immediately freeze up."
    "Flashes of Sibyl's sleeping face from the moment I met her fill my mind's eye alongside the newly familiar scent, and I reflexively toss the shampoo bottle back down in a hurry."
    "It takes a flurry of head shaking to banish the images from my mind."
    jump breakfast
    
label breakfast:
    scene bg black with fade
    scene bg cafeteria with dissolve
    "Reluctantly, but with a mind to how fast the previous night's peanut butter and jelly sandwich has sated me, I make my way to the cafeteria alongside Sibyl."
    "I don't breathe a word of it to her, but I actually do feel considerably less cranky and more awake after getting proper food in my stomach."
    "In fact, I gobbled my breakfast down way too quickly. With Sibyl seemingly distracted with something of her own, I'm left with nothing to do but people watch."
    C "(So all of these girls are going to be my classmates, huh?)"
    "Easily half, if not more, seem to be pretty well-to-do types, no doubt bred from \"elite\" families. It's evident simply in their mannerisms and how they hold themselves."
    "The rest, I find, appear normal enough. What's most odd is how everyone seems bright and cheery, like they actually {b}want{/b} to be stuck in this stupid boarding school."
    C ("I wish I had my smartphone to dull this cloying boredom.")
    "Sibyl was adamant that I leave it behind. Apparently it's some kind of school rule that everyone actually seems to follow for some reason."
    C "(Everyone here's just so... {b}proper{/b}. I can only imagine how snobbish the student council must be.)"
    "What's more, I find that students arrive in pairs. At first it's an obvious conclusion that they are arriving with their roommate, like I did."
    "But I also notice how close a few of these pairs seem to be, often holding hands, and generally being exceptionally chummy."
    C "(Is this what Sibyl wants to be like with me? Is this what it means to be a, what's it called, {b}Vertu{/b} parter?)"
    "And then I see one of the pairs... kiss."
    "Not on the lips, but {b}very{/b} affectionately on the cheek. The intense eye contact alone between the pair reveals every intent behind the gesture."
    C "Oh my God, they kissed..."
    "My thoughts leak out in a soft expression of surprise, bringing Sibyl back to the present from where she was peering toward the doorway."
    S "What as that, Clover?"
    C "A kiss."
    S "What?"
    C "Lesbians, they're gay, Sibyl!"
    "Sibyl gives me a slightly puzzled expression right back, which I probably deserve after my nonsensical outburst."
    S "Oh you mean...?"
    "Sibyl glances toward where I'm gaping with a stealthy motion to make it look like she's not obviously looking their way."
    "She doesn't seem surprised at all, and I don't really know why I am either, considering I have nothing against lesbians, despite not being one myself."
    S "When I first decided I wanted to come here, one of my older sisters stated with such horror, \"A {b}girls'{/b} school? With no {b}boys{/b}?\"."
    S "I've only been here half a year but, yeah, I get what she means now. I guess it's just more common at an all girls school."
    C "Uh huh...?"
    "My eyes stay fixed on the pair of girls who had kissed, watching them now enjoy their breakfast long past what might be considered merely rude."
    "I shift my gaze back to Sibyl, but feeling suddenly awkward watching her, turn my attention instead toward some unexceptional, empty section of the dining hall."
    S "And it's not just the students; our art teacher is a lesbian too. I'd say it's an open secret but it's barely a secret at all."
    C "What do you mean?"
    "For a moment Sibyl is quiet, no doubt trying to find the correct way to answer my question. Her gaze turns upward like she's recalling something, and her reply begins slowly."
    S "When we did a nude study in the art club she was practically drooling the entire time."
    C "That's, uhh, kinda weird. You're in the art club?"
    S "Why is me being in the art club strange to you, Clover?"
    show choice_darkness with dissolve
    menu:
        "\"I meant that the teacher is weird. I was just surprised that you're in the art club.\"":
            hide choice_darkness with dissolve
            C "I meant that the teacher is weird. I was just surprised that you're in the art club."
            "I feel like there's a subtle hint of annoyance in the way she replies, and I find myself oddly quick to alleviate her condition."
            C "And I guess you did make that big banner for me and everything."
            "Sibyl turns away from a glance toward the doorway to give me a bright, genuine smile."
            S "So you did enjoy the banner! If only I weren't asleep and could have displayed it properly."
            "Sudden bashfulness overtakes me as she radiantly smiles upon me, no doubt showing as a blush which I feel as a soft heat on my cheeks."
            "I find it best just to cooly change the subject altogether."
        "\"I thought it'd be the, uh... nagging club, I don't know.\"":
            hide choice_darkness with dissolve
            C "I thought it'd be the, uh... nagging club, I don't know."
            "I fall back into the usual disinterested routine, having no idea why I ever really cared what club she was in to begin with."
            S "Contrary to what you might think, I had my own life long before you came into it yesterday."
            "Sibyl, rather than jab back, seemingly chooses to politely shut me down, and I lose the one thing keeping me entertained just as easily."
    C "What do you keep looking for anyway?"
    "It's not like I want to keep talking to Sibyl or anything, but she's my only entertainment, and her attention keeps getting drawn away toward the door."
    S "My friend from the art club. She's late, and the breakfast period is almost over."
    C "So you have friends, huh?"
    "As if one cue, Sibyl starts up suddenly from her seat at the moment a particular girl walks through the doorway solo, flagging her down to our location with a wave of her arm."
    C "(Alone, huh? Maybe I can get her to take Sibyl as her Vertu instead of me.)"
    st "Sibyl! I'm so sorry, {b}Sierra{/b} held me up again."
    "It's clear from the way she speaks and the lightly disdainful flip of her sleek black hair that there's some bad blood between this girl and the other \"Sierra\" girl."
    C "First day back from vacation and you're {b}already{/b} on the outs?"
    "Before any more is said, Sibyl rises from her seat and the two share a short but warm embrace, while I sit awkwardly nearby watching in silence."
    st "You know how she is..."
    S "Mmhm. Tanya, I'd like you to meet my new Vertu, Clover."
    S "Clover, this is my best friend, Tanya."
    "Having made the introductions, our eyes lock together for a brief moment before she breaks into an equally warm but decidedly more distant greeting."
    T "Nice to meet you, Clover! Are you taking good care of Sibyl for me?"
    "There's a subtle accent in her speech that I just can't place but she speaks so fluently that it's clear she's been speaking English for quite some time."
    S "Taking care of {b}me{/b}? I practically had to {b}drag{/b} her butt out of bed this morning and it's only her first day!"
    "As evidenced by how playfully she says it, there's no real malice in her choosing to reveal this embarrassing fact, and Tanya doesn't look too hard on me for it."
    C "(And she didn't mention the little fit I threw either, so I guess I owe her for that. Not that I care what Tanya thinks of me anyway.)"
    S "We'd better go and get your breakfast before they close the kitchen, Tanya. Want to come with, Clover?"
    "I turn them down with an excuse about having already eaten too much despite knowing full well she wasn't asking if I wanted any more food."
    "For a moment I think I see Tanya flick a glance my way as they leave me at the table, but it might just be my imagination."
    "My eyes linger upon them while they wander off to fetch another tray for Tanya. They're obviously close already, after just half a school year."
    "Tanya is particular isn't shy about their friendship, walking quite close by her side and even reaching to touch her arm as they laugh about something to one another."
    "It leaves a bitter taste in my mouth as I think about my friends back home, all of which seem to have slowly forgotten about me as my life was upended."
    C "(I should have located the classroom beforehand so I wouldn't have to wait for Sibyl.)"
    "But there's nothing to be done about it now as Sibyl and Tanya return from the kitchens."
    "The latter immediately takes the strawberries off her yogurt parfait and turns to plop it into the former's open mouth like it's an everyday ritual."
    C "(They might actually do this same this every day for all I know.)"
    "Watching them go about the motions of the day so in sync, even if it's just eating breakfast, makes me realize just how close they are."
    C "So are you two, like, girlfriends?"
    "Tanya nearly snorts yogurt out of her nose when I say it, and quickly apologizes in a nasally voice as she recovers from the surpise question."
    S "Sibyl, meanwhile, merely takes my breaking of the silence as close friends, Clover."
    C "Yeah, but we never fed each other."
    S "Tanya hates strawberries. I love strawberries. It's a win-win."
    T "No fruit should have that many seeds. And why are they on the outside? They make no sense."
    C "(She sure has strong opinions about fruit.)"
    S "The way I see it, we need more strawberries, and star fruits, and pawpaws, and whatnot. The stranger the better."
    C "How did you both eer become friends?"
    S "Tanya is in our class but we became friends mostly through the art club."
    "With Tanya still deep into her breakfast, it's mostly Sibyl who keeps engaging me in conversation, though at my next question Tanya does huff into her parfait."
    C "Uh huh. And who's Sierra."
    S "That's Tanya's Vertu partner. They don't exactly get along super well."
    C "So we're {b}allowed{/b} to not act like we're BFFs with our roommate here? I almost thought it was required by the way everyone else here is acting."
    S "Some people {b}enjoy{/b} the support and companionship a Vertu partnership provides, Clover."
    T "If you're lucky enough to get a good Vertu partner."
    C "If it were up to me I would have my own room all to myself."
    S "No kidding?"
    "An obvious tone of ironic surprise is evident in Sibyl's reply, and for a moment I wonder if her best friend act is getting worn down already, but she instead continues seriously."
    S "At first I thought it was {b}fortuituous{/b} when they told me I was the odd girl out and had no Vertu partner. I had a {b}whole room{/b} to myself for the first time in my life."
    C "Do you want it back? Maybe there's an extra room I can camp out in."
    "Sibyl seemingly ignores my interjection and continues on without ackowledging me at all."
    C "My first few weeks were nothing but eating alone and going to classes alone, before finding friends."
    S "Every night, I sat in my lonesome room with my only company being the empty bed across the way."
    C "That's a bit dramatic, don't you think?"
    "Both Sibyl and Tanya give me a hard look, and for just a moment I feel that maybe I shouldn't have said it aloud when she is clearly being so serious."
    C "But you have Tanya now, right? So you don't need me."
    S "Even gaining a friend in art club didn't make my dorm life any less solitary."
    C "Well Tanya hates her own Vertu, so why haven't you switched?"
    T "You can't just... {b}switch{/b} your Vertu partner."
    "Both of them look almost shocked, like this is the most absurd thing they've ever heard, and not at all a totally rational idea."
    S "Okay, okay, I get it. No switching Vertus. It's a sacred bond between two girls that can never be broken."
    "Sibyl smiles at my sarcastic reply even though it should be clear from my tone that it is indeed incredibly sarcastic."
    C "(I suppose she just likes hearing me say it, as if that will make me believe it eventually too.)"
    T "It is true that I would have preferred a different Vertu partner, but I respect the rules and traditions of this academy more than I dislike Sierra."
    S "I hope all this talk about Sierra and Vertus helped you realize how important you are to me, Clover."
    "Out of nowhere, Sibyl hits me with the guilt trip, and something in her words stirs butterflies in my stomach."
    "Tanya quickly finishes her yogurt parfait and the time comes for us to head to our classrom, thankfully cutting the conversation short."
    jump class_intro

label class_intro:
    scene bg black with fade
    scene bg classroom with dissolve
    "Unfortunately, I could not simply go back to my room and bury myself back into my sheets again."
    "Sibyl kept a close watch on me as we wound our way through campus toward the school building like she was afraid I would run off if she did now, which I probably would have to be fair."
    "As I now stand in front of the classroom with over a dozen matching uniforms staring at me, I suddenly wish I'd just taken off sprinting anyway."
    C "M-My name is Clover Ipswich..."
    "Stage fright hits me like an overstuffed tanker truck full of liquid lead, as usual."
    "Sweat feels like it's pouring out all over me, my brain pounds against my skull, and I'm suddenly way too conscious of the weight of the arms by my side."
    C "(Imagine them in their underwear! Isn't that what they always say?)"
    "I try to imagine all the girls before me in their underwear, but to no avail. My attention is only brought to the one girl who I've already seen undressed."
    te "I'd like you all to please assist Clover as she joins your classes."
    "There's a chorus of agreement from the audience as the homeroom teacher takes over again, but she all too quickly puts the spotlight right back on me in the worst way."
    te "Is there anything else you'd like to tell the class, Clover? Maybe about your hobbies, what you do for fun, or what you have on your mind as you begin your time here?"
    "The dreaded \"tell us about yourself\" question. It parlayses my brain, caught somewhere between frozen like a block of ice and working overtime to get me out of this situation."
    show choice_darkness with dissolve
    menu:
        "\"I think I'm gonna throw up...\"":
            hide choice_darkness with dissolve
            C "I think I'm gonna throw up..."
            "I can't see what I look like, but I feel positively {b}green{/b} just standing there at the front of the classroom with every eye on me."
            "From within the haze of my mind I hear the teacher ask if I need to see the nurse, and instinctively I just say I need to sit down."
            "It's only when I finally feel the seat under me that I realize I could have just gone to the nurse's office and gotten out of this whole mess altogether."
            S "If you start feeling bad again, I can help you to the nurse."
        "\"I-I can't stop thinking about Sibyl's underwear.\"":
            hide choice_darkness with dissolve
            C "I-I can't stop thinking about Sibyl's underwear."
            "Unbelievably, I say exactly what's on my mind despite how it's quite possibly the worst thing I could say at this moment."
            "There's an immediate round of giggles from the assembled class before me, and I pray that I'm about to just drop dead any second."
            "But the sweet relief of a lightning strike from the heavens never comes, and I quickly stammer out a weak explanation in possibly the highest pitched voice to ever leave my throat."
            C "I-I mean, I was trying to imagine... y-you all in your u-underwear..."
            "I don't even know what I'm saying anymore, and just shut my mouth to quickly shuffle off toward my seat when the teacher dismisses me."
            S "I'm flattered, Clover. It's tough being put on the spot, huh?"
        "\"I-I like k-koalas.\"":
            hide choice_darkness with dissolve
            C "I-I like k-koalas."
            C "..."
            "There's a small silence as everyone, including myself, takes in what I have to say. All three words of it."
            C "(What. The hell.)"
            te "Thank you, Clover. Why don't you take a seat?"
            "I don't even have any particular interest in kaolas, it's just the first thing that came to mind somehow."
            C "Y-Yeah..."
            "I just {b}know{/b} that from this day forth, I'm going to be forever known as \"the koala girl\"."
            S "I think koalas are cute too, Clover!"
    "Sibyl whispers some kind but unhelpful words from the seat beside me in a futile attempt to revive my pale, deathly visage."
    "The embarrassment just hits me all the more forcefully, and I draw my hair around my face like curtains in which to hide my shame."
    jump after_lunch

label after_lunch:
    scene bg black with fade
    scene bg aquarium with dissolve
    "The classes I attend during the day pass in a blur as a myriad of thoughts and emotions roll around my skull."
    "Feigning a trip to get second helpings of lunch, I sneak away from Sibyl and out of the cafeteria entirely in favor of wandering around until I find someplace quiet to be alone."

    C "You don't have a care in the world, huh?"
    "Eventually I find my way to the aquarium room, which this school has for some reason I cannot begin to fathom."
    "Most importantly, I find it deserted and soothingly silent. Only the eyes of the fish around me trace my footsteps."
    "They crowd around my finger as I tap it softly against the glass, and in return I immitate their wide open fish mouths right back at them."
    "A breathy sigh heaves from my chest, scaring the assembled fish back into various corners of the tank."
    C "You're all running away too? Fine, I came here to be alone anyway."
    "Finding an open chair, I flop down into it, arms crossed."
    "I've only been here twenty-four hours and yet I've already been both sexually assaulted and then humiliated in front of the whole class."
    "I knew I was going to hate it here, and everything so far has just been proving my intuition correct."
    C "(Where did everything go so wrong?)"
    "It feels like just yesterday that I was at home playing with my dog Abraxas, and having pizza and a movie night with my parents every Monday night."
    C "(Now they're fighting over which one of them is taking Abraxas, and which one of them is taking me, like we're both items to be bartered with!)"
    "I don't know when it happened, but the tickle of a wet drop running down my arm alerts to me both that my face is buried in my hands, and that I'm just barely choking back tears."
    C "(God, I'm so pathetic.)"
    "Like, \"barely holding it together\" type pathetic."
    "Classes were actually a welcome distraction, even the French class, in which I was totally lost, and the etiquette class, which was a total surprise to me to begin with."
    C "(I {b}really{/b} need to read tha pamphlet sometime. At least Sibyl was there to nudge me in the right direction and keep me from making a fool of myself again.)"
    "Somehow, thinking about classes instead of my awful life circumstances makes me come around slightly."
    "A little sniffle here and a smudge of my sleeve across my eyes there and I'm already halfway to only being a mess instead of a disaster."
    C "(I'm all right. You're all right. Clover's all right. See? We're all right.)"
    "Drawing my fingers through my hair, I run them up and through to the ends to toss my blonde tresses out in a physical manifestation of doing away with my emotional instability."
    C "Hahn..."
    "I sit still like I'm calm, but deep down I can feel the pain welling back up inside."
    "It's just at that moment that the door clicks open. My head raises instinctively."
    C "Sibyl?"
    "But it's not luxurious mahogany curls which I see flutter through the doorway, but rather straight black curtains like a negative of my own."
    T "Clover! So this is where you ran off to."
    C "Y-Yeah. I just needed some time alone."
    "Knowing that my fae must be quite something to see, I turn my head aside away from Tanya."
    T "That's what we figured, but it's almost curfew time."
    C "...Why didn't Sibyl come for me?"
    T "Hmm?"
    "She steps closer, and I turn away that much further, not even looking at her."
    C "She's the one always saying that we're supposed to support each other, and she didn't even come looking for me?"
    T "We {b}both{/b} went looking for you, Clover. It's a big school."
    T "Hey, are you alright, Clover?"
    "The soft tone of concern about a girl she barely knows kind of annoys me, and I cannot stop myself from letting it show."
    C "What does it matter to you anyway? You're not my roommate, Sibyl is. Don't you have your own Virtue to worry about?"
    "Tanya's tone again turns, this time more firmly, which is really no surprise with how obstinate I'm being toward her."
    T "Vertu. It's called a {b}vertu{/b} and it is a foundational aspect of this academy."
    "Tanya corrects me with a measure of her fading patience clear in her voice."
    T "It matters to me because it matters to Sibyl."
    T "You're all she's thought about all day. She's barely said a word to me today that wasn't about {b}you{/b}!"
    T "So please, just come on and let's hurry back before the bell rings for curfew."
    "Tanya reaches out for me, which I don't realize until her hand is on my own."
    "I quickly brush it off and shove back at her."
    C "Just leave me alone!"
    T "Augh!"
    "I'm actually a little surprised by the loud huff of frustration that comes from Tanya, and quickly look her way for the first time since she walked in."
    "My petulant behavior has clearly ticked her off. Her hair is ever so slightly amiss from my shove, and her cheeks are flushed light pink."
    T "Don't you know that Sibyl is trying {b}so hard{/b} to do right by you, and you just keep... shoving it all back in her face!"
    "Before I even know what's happening, Tanya has cornered me against the fish tanks, both of her arms stretched out to my sides as she tells me off."
    T "Maybe {b}she{/b} isn't pissed off, but {b}I{/b} am."
    "Under my breath, I hiss a quiet \"if you love her so much, why don't you marry her\" like a devilish little imp, and it succeeds in making little miss best friend red to the face."
    "Tanya nearly looks like she's about to claw my face off, but instead pushes back off of me to turns away and stomp out of the aquarium."
    "With the angry presence before me suddenly gone, I just slump down on the ground right there with my bcak against the fish tank."
    C "(She was the one trying to get all up in my business. She was asking for that, right?)"
    "My irritable mood quickly fades back into morose, and consequently my brain comes right back around to everything that just happened."
    pause 0.5
    # TODO: insert bing bong here
    pause 0.5
    C "Crap."
    scene bg hallway with dissolve
    "I don't know what the penalty for being out after curfew is, but I don't exacly want to find out."
    "Stealthily as I can, I creep down the hallway like I'm the heroine of a spy movie, mostly successfully, until I turn around a corner straight into the worst possible person I could."
    H "Ah! Our missing Clover."
    O "Flaunting curfew on your first da—"
    "Before they can even begin doing anything {b}weird{/b} I take off running down the hallway, and thankfully don't see them taking up the chase behind."
    "I'm slightly out of breath by the time I make it back to my dorm, but I make it back in one piece, unmolested, and without drawing attention of any of the teachers."
    "The first thing I see when I come down the hallway is Sibyl, pacing in place outside the door."
    "When she sees me, her face lights up and she herself runs a few steps to throw her arms around me."
    S "You made it back!"
    C "Y-Yeah..."
    "I don't even know what to say. Feeling Sibyl's warmth around me seemingly sap all the angst and anger right out of my body, leaving me a weak, tired mess that clings to her."
    "It is she who pulls away, more quickly than my brain seems to like, and pushes me in through the door into our room."
    S "I got so worried when you didn't come back!"
    C "S-Sorry... I just needed to be alone after eating. It's been a long day."
    "I don't know whether it's the guilt of having blown up at Tanya or not, or how delighted Sibyl's face appears that I've returned, but I just can't find the anger inside that I did before."
    S "I knew you weren't going back for seconds. I meant to let you have your time alone, but I started to get more and more worried as the clock kept ticking later."
    C "I-Is the penalty for braking curfew that steep?"
    S "No, it's not, I just... wanted to make sure you were okay."
    C "Why?"
    S "Huh?"
    C "Why do you care so much about me?"
    C "Tanya is right. It's only been a day and all I've ever done is be a terrible, miserable person to you."
    S "You've told me everything already. Well, you've said enough at least."
    S "You've been through a big life adjustment. It's hard. It's confusing, miserable, and it leaves you a total wreck. I know it all too well."
    S "I'll wait as long as it takes for you to come around, and if you need to talk about it, I'll be right here."
    "I feel like I'm having a heart attack as she says it, with my strangly my heart starts beating in my chest."
    C "(But... I haven't said a single thing about my parents' divorce to her?)"
    "Bashfulness creeps back up into my face, and staggeringly, I back away from Sibyl. Her benevolence is just too shining."
    S "Oh, and your phone was ringing like crazy earlier."
    "The heat in my body all of a sudden dissipates. I jump across the room and clutch at my smartphone. One missed call, and a text message following it."
    C "(\"Hi, sweetie, how was your first day at school?\")"
    "It's from my mom. She's asking about my first day at school."
    "Like it wasn't her idea to drag me out of my old school and abandon me here at this one."
    "Like she isn't conspiring with my dad to tear our family apart and destroy our lives."
    "Like she cares a single bit about me after all that."
    "I chuck the smartphone into my pillow at full force, clearly alarming Sibyl behind me."
    S "C-Clover?"
    C "I'm {b}fine{/b}! It's just my mom."
    S "Your mom, that's great!"
    "Whatever Sibyl thinks is so great about it, I cannot possibly understand."
    "What would be {b}great{/b} is if she said it was all some awful practical joke, I can come home, and we were going to be a family again."
    "But that's not going to happen."
    "Contrary to having just throw my phone on the bed, I immediately swipe it off onto the floor and collapse face-first onto the bed instead."
    S "You're going through a lot, I can tell."
    S "I won't pry about it, but when you're ready you can talk to me about it. You might feel better."
    C "You wouldn't understand!"
    "There's a silence for a few moments before Sibyl's soft, calming voice returns."
    S "Maybe not exactly, but I also might know more than you think."
    "She leaves me with that piece of advice, then leaves me to my own devices. With all the emotional toil of the past day, I fall asleep before I know it."
    jump crisis

label crisis:
    scene bg black with fade
    scene bg bedroom with dissolve
    "I am awoken the next day with the light sound of Sibyl's voice calling my name."
    S "Clover... are you going to get up?"
    C "No."
    S "I'm going to pull the sheets off again if you don't get up."
    C "Do your worst."
    "The possibility of facing my homeroom class again after yesterday's stunt is foremost in my mind, not to mention the lingering malaise of everything that happened last night."
    S "You asked for it. Literally."
    "And whoosh, off come the sheets. I brace against the shock of the cold air but stay flopped in my bed resolutely."
    S "Clover..."
    C "No."
    S "Hmmm..."
    "I think, for a moment, that I've won, but all of a sudden I feel hand on my feet."
    C "What are you—"
    S "{b}Hnnngg!{/b}"
    "With one big tug, Sibyl pulls my legs right off the bed up to my knee."
    S "Are you getting up now?"
    C "Nuh-uh."
    S "{b}Hnng!{/b}"
    "My hips leave the bed, making me hang limp where she holds my legs up while my upper body rests on the bed."
    S "How about now?"
    C "N—"
    S "{b}Hnnnnnngggg!{/b}"
    "My body drops like a stone onto the floor, and finding Sibyl release my legs, I roll over fully onto my back to stare blankly up at Sibyl standing above me."
    C "Ow."
    scene bg black with dissolve
    scene bg cafeteria with dissolve
    "Sibyl and Tanya start chatting the moment they meet in the cafeteria, apparently about Sierra. I don't pay much attention, instead wandering off in search of French toast."
    "When I've gotten back to my seat and stuffed the first bite of fluffy bread into my mouth, Sibyl goes off to get her own food, leaving me alone with Tanya."
    C "(Awkward.)"
    "A quick glance while I've still got my fork in my mouth catches Tanya's eyes. All she does is give me a sharp, dismissive glare."
    C "(Yup, she hates me now. Oh well, maybe I can make friends with Sierra instead. That'll really piss her off.)"
    "When Sibyl returns, the two of them continue their chatting while I stay silent and stare down syrup remaining on the plate which formerly contained French toast."
    C "(Sh-Should I lick it?)"
    "While still re-playing in my mind what I learned about licking plates in etiquette class (namely not to do it), I manage to catch Sibyl calling my name."
    S "Earth to Clover, hello."
    C "Huh? Oh, I'm here."
    S "Good. I was just saying that we have art class today so you'll finally get to meet Miss Izzie."
    C "Y-Yeah? What's so special about her?"
    "I'm sure she must have a good reason to bring it up like this, but it's hard to be excited for something I have no idea about."
    S "She's a popular teacher among us students. She's young, and, well, pretty strange, but fun. I think you'll like her."
    C "Let's hope."
    S "...Maybe even snap you out of this funk!"
    C "Doubt it."
    T "Oh, just leave her alone. If she want to be miserable, let her be miserable."
    scene bg black with dissolve
    scene bg artroom with dissolve
    "Sibyl remains by my side, regardless of whatever Tanya says, and Tanya never leaves Sibyl's side either."
    