label sibyl_talk:
    show bg transition with fade
    show bg cafeteria with dissolve
    "The next day, I get out of bed without a fuss and follow Sibyl to breakfast."
    "She and Tanya follow their usual routine of exchanging the strawberry and jumping right into whatever crazy thing Sierra did the previous day."
    "I, meanwhile, revel in my double helping of French toast."
    C "(If I stay at this school any longer they're going to have to roll me out.)"
    "I resolve to go with a decidedly lighter calorie yogurt parfait tomorrow, but for today am satisfied that I need the calories after how hard my brain was churning all night."
    T "And then she told me that I had {b}\"perfectly perfunctory perfumery\"{/b}!"
    S "I think... I think that was an insult."
    T "When it comes to Sierra, who even knows?"
    "Sibyl's laughter at Tanya's expressive storytelling rings sweetly in my ears, no doubt sounding very much like a veritable chorus of angels if they were to be placed beside my goofy guffaws."
    C "(Is there {b}anything{/b} wrong with her?)"
    "A cube of cantaloupe speared on a fork slips through her lips while she listens to her friend."
    "A shiver trembles my shoulders at the exact same moment that I think I could do the same tomorrow with the strawberry atop my yogurt parfait, just like Tanya does every day."
    C "(I like strawberries too, but maybe Sibyl likes they way more than me?)"
    "Thoughts like these are new as of yesterday. After calming down considerably from the emotional highs of the care package, I finally called my parents."
    "I felt a considerable amount of anxiety when to do it; it felt like Abraxas was sitting on my chest as I dialed the numbers."
    "But when the phone connected and I heard my parents' voices again, the rush of anger that I had expected never materialized."
    "We spoke about a lot of things. Most of all they wanted to hear about my new school and friends, which I realized I know embarrassingly little to speak about."
    "I couldn't bear to tell my parents I had {b}no{/b} friends whatsoever, but I did tell them about my roommate."
    C "(If there's anyone who might fit the bill, it's the girl who turn on me even after being so mean to her.)"
    "Sibyl hasn't treated me any differently, but I'd still like to apologize. I just can't figure out how to make \"sorry for being such a bitch\" sound better."
    "Most important of all, I promised my parents that I'd have more to tell them about next time they called, so I have good reason to be watching Sibyl so closely."
    S "Clover?"
    C "A-Hunh?"
    "Lost in my thoughts while observing fruit disappear between her lips, I don't even realize when Sibyl addresses me directly. Tanya, it seems, has gone off somewhere, leaving the two of us alone."
    S "Are you feeling well? You've been kinda... lost in space, all morning."
    C "I'm... I'm good."
    "Shaking off the daze from the depth of my thoughts, an awkwardness seems in to replace it."
    S "Mmm. Glad to hear it."
    "Sibyl must be feeling it too. I can tell she's restraining herself around me despite being such a chatterbox with Tanya. It's actually making me feel a little jealous for some reason."
    C "Sibyl, umm... what did you do?"
    S "Excuse me...?"
    C "(Words, Clover, use your words!)"
    "As usual, my intense rate of mental processing is making my thoughts churn through faster than my mouth can voice them."
    C "Before I came here. When you weren't with Tanya, how did you spend your time outside of class?"
    S "You... want to know about me?"
    "She says the words like a question, but by the looks of her face it's more of a surprised yet joyful statement."
    S "How wonderful! And after only a week!"
    "I can already feel a flush spread across my face but push through it for the sake of learning more about the one and only person I might potentially call a friend."
    S "I'm so glad you're feeling better, Clover. You {b}are{/b} feeling better, right?"
    C "I-I think so...? Let's say \"yes\" for now."
    "The anger might be gone but there's still a confusing vortex of different emotions swirling inside of me which I have yet to place."
    C "But anyway, I'd like to know more. About you. Which is why I asked."
    S "I see! Well, whenever I was alone I would most often either work on a project in the art room or find a new book in the library."
    S "Have you visited the library yet, Clover? It's {b}wondrous{/b}. The light streams through the windows is such a picturesque way and the smell is just perfect."
    C "(The smell? Of the library? Is that a normal thing to appreciate?)"
    C "Just once but I was kind of out of it at the time."
    S "Oh? Then you {b}must{/b} come with me after class? I've been meaning to pick up a new novel anyway."
    C "O-Oh, yeah? I didn't know you were so into reading, Sibyl."
    S "There's a lot of things you don't know about me Clover!"
    "I distinctly feel as though we've had this conversation before, but this time Sibyl is much more happy to be saying the same thing."
    T "They were out of blueberry so I got us lemon poppy seed. Is that alright, Sibyl?"
    "Tanya returns out of nowhere and drops a tasty-looking muffin in front of Sibyl and her own seat at the table."
    S "Lemon poppy seed is just as delicious. Thank you."
    C "(So, wait, Tanya dislikes strawberries for having seeds on the outside, but is okay with muffins freckled with seeds?)"
    S "Tanya, I am going to show Clover the library after classes today. Would you like to come with us?"
    "Sibyl's best friend unexpectedly turns down the offer, which is a surprise to me until she gives me a dirty look the second Sibyl turns away."
    C "(I'm not trying to {b}steal{/b} your best friend.)"
    "I say the words in my head but they obviously don't transmit into Tanya's mind through the air."
    S "You have to make a visit to our academy royalty, hmm? Maybe another time then; I'd like to find an activity the three of us can do together."
    "I don't even know whether she's intentionally guilt tripping us, but both Tanya and I simultaneously fail to meet Sibyl's gaze."
    "Despite what I thought just before, some part of me actually is quite glad that Tanya won't be showing her face at the library later."
    jump lacrosse_practice

label lacrosse_practice:
    show bg black with fade
    show bg classroom with dissolve
    "Tanya continues to monopolize Sibyl's attention throughout the day as best she can like she has to make up for not seeing her after class."
    "There's no doubt that her obstructing me from learning about Sibyl now that I actually want to is getting on my nerves, but my patience is rewarded when the time comes for gym class."
    show bg gym with dissolve
    mw "Girls! Gather up, please."
    "As instructed, we gather all around Miss Woolsey as she wheels out a cart full of sticks with nets topping them."
    mw "We're going to be picking up the lacrosse sticks again today. I'd like you all to get together with your Vertu partners and practice passing and catching."
    T "Ughhhhh."
    "Almost immediately after being dismissed to begin practicing, Tanya groans out her obvious disinclination toward pairing up with her Vertu partner."
    T "Sibyl, save me."
    S "Sorry, Tanya. Just think of Sierra's face as the target and give it your all."
    "Just as Tanya leaves dragging her feet, Miss Woolsey steps over smartly to address Sibyl and I."
    mw "Sibyl! Clover! How have you two been?"
    S "Forging the sacred bonds of our Vertu partnership, Miss Woolsey!"
    C "...What she said."
    "It's a bitter slice of humble pie, but I meekly accept the cheerful reply of Sibyl to Miss Woolsey's equally cheerful question."
    "I know very well it's a total one-eighty from how I was feeling just days before and can barely stand to show my face to Miss Woolsey after all the theatrics of my first night."
    mw "Happy to hear it! You've been a great gym partner, Sibyl, but now it's your turn to teach Clover the ropes. Are you up for it?"
    S "Yes, ma'am!"
    "A certain thoughts sticks with me while watching Sibyl and Miss Woolsey go back and forth in such a warm and friendly manner, and I cannot help but voice it when our teacher finally leaves."
    C "You can Miss Woolsey are good friends, huh?"
    "It probably should have been clear to me by how they acted around one another the first day when we missed dinner, but I was way too far into my head then to realize it."
    S "I have had the honor of having Miss Woolsey for my gym partner these past few months, owing of course to having no Vertu partner of my own."
    C "I'm so sorry..."
    "Truly full of pity, I can only shudder to think about it. being forced to pair with the gym teacher {b}every class{/b} is all but tantamount so social suicide by standard high school convention."
    S "Don't be; Miss Woolsey is a hoot and a half! I don't think there's a single person who has as encyclopedic a knowledge about cats as she does."
    C "Maybe it's the dog lover in me speaking, but she sounds, umm... quirky."
    S "We all have our quirks, Clover. Is that any different from knowing all about \"Abraxas, the three hundred sixth fifth prince of the basilica gnocchi—\""
    C "Ahh, no, stop!"
    "Frantically, I wave my arms about until Sibyl hushes up about all the stupid stuff I was interested in during middle school, despite how {b}wrong{/b} she is getting it all."
    "My cheeks burn red, but no one around seems to have noticed a thing. Sibyl merely smiles back as she offers out a lacrosse stick for me to grab."
    S "Have you played lacrosse before, Clover?"
    C "Nope. But we had a girls' team at my old school."
    "I start with the intention of passing the ball from the netting at the end of my stick by planting my feet and whipping the head forward, but nothing happens."
    "The ball remains stubbornly in my net despite how much I shake it out in frustration, ultimately ending up with smacking myself over the head with my own stick."
    "Sibyl barely holds back a giggle at my expense."
    C "Ow. Okay, yeah, I have no idea what I'm doing. Help me, Sibyl."
    "Sibyl instructs me on where to properly place my hands upon the {i}crosse{/i} stick, how to take the correct stance, and finally the correct motion to make the pass successfully."
    "In no time at all we're passing the ball back and forth like I didn't just pick up this {i}crosse{/i} for the first time in my life."
    C "(This is actually... kind of fun!)"
    S "You're a natural, Clover!"
    C "Hehe, thanks!"
    "It feels so strangely good to move in time with Sibyl as we volley to each other that I cannot help but allow my lps to spread into a broad grin."
    S "You should think about joining the academy's team! They're always looking for more girls."
    C "The lacrosse team? Are you on it too?"
    "I know it's a silly question the moment I speak it aloud as I am well aware that Sibyl is part of the art club instead. The playful mood of the moment must have made me dumb."
    S "No, but some of the girls on the team split their time with the art club on days the lacrosse team has no training."
    "I cannot deny that it feels pretty good but I don't know how I'd compare against actual players, and without the major confidence boost from Sibyl's encouragement ether."
    C "I'll think about it."
    "As much fun as I may be having, the exertion finally catches up to both of us and we have to pause to catch our breaths. A small commotion catches my eye across the gym."
    "It's Tanya, with her hair all disarrayed and face flushed like that time I made her mad in the aquarium, but this time I'm not the one facing her fury."
    T "Hraaah!"
    "Her stick swishes through the air in a mighty arc, propelling the ball forcefully toward another girl across from her, who dodges it with a sharp squeal."
    C "Is that...?"
    S "Sierra? Mmhm."
    "I've noticed her in classes but never really {b}seen{/b} her, so to speak."
    "Now that I do, she fits just about every expectation I might have expected given the wave Tanya speaks about her."
    C "She's gorgeous."
    "It's not just a natural beauty, but also the manner in which she holds herself, keeping her chin upright no matter how fast the balls come whizzing at her head."
    S "It's really too bad about her personality though."
    "As supernaturally pretty as Sierra might be, she doesn't capture my attention nearly as much as Sibyl, to whom I find my gaze drawn back toward."
    "It's that kind of \"flawless skin using only moisturizer\" type of modest, innate beauty in which Sibyl excels."
    S "Clover?"
    C "Hmm?"
    S "Are you ready to begin again?"
    "I may be lost in my mind once again, but Sibyl only sees my physical body, now back facing her on the gym floor."
    C "O-Oh, yeah, I'm ready."
    show bg black with transition
    "My spirits remain high after playing lacrosse with Sibyl until the moment Tanya returns to capture Sibyl's attention once again."
    "They chatter and giggle between themselves about how Sierra's athletic performance to dodging the rubber lacrosse balls while I hover awkwardly nearby."
    "Just a few days ago I only wanted to be \"just her roommate\" and now, as I watch the shared laughs and smiles from the sidelines, I'm feeling every bit of the self-imposed distance that I wished for."
    jump lunch_sans_tanya

label lunch_sans_tanya:
    show bg transition with fade
    show bg bedroom with dissolve
    "My eyelids open heavily against the fury of the bright sunlight of the morning of my first weekend at Prudence Prep."
    "I blink around the room and make out no figure belonging to Sibyl, nor hear any running water in the adjoining bathroom, and so I quickly close the curtains and fall right back into a heavy sleep."
    show bg black with dissolve
    "In my dream I run across a wide open grassy field. In my hand is a lacrosse stick much like we used in gym class."
    "The whole world is green and warm, and the soft cool breeze feels warm against my face as I rush through toward the goal at the far end of the field."
    S "Clover!"
    "Standing by the net is Sibyl, far away but so close, waving her stick at me for a pass."
    C "(She's wide open!)"
    "But now standing before me are many shadowy figures blocking the path between me and Sibyl. Their hard eyes glare at me as sharply as their sleek black hair cuts down their blurred faces."
    S "Clover!"
    "One figure leaps forward to grab at my leg, trying to hold me down, and my hopes of making it through diminish into the breeze."
    C "Sibyl, catch!"
    "Giving it my all, I take reposition my hands on the stick just as Sibyl taught me, take the stance, and launch the large strawberry in my net as hard as my arms will allow."
    S "Clover!"
    "It soars through the air toward Sibyl, still cheering me on behind the evil shadowy figures who hiss at the fruit as it flies over their heads."
    S "Clover!"
    "My aim is perfect. The strawberry reaches the apex of the arc and descends toward Sibyl's waiting stick..."
    show bg bedroom with dissolve
    "When my eyes open again, sunlight once more streams in through the large glass panes of the windows of my dorm room."
    S "Clover!"
    "A small pressure wiggles against my leg, and finally my brain connects the dots."
    C "S-Sibyl!"
    "Sitting up in bed, I find Sibyl there at the edge gently shaking my leg over the covers, calling my name."
    S "You're a really heavy sleeper, huh?"
    S "It's almost noon now. If you don't get out of bed soon you'll miss lunch!"
    "Having already slept through one meal time, my stomach agrees that it's high time for me to get out of bed too."
    show bg black with dissolve
    show bg cafeteria with dissolve
    "Sibyl accompanies me to the cafeteria and engages in small talk with me while I craft the ultimate brunch from the salad bar."
    S "We really went all out in gym class yesterday, didn't we?"
    "When we sit down, I start to munch on my salad while Sibyl holds her arm out to point out each muscle which was sore from the day before."
    "Now that she mentions it, I feel the same soreness in my arms and legs."
    C "I thought I was just sleeping funny but you're right; it's probably from lacrosse yesterday."
    C "(It would also explain the dream I had too.)"
    S "You looked like you were deep in a dream so I felt a little guilty about rousing you awake."
    C "I {b}was{/b} dreaming, but that's okay."
    S "Oh yeah?"
    "Sibyl looks genuinely interested in my dream. She sits across from me at the lunch table with not a single plate before her and all of her attention instead solely on me."
    C "Yeah. I was playing lacrosse. It was a nice spring day out and I was running down toward the goal to pass the strawberry to you, but all these shadows got in the way."
    S "That explains why you were kicking your legs so much. We were playing lacrosse with a strawberry?"
    C "Yup, a strawberry. My brain is defective sometimes."
    C "(Particularly as of late...)"
    S "I think this is a good omen. You should go join the lacrosse team after we visit the library, or at least observe them for a bit before you decide on it."
    C "(Oh right, I was going to the library with Sibyl today.)"
    C "Maybe I will. After all, who else should I trust to interpret omens than a sibyl?"
    "The namesake girl smiles at me brightly from across the table and I nearly choke on a ham cube which I had speared out of the bottom of my salad bowl."
    S "Are you alright, Clover?"
    C "Y-Yeah, sorry, just went down the wrong way."
    "I massage my throat even after the obstruction passes, but why I got choked up in the first place is still a mystery."
    C "(Probably fatigue from yesterday.)"
    C "Are you not going to eat anything?"
    S "Oh, I already ate with Tanya."
    C "Hmm. I {b}thought{/b} something felt different today."
    "I obviously noticed she wasn't hanging around Sibyl as she usually does, but hadn't brought it up at all as if she might suddenly appear to draw off Sibyl if I spoke her name aloud."
    S "Tanya always disappears for hours on Saturday afternoon."
    C "Why?"
    S "She says it's something to do with the ESL students but I don't know exactly."
    "It seems odd to me that Tanya, who I've witnessed share every little moment of her life with Sibyl, hasn't told her anything about what she does every Saturday."
    C "(If she were tutoring students who are not as strong with English as she is, surely she'd be telling Sibyl about it all through breakfast, lunch, and dinner.)"
    "I even get the feeling that Sibyl has further thoughts on the matter but don't press my curiosity. I don't need {b}any more{/b} of Tanya in my life."
    C "I'm stuffed. Let's go to the library, and maybe take the long way there to burn off some of these calories."
    S "Okie doke!"
    jump a2_library

label a2_library:
    show bg black with fade
    show bg library with dissolve
    "It is plainly clear that Sibyl is in her element from the moment she steps into the library."
    "From the very first step she waves a small greeting to a girl seated at a desk to the far left."
    C "Do you know her?"
    S "She's a member of the library committee. They manage the library, including keeping tracks of books lent out to students."
    "I didn't see anyone like that here on my first visit, but I was also skipping class at the time."
    C "(A student who joins the library committee probably isn't the type to skip class.)"
    "Sibyl eagerly floats ahead of me toward a small rack at the far end of the room."
    "Despite the chill air and blanket of snow outside, warm rays of sunlight flood through the large windows, bathing everything in their radiance."
    "Most radiant of all is assuredly Sibyl, whose auburn hair alights in the glow, making the red flecks in her hair sparkle like tiny rubies embedded in her tresses."
    S "Clover, come here!"
    "Sibyl beckons to me in a hushed but emphatic whisper which sets my legs moving toward her at once."
    C "What is it?"
    S "This is the new releases rack where popular new additions to the library are shelved before being put into general circulation."
    S "And look! The new book from one of my favorite series is here! I've been chasing this thing for weeks!"
    "I glance at the cover as she holds it up. Gracing the front of the book is a stylistic drawing of a woman in a black dress with a furred collar and an extraordinarily large hat."
    "\"Sylvia Valemont and the Diamond Lorgnette\" I read aloud, softly speaking the title between the two of us."
    S "Sylvia is a lady of high society in the Roaring Twenties, and kind of a femme fatale too."
    S "Every story is about some particular intrigue or scandal which she uncovers and exposes through clever usage of her wits or wiles."
    "Being the former goth girl that I am, I've never once in my life had fantasies about high culture or anything of the sort."
    S "I just {b}love{/b} it!"
    "Sibyl opens the book and presses her face into pages with a sigh."
    S "Still has the new book smell..."
    "With Sibyl's obvious enthusiasm for the book, I cannot do anything but smile and say a few words about how interesting the premise sounds."
    "Evidently my ruse is not good enough, because she sees right through it. Thankfully, she doesn't hold my bending of the truth against me at all."
    S "What do {b}you{/b} like to read, Sibyl?"
    show choice_darkness with dissolve
        menu:
            "\"I haven't checked out a library book since my elementary school taught us the Dewey Decimal system.\"":
                hide choice_darkness with dissolve
                C "I haven't checked out a library book since my elementary school taught us the Dewey Decimal system."
                "After having had my little white lie seen through immediately, I try to be brutally honest with Sibyl."
                C "I haven't checked out a library book since my elementary school taught us the Dewey Decimal system."
                C "(You don't find the kind of books I was reading in middle school at just any library.)"
                S "Not even once!?"
                C "I can't say for sure, but probably not."
            "\"If I were in middle school, I probably would have said something like \'esoteric grimoires from bygone civilizations\'.\"":
                hide choice_darkness with dissolve
                C "If I were in middle school, I probably would have said something like \"esoteric grimoires from bygone civilizations\"."
                "The warm flush of embarrassment comes quickly to my face as I remember all the late nights camped out under my sheets with a big tome and a flashlight whispering spells into the night."
                C "But I'm in high school now and left all that behind me, so I don't really know what I like these days."
                S "Some of the people here are really religious, so you're probably not going to find any of those kind of books anyway."
                C "Maybe something with a strong female protagonist, like the shows I used to watch on WebFlicks before I was sent here."
    C "Do you have any suggestions for me, Sibyl?"
    