label sibyl_talk:
    show bg transition with fade
    show bg cafeteria with dissolve
    "The next day, I get out of bed without a fuss and follow Sibyl to breakfast."
    "She and Tanya follow their usual routine of exchanging the strawberry and jumping right into whatever crazy thing Sierra did the previous day."
    "I, meanwhile, revel in my double helping of French toast."
    C "(If I stay at this school any longer they're going to have to roll me out.)"
    "I resolve to go with a decidedly lighter calorie yogurt parfait tomorrow, but for today am satisfied that I need the calories after how hard my brain was churning all night."
    T "And then she told me that I had {b}\"perfectly perfunctory perfumery\"{/b}!"
    S "I think... I think that was an insult."
    T "When it comes to Sierra, who even knows?"
    "Sibyl's laughter at Tanya's expressive storytelling rings sweetly in my ears, no doubt sounding very much like a veritable chorus of angels if they were to be placed beside my goofy guffaws."
    C "(Is there {b}anything{/b} wrong with her?)"
    "A cube of cantaloupe speared on a fork slips through her lips while she listens to her friend."
    "A shiver trembles my shoulders at the exact same moment that I think I could do the same tomorrow with the strawberry atop my yogurt parfait, just like Tanya does every day."
    C "(I like strawberries too, but maybe Sibyl likes they way more than me?)"
    "Thoughts like these are new as of yesterday. After calming down considerably from the emotional highs of the care package, I finally called my parents."
    "I felt a considerable amount of anxiety when to do it; it felt like Abraxas was sitting on my chest as I dialed the numbers."
    "But when the phone connected and I heard my parents' voices again, the rush of anger that I had expected never materialized."
    "We spoke about a lot of things. Most of all they wanted to hear about my new school and friends, which I realized I know embarrassingly little to speak about."
    "I couldn't bear to tell my parents I had {b}no{/b} friends whatsoever, but I did tell them about my roommate."
    C "(If there's anyone who might fit the bill, it's the girl who turn on me even after being so mean to her.)"
    "Sibyl hasn't treated me any differently, but I'd still like to apologize. I just can't figure out how to make \"sorry for being such a bitch\" sound better."
    "Most important of all, I promised my parents that I'd have more to tell them about next time they called, so I have good reason to be watching Sibyl so closely."
    S "Clover?"
    C "A-Hunh?"
    "Lost in my thoughts while observing fruit disappear between her lips, I don't even realize when Sibyl addresses me directly. Tanya, it seems, has gone off somewhere, leaving the two of us alone."
    S "Are you feeling well? You've been kinda... lost in space, all morning."
    C "I'm... I'm good."
    "Shaking off the daze from the depth of my thoughts, an awkwardness seems in to replace it."
    S "Mmm. Glad to hear it."
    "Sibyl must be feeling it too. I can tell she's restraining herself around me despite being such a chatterbox with Tanya. It's actually making me feel a little jealous for some reason."
    C "Sibyl, umm... what did you do?"
    S "Excuse me...?"
    C "(Words, Clover, use your words!)"
    "As usual, my intense rate of mental processing is making my thoughts churn through faster than my mouth can voice them."
    C "Before I came here. When you weren't with Tanya, how did you spend your time outside of class?"
    S "You... want to know about me?"
    "She says the words like a question, but by the looks of her face it's more of a surprised yet joyful statement."
    S "How wonderful! And after only a week!"
    "I can already feel a flush spread across my face but push through it for the sake of learning more about the one and only person I might potentially call a friend."
    S "I'm so glad you're feeling better, Clover. You {b}are{/b} feeling better, right?"
    C "I-I think so...? Let's say \"yes\" for now."
    "The anger might be gone but there's still a confusing vortex of different emotions swirling inside of me which I have yet to place."
    C "But anyway, I'd like to know more. About you. Which is why I asked."
    S "I see! Well, whenever I was alone I would most often either work on a project in the art room or find a new book in the library."
    S "Have you visited the library yet, Clover? It's {b}wonderous{/b}. The light streams through the windows is such a picturesque way and the smell is just perfect."
    C "(The smell? Of the library? Is that a normal thing to appreciate?)"
    C "Just once but I was kind of out of it at the time."
    S "Oh? Then you {b}must{/b} come with me after class? I've been meaning to pick up a new novel anyway."
    C "O-Oh, yeah? I didn't know you were so into reading, Sibyl."
    S "There's a lot of things you don't know about me Clover!"
    "I distinctly feel as though ew've had this conversation before, but this time Sibyl is much more happy to be saying the same thing."
    T "They were out of blueberry so I got us lemon poppyseed. Is that alright, Sibyl?"
    "Tanya returns out of nowhere and drops a tasty-looking muffin in front of Sibyl and her own seat at the table."
    S "Lemon poppyseed is just as delicious. Thank you."
    C "(So, wait, Tanya dislikes strawberries for having seeds on the outside, but is okay with muffins freckled with seeds?)"
    S "Tanya, I am going to show Clover the library after classes today. Would you like to come with us?"
    "Sibyl's best friend unexpectedly turns down the offer, which is a surprise to me until she gives me a dirty look the second Sibyl turns away."
    C "(I'm not trying to {b}steal{/b} your best friend.)"
    "I say the words in my head but they obviously don't transmit into Tanya's mind through the air."
    S "You have to make a visit to our academy royalty, hmm? Maybe another time then; I'd like to find an activity the three of us can do together."
    "I don't even know whether she's intentionally guilt tripping us, but both Tanya and I simultaneously fail to meet Sibyl's gaze."
    "Despite what I thought just before, some part of me actually is quite glad that Tanya won't be showing her face at the library later."
    jump lacrosse_practice

label lacrosse_practice:
    show bg black with fade
    show bg classroom with dissolve
    "Tanya continues to monopolize Sibyl's attention throughout the day as best she can like she has to make up for not seeing her after class."
    "There's no doubt that her obsstructing me from learning about Sibyl now that I actually want to is getting on my nerves, but my patience is rewarded when the time comes for gym class."
    show bg gym with dissolve
    mw "Girls! Gather up, please."
    "As instructed, we gather all around Miss Woolsey as she wheels out a cart full of sticks with nets topping them."
    mw "We're going to be picking up the lacrosse sticks again today. I'd like you all to get together with your Vertu partners and practice passing and catching."
    T "Ughhhhh."
    "Almost immediately after being dismissed to begin practicing, Tanya groans out her obvious disinclination toward pairing up with her Vertu partner."
    T "Sibyl, save me."
    S "Sorry, Tanya. Just think of Sierra's face as the target and give it your all."
    "Just as Tanya leaves dragging her feet, Miss Woolsey steps over smartly to address Sibyl and I."
    mw "Sibyl! Clover! How have you two been?"
    S "Forging the sacred bonds of our Vertu partnership, Miss Woolsey!"
    C "...What she said."
    "It's a bitter slice of humble pie, but I meekly accept the cheerful reply of Sibyl to Miss Woolsey's equally cheerful question."
    "I know very well it's a total one-eighty from how I was feeling just days before and can barely stand to show my face to Miss Woolsey after all the theatrics of my first night."
    mw "Happy to hear it! You've been a great gym partner, Sibyl, but now it's your turn to teach Clover the ropes. Are you up for it?"
    S "Yes, ma'am!"
    "A certain thoughts sticks with me while watching Sibyl and Miss Woolsey go back and forth in such a warm and friendly manner, and I cannot help but voice it when our teacher finally leaves."
    C "You can Miss Woolsey are good friends, huh?"
    "It probably should have been clear to me by how they acted around one another the first day when we missed dinner, but I was way too far into my head then to realize it."
    S "I have had the honor of having Miss Woolsey for my gym partner these past few months, owing of course to having no Vertu partner of my own."
    C "I'm so sorry..."
    "Truly full of pity, I can only shudder to think about it. being forced to pair with the gym teacher {b}every class{/b} is all but tantamount so social suicide by standard high school convention."
    S "Don't be; Miss Woolsey is a hoot and a half! I don't think there's a single person who has as encyclopedic a knowledge about cats as she does."
    C "Maybe it's the dog lover in me speaking, but she sounds, umm... quirky."
    S "We all have our quirks, Clover. Is that any different from knowing all about \"Abraxas, the three hundred sixth fifth prince of the basilica gnocci—\""
    C "Ahh, no, stop!"
    "Frantically, I wave my arms about until Sibyl hushes up about all the stupid stuff I was interested in during middle school, despite how {b}wrong{/b} she is getting it all."
    "My cheeks burn red, but no one around seems to have noticed a thing. Sibyl merely smiles back as she offers out a lacrosse stick for me to grab."
    S "Have you played lacrosse before, Clover?"
    C "Nope. But we had a girls' team at my old school."
    "I start with the intention of passing the ball from the netting at the end of my stick by planting my feet and whipping the head forward, but nothing happens."
    "The ball remains stubbornly in my net despite how much I shake it out in frustration, ultimately ending up with smacking myself over the head with my own stick."
    "Sibyl barely holds back a giggle at my expense."
    C "Ow. Okay, yeah, I have no idea what I'm doing. Help me, Sibyl."
    "Sibyl instructs me on where to properly place my hands upon the {i}crosse{/i} stick, how to take the correct stance, and finally the correct motion to make the pass successfully."
    "In no time at all we're passing the ball back and forth like I didn't just pick up this {i}crosse{/i} for the first time in my life."
    C "(This is actually... kind of fun!)"
    S "You're a natural, Clover!"
    C "Hehe, thanks!"
    "It feels so strangely good to move in time with Sibyl as we volley to each other that I cannot help but allow my lps to spread into a broad grin."
    S "You should think about joining the academy's team! They're always looking for more girls."
    C "The lacrosse team? Are you on it too?"
    "I know it's a silly question the moment I speak it aloud as I am well aware that Sibyl is part of the art club instead. The playful mood of the moment must have made me dumb."
    S "No, but some of the girls on the team split their time with the art club on days the lacrosse team has no training."
    "I cannot deny that it feels pretty good but I don't know how I'd compare against actual players, and without the major confidence boost from Sibyl's encouragement ether."
    C "I'll think about it."
    "As much fun as I may be having, the exertion finally catches up to both of us and we have to pause to catch our breaths. A small commotion catches my eye across the gym."
    "It's Tanya, with her hair all disarrayed and face flushed like that time I made her mad in the aquarium, but this time I'm not the one facing her fury."
    T "Hraaah!"
    "Her stick swishes through the air in a mightly arc, propelling the ball forcefully toward another girl across from her, who dodges it with a sharp squeal."
    C "Is that...?"
    S "Sierra? Mmhm."
    "I've noticed her in classes, now that I look at her, but never really {b}seen{/b} her, so to speak."
    "Now that I do, she fits just about every expectation I might have expected given the wave Tanya speaks about her."
    C "She's gorgeous."
    "It's not just a natural beauty, but also the manner in which she holds herself, keeping her chin upright no matter how fast the balls come whizzing at her head."
    S "It's really too bad about her personality though."
    "As supernaturally pretty as Sierra might be, she doesn't capture my attention nearly as much as Sibyl, to whom I find my gaze drawn back toward."
    "It's a kind of \"flawless skin while using only moisturizer\" type of modest, innate beauty in which Sibyl excels."
    S "Clover?"
    C "Hmm?"
    S "Are you ready to begin again?"
    "I may be lost in my mind once again, but Sibyl only sees my physical body, now back facing her on the gym floor."
    C "O-Oh, yeah, let's go."
    jump a2_library

label a2_library:
    show bg black with fade
    show bg library with dissolve