
label howto:
    scene bg bedroom with dissolve
    "The twins don't chase me as I stomp down the hallway back the way I came."
    "With my mind whirling and nowhere in particular to go I end up returning back to my dorm room where I come face to face suddenly with Sibyl."
    C "Eyeep!"
    "A little squeal of surprise leaks from my lips from suddenly having to confront the girl who has my brain all mixed up so badly."
    "After fending off her concerns for my illness, I sit down at my desk to try to actually do some of that homework that I meant to do yesterday, but find my mind always diverted elsewhere."
    C "(The sine is... the ratio of the side opposite the angle to the hypotenuse.)"
    C "(...Hippopotenuse. Sibyl would think that's funny.)"
    "My fingers flick my mechanical pencil against a diagram of a right triangle while my gaze flicks aside to where Sibyl reclines on her bed."
    "Sibyl finished her homework last night while I was in bed pretending to be sick. Her beautiful blue eyes now sweep from side to side as she reads through the lines of her latest novel."
    "Turning back to my homework, I try to wrap my head around trigonometry once again but just as quickly have my mind pulled away to more important matters to my well-being."
    "Idly, I pencil in a \"C\" at one end of a hypotenuse, and \"S\" at the other. On the right angle, I draw in a small \"T\" as an aside."
    C "(Hmm...)"
    "I stare at the labelled right triangle so long that the image gets burned into my brain but nothing comes to mind that will make the hypotenuse shorter and brings those two letters together."
    "Taking a different approach, I pick up my smartphone and flip to a fresh page of my notebook."
    "The keyboard on my screen flickers to life as I type my question into the search bar: \"how to make a girl fall in love with you\"."
    C "(\"Six Simple Steps\"? Is that all it takes?)"
    "I jot down the highlights into a series of bullet points and leave plenty of space in between to fill in my notes."
    C "(Step One: Be yourself!)"
    "There's a whole paragraph that follows it but I skip reading all that in its entirety because I've never been anyone {b}but{/b} myself."
    "In the empty lines I left to take notes of what I should do to fulfill the first step I draw a giant check mark to take up the space."
    C "(Step Two: Look good and feel good!)"
    "Sibyl might be far and away more beautiful with her soft, fluffy hair and eyes that anyone would get lost in, but I think I'm decently pretty the way I am after ditching the goth gear."
    C "(Blondes are pretty popular, right? So I've got that going for me too.)"
    "As far as \"feeling\" good, that's easy. I haven't felt as good than I do now since before all the nastiness of the fallout with my middle school friends and my parents' divorce."
    C "(Ugh...)"
    "What is supposed to be an optimistic thought I unexpectedly find still strike at surprisingly deep wounds even after having thought I'd made peace with them."
    C "(Sibyl has it worse than me. She never even knew her parents.)"
    "My pen scrawls out a slightly more modest check mark for the second step of the list. My wounds have not fully healed but if I can win over Sibyl they won't hurt anywhere near as bad."
    C "(Step Three: Take an interest in her!)"
    "I have to read further on with this one because obviously I'm interested in her or I wouldn't be here searching on the web for how to win her heart like this."
    "What the step wants me to do is be open and communicative, and also take an interest in her life and hobbies."
    C "(I've already been doing that, but I can do more too!)"
    "With a broad smile, I give step three another big check mark. Proud of myself, I snatch another gaze aside at the girl I'm going to win over to reward myself for being so well ahead of all the steps."
    C "(Step Four: Befriend her friends!)"
    "I have to re-read step four more than once to be sure that I read it correctly the first time but the words don't change no matter how many times I read them."
    "The nervous habit of tapping my pencil against the paper emerges once again as I stare into the blank lines I left under the step. I know what I need to write in there but lack the courage to do so."
    C "(If it means making Sibyl mine... I will do it.)"
    "In small print I write simply, \"befriend Tanya\"."
    C "(Enough of that. Step Five: Be flirtatious!)"
    "Once again, I physically blink at the outrageously simple heading for something so difficult."
    C "(Why does it just {b}assume{/b} I know how to flirt?)"
    "I read through the paragraph below the step header for more details. It's clearly written with a guy in mind but it's not entirely unhelpful for me either."
    C "(\"Make her known you're interested in more than friendship.\" Smiling, frequent eye contact, playful comments...)"
    "I read on further to try to find out how this is any different from normal friendship, but entirely fail to understand what makes flirting \"flirting\"."
    C "(And the first three steps were going to smoothly too...)"
    "Ultimately, I just note it down as something to do more research on later and work on further."
    C "(Step Six: Get physical!)"
    "At first I think this step is something salacious but it turns out to mean using small touches to increase our physical bond."
    "I don't immediately see how this is possible to be done smoothly but feel confident enough that I can work simple touches into our everyday routines."
    C "Okay, done! Now I just need to work on those few tricky parts."
    "Skipping quickly over step four, I review the other steps to my master seduction plan and decide to put it into practice right away."
    C "Sibyl!"
    "My crush's name slips smooth as silk from my lips as I walk over to her bed. Her attention draws away from her novel and onto me, just as planned."
    C "What's up, Clover? Need some help with the homework?"
    "My feet pause when I reach her bed. Thinking quickly, I sit right on the edge and place my hand casually on her shoulder."
    C "Your eyes are so pretty. What's your favorite color?"
    "It's a sure win, so I think initially, but every passing microsecond that Sibyl gives me a strange look like I'm not even speaking English lessens my confidence."
    S "...Yellow."
    S "Are you sure you're feeling all right, Clover?"
    "Sibyl turns quickly to face me, far too close for comfort given the emotional state I'm in right now, and lays her palm against my forehead."
    S "You feel warm..."
    C "(That's because you're so close!)"
    C "Yup, so good, never better!"
    "Sibyl doesn't seem to think me any more sane than before so I just take the little victories I've earned and play off the rest as an awkward way of asking for help with homework."
    "As it turns out, homework is {b}so{/b} much more enjoyable when Sibyl is sitting close beside me and explaining everything right into my ear. I almost don't want to it be over so quickly."
    jump failed_seduction

label failed_seduction:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "At lunch, I take the seat at Sibyl's other side completely opposite of Tanya rather than sit across from her as usual."
    "I intentionally sit close enough that I'm sure to brush my shoulders against her plenty. When Sibyl scooches down the bench slightly, I subtly do the same until we're rubbing shoulders once again."
    S "Is there something wrong with the other side of the table, Clover?"
    C "No. I just felt like sitting next to you today."
    "In truth, I prefer to be opposite of Sibyl where I can enjoy each expression as she converses with Tanya, from the way her cheeks puff up wth laughter to how high her eyebrows raise with surprise."
    S "That's all well and good, but I feel like a sardine."
    C "No way! You're not extremely salty and disgusting!"
    S "I meant how they're always tightly packed together into cans."
    T "Just move to the other side of the table, Clover."
    "Tanya only now breaks from her back and forth conversation with Sibyl, though I have caught some glowering glances my direction thus far into our mealtime."
    C "Why don't you? Didn't you used to sit on the other side every day before I did?"
    T "After {b}you{/b} took my spot, I have come to enjoy sitting beside Sibyl."
    C "But I want to sit beside Sibyl too!"
    S "You can both be so {b}stubborn{/b} sometimes!"
    "Sibyl stands right up and moves to the other side of the table herself, leaving a Sibyl-sized hole between me and Tanya which goes unfilled the rest of the meal."
    scene bg black with dissolve
    scene bg classroom with dissolve
    "Sibyl returns from the front of our science classroom with a tray full of small vials of differently colored mystery liquids."
    C "So what are all these vials for?"
    S "Were you even listening during the lecture?"
    "I honestly was not. It's so hard to concentrate when our science teacher starts droning on, and I never had the head for math or science to begin with unlike Sibyl."
    C "Sorry. I kinda zoned out."
    S "You've been kinda spacey lately, Clover. Are you sure you're alright?"
    C "Never better!"
    "I try to reassure her that I'm just fine without giving away my strong new feelings for her before she's ready to accept them. Sibyl gives me a suspicious glance but turns back to her work."
    S "The abstract for the experiment should go over the basics. Please read through it while I sort these out."
    "Lifting up the page, I read the title of the experiment we are doing today."
    "\"Determining Acidity by Titration with an Indicator Solution\""
    C "What's a \"tit-ration\"."
    S "{b}Titration{/b}."
    "Sibyl corrects me quickly, probably embarrassed with how I pronounced the words in an entirely different fashion."
    C "(I want some of Sibyl's tit-rations.)"
    S "Titration is adding a solution with a known concentration into a a solution with an unknown solution to determine concentration."
    S "For the purposes of our lab, we are going to first note the color change as we add the {i}titrant{/i}."
    C "(Tit-rant.)"
    "I must be feeling extras stupid today, as well as extra horny. Every since discovering what I feel about Sibyl it's just about all I can think about."
    "Sibyl goes on to explain even more about the experiment but it only half gets through my head as I zone out once more to focus on how pretty she looks while concentrating."
    C "(She's doing it again!)"
    "Just like when she's focused intently on her own artwork, Sibyl does the thing where her tongue just barely sticks out from between her lips as she moves little drops of liquid between glass vials."
    S "There we go! Would you like to do the honors, Clover?"
    C "Huh? Oh, sure..."
    "Sibyl finishes up whatever she's doing while I'm still gawking and I try to cover up my absentmindedness by pretending I know what I'm doing by volunteering for the next task."
    C "Remind me again how I should do this part?"
    S "Just one drop at time from the pipette. I'll tell you when to stop."
    "The click of a pen tells me it's time to go. I squeeze the dropper ever so slightly and let one drop loose, then turn back expectantly toward Sibyl."
    S "Keep going."
    "We do this a few more times until Sibyl suddenly tells me to hold off. Showing me her notes, she points out the difference in color between the new vial and our control vial."
    S "With this, we can do a small calculation to estimate the concentration difference and plot a titration curve!"
    C "Sibyl, you're a genius!"
    "Sibyl beams at the compliment. What I tell her is no mere flattery; things that make no sense to me suddenly aren't so scary once Sibyl explains them."
    C "Can you just marry me so I don't have to think so hard ever again."
    "With her genial mood as it is I try to squeeze in a little flirting, like planting the idea of marriage in her mind while playing it off as a joke."
    "I even try to reduce the physical distance between us by taking her free hand to examine her ring finger."
    "It's all in good fun, I believe, but the falter in a newly cautious smile upon Sibyl's face tells a very different story than what I'd hoped would play out."
    S "Come now, Clover. You have to learn all this for yourself. I will not always be around."
    C "(Why {b}can't{/b} you be?)"
    "Sibyl withdraws the hand I took of hers to bring back close to her chest, then turn away from me to finish writing down the details of our experimental results."
    C "(She's just worried about my performance on our exams, right?)"
    "While I am left wondering about the shift in mood behind Sibyl's back, I spot Tanya and Sierra at teh far end of the room."
    "Something clearly has gone wrong because Tanya's face is dripping with {b}something{/b} wet and she's angrily gripping one of those tubes Sibyl calls a {i}burette{/i} like she's going to jam it up Sierra's butt."
    S "Would you like to review my work, Clover?"
    "Sibyl turns to offer the worksheet out to me to verify our lab findings. It doesn't make any real sense to me but it's good to see Sibyl return to her usual self once again."
    scene bg black with dissolve
    scene bg library with dissolve
    "I keep trying my hardest to break through to Sibyl, but my efforts seem only to be doing the opposite."
    "Rather than make her fall in love wih me, I feel like she is only getting pushed further away."
    "I know I'm not exactly an expert at seduction, but whereas she would previously laugh off whatever I try as me being silly, now she just gives me a serious reply and a kind smile."
    "While picking through a stack of returns in the library one evening, I come across a book title which I think I can use to flirt with."
    C "Hey, Sibyl check it out! I didn't know they wrote a book about you?"
    "I hold back the book for just long enough to pique her interest and draw her attention away from the new novel she picked up just a few minutes ago."
    C "It's {i}A Little Princess{/i}. Because you're so cute and good at etiquette class. ...Get it?"
    "I wave the book I found in front of Sibyl, but her expression remains particularly stony."
    S "You don't know anything about that book, do you?"
    C "Well the... girl on the cover kind of looks like you, doesn't she?"
    S "It's about a girl who becomes an orphan and all the terrible things that surround that."
    C "O-Oh sorry, I didn't realize..."
    "I quickly stuff the book behind my back and offer Sibyl the most sheepish apology possible."
    "After having been making such a big mess about my parents' divorce and then showing her all the things they sent me to show they love me, I try to leave Sibyl out of my family life for now."
    S "It's okay, Clover. I know you didn't mean anything by it. And the story ends well enough I suppose."
    "Somehow I am not surprised that Sibyl has read this random book I pulled off the shelves as well. Knowing now that it is about an orphan girl, perhaps it is not mere coincidence."
    S "I'm fine with it, you know? Being an orphan, I mean. My foster families have always been kind and welcoming."
    "This topic is something I've rarely heard Sibyl bring up since she first told me. She always seems rather positive about it, but somehow I feel like there's some lack of depth behind the smile."
    C "(Maybe it's the way that she always seems to be looking down when she speaks about it. I'd rather see her looking up!)"
    "When I sit down across the table from Sibyl she looks back up again, right at me."
    S "Sorry, I'm spoiling the mood, aren't I?"
    S "Just know that I am doing well just the way I am. I have a big future ahead of me and lots of plans, so don't you worry. I can read it on your face, you know."
    "Seeing Sibyl cheer up goes a long way to helping me shake off the awkwardness of my blunder just moments before."
    C "What sort of plans do you have, Sibyl? Are you going to be an author... or some kind of fancy artists?"
    S "Maybe, I would probably have to attend an art school for that, though, and I don't know if I'm good enough."
    C "You're good enough! You're {b}way{/b} good enough for sure!"
    "Sibyl laughs softly and tells me to calm down and that her art is't anything special, despite my protests."
    S "What I mean is that I want to be a mother. Some day I am going to have a big, happy family and I'll be the best mother in the world."
    "Unlike before, I can now see the warmth fill in behind SIbyl's cool blue eyes."
    C "You'll be the best foster mother ever, I'm sure of it."
    S "I may foster some children, but I want my own children to love too. I want them more than anything."
    C "Y-Yeah. ...Science is getting pretty good these days."
    "My reply comes out loose and mumbling. I can feel my body go stiff and hands clam up as I sit at the table across from Sibyl."
    "Perhaps Sibyl notices, because she reaches across to take my hand, which instantly revives me with its warmth."
    S "Clover, you will always be my {b}friend{/b}. No matter what happens, know that I will {b}always{/b} here here for you, and I hope I can count on the same from you."
    "I hope she doesn't feel my hand tremble when she says the word \"friend\"."
    C "(Yeah, I want to be her friend. I want to be her {b}girl{/b}friend!)"
    "I try to play it cool, but my brain is screaming out to tell her I need to be more than \"friends\" with her. At the same time, some small part of me is telling my brain that maybe it should stay silent."
    C "O-Of course, Sibyl. You're my best friend in the world."
    "Sibyl smiles so brightly when I reply to her that I think my heart is going to burst out of my chest. She releases my hand, thankfully, so she definitely can't feel me heart about to explode."
    "I sit there for what must be a few minutes but feels like hours, just contemplating the short exchange we just had while Sibyl silently returns to her novel across from me."
    "The only realization that I come to is that I will have to do the one thing I most wish I would not have to."
    jump beg_twins

label beg_twins:
    scene bg transition with fade
    scene bg black with dissolve
    "I don't want to do it. I said I'd never do it again. I {b}hate{/b} that this is my only option left."
    scene bg meeting with dissolve
    H "What is this? Has our surly little Miss Lovestruck came crawling back?"
    O "Surely this does not bode well at all for her fortunes of the heart."
    "The twins immediately start circling me like vultures when I find them alone together. I just stand there and let them get their teasing out of their systems."
    C "(You {b}need{/b} their help, Clover. You can't do it alone.)"
    "Steeling myself, I finally disturb their play time and get right to heart of the matter, at which point they also stop their circling to listen to me."
    C "I need your help with Sibyl."
    "I swallow the thick lump forming in my throat, feeling kind of sick for having voiced what I did."
    "With Sibyl and Tanya away at their art club session and all my own attempts failing, it's basically now or never to get the assistance I need to make her mine."
    O "You need {b}our{/b} help?"
    H "You wish to consort with \"devils\" such as us?"
    C "Go ahead and have your fun at my expense. I'm desperate, okay?"
    "Finding me no longer pushing back against them, the set of twins return to a more relaxed posture, each taking their seat around the big table. I find my own seat, glad to have them finally back off."
    O "Well, what have you tried?"
    "I pause for just a moment, trying to think up how to summarize everything I learned, what I have tried, and how those results never really panned out."
    C "I'm pretty new at this whole thing so I did some research on the Internet and tried to use them on Sibyl."
    H "Sibyl does not seem the type to respond well to pick up lines."
    "I'm a little surprised at how rationally Vittoria is listening to me. It's quite possible that how I have acted in the past only encourages she and her sister to act out further."
    C "No, not pick up lines. I mean, like, the basics. I have been trying to pay her compliments, take an interest in her life, and introduce small touches into our everyday exchanges."
    O "That is a good start. How has she responded to those?"
    C "Well... normal at first. She would just laugh it off like always when I would say something dumb."
    C "But more recently Sibyl just gives me a polite reply and goes on about what she is doing like it never even happened." 
    "The twins look toward each other in quiet communication, then back toward me."
    O "At some point, you will have to give up."
    C "B-But...! Don't you have some surefire way to win her over? I mean, you're doing it all the time with other girls!"
    H "We are not {b}witches{/b}, Clover. There is no magic love potion."
    O "If she is not at all receptive to your advances then there is simply nothing to be done about it."
    C "No! I refuse to accept that!"
    "I'm standing out of my chair before I know it. I'm not mad at them exactly, merely mad that these two are so cool about telling me my love is in vain, again."
    C "Isn't there {b}anything{/b} you can do?"
    H "Well, we do have certain methods...."
    O "If you're up to the task..."
    "I can just feel how they're drawing me out for something now. That infuriating lilt of their voices that they use for teasing returns once more."
    C "I'll do anything!"
    H "{b}Anything{/b} she says."
    "Vittoria gives a frisky grin to her sister, who returns the playful grin back to me."
    O "Are you {b}sure{/b} about that, Clover?"
    "The twins both smile back at me silently. I feel a hunger emanating from Vittoria which makes me shiver to my toes, while from Vincenza I sense a different but no less disturbing desire."
    "All sorts of possibilities flow through my imagination, each one more extreme and less pleasant than the next."
    C "(But this is {b}Sibyl{/b} on the line here.)"
    "In the end, the choice is clear. Nothing matters as much as Sibyl, and so I give my assurances through gritted teeth"
    C "What would you have me do?"
    O "Beg for us."
    C "{b}Beg!?{/b} Like, grovel on my knees before you and kiss your shoes!?"
    H "Y—"
    O "A delightful idea but for now not necessary. Just tell us clearly how you want and {b}need{/b} our help. I want you to say {b}please{/b} and {b}mean{/b} it."
    C "Ugh!"
    "That Vincenza silenced her sister is the biggest surprise here, and that Vittoria accepted it. I thought they shared a mind entirely as one, but maybe sharing also means having to give and take sometimes."
    "Vittoria wants my body, that much is clear. I thought that would be the worst of it, but Vincenza wants something far more dangerous."
    C "(Vincenza wants my {b}pride{/b}.)"
    "She knows that for a stubborn and spirited girl like me, that is most truly what I cannot let be sullied. And so here she is, asking for me to willingly have it debased before them."
    "I knew I wouldn't like whatever the price of this would be, and sure enough, I don't like it. The alternative, however, would be to let go of my love for Sibyl forever, and that is not an option."
    C "Fine."
    H "We're waiting, Clover."
    "I grit my teeth again and push out the words to get it over with."
    C "Please, I beg you."
    O "Who is this \"you\" person? We have names."
    C "Vincenza and Vittoria, I beg you to help me."
    H "What is it you want our help with, dear?"
    "They're toying with me again, I know it, but there's nothing left for me but to play along."
    C "Please, Vincenza and Vittoria, I beg you help me make Sibyl fall in love with me!"
    H "Very good!"
    O "Thank you."
    "With this, both of the twins appear pleased enough. It's a hit to my pride, but that's a small price to pay for a miracle such that I require."
    C "So you'll do it?"
    H "We are women of our words, Clover."
    O "I promise that Vittoria and I, as well as some of our choice associates..."
    "There's a pause where the two glance to each other again, clearly already formulating plans between them already."
    O "...Will do what we can to help you. Keep in mind that all we can do is give you and Sibyl a push."
    H "The rest is up to you. You must be willing to give it your all."
    C "I-I am!"
    O "Be confident. Push yourself onto her if you have to."
    H "Use your wiles. {b}All{/b} of them. Maybe hike your skirt up a little."
    "That I don't know exactly what the twins have planned concerns me slightly, but with a renewed fire in my heart I commit their advice to memory."
    jump aqua_date

label aqua_date:
    scene bg transition with fade
    scene bg hallway with dissolve
    "I don't have to wait long to see the results of sacrificing my dignity to Vincenza and Vittoria."
    "That Saturday afternoon, the twins deliver an odd request to Sibyl personally."
    S "You don't have to come with me, Clover. They said it's a two person job but I can handle a few fish by myself."
    C "No, it's okay! I was getting tired of trying to wrap my head around trigonometrics anyway."
    "Excitement speeds my limbs into walking extra fast to the point where I'm almost racing ahead of Sibyl toward the aquarium."
    "I don't know exactly what they have planned, but it cannot be a coincidence that they ask this specifically of Sibyl and tell her to bring someone with her."
    C "(And at a time that Tanya isn't around too!)"
    scene bg aquarium with dissolve
    S "What's all this?"
    "I have the same reaction at first when I see the aquarium over Sibyl's shoulder, but then I think it's absolutely perfect."
    C "(I can work with this. Come on, Clover, time to strut your stuff!)"
    "It's the same old aquarium as the one I had that confrontation with Tanya in when I first got here, but the twins clearly dialed it up a notch to make it perfectly romantic."
    "A couple dozen candles, at least, all flicker at random where they're placed around the room, their little lights becoming twisted amongst the tanks and casting moving fish shadows on the walls."
    "From somewhere hidden away emanates the easy tones of soft jazz, and in the center of the room sits a huge bean bag that looks just big enough for two people to comfortably sink into it."
    S "Do you think the President and Vice President used this for their... \"extracurricular lessons\"?"
    C "(Is that what they call it?)"
    "Sibyl flicks on the light switch, dispelling the uniquely alluring atmosphere and steps into the room fully."
    "Having none of that when it's all so perfect and exactly what I need, I flick it back off behind her and step in after my prize."
    C "Oh come on, doesn't this look so cool? I mean, look at this bean bag!"
    "I flop right down into it and immediately sink more deeply than I expect into it's depths, but try to remain cool despite that. Subtly, I try to raise the hem of my skirt way up my thigh like it just landed that way."
    C "It's so comfortable, you {b}have{/b} to try this!"
    "I pat at the empty space beside me, knowing she's definitely going to be sinking deeper into the bag right next to me if she sits down, just as planned."
    S "Eww, no thanks. I don't want to know what's soaked into that thing."
    "Before I can say any more, Sibyl has already stepped over to blow out one of the many candles providing the atmosphere in the room."
    C "Hey, what are you doing!?"
    S "These candles are a fire hazard."
    "Puff go another three candles before I can extricate myself from the extraordinarily deep bean bag and squeeze my way between Sibyl and the next candle."
    C "M-Maybe leave some lit up for now?"
    "I try to lean casually against the fish tank between Sibyl and the candle behind me, while also holding my arms together before me in such a way to squeeze my boobs together so they look bigger."
    S "What's gotten into you, Clover?"
    show choice_darkness with dissolve
        menu:
            "\"I just... think we shouldn't rush to waste this nice atmosphere, that's all.\"":
                hide choice_darkness with dissolve
                C "I just... think we shouldn't rush to waste this nice atmosphere, that's all."
                S "Clover, I think they set this all up for {b}sex{/b} with their \"conquests\"."
                "Part of me does think this is just way too perfect for it to be something they thought of last minute, but I don't care. It's exactly what I need right now, so I just feign surprise at Sibyl's words."
                C "You think so?"
                S "Just from knowing the twins since the start of the year? Yes, I think so."
                S "They're super helpful when they want to be, but I just don't agree with their \"peculiarities\"."
                "The excitement inside my suddenly douses like the candles Sibyl is wont to snuff."
                C "You mean because they're... gay?"
                "The lights flick on to dispel the atmosphere again after Sibyl brushes past me to end the mood once and for all."
                S "It's not that they're gay. I just think two people shouldn't do that unless they're in love."
                "Instantly, my soul is revived."
                C "I get what you mean! I think doing \"that\" with the person you're in love with would be amazing!"
                "I very nearly blurt out that I want to do it with her right then and there but hold my tongue enough to quickly step over and grab her hands for one last go at winning her over."
            "\"I'm all hyped up from lacrosse practice this morning.\"":
                hide choice_darkness with dissolve
                C "I'm all hyped up from lacrosse practice this morning."
                "The first thing that comes to mind also tumbles right out of my mouth."
                C "...I got, like, so jittery and excited from that, and now that I'm free from the trigonometry all the energy is coming back again. That's all!"
                S "I'm happy you're enjoying lacrosse, Clover! Have you been getting along well with Tanya?"
                C "(Why is she talking about Tanya at a time like this? Can't you see that we're having a moment?)"
                "But the moment doesn't seem to be the same one that Sibyl is having, because she brushes right past me again to flip on the lights and dispel the atmosphere for good."
                "Defeated for the moment, I answer the question while trying to think of my next attempt to claw my way inside her heart."
                C "Yeah. She's pretty good at lacrosse and I've learned a lot."
                "Honestly, we barely interact excess when we meet during play."
                C "(She {b}is{/b} pretty good at the game, to be fair.)"
                S "That's great news! I think the two of you could be best friends if you both give it a try."
                "Not content to let this opportunity be wasted, I slip right back in front of Sibyl and take her hands for one last \"Hail Mary\" attempt."
    C "The music is pretty good, isn't it? Want to dance?"
    "Sibyl just smiles at me softly, then takes her hands back from mine."
    S "We're just here to feed the fish, Clover."
    "Just like that, the whole evening is wasted. I gave it my all and Sibyl shut me down very single time."
    C "(Is she just dense or what? Do I have to come right out and say it? {b}Should{/b} I have? Did I miss my chance?)"
    "The questions about my failed allurement plague me all the way through feeding the fish and well into the remainder of my math homework."
    jump tanya_trouble

label tanya_trouble:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "Breakfast on Sunday starts like any other, except that something is clearly eating at Tanya."
    "Sibyl tries to pry it out of her, to no avail. It's not really my concern at all, so I just happily eat away at my French toast until I'm ready for seconds."
    C "I'm going to go grab another plate. I'll be right back!"
    scene bg kitchens with dissolve
    "I'm not disappointed about my failure to finally win over Sibyl last evening, not when I have so much sugar and syrup flowing through my veins."
    C "(There will be more chances. Vittoria and Vincenza will have something up their sleeves, or those \"associates\" they spoke of will.)"
    "My only priority for the moment is getting back in line to order another stack of my favorite breakfast from the chefs, but even that gets ruined right away."
    T "Come with me."
    "I feel a sharp tug at my arm just as I hear the words spoken softly in my ear, and nearly stumble as I'm pulled out of the line."
    C "What the hell was that about—"
    T "Stop making a scene. I just want to talk. Somewhere private."
    "Tanya is being particularly terse, but not overtly hostile aside from the initial jerk to my body."
    C "(You're {b}already{/b} making a scene!)"
    "The other girls in the line for the chefs stare at us, some more overtly than others, but everyone in the cafeteria proper can't see us."
    C "I don't care what's wrong with you. Go tell it to Sibyl."
    T "It's not about me, it's about Sibyl."
    scene bg dorm with dissolve
    "After just a little bit more of half-whispered back and forth arguing, I end up around the corner of the hallway just outside the cafeteria alongside Tanya."
    C "What's your {b}problem{/b}, Tanya?"
    "She's more irritable than normal today, that much was clear before, but as she looks at me she's practically throwing daggers with her eyes."
    T "What's {b}my{/b} problem? I thought I {b}told{/b} you to stay away from Sibyl!"
    C "I can do whatever I want with Sibyl. She's {b}my{/b} Vertu."
    T "She's her own person, not yours to do whatever you want with!"
    T "I heard all about it, you know — that Vincenza and Vittoria are trying to set you two up together. They think it's as foolish as I do."
    C "(Yet they're still doing it anyway! Because they know I still have a chance!)"
    "It's a surprise to me that the twins told her about this at all, let alone after less than a day, but as I think back I never did tell them to keep it a secret. That should have been understood."
    C "What about it? If she's her own person why do you have to get in my way of pursuing her?"
    T "First of all, because she's never love you and all you're doing is causing her pain, and secondly, because I—... I \"like\" Sibyl too."
    C "Okay? We both know she's going to be your friend no matter what so just back off."
    T "For the love of God, Clover, how can you be so dense! I {b}love{/b} Sibyl. Just like you do."
    "This surprises me probably more so than it should. It actually makes a lot of sense with a brief moment to think about it, even with Tanya still angrily close to me in the hallway."
    C "S-So, what? It's her choice if she wants to go out with me. You've had {b}months{/b} already to take your shot."
    T "Arrgh! Clover, will you {b}listen{/b}!? There is no \"shot\" to take. Sibyl is straight and that's the end of it."
    T "My feelings for her aside, you're only going to hurt her if you keep pursuing her like this."
    C "That's exactly what a love rival would say to make me give up on her."
    T "Yes, exactly, I'm {b}trying{/b} to make you give up on her! {b}I{/b} already gave up on her and am content to be her friend."
    "Tanya keeps saying things forcefully in my direction, nearly backing me against the wall. I make my own attempt at trying to look cool and unbothered despite how annoyed she is making me."
    C "Maybe {b}you{/b} just don't love her enough if you gave up so easily."
    T "Would you {b}please{/b} think about someone beside {b}yourself{/b} for a minute?"
    "Tanya gets that look in her eyes that she's about to rip my hair out of head for just a moment, but cools herself down quickly with a few deep breaths."
    T "I'm not going to let you get to me again, Clover. If you want to think about it from your perspective, fine."
    T "Consider this: if things don't work out as you hope, and they won't, it will be incredibly awkward between the two of you. If you value your friendship with her, you should just accept that it's over."
    "It's a good point and we both know it. I don't want to admit, but te thought has crossed my mind before."
    C "Okay, yeah, I've thought of that, but what do you want me to do, deny my feelings forever?"
    "There's a sigh of relief from Tanya that I've finally come to the conclusion that has prepared for me."
    "Her anger is way down and way more like defeat instead, and I find myself cooled down similarly now that she's not quietly screaming in my face."
    T "If you have to, yeah. It's not easy but it's what's best for both of you."
    "Tanya pushes her back against the wall beside me, turning her head away. She mumbles quiet to herself."
    T "Izzie was right; straight girls are the worst."
    C "What was that?"
    T "Nothing. You're just absolutely infuriating in every way, you know that?"
    "I know Tanya is being dead serious when she says it, but with the slump of defeat in her tone of voice, it actually sounds kind of friendly in some strange way."
    C "(Maybe I can reconcile I little bit with her. I never did get around to that one step of the process about \"making friends with her friends\" at all.)"
    "Trying my best to summon up as much reconciliation as I can, I strike out a sympathetic but firm tone with Tanya."
    C "I'm not giving up on Sibyl, Tanya, but I do appreciate how much you care about her. I promise that I would never do anything to hurt her."
    "Tanya's face turns sour, or perhaps better described as bitter, while I calmly tell her that I have absolutely no plans to give up on Sibyl. She remains calm nonetheless, and searches my eyes with her own."
    T "Your strong will would be admirable if it weren't so misplaced, Clover."
    C "I could say the same about you, Tanya."
    T "So what now? We agree to disagree, and I come back to beat your ass when you eventually make Sibyl cry?"
    C "Unlikely, seeing as how I'm going to make her fall madly in love with me in no time."
    "Tanya snorts dramatically with disbelief at my unflinching assertion, but I don't take it personally."
    T "What do you even love about her anyway? You've known her for a {b}month{/b}."
    C "Well, she's totally amazing at everything, isn't she? She's kind, and playful, and..."
    T "And what? Lots of people are kind and playful."
    C "(Why {b}do{/b} I love Sibyl?)"
    "I can feel it so intensely in my chest, but when I try to compress those feelings into the form of words, nothing really seems to fit properly."
    C "Well she's super gorgeous. Her hair seems to shimmer in the sunlight, and at the same time her eyes sparkle like bright blue sapphires—"
    T "Aquamarine."
    C "What?"
    T "Sapphires are dark blue. Aquamarine are light blue, like Sibyl's eyes."
    C "Huh, yeah... aquamarine."
    "For a moment I am lost in thinking about Sibyl's eyes and how well the aquamarine description fits them, but a sudden small outburst from Tanya beside me breaks the hold."
    T "I can't {b}believe{/b} you."
    C "What are you on about now?"
    T "All this and you don't even know why you love her. Are you sure you're not just, like, mega horny?"
    C "What? No! I'm not—"
    "I pause for a moment to consider what Tanya says, finding it perhaps more accurate than I'd like to admit, which gives Tanya a terrible shock that shows clearly on her face."
    C "Wait, no, I'm totally serious about Sibyl, for real!"
    T "If you don't actually love about her as a person I'm going to murder you for real, and you can quote me on that that in your own blood writing for when the police find your body."
    C "What do {b}you{/b} love about Sibyl anyway?"
    "I deflect the question right back at Tanya to get her off my case and maybe find out what I truly love about Sibyl based upon what she says."
    T "Her compassion, warm and limitless. Her freedom, so simple and joyous."
    "I don't get the chance to ask her what she means by \"freedom\" as the bell rings to signal the end of the lunch period and we both realize we've left Sibyl alone way too long."
    scene bg cafeteria with dissolve
    "When we both return together to the table, the worries expression on Sibyl's face almost breaks my heart just like it's probably doing to Tanya."
    "She doesn't even need to ask the question before we answer with our own little white lies."
    T "Something was wrong with the toilets."
    C "...The kitchen line was really long."
    S "Is that all? Good."
    C "(What did she think was happening?)"
    "Our excuses do much to alleviate Sibyl's concerns, and I am relieved to find a bright smile back upon her face in no time now that Tanya and I have returned to her."
    jump gymclassflirt

label gymclassflirt:
    scene bg transition with fade
    scene bg black with dissolve
    