
label howto:
    scene bg bedroom with dissolve
    "The twins don't chase me as I stomp down the hallway back the way I came."
    "With my mind whirling and nowhere in particular to go I end up returning back to my dorm room where I come face to face suddenly with Sibyl."
    C "Eyeep!"
    "A little squeal of surprise leaks from my lips from suddenly and unexpectedly confronting the girl who has my brain all mixed up so badly."
    "She greets me warmly as she does every morning and thankfully doesn't notice anything off about me that I can't blame on my \"illness\" from the night before."
    "After fending off her concerns for my illness, I sit down at my desk to try to actually do some of that homework that I meant to do yesterday, but find my mind always diverted elsewhere."
    C "(The sine is... the ratio of the side opposite the angle to the hypotenuse.)"
    C "(...Hippopotenuse. Sibyl would think that's funny.)"
    "My fingers flick my mechanical pencil against a diagram of a right triangle while my gaze flicks aside to where Sibyl reclines on her bed."
    "Sibyl finished her homework last night while I was in bed pretending to be sick. Her beautiful, clear blue eyes now sweep from side to side as she reads through the lines of her latest novel."
    "Turning back to my homework, I try to wrap my head around trigonometry once again, but just as quickly have my mind pulled away to more important matters to my well-being."
    "Idly, I pencil in a \"C\" at one end of a hypotenuse, and \"S\" at the other. On the right angle, I draw in a small \"T\" as an aside."
    C "(Hmm...)"
    "I stare at the labelled right triangle so long that the image gets burned into my brain, but nothing comes to mind that will make the hypotenuse shorter and brings those two letters together."
    "Taking a different approach, I pick up my smartphone and flip to a fresh page of my notebook."
    "The keyboard on my screen flickers to life as I type my question into the search bar: \"how to make a girl fall in love with you\"."
    C "(\"Six Simple Steps\"? Is that all it takes?)"
    "I jot down the highlights into a series of bullet points and leave plenty of space in between to fill in my notes."
    C "(Step One: Be yourself!)"
    "There's a whole paragraph that follows it, but I entirely skip reading all that because I've never been anyone {b}but{/b} myself."
    "In the empty lines I left to take notes of what I should do to fulfill each step, I draw a giant check mark to take up the space."
    C "(Step Two: Look good and feel good!)"
    "Sibyl might be far and away more beautiful with her soft, fluffy hair and eyes that anyone would get lost in, but I think I'm decently pretty the way I am, and especially after ditching the goth gear."
    C "(Blondes are pretty popular, right? So I've got that going for me too.)"
    "As far as \"feeling\" good, that's easy. I haven't felt as good than I do now since before all the nastiness of the fallout with my middle school friends and my parents' divorce."
    C "(Ugh...)"
    "The thoughts come out so lightheartedly in my mind, but I unexpectedly find that those wounds still strike surprisingly deep even after having thought I'd made peace with them."
    C "(Sibyl has it worse than me. She never even knew her parents.)"
    "My pen scrawls out a slightly more modest check mark for the second step of the list. My wounds have not fully healed, but if I can win over Sibyl they won't hurt anywhere near as bad."
    C "(Step Three: Take an interest in her!)"
    "I have to read further on with this one, because obviously I'm interested in her or I wouldn't be here searching on the web for how to win her heart like this."
    "As it turns out, what the step wants me to do is be open and communicative, and also take an interest in her life and hobbies."
    C "(I've already {b}been{/b} doing that!)"
    "With a broad smile, I give step three another big check mark. Proud of myself, I snatch another gaze aside at the girl I'm going to win over to reward myself for being so well ahead of all the steps."
    C "(Step Four: Befriend her friends!)"
    "I have to re-read step four more than once to be sure that I read it correctly the first time, but the words don't change before my eyes whatsoever."
    "The nervous habit of tapping my pencil against the paper emerges once again as I stare into the blank lines I left under the step. I know what I need to write in there but lack the courage to do so."
    C "(If it means making Sibyl mine... I will do it.)"
    "In small print I write simply, \"befriend Tanya\"."
    C "(Enough of that. Step Five: Be flirtatious!)"
    "Once again, I physically blink at the outrageously simple heading for something so difficult."
    C "(Why does it just {b}assume{/b} I know how to flirt?)"
    "I read through the paragraph below the step header for more details. It's clearly written with a guy in mind, but it's not entirely unhelpful for me either."
    C "(\"Make her known you're interested in more than friendship.\" Smiling, frequent eye contact, playful comments...)"
    "I read on further to try to find out how this is any different from normal friendship, but entirely fail to understand what makes flirting \"flirting\"."
    C "(And the first three steps were going to smoothly too...)"
    "Ultimately, I just note it down as something to do more research on later and work on further."
    C "(Step Six: Get physical!)"
    "At first I think this step is something salacious, and some salacious thoughts quickly follow, but it turns out to mean using small touches to increase our physical bond."
    "I don't immediately see how this is possible to be done smoothly, but feel confident enough that I can work simple touches into our everyday routines."
    C "Okay, done! Now I just need to work on those... few tricky parts."
    "Skipping quickly over step four, I review the other steps to my master seduction plan and decide to put it into practice right away."
    C "Sibyl!"
    "My crush's name slips smooth as silk from my lips as I walk over to her bed. Her attention draws away from her novel and onto me, just as planned."
    C "What's up, Clover? Need some help with the homework?"
    "My feet pause when I reach her bed, and thinking quickly, I sit right on the edge and place my hand casually on her shoulder."
    C "Your eyes are so pretty. What's your favorite color?"
    "It's a sure win, so I think initially, but every passing microsecond that Sibyl gives me a strange look like I'm not even speaking English lessens my confidence."
    S "...Yellow."
    S "Are you sure you're feeling all right, Clover?"
    "Sibyl turns quickly to face me, far too close for comfort given the emotional state I'm in right now, and lays her palm against my forehead."
    S "You feel warm..."
    C "(That's because you're so close!)"
    C "Yup, so good, never better!"
    "Sibyl doesn't seem to think me any more sane than before so I just take the little victories I've earned and play off the rest as an awkward way of asking for help with homework."
    "As it turns out, homework is {b}so{/b} much more enjoyable when Sibyl is sitting close beside me and explaining everything right into my ear. I get done with plenty of time to spare before lunch ends."
    jump make_up_with_tanya

label make_up_with_tanya:
    scene bg black with fade
    scene bg locker with dissolve
    