
label howto:
    scene bg bedroom with dissolve
    "The twins don't chase me as I stomp down the hallway back the way I came."
    "With my mind whirling and nowhere in particular to go I end up returning back to my dorm room where I come face to face suddenly with Sibyl."
    C "Eyeep!"
    "A little squeal of surprise leaks from my lips from suddenly having to confront the girl who has my brain all mixed up so badly."
    "After fending off her concerns for my illness, I sit down at my desk to try to actually do some of that homework that I meant to do yesterday, but find my mind always diverted elsewhere."
    C "(The sine is... the ratio of the side opposite the angle to the hypotenuse.)"
    C "(...Hippopotenuse. Sibyl would think that's funny.)"
    "My fingers flick my mechanical pencil against a diagram of a right triangle while my gaze flicks aside to where Sibyl reclines on her bed."
    "Sibyl finished her homework last night while I was in bed pretending to be sick. Her beautiful blue eyes now sweep from side to side as she reads through the lines of her latest novel."
    "Turning back to my homework, I try to wrap my head around trigonometry once again but just as quickly have my mind pulled away to more important matters to my well-being."
    "Idly, I pencil in a \"C\" at one end of a hypotenuse, and \"S\" at the other. On the right angle, I draw in a small \"T\" as an aside."
    C "(Hmm...)"
    "I stare at the labelled right triangle so long that the image gets burned into my brain but nothing comes to mind that will make the hypotenuse shorter and brings those two letters together."
    "Taking a different approach, I pick up my smartphone and flip to a fresh page of my notebook."
    "The keyboard on my screen flickers to life as I type my question into the search bar: \"how to make a girl fall in love with you\"."
    C "(\"Six Simple Steps\"? Is that all it takes?)"
    "I jot down the highlights into a series of bullet points and leave plenty of space in between to fill in my notes."
    C "(Step One: Be yourself!)"
    "There's a whole paragraph that follows it but I skip reading all that in its entirety because I've never been anyone {b}but{/b} myself."
    "In the empty lines I left to take notes of what I should do to fulfill the first step I draw a giant check mark to take up the space."
    C "(Step Two: Look good and feel good!)"
    "Sibyl might be far and away more beautiful with her soft, fluffy hair and eyes that anyone would get lost in, but I think I'm decently pretty the way I am after ditching the goth gear."
    C "(Blondes are pretty popular, right? So I've got that going for me too.)"
    "As far as \"feeling\" good, that's easy. I haven't felt as good than I do now since before all the nastiness of the fallout with my middle school friends and my parents' divorce."
    C "(Ugh...)"
    "What is supposed to be an optimistic thought I unexpectedly find still strike at surprisingly deep wounds even after having thought I'd made peace with them."
    C "(Sibyl has it worse than me. She never even knew her parents.)"
    "My pen scrawls out a slightly more modest check mark for the second step of the list. My wounds have not fully healed but if I can win over Sibyl they won't hurt anywhere near as bad."
    C "(Step Three: Take an interest in her!)"
    "I have to read further on with this one because obviously I'm interested in her or I wouldn't be here searching on the web for how to win her heart like this."
    "What the step wants me to do is be open and communicative, and also take an interest in her life and hobbies."
    C "(I've already been doing that, but I can do more too!)"
    "With a broad smile, I give step three another big check mark. Proud of myself, I snatch another gaze aside at the girl I'm going to win over to reward myself for being so well ahead of all the steps."
    C "(Step Four: Befriend her friends!)"
    "I have to re-read step four more than once to be sure that I read it correctly the first time but the words don't change no matter how many times I read them."
    "The nervous habit of tapping my pencil against the paper emerges once again as I stare into the blank lines I left under the step. I know what I need to write in there but lack the courage to do so."
    C "(If it means making Sibyl mine... I will do it.)"
    "In small print I write simply, \"befriend Tanya\"."
    C "(Enough of that. Step Five: Be flirtatious!)"
    "Once again, I physically blink at the outrageously simple heading for something so difficult."
    C "(Why does it just {b}assume{/b} I know how to flirt?)"
    "I read through the paragraph below the step header for more details. It's clearly written with a guy in mind but it's not entirely unhelpful for me either."
    C "(\"Make her known you're interested in more than friendship.\" Smiling, frequent eye contact, playful comments...)"
    "I read on further to try to find out how this is any different from normal friendship, but entirely fail to understand what makes flirting \"flirting\"."
    C "(And the first three steps were going to smoothly too...)"
    "Ultimately, I just note it down as something to do more research on later and work on further."
    C "(Step Six: Get physical!)"
    "At first I think this step is something salacious but it turns out to mean using small touches to increase our physical bond."
    "I don't immediately see how this is possible to be done smoothly but feel confident enough that I can work simple touches into our everyday routines."
    C "Okay, done! Now I just need to work on those few tricky parts."
    "Skipping quickly over step four, I review the other steps to my master seduction plan and decide to put it into practice right away."
    C "Sibyl!"
    "My crush's name slips smooth as silk from my lips as I walk over to her bed. Her attention draws away from her novel and onto me, just as planned."
    C "What's up, Clover? Need some help with the homework?"
    "My feet pause when I reach her bed. Thinking quickly, I sit right on the edge and place my hand casually on her shoulder."
    C "Your eyes are so pretty. What's your favorite color?"
    "It's a sure win, so I think initially, but every passing microsecond that Sibyl gives me a strange look like I'm not even speaking English lessens my confidence."
    S "...Yellow."
    S "Are you sure you're feeling all right, Clover?"
    "Sibyl turns quickly to face me, far too close for comfort given the emotional state I'm in right now, and lays her palm against my forehead."
    S "You feel warm..."
    C "(That's because you're so close!)"
    C "Yup, so good, never better!"
    "Sibyl doesn't seem to think me any more sane than before so I just take the little victories I've earned and play off the rest as an awkward way of asking for help with homework."
    "As it turns out, homework is {b}so{/b} much more enjoyable when Sibyl is sitting close beside me and explaining everything right into my ear. I almost don't want to it be over so quickly."
    jump failed_seduction

label failed_seduction:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "At lunch, I take the seat at Sibyl's other side completely opposite of Tanya rather than sit across from her as usual."
    "I intentionally sit close enough that I'm sure to brush my shoulders against her plenty. When Sibyl scooches down the bench slightly, I subtly do the same until we're rubbing shoulders once again."
    S "Is there something wrong with the other side of the table, Clover?"
    C "No. I just felt like sitting next to you today."
    "In truth, I prefer to be opposite of Sibyl where I can enjoy each expression as she converses with Tanya, from the way her cheeks puff up wth laughter to how high her eyebrows raise with surprise."
    S "That's all well and good, but I feel like a sardine."
    C "No way! You're not extremely salty and disgusting!"
    S "I meant how they're always tightly packed together into cans."
    T "Just move to the other side of the table, Clover."
    "Tanya only now breaks from her back and forth conversation with Sibyl, though I have caught some glowering glances my direction thus far into our mealtime."
    C "Why don't you? Didn't you used to sit on the other side every day before I did?"
    T "After {b}you{/b} took my spot, I have come to enjoy sitting beside Sibyl."
    C "But I want to sit beside Sibyl too!"
    S "You can both be so {b}stubborn{/b} sometimes!"
    "Sibyl stands right up and moves to the other side of the table herself, leaving a Sibyl-sized hole between me and Tanya which goes unfilled the rest of the meal."
    scene bg black with dissolve
    scene bg classroom with dissolve
    "Sibyl returns from the front of our science classroom with a tray full of small vials of differently colored mystery liquids."
    C "So what are all these vials for?"
    S "Were you even listening during the lecture?"
    "I honestly was not. It's so hard to concentrate when our science teacher starts droning on, and I never had the head for math or science to begin with unlike Sibyl."
    C "Sorry. I kinda zoned out."
    S "You've been kinda spacey lately, Clover. Are you sure you're alright?"
    C "Never better!"
    "I try to reassure her that I'm just fine without giving away my strong new feelings for her before she's ready to accept them. Sibyl gives me a suspicious glance but turns back to her work."
    S "The abstract for the experiment should go over the basics. Please read through it while I sort these out."
    "Lifting up the page, I read the title of the experiment we are doing today."
    "\"Determining Acidity by Titration with an Indicator Solution\""
    C "What's a \"tit-ration\"."
    S "{b}Titration{/b}."
    "Sibyl corrects me quickly, probably embarrassed with how I pronounced the words in an entirely different fashion."
    C "(I want some of Sibyl's tit-rations.)"
    S "Titration is adding a solution with a known concentration into a a solution with an unknown solution to determine concentration."
    S "For the purposes of our lab, we are going to first note the color change as we add the {i}titrant{/i}."
    C "(Tit-rant.)"
    "I must be feeling extras stupid today, as well as extra horny. Every since discovering what I feel about Sibyl it's just about all I can think about."
    "Sibyl goes on to explain even more about the experiment but it only half gets through my head as I zone out once more to focus on how pretty she looks while concentrating."
    C "(She's doing it again!)"
    "Just like when she's focused intently on her own artwork, Sibyl does the thing where her tongue just barely sticks out from between her lips as she moves little drops of liquid between glass vials."
    S "There we go! Would you like to do the honors, Clover?"
    C "Huh? Oh, sure..."
    "Sibyl finishes up whatever she's doing while I'm still gawking and I try to cover up my absentmindedness by pretending I know what I'm doing by volunteering for the next task."
    C "Remind me again how I should do this part?"
    S "Just one drop at time from the pipette. I'll tell you when to stop."
    "The click of a pen tells me it's time to go. I squeeze the dropper ever so slightly and let one drop loose, then turn back expectantly toward Sibyl."
    S "Keep going."
    "We do this a few more times until Sibyl suddenly tells me to hold off. Showing me her notes, she points out the difference in color between the new vial and our control vial."
    S "With this, we can do a small calculation to estimate the concentration difference and plot a titration curve!"
    C "Sibyl, you're a genius!"
    "Sibyl beams at the compliment. What I tell her is no mere flattery; things that make no sense to me suddenly aren't so scary once Sibyl explains them."
    C "Can you just marry me so I don't have to think so hard ever again."
    "With her genial mood as it is I try to squeeze in a little flirting, like planting the idea of marriage in her mind while playing it off as a joke."
    "I even try to reduce the physical distance between us by taking her free hand to examine her ring finger."
    "It's all in good fun, I believe, but the falter in a newly cautious smile upon Sibyl's face tells a very different story than what I'd hoped would play out."
    S "Come now, Clover. You have to learn all this for yourself. I will not always be around."
    C "(Why {b}can't{/b} you be?)"
    "Sibyl withdraws the hand I took of hers to bring back close to her chest, then turn away from me to finish writing down the details of our experimental results."
    C "(She's just worried about my performance on our exams, right?)"
    "While I am left wondering about the shift in mood behind Sibyl's back, I spot Tanya and Sierra at teh far end of the room."
    "Something clearly has gone wrong because Tanya's face is dripping with {b}something{/b} wet and she's angrily gripping one of those tubes Sibyl calls a {i}burette{/i} like she's going to jam it up Sierra's butt."
    S "Would you like to review my work, Clover?"
    "Sibyl turns to offer the worksheet out to me to verify our lab findings. It doesn't make any real sense to me but it's good to see Sibyl return to her usual self once again."
    scene bg black with dissolve
    scene bg library with dissolve
    "I keep trying my hardest to break through to Sibyl, but my efforts seem only to be doing the opposite."
    "Rather than make her fall in love wih me, I feel like she is only getting pushed further away."
    "I know I'm not exactly an expert at seduction, but whereas she would previously laugh off whatever I try as me being silly, now she just gives me a serious reply and a kind smile."
    "While picking through a stack of returns in the library one evening, I come across a book title which I think I can use to flirt with."
    C "Hey, Sibyl check it out! I didn't know they wrote a book about you?"
    "I hold back the book for just long enough to pique her interest and draw her attention away from the new novel she picked up just a few minutes ago."
    C "It's {i}A Little Princess{/i}. Because you're so cute and good at etiquette class. ...Get it?"
    "I wave the book I found in front of Sibyl, but her expression remains particularly stony."
    S "You don't know anything about that book, do you?"
    C "Well the... girl on the cover kind of looks like you, doesn't she?"
    S "It's about a girl who becomes an orphan and all the terrible things that surround that."
    C "O-Oh sorry, I didn't realize..."
    "I quickly stuff the book behind my back and offer Sibyl the most sheepish apology possible."
    "After having been making such a big mess about my parents' divorce and then showing her all the things they sent me to show they love me, I try to leave Sibyl out of my family life for now."
    S "It's okay, Clover. I know you didn't mean anything by it. And the story ends well enough I suppose."
    "Somehow I am not surprised that Sibyl has read this random book I pulled off the shelves as well. Knowing now that it is about an orphan girl, perhaps it is not mere coincidence."
    S "I'm fine with it, you know? Being an orphan, I mean. My foster families have always been kind and welcoming."
    "This topic is something I've rarely heard Sibyl bring up since she first told me. She always seems rather positive about it, but somehow I feel like there's some lack of depth behind the smile."
    C "(Maybe it's the way that she always seems to be looking down when she speaks about it. I'd rather see her looking up!)"
    "When I sit down across the table from Sibyl she looks back up again, right at me."
    S "Sorry, I'm spoiling the mood, aren't I?"
    S "Just know that I am doing well just the way I am. I have a big future ahead of me and lots of plans, so don't you worry. I can read it on your face, you know."
    "Seeing Sibyl cheer up goes a long way to helping me shake off the awkwardness of my blunder just moments before."
    C "What sort of plans do you have, Sibyl? Are you going to be an author... or some kind of fancy artists?"
    S "Maybe, I would probably have to attend an art school for that, though, and I don't know if I'm good enough."
    C "You're good enough! You're {b}way{/b} good enough for sure!"
    "Sibyl laughs softly and tells me to calm down and that her art is't anything special, despite my protests."
    S "What I mean is that I want to be a mother. Some day I am going to have a big, happy family and I'll be the best mother in the world."
    "Unlike before, I can now see the warmth fill in behind SIbyl's cool blue eyes."
    C "You'll be the best foster mother ever, I'm sure of it."
    S "I may foster some children, but I want my own children to love too. I want them more than anything."
    C "Y-Yeah. ...Science is getting pretty good these days."
    "My reply comes out loose and mumbling. I can feel my body go stiff and hands clam up as I sit at the table across from Sibyl."
    "Perhaps Sibyl notices, because she reaches across to take my hand, which instantly revives me with its warmth."
    S "Clover, you will always be my {b}friend{/b}. No matter what happens, know that I will {b}always{/b} here here for you, and I hope I can count on the same from you."
    "I hope she doesn't feel my hand tremble when she says the word \"friend\"."
    C "(Yeah, I want to be her friend. I want to be her {b}girl{/b}friend!)"
    "I try to play it cool, but my brain is screaming out to tell her I need to be more than \"friends\" with her. At the same time, some small part of me is telling my brain that maybe it should stay silent."
    C "O-Of course, Sibyl. You're my best friend in the world."
    "Sibyl smiles so brightly when I reply to her that I think my heart is going to burst out of my chest. She releases my hand, thankfully, so she definitely can't feel me heart about to explode."
    "I sit there for what must be a few minutes but feels like hours, just contemplating the short exchange we just had while Sibyl silently returns to her novel across from me."
    "The only realization that I come to is that I will have to do the one thing I most wish I would not have to."
    jump beg_twins

label beg_twins:
    scene bg transition with fade
    scene bg black with dissolve
    "I don't want to do it. I said I'd never do it again. I {b}hate{/b} that this is my only option left."
    scene bg meeting with dissolve
    H "What is this? Has our surly little Miss Lovestruck came crawling back?"
    O "Surely this does not bode well at all for her fortunes of the heart."
    "The twins immediately start circling me like vultures when I find them alone together. I just stand there and let them get their teasing out of their systems."
    C "(You {b}need{/b} their help, Clover. You can't do it alone.)"
    "Steeling myself, I finally disturb their play time and get right to heart of the matter, at which point they also stop their circling to listen to me."
    C "I need your help with Sibyl."
    "I swallow the thick lump forming in my throat, feeling kind of sick for having voiced what I did."
    "With Sibyl and Tanya away at their art club session and all my own attempts failing, it's basically now or never to get the assistance I need to make her mine."
    O "You need {b}our{/b} help?"
    H "You wish to consort with \"devils\" such as us?"
    C "Go ahead and have your fun at my expense. I'm desperate, okay?"
    "Finding me no longer pushing back against them, the set of twins return to a more relaxed posture, each taking their seat around the big table. I find my own seat, glad to have them finally back off."
    O "Well, what have you tried?"
    "I pause for just a moment, trying to think up how to summarize everything I learned, what I have tried, and how those results never really panned out."
    C "I'm pretty new at this whole thing so I did some research on the Internet and tried to use them on Sibyl."
    H "Sibyl does not seem the type to respond well to pick up lines."
    "I'm a little surprised at how rationally Vittoria is listening to me. It's quite possible that how I have acted in the past only encourages she and her sister to act out further."
    C "No, not pick up lines. I mean, like, the basics. I have been trying to pay her compliments, take an interest in her life, and introduce small touches into our everyday exchanges."
    O "That is a good start. How has she responded to those?"
    C "Well... normal at first. She would just laugh it off like always when I would say something dumb."
    C "But more recently Sibyl just gives me a polite reply and goes on about what she is doing like it never even happened." 
    "The twins look toward each other in quiet communication, then back toward me."
    O "At some point, you will have to give up."
    C "B-But...! Don't you have some surefire way to win her over? I mean, you're doing it all the time with other girls!"
    H "We are not {b}witches{/b}, Clover. There is no magic love potion."
    O "If she is not at all receptive to your advances then there is simply nothing to be done about it."
    C "No! I refuse to accept that!"
    "I'm standing out of my chair before I know it. I'm not mad at them exactly, merely mad that these two are so cool about telling me my love is in vain, again."
    C "Isn't there {b}anything{/b} you can do?"
    H "Well, we do have certain methods...."
    O "If you're up to the task..."
    "I can just feel how they're drawing me out for something now. That infuriating lilt of their voices that they use for teasing returns once more."
    C "I'll do anything!"
    H "{b}Anything{/b} she says."
    "Vittoria gives a frisky grin to her sister, who returns the playful grin back to me."
    O "Are you {b}sure{/b} about that, Clover?"
    "The twins both smile back at me silently. I feel a hunger emanating from Vittoria which makes me shiver to my toes, while from Vincenza I sense a different but no less disturbing desire."
    "All sorts of possibilities flow through my imagination, each one more extreme and less pleasant than the next."
    C "(But this is {b}Sibyl{/b} on the line here.)"
    "In the end, the choice is clear. Nothing matters as much as Sibyl, and so I give my assurances through gritted teeth"
    C "What would you have me do?"
    O "Beg for us."
    C "{b}Beg!?{/b} Like, grovel on my knees before you and kiss your shoes!?"
    H "Y—"
    O "A delightful idea but for now not necessary. Just tell us clearly how you want and {b}need{/b} our help. I want you to say {b}please{/b} and {b}mean{/b} it."
    C "Ugh!"
    "That Vincenza silenced her sister is the biggest surprise here, and that Vittoria accepted it. I thought they shared a mind entirely as one, but maybe sharing also means having to give and take sometimes."
    "Vittoria wants my body, that much is clear. I thought that would be the worst of it, but Vincenza wants something far more dangerous."
    C "(Vincenza wants my {b}pride{/b}.)"
    "She knows that for a stubborn and spirited girl like me, that is most truly what I cannot let be sullied. And so here she is, asking for me to willingly have it debased before them."
    "I knew I wouldn't like whatever the price of this would be, and sure enough, I don't like it. The alternative, however, would be to let go of my love for Sibyl forever, and that is not an option."
    C "Fine."
    H "We're waiting, Clover."
    "I grit my teeth again and push out the words to get it over with."
    C "Please, I beg you."
    O "Who is this \"you\" person? We have names."
    C "Vincenza and Vittoria, I beg you to help me."
    H "What is it you want our help with, dear?"
    "They're toying with me again, I know it, but there's nothing left for me but to play along."
    C "Please, Vincenza and Vittoria, I beg you help me make Sibyl fall in love with me!"
    H "Very good!"
    O "Thank you."
    "With this, both of the twins appear pleased enough. It's a hit to my pride, but that's a small price to pay for a miracle such that I require."
    C "So you'll do it?"
    H "We are women of our words, Clover."
    O "I promise that Vittoria and I, as well as some of our choice associates..."
    "There's a pause where the two glance to each other again, clearly already formulating plans between them already."
    O "...Will do what we can to help you. Keep in mind that all we can do is give you and Sibyl a push."
    H "The rest is up to you. You must be willing to give it your all."
    C "I-I am!"
    O "Be confident. Push yourself onto her if you have to."
    H "Use your wiles. {b}All{/b} of them. Maybe hike your skirt up a little."
    "That I don't know exactly what the twins have planned concerns me slightly, but with a renewed fire in my heart I commit their advice to memory."
    jump aqua_date

label aqua_date:
    scene bg transition with fade
    scene bg hallway with dissolve
    "I don't have to wait long to see the results of sacrificing my dignity to Vincenza and Vittoria."
    "That Saturday afternoon, the twins deliver an odd request to Sibyl personally."
    S "You don't have to come with me, Clover. They said it's a two person job but I can handle a few fish by myself."
    C "No, it's okay! I was getting tired of trying to wrap my head around trigonometrics anyway."
    "Excitement speeds my limbs into walking extra fast to the point where I'm almost racing ahead of Sibyl toward the aquarium."
    "I don't know exactly what they have planned, but it cannot be a coincidence that they ask this specifically of Sibyl and tell her to bring someone with her."
    C "(And at a time that Tanya isn't around too!)"
    scene bg aquarium with dissolve
    S "What's all this?"
    "I have the same reaction at first when I see the aquarium over Sibyl's shoulder, but then I think it's absolutely perfect."
    C "(I can work with this. Come on, Clover, time to strut your stuff!)"
    "It's the same old aquarium as the one I had that confrontation with Tanya in when I first got here, but the twins clearly dialed it up a notch to make it perfectly romantic."
    "A couple dozen candles, at least, all flicker at random where they're placed around the room, their little lights becoming twisted amongst the tanks and casting moving fish shadows on the walls."
    "From somewhere hidden away emanates the easy tones of soft jazz, and in the center of the room sits a huge bean bag that looks just big enough for two people to comfortably sink into it."
    S "Do you think the President and Vice President used this for their... \"extracurricular lessons\"?"
    C "(Is that what they call it?)"
    "Sibyl flicks on the light switch, dispelling the uniquely alluring atmosphere and steps into the room fully."
    "Having none of that when it's all so perfect and exactly what I need, I flick it back off behind her and step in after my prize."
    C "Oh come on, doesn't this look so cool? I mean, look at this bean bag!"
    "I flop right down into it and immediately sink more deeply than I expect into it's depths, but try to remain cool despite that. Subtly, I try to raise the hem of my skirt way up my thigh like it just landed that way."
    C "It's so comfortable, you {b}have{/b} to try this!"
    "I pat at the empty space beside me, knowing she's definitely going to be sinking deeper into the bag right next to me if she sits down, just as planned."
    S "Eww, no thanks. I don't want to know what's soaked into that thing."
    "Before I can say any more, Sibyl has already stepped over to blow out one of the many candles providing the atmosphere in the room."
    C "Hey, what are you doing!?"
    S "These candles are a fire hazard."
    "Puff go another three candles before I can extricate myself from the extraordinarily deep bean bag and squeeze my way between Sibyl and the next candle."
    C "M-Maybe leave some lit up for now?"
    "I try to lean casually against the fish tank between Sibyl and the candle behind me, while also holding my arms together before me in such a way to squeeze my boobs together so they look bigger."
    S "What's gotten into you, Clover?"
    show choice_darkness with dissolve
        menu:
            "\"I just... think we shouldn't rush to waste this nice atmosphere, that's all.\"":
                hide choice_darkness with dissolve
                C "I just... think we shouldn't rush to waste this nice atmosphere, that's all."
                S "Clover, I think they set this all up for {b}sex{/b} with their \"conquests\"."
                "Part of me does think this is just way too perfect for it to be something they thought of last minute, but I don't care. It's exactly what I need right now, so I just feign surprise at Sibyl's words."
                C "You think so?"
                S "Just from knowing the twins since the start of the year? Yes, I think so."
                S "They're super helpful when they want to be, but I just don't agree with their \"peculiarities\"."
                "The excitement inside my suddenly douses like the candles Sibyl is wont to snuff."
                C "You mean because they're... gay?"
                "The lights flick on to dispel the atmosphere again after Sibyl brushes past me to end the mood once and for all."
                S "It's not that they're gay. I just think two people shouldn't do that unless they're in love."
                "Instantly, my soul is revived."
                C "I get what you mean! I think doing \"that\" with the person you're in love with would be amazing!"
                "I very nearly blurt out that I want to do it with her right then and there but hold my tongue enough to quickly step over and grab her hands for one last go at winning her over."
            "\"I'm all hyped up from lacrosse practice this morning.\"":
                hide choice_darkness with dissolve
                C "I'm all hyped up from lacrosse practice this morning."
                "The first thing that comes to mind also tumbles right out of my mouth."
                C "...I got, like, so jittery and excited from that, and now that I'm free from the trigonometry all the energy is coming back again. That's all!"
                S "I'm happy you're enjoying lacrosse, Clover! Have you been getting along well with Tanya?"
                C "(Why is she talking about Tanya at a time like this? Can't you see that we're having a moment?)"
                "But the moment doesn't seem to be the same one that Sibyl is having, because she brushes right past me again to flip on the lights and dispel the atmosphere for good."
                "Defeated for the moment, I answer the question while trying to think of my next attempt to claw my way inside her heart."
                C "Yeah. She's pretty good at lacrosse and I've learned a lot."
                "Honestly, we barely interact excess when we meet during play."
                C "(She {b}is{/b} pretty good at the game, to be fair.)"
                S "That's great news! I think the two of you could be best friends if you both give it a try."
                "Not content to let this opportunity be wasted, I slip right back in front of Sibyl and take her hands for one last \"Hail Mary\" attempt."
    C "The music is pretty good, isn't it? Want to dance?"
    "Sibyl just smiles at me softly, then takes her hands back from mine."
    S "We're just here to feed the fish, Clover."
    "Just like that, the whole evening is wasted. I gave it my all and Sibyl shut me down very single time."
    C "(Is she just dense or what? Do I have to come right out and say it? {b}Should{/b} I have? Did I miss my chance?)"
    "The questions about my failed allurement plague me all the way through feeding the fish and well into the remainder of my math homework."
    jump tanya_trouble

label tanya_trouble:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "Breakfast on Sunday starts like any other, except that something is clearly eating at Tanya."
    "Sibyl tries to pry it out of her, to no avail. It's not really my concern at all, so I just happily eat away at my French toast until I'm ready for seconds."
    C "I'm going to go grab another plate. I'll be right back!"
    scene bg kitchens with dissolve
    "I'm not disappointed about my failure to finally win over Sibyl last evening, not when I have so much sugar and syrup flowing through my veins."
    C "(There will be more chances. Vittoria and Vincenza will have something up their sleeves, or those \"associates\" they spoke of will.)"
    "My only priority for the moment is getting back in line to order another stack of my favorite breakfast from the chefs, but even that gets ruined right away."
    T "Come with me."
    "I feel a sharp tug at my arm just as I hear the words spoken softly in my ear, and nearly stumble as I'm pulled out of the line."
    C "What the hell was that about—"
    T "Stop making a scene. I just want to talk. Somewhere private."
    "Tanya is being particularly terse, but not overtly hostile aside from the initial jerk to my body."
    C "(You're {b}already{/b} making a scene!)"
    "The other girls in the line for the chefs stare at us, some more overtly than others, but everyone in the cafeteria proper can't see us."
    C "I don't care what's wrong with you. Go tell it to Sibyl."
    T "It's not about me, it's about Sibyl."
    scene bg dorm with dissolve
    "After just a little bit more of half-whispered back and forth arguing, I end up around the corner of the hallway just outside the cafeteria alongside Tanya."
    C "What's your {b}problem{/b}, Tanya?"
    "She's more irritable than normal today, that much was clear before, but as she looks at me she's practically throwing daggers with her eyes."
    T "What's {b}my{/b} problem? I thought I {b}told{/b} you to stay away from Sibyl!"
    C "I can do whatever I want with Sibyl. She's {b}my{/b} Vertu."
    T "She's her own person, not yours to do whatever you want with!"
    T "I heard all about it, you know — that Vincenza and Vittoria are trying to set you two up together. They think it's as foolish as I do."
    C "(Yet they're still doing it anyway! Because they know I still have a chance!)"
    "It's a surprise to me that the twins told her about this at all, let alone after less than a day, but as I think back I never did tell them to keep it a secret. That should have been understood."
    C "What about it? If she's her own person why do you have to get in my way of pursuing her?"
    T "First of all, because she's never love you and all you're doing is causing her pain, and secondly, because I—... I \"like\" Sibyl too."
    C "Okay? We both know she's going to be your friend no matter what so just back off."
    T "For the love of God, Clover, how can you be so dense! I {b}love{/b} Sibyl. Just like you do."
    "This surprises me probably more so than it should. It actually makes a lot of sense with a brief moment to think about it, even with Tanya still angrily close to me in the hallway."
    C "S-So, what? It's her choice if she wants to go out with me. You've had {b}months{/b} already to take your shot."
    T "Arrgh! Clover, will you {b}listen{/b}!? There is no \"shot\" to take. Sibyl is straight and that's the end of it."
    T "My feelings for her aside, you're only going to hurt her if you keep pursuing her like this."
    C "That's exactly what a love rival would say to make me give up on her."
    T "Yes, exactly, I'm {b}trying{/b} to make you give up on her! {b}I{/b} already gave up on her and am content to be her friend."
    "Tanya keeps saying things forcefully in my direction, nearly backing me against the wall. I make my own attempt at trying to look cool and unbothered despite how annoyed she is making me."
    C "Maybe {b}you{/b} just don't love her enough if you gave up so easily."
    T "Would you {b}please{/b} think about someone beside {b}yourself{/b} for a minute?"
    "Tanya gets that look in her eyes that she's about to rip my hair out of head for just a moment, but cools herself down quickly with a few deep breaths."
    T "I'm not going to let you get to me again, Clover. If you want to think about it from your perspective, fine."
    T "Consider this: if things don't work out as you hope, and they won't, it will be incredibly awkward between the two of you. If you value your friendship with her, you should just accept that it's over."
    "It's a good point and we both know it. I don't want to admit, but te thought has crossed my mind before."
    C "Okay, yeah, I've thought of that, but what do you want me to do, deny my feelings forever?"
    "There's a sigh of relief from Tanya that I've finally come to the conclusion that has prepared for me."
    "Her anger is way down and way more like defeat instead, and I find myself cooled down similarly now that she's not quietly screaming in my face."
    T "If you have to, yeah. It's not easy but it's what's best for both of you."
    "Tanya pushes her back against the wall beside me, turning her head away. She mumbles quiet to herself."
    T "Izzie was right; straight girls are the worst."
    C "What was that?"
    T "Nothing. You're just absolutely infuriating in every way, you know that?"
    "I know Tanya is being dead serious when she says it, but with the slump of defeat in her tone of voice, it actually sounds kind of friendly in some strange way."
    C "(Maybe I can reconcile I little bit with her. I never did get around to that one step of the process about \"making friends with her friends\" at all.)"
    "Trying my best to summon up as much reconciliation as I can, I strike out a sympathetic but firm tone with Tanya."
    C "I'm not giving up on Sibyl, Tanya, but I do appreciate how much you care about her. I promise that I would never do anything to hurt her."
    "Tanya's face turns sour, or perhaps better described as bitter, while I calmly tell her that I have absolutely no plans to give up on Sibyl. She remains calm nonetheless, and searches my eyes with her own."
    T "Your strong will would be admirable if it weren't so misplaced, Clover."
    C "I could say the same about you, Tanya."
    T "So what now? We agree to disagree, and I come back to beat your ass when you eventually make Sibyl cry?"
    C "Unlikely, seeing as how I'm going to make her fall madly in love with me in no time."
    "Tanya snorts dramatically with disbelief at my unflinching assertion, but I don't take it personally."
    T "What do you even love about her anyway? You've known her for a {b}month{/b}."
    C "Well, she's totally amazing at everything, isn't she? She's kind, and playful, and..."
    T "And what? Lots of people are kind and playful."
    C "(Why {b}do{/b} I love Sibyl?)"
    "I can feel it so intensely in my chest, but when I try to compress those feelings into the form of words, nothing really seems to fit properly."
    C "Well she's super gorgeous. Her hair seems to shimmer in the sunlight, and at the same time her eyes sparkle like bright blue sapphires—"
    T "Aquamarine."
    C "What?"
    T "Sapphires are dark blue. Aquamarine are light blue, like Sibyl's eyes."
    C "Huh, yeah... aquamarine."
    "For a moment I am lost in thinking about Sibyl's eyes and how well the aquamarine description fits them, but a sudden small outburst from Tanya beside me breaks the hold."
    T "I can't {b}believe{/b} you."
    C "What are you on about now?"
    T "All this and you don't even know why you love her. Are you sure you're not just, like, mega horny?"
    C "What? No! I'm not—"
    "I pause for a moment to consider what Tanya says, finding it perhaps more accurate than I'd like to admit, which gives Tanya a terrible shock that shows clearly on her face."
    C "Wait, no, I'm totally serious about Sibyl, for real!"
    T "If you don't actually love about her as a person I'm going to murder you for real, and you can quote me on that that in your own blood writing for when the police find your body."
    C "What do {b}you{/b} love about Sibyl anyway?"
    "I deflect the question right back at Tanya to get her off my case and maybe find out what I truly love about Sibyl based upon what she says."
    T "Her compassion, warm and limitless. Her freedom, so simple and joyous."
    "I don't get the chance to ask her what she means by \"freedom\" as the bell rings to signal the end of the lunch period and we both realize we've left Sibyl alone way too long."
    scene bg cafeteria with dissolve
    "When we both return together to the table, the worried expression on Sibyl's face almost breaks my heart just like it's probably doing to Tanya."
    "She doesn't even need to ask the question before we answer with our own little white lies."
    T "Something was wrong with the toilets."
    C "...The kitchen line was really long."
    S "Is that all? I'm glad."
    C "(What did she think was happening?)"
    "Our excuses do much to alleviate Sibyl's concerns, and I am relieved to find a bright smile back upon her face in no time now that Tanya and I have returned to her."
    jump libraryflirt

label libraryflirt:
    scene bg transition with fade
    scene bg library with dissolve
    "A significant portion of Sunday is spent in the library as has become somewhat accustomed for us since I began to settle in to my life with Sibyl at the academy."
    "Tanya comes with us as she sometimes does, though today she definitely cranked up her efforts in getting between me and Sibyl as much as possible."
    C "Hey Sibyl, check this out! Doesn't this couple look so cozy sharing this scarf? I bet it's so warm..."
    "I point out a stock photo of a man and woman sharing a scarf in some article of a magazine I'm flipping through."
    "I don't actually have any strong feelings about the scarf or the article, but I also fully intend to use anything and everything to flirt while I have the advantage of my secret helpers."
    S "Hmm?"
    "Sibyl's head lifts up from her own teen magazine. This kind of fashionable flirty column is exactly what I can use to get her attention."
    C "I've never shared a scarf before. Want to try it with me?"
    "With an falsely casual motion to hide my eagerness, I slide the magazine across to Sibyl. Tanya intercepts it instead and pulls the magazine away from Sibyl before she can get a good look."
    T "Oh, is this the issue with the article about capybaras?"
    S "Capybara? Are there pictures!?"
    C "What? No! There's nothing like that in there!"
    "I know there are no articles about capybaras in that back issue of a stupid teen fashion magazine, and Tanya does too most likely."
    "Tanya also seems to know that Sibyl is crazy about them to the point where she spend the next few minutes telling me all about them with Tanya's prompting to keep her going."
    C "(Sibyl is {b}so{/b} cute when she's gushing about capybaras.)"
    "I'm enjoying seeing the bright, happy expression of wonder on my face while Sibyl speaks about something she loves, even if the whole topic was just a plot by Tanya to disturb my attempt at flirting."
    S "Did you know their teeth are always constantly growing? Can you imagine if our teeth did that?"
    "From where I sit at the table facing the door, I spot Vittoria and Vincenza step into the library. The pair immediately give me a secret wave and make their way toward me."
    C "(It's Vincenza and Vittoria! If only Tanya weren't here to ruin whatever they have planned.)"
    "With Sibyl and Tanya facing me from the other side of our table, neither recognize that the twins have entered the library until they're enough for Vincenza to fake a stumble into Tanya's chair."
    H "Dear me, Vincenza! Are you quite alright!?"
    O "Yes, yes, I am fine, just a— ouch!"
    "Vincenza stands upright once again, immediately wincing when she puts her weight on her left foot."
    S "Vincenza? Are you hurt?"
    "Sibyl is immediately concerned for Vincenza and stands to help, but the injured party waves her off and motions her to sit back down."
    O "No, not too badly, but... ah."
    "Vincenza again acts out a flinch when placing weight upon her foot, which Vittoria plays up her concern just a little too much behind, fawning over her sister animatedly."
    H "Oh no, we {b}must{/b} get you to the nurse."
    O "But I must return this book today!"
    H "Sibyl and Clover can handle that, dear sister. We must seek treatment before your ankle swells, right away! Would you help me take her to the nurse, Tanya?"
    "While I at least try to act a little concerned, Tanya's expression is nothing but a look of utmost disbelief, like her face is screaming \"you can't be serious\" without words."
    "I can see it from the side due to my vantage across the table, and the twins get the full brunt of it, but Sibyl is totally clueless to her skepticism until spoken."
    T "Seriously?"
    O "Alas, I am seriously injured! Please help me to the nurse, Tanya!"
    H "Here, Clover, please take this book to return. If there are any notes left inside, please remove them."
    "Vittoria hands me the book while Vincenza supports herself half against Tanya's chair and half against her shoulder at the same time."
    S "Aren't you going to help her, Tanya? She's your friend!"
    T "But...!"
    "Tanya's head whips back and forth between the twins and Sibyl, then rests on me for a moment with a dark grimace."
    C "(Better luck next time, Tanya!)"
    "I give her a smile flush with the thrill of victory, then pile on the train right after Sibyl."
    C "You'd be best to help her, Tanya. You've got that {b}chunky{/b} lacrosse body."
    T "Ch-Chunky!?"
    "I cannot help but giggle internally seeing Tanya fume at me from across the table, but mostly succeed at stifling my grin."
    O "Ow, ouch!"
    S "{b}Tanya!{/b}"
    T "O-Okay, okay, come here!"
    "Giving in to Sibyl's concern, Tanya stands to allow Vincenza over one shoulder and walk her out of the room with Vittoria on the other side."
    S "I hope she's okay..."
    C "Vincenza is a tough girl. I'm sure she'll be just fine."
    "When they all finally leave Sibyl alone with me, Sibyl remains a little on edge. She looks back occasionally and I just know in her mind she's thinking about going after them, so I try to distract her."
    C "So this is what Vincenza likes to read?"
    S "What is it?"
    "I read the title myself, then turn te cover toward Sibyl who is immediately curious."
    S "{i}Little Women{/i}."
    C "What's it about?"
    S "I've never read it, but it's about the lives of four sisters."
    C "So there are books you {b}haven't{/b} read?"
    S "Of course there are!"
    "I'm just lightly teasing, and I'm pretty sure even Sibyl knows that, but it feels so good to get a reaction out of her that I cannot help but do it."
    "I'm just about to set the book down when I notice a slip of yellow paper sticking out of the side, and remember what Vittoria told me. I flip open to the page to find a whole bunch of sticky notes."
    C "(Oh... I get it now.)"
    "Each sticky note is crammed with moves for me to try with Sibyl like little squares of pure gold seduction meant just for me."
    C "(These work for the twins, right? It can't be that hard to pull off if I give it a try.)"
    "I casually glance over the first few words of each to decide which one I should hit Sibyl with first."
    show choice_darkness with dissolve
        menu:
            "\"Tell her there's something on her cheek then...\"":
                hide choice_darkness with dissolve
                "Sibyl has already gotten sucked back into her magazine, so I take the time to read through the prompt and try to play it out in my head. After a few minutes I work up the courage to put the plan into action."
                C "H-Hey, Sibyl, there's something on your cheek."
                S "Hmm? What is it?"
                "Her hand raises predictably to brush against her cheek, trying to shake off something which doesn't exist whatsoever."
                S "Did I get it?"
                C "Not quite. Here, let me..."
                "With my heart still pounding in my chest, I stand to lean across the table to place my hand under her chin and raise her face up to my standing level."
                C "(I hope she doesn't feel how shaky I am.)"
                "I rub my thumb slightly against her cheek, nearly having a heart attack from how soft and pleasantly malleable it is, not to mention the incredibly cute squirm she does as I prod at her face."
                S "Did you get it?"
                "Sibyl stares right into my face and asks me so innocently that I feel a rush of guilt for being os sly, but push that aside and steel myself to take the next step."
                C "Not quite. Just a little more..."
                "Edging ever closer to her face under the guise of getting the phantom spot off, our face inches closer than ever before. My gaze is glued to her lips."
                C "(Go for it, Clover, you're so close!)"
                "I press forward to kis Sibyl, in the moment bolder than I've ever been in my life, and immediately fall flat on my face atop the table when my foot slips out underneath me."
                S "Clover! Are you alright?"
                C "Y-Yeah. I got it."
                "My nose hurts terribly, but only my pride is severely damaged."
            "\"Lightly brush your foot up against her ankle and...\"":
                hide choice_darkness with dissolve
                "Sibyl has already gotten sucked back into her magazine, so I take the time to read through the prompt and try to play it out in my head. After a few minutes I work up the courage to put the plan into action."
                "I open the magazine in front of me again as a cover, then shift my legs slightly to press the tip of my foot against Sibyl's ankle."
                "When she wordlessly moves her foot aside slightly, I glance up over my magazine to watch her reaction, then try it again. This time I go even further, slightly trailing the front side of my shoe up her shin."
                "There's a flicker of recognition that comes across Sibyl's face, but she again just wordlessly shifts in her seat."
                C "(Playing hard to get, huh? Fine.)"
                "Boldly, I rub my foot against Sibyl's ankle yet again, in such a manner that there's no doubt I'm doing it intentionally."
                "At last, I am rewarded with Sibyl looking up at me."
                S "Do you have to pee, Clover?"
                C "W-What!?"
                S "You're fidgeting all over."
            "\"While she's watching, but your lower lip and glance...\"":
                hide choice_darkness with dissolve
                "Sibyl has already gotten sucked back into her magazine, so I take the time to read through the prompt and try to play it out in my head. After a few minutes I work up the courage to put the plan into action."
                "Brushing my hair back into place as best I can, I clear my throat to sneakily gain Sibyl's attention and prepare myself to be as alluring as possible."
                "When Sibyl glances up toward me, I lower my eyelids and rake my teeth gently along my lower lips. I think it's a surefire win but Sibyl goes right back to her magazine."
                "Trying again, I clear my throat louder. Sibyl once again glances above her magazine at me, and I lightly flick my tongue out across my lips as sensually as possible. Still, Sibyl goes right back to her magazine."
                C "(You want to play hard to get? Fine. You can't ignore {b}this{/b}!)"
                "I clear my throat again for the third time even louder than before, drawing the attention of not just Sibyl but also the library committee member on duty, who raises a finger to her lips to silence me."
                S "Is your throat dry, Clover? Would you like to get some water?"
                "I'm about to say no, but after all that false throat clearing, my throat does kind of hurt now."
    "It's just in that moment that Tanya trudges back into the library and flops into her seat beside Sibyl once again."
    S "You're back already, Tanya? Is Vincenza doing okay?"
    T "She'll be just fine. I've never {b}seen{/b} her more healthy."
    "Sibyl is all smiles to know that the Vincenza is recovering quickly from her \"injury\", and goes even further to praise Tanya for being willing to help a friend in need."
    "I may have failed to capitalize on the twins' helpful tips, but getting to see Sibyl's peerless compassion in action is its own reward."
    "That I also have the rest of the sticky notes stashed away after returning Vincenza's book is another reason for me to smile too."
    jump artclassflirt

label artclassflirt:
    scene bg transition with fade
    scene bg artroom with dissolve
    "Long nights are spent lying in bed trying to come up with the right way to get Sibyl to fall in love with me."
    "Even longer days of looking for opportunities to make Sibyl miraculously fall in love with me prove continually fruitless."
    "I stand in front of the 3D printer in art class, watching it slowly build my hand-held statue of of a puppy layer-by-layer. It's supposed to be Abraxas, but my 3D modeling skills are terribly lacking."
    C "(There's no way I could give this crappy plastic blob his name!)"
    "Despite my dissatisfaction, it's actually really cool to see something I made materialize out of nothing in front of me."
    C "And it's actually something I can sorta manage to do."
    "Behind me, I turn to spot Sibyl and Tanya chatting and laughing together, side by side in front of easels."
    "I've already tried some of the more traditional types of art but produce little more than stick figures and what Sibyl politely calls \"contemporary art\"."
    C "(Sibyl really is way too courteous for her own good. She need someone like me who doesn't take any shit by her side. Yeah.)"
    "I smile softly, eyes locked upon Sibyl's face where her attention flickers between where her paintbrush flick hues here and there, and to her friend beside her."
    mi "She's cute. I can see why you like her."
    C "{b}Hyah!{/b}"
    "The voice of my art teacher suddenly sounds out right beside me and I nearly knock the 3D printer right over with surprise, messing up my little dog sculpture in the process."
    mi "Oops, think you're going to have to start over on that one."
    C "W-What did you say!?"
    mi "Your little doggie. The layers are all off after the table was bumped, see?"
    "My eyes look to the dog in the printer, now knocked over and with new layers being printed on his side, but my brain is elsewhere."
    C "(The twins seriously told {b}my teacher{/b} of all people? It's bad enough that Tanya knows.)"
    "I feel a distinct amount of betrayal from the twins, but then again, I've already seen how friendly they are with Miss Izzie so maybe I shouldn't be so surprised."
    C "You can't.... {b}tell{/b} anyone!"
    mi "We have dozens of rolls of this stuff. It's no problem at all to print another copy."
    C "No, I mean about..."
    "I lower my voice, speaking the name of my crush as quietly as I can muster while anxiously eyeing the people vaguely around us."
    mi "You hardly need to whisper her name, Clover. You were staring right at her for minutes on end. I don't think I saw you blink even once."
    "A rush of warmth swells into my face, which I suddenly find intolerable to show freely out of shame. Miss Izzie ruffles the hair atop my head yet again, trying to cheer me up."
    mi "So anyway, a pair of birdies flew in recently and told me that you needed some help wooing a pretty peacock."
    C "I... uhh..."
    "Miss Izzie gives a moment to hem and haw about whether I should acknowledge this crazy thing I asked of the twins, but then ultimately goes on anyway even without my approval."
    mi "Well today's your lucky day, because there's no better hands for a woman to be in than mine."
    "Miss Izzie gives me a little wink and a smile, which feels a little eerie somehow, despite that she's telling me she's also going to help me win over Sibyl."
    C "What... what are you going to do?"
    mi "You'll see. Just come talk to Sibyl in a few minutes, okay? And remember that whatever happens, you have to be {b}bold{/b}. Sibyl's going to be a tough nut to crack."
    C "O-Okay..."
    C "(Is this really happening? if my teacher trying to set me up?)"
    "I want Miss Izzie slither off toward Sibyl. The pair start talking about something, and rather than stare now that I'm conscious of it, I pull my failed sculpture from the 3D printer while my waiting time ticks away."
    "When the moment arrives, or what feels like I've waited long enough anyway, I start my walk over toward where Sibyl and Miss Izzie remain chatting."
    T "I fail to see why she can't just do this with {b}me{/b}, Miss Izzie."
    mi "You know exactly why, Tanya."
    T "Enlighten me. Please."
    "Whatever this plan of hers may be, Tanya doesn't seem to be very enthused about it."
    mi "Because they're Vertu partners of course!"
    mi "Oh, Clover, right on time! I have other students to check on, but maybe you could fill her in on the idea, Sibyl?"
    S "I can take it from here, Miss Izzie."
    "My mischievous art teacher again sends me a thumbs up as she departs, but I am much more interested in what Sibyl is talking about now."
    S "Miss Izzie has a wonderful idea. So remember how I did that portrait of you a few weeks back?"
    "There's no way I would have forgotten the nude drawing she made of me soon after meeting her. It was strange at the time, but now I'd gladly strip everything right off to model for her, if she'd do the same."
    "My reply comes out with a modest \"yes\" without needing to tell her about all the rest."
    S "Miss Izzie thinks it's a good opportunity to translate the same subject into a tactile medium."
    C "Tactile...?"
    S "Like a sculpture! Rather than look at you and translate that into a two dimensional drawing, Miss Izzie thinks it would be beneficial for me to {b}feel{/b} you with my hands and use my other sense to mold clay."
    "When Sibyl says what she does, I can barely believe it."
    C "(She wants to... {b}feel{/b} me. My naked body. {b}Over and over again{/b}, diligently enough to perfectly sculpt me by touch alone.)"
    "My brain kind of freezes for a moment. I don't know what expression could possibly be on my face, but it's at that moment that Tanya jumps back in to try to ruin this incredible development."
    T "Look at her! I knew this was a bad idea."
    "Tanya quickly turns to Sibyl, wasting no time in grabbing her hand and drawing her attention away from me."
    T "I'm totally fine with it though! We've already both painted nude studies before, remember? So I know how to model properly. The {b}natural{/b} choice is obvious to choose me, and I want to do it!"
    "I've never seen Tanya speak as quickly as she does now, half vomiting words and half pleading with Sibyl to sculpt her over me."
    C "{b}No!{/b}"
    "I shout out into the space between Sibyl and Tanya, drawing the attention of everyone immediately surrounding us. The eyes suddenly on me freeze me to my core but thankfully fade away just as quickly."
    C "I mean, Miss Izzie was right. I'm her Vertu partner, and she already drew me, so it's got to be me, right? I'll do it."
    S "Are you sure? if you really don't want to I'll just have Tanya—"
    C "{b}I want to do it!{/b}"
    "I cannot begin to comprehend what Sibyl must be thinking, but in the end she agrees to model me and wanders off to the storeroom to fetch clay for the project."
    T "I'm seriously going to murder you."
    "Tanya makes her feelings about the situation clear the moment Sibyl leaves the two of us alone."
    C "Not before {b}I{/b} get felt up {b}all over{/b} by Sibyl, you're not."
    "It is expressly clear that Tanya has yet more to say, but Sibyl returns quickly enough, leading her to just go back to her painting while also keeping a sharp eye on the two of us."
    C "S-So do you want me to... s-strip here, or...?"
    "Now that it's come down to it, I'm starting to feel self-conscious about the prospect of stripping down right in the middle of art class, even if it means Sibyl touching my naked body."
    "The combination of lacrosse exercise and fewer French toast breakfasts has been working like a charm, but I'm still not {b}that{/b} confident in my body."
    S "Strip? I'm just doing a bust, Clover."
    C "B-Bust...?"
    "My hands raise up to my chest without thinking. My chest isn't anything particularly special but it would still be awkward to take my top off here."
    "The first sign that I have a terrible misconception of what Sibyl wants to do is when I hear Tanya's viciously mirthful snickering from nearby."
    S "No, I mean a sculpture bust. That's just your shoulder on up. You won't need to take anything off at all."
    C "O-Oh...."
    "I {b}know{/b} my face must be burning crimson but Sibyl doesn't call me on it, instead just getting her workspace set up before her while I sit trying not to squirm in my chair."
    "When the time finally comes to begin, Sibyl merely stands before me, visually inspecting me all over but not touching one bit."
    C "I-I thought you were supposed to, umm.. {b}touch{/b} me."
    S "Yes, you're right, but... hmm, I just don't know where to start."
    "I suddenly realize that it's not just me who is anxious about this whole thing, and that maybe my uneasiness might be taking Sibyl off her game as well."
    C "(I'm making this even harder for her... I have to calm down.)"
    "I try my hardest to sit still and calm my racing heart, but when I finally feel Sibyl's fingers against my cheeks, I cannot help but jump."
    S "Are you alright?"
    C "Sorry, your fingers are just a little cold."
    S "You do feel warm."
    "Pausing for the moment, Sibyl rubs her hands together vigorously to warm them up, then reaches out to start touching my face again."
    "It's embarrassing and a totally weird feeling, the way she pulls and smushes my face this way and that, trying to feel the curves and contours of my face."
    C "(Is she going to mold the clay or mold my face?)"
    "When she withdraws her hands for the first time to mold her clay, it suddenly feel more strange to {b}not{/b} have her hands working into my skin."
    C "(It was a good idea at least even if it didn't work out, Miss Izzie)"
    "i still have no idea if my teacher really expected one of her students to strip down and fondle another, but she sure seemed enthusiastic about it."
    C "(She also told me to be \"bold\". How am I supposed to be bold when {b}I'm{/b} the one getting felt up here?)"
    "If the roles were reversed, I imagine that I could maybe try my luck in touching places that I don't normally get to touch, but from this perspective I don't have a clue what that would mean."
    "As Sibyl returns to rubs her hands all around my face and down my neck, my eyes are drawn to her face. Her expression remains still and focused, much like when she works on her other art projects."
    C "(She's so close!)"
    "Even though the project goal is to sculpt by feel, Sibyl still puts her large blue eyes to work inspecting how my flesh reacts to prodding by her fingers."
    "Her face is so incredibly close that I can smell her shampoo, and my heartbeat once again starts running into overdrive."
    C "(Her lips! Ahh, I want to kiss her!)"
    "They're right before me. I could lean just a {b}little{/b} closer and touch them with my own."
    C "(Should I kiss her? Would she freak out? Can I play it off an an accident?)"
    "A multitude of thoughts in a similar fashion continue to play through my mind, devolving rapidly with my mental state."
    C "Sibyl so close! I love her, I love her I love her. I'm going to do it! I'm going to kiss her, and then play it off real smooth... or maybe I should just tell her I love her right now?"
    "I feel warm already, my heart coursing blood fast and strong through my body. Jitters return to my limbs as I try to hype myself up to do something risky and incredible."
    "And then Sibyl stops touching me to return to her clay. My single-minded focus breaks intensity, and for the first time I notice both Tanya and Miss Izzie together stealthily watching from across the room."
    "Tanya has her arms crossed like she's pouting and sports an equally dark expression when she catches my line of sight, while Miss Izzie beside her flashes a peace sign at me when I look her way."
    S "I'm almost done the basic shape of the head and shoulders. How are you holding up, Clover?"
    C "Oh, umm, pretty good. Thanks."
    "I'm not at all \"pretty good\", but I can't exactly tell her that I was just about to surprise kiss her a few moments ago."
    "Now that I know I have an audience, and remember that I'm still in the middle of art class, I just can't bring myself to attempt it anymore."
    C "(I'm sorry, Miss Izzie, I just can't be {b}that{/b} bold.)"
    "I thought I was going to be able to make Sibyl fall for me naturally just by being around her, just like how she charmed me so easily, but now I realize that may not work as planned."
    C "(Maybe I've been a little naive in thinking she would just automatically fall in love with me if I try to surround her with my being, just like I so easily fell in love with her.)"
    "Vittoria and Vincenza warned me that Sibyl wouldn't be so easy to win over, and now Miss Izzie told me the same thing."
    C "({b}Bold{/b}. I need to be {b}bold{/b}.)"
    "The whole setup by Miss Izzie ultimately does not result in any real progress with Sibyl, but what it does do is harden my resolve to be make Sibyl {b}mine{/b}, by any means necessary."
    jump cloverdecorations

label cloverdecorations:
    