label lacrosse_anew:
    scene bg gym with dissolve
    "With my name written in bold pink letters across my back and the crosse held confidently in my hands, I envision myself as a brand new woman ready to tackle any obstacle in her path."
    C "({b}Goodbye{/b} creepy goth, angsty bitch, and love-struck loser Clover; nice to meet you, fun and sporty athlete Clover!)"
    "I haven't felt this clear-minded and energized in months, or maybe even years. I've put all the darkness both literally and metaphorical in my past, and now finally also moved out of Sibyl's shadow."
    C "(I was way too distracted for my first few weeks of lacrosse practice, but today I will kick it into high gear!)"
    "Saturday morning practice starts with a paired warm up passing exercise. Overhand, underhand, even sidearm — I do them all, and well enough that Miss Woolsey is impressed by my speed in picking up the technique too."
    "After warmup we split to play shifts of {i}sixes{/i}, a type of lacrosse where two teams of five \"runners\", who play both offense and defense, and a goaltender face off in a fast-paced, non-stop lacrosse match."
    "While I wait my turn to run to play as one of the runners, I focus my energies on practicing my {i}cradle{/i} technique."
    "By moving the crosse in a semi-circular motion to produce centrifugal forces, the ball can be kept securely in the crosse even at an elevated position."
    "It's an essential skill which has been something of an issue for me in past practices, so starting today it's one of my highest priorities to get right."
    mw "Priya, swap out; Clover, you're in!"
    "Miss Woolsey calls out my name as part of substitutions for the next sixes match, giving me the perfect opportunity to put my new and improved skills to the test."
    C "Yes, ma'am!"
    "Full of confidence, I place myself forward to take the draw and hopefully win the ball to start my team off with possession."
    "As I line up with my stick crossed at waist level before me, I narrow my focus on what actions I'm going to take to sweep the ball to my teammates."
    "Nothing else matters in all the world but winning that little yellow rubber ball... until my opponent arrives to place her stick right up against mine."
    T "You're going down, Clover."
    C "(She—! She's {b}trash talking{/b} me!)"
    C "Shut your fat mouth, you... fattie!"
    T "Is that the best you've got?"
    "The coolness of Tanya's reply, and particularly the cavernous depths of smugness present on her face as she says it, really ruffles my feathers."
    "My trash talking doesn't hold a candle and I know it, but try again I must lest Tanya take away this exchange as a victory of her own."
    C "(I have to really make this one count!)"
    show choice_darkness with dissolve
    menu:
        "\"I'm going to launch that ball so hard up your butt that it comes out your mouth.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the lacrosse ball between us."
            C "I'm going to launch that ball so hard up your butt that it comes out your mouth."
        "\"When I'm through with you, you'll be using your stick for crutches.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the lacrosse stick held firmly in my hands."
            C "When I'm through with you, you'll be using your lacrosse stick for crutches."
        "\"You're going to be hanging up your jersey for good after this match is through.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the matching uniforms on our backs."
            C "You're going to be hanging up your jersey for good after this match is through."
    "I catch a glimpse of Miss Woolsey coming over to drop the ball and start the match so I am forced to hiss my rude reply out quietly between my teeth. Tanya only grins at the abuse."
    T "You've already lost, Clover."
    C "Huh—?"
    "The ball drops in front of us and I'm way late to the snap given my preoccupations with Tanya taking precedence over watching Miss Woolsey. Tanya wins the draw and lobs the ball her side with barely any challenge."
    C "(I played right into her head games, that bitch!)"
    "In the next millisecond after Tanya receives the ball from her teammate, I run right up to get in her face. She tries to juke to the side to pass to her teammate but I read the scoundrel's intentions clearly enough."
    "With a quick flick of my stick against hers, my first ever stick check works wonderfully in popping the ball right out of her crosse pocket and away to be scooped up by my teammate."
    mw "Great check, Clover!"
    "Miss Woolsey calls aloud to join the praises in my head for this wonderful work of stick craft, and my teammate subsequently scores the first point of the match to top it all off."
    C "(Take {b}that{/b}, Tanya!)"
    "I trot right on over to her to gloat in the few second it takes for the goaltender to fetch the ball and throw it back into play, but when I face her she isn't visibly upset in the slightest."
    T "Nice take away, Clover."
    C "Uhh... thanks."
    "The interaction leaves me deflated and confused as play resumes once again. I try not to let her behavior get to me any further and keep the obtrusive thoughts at bay, but they remain there in the back of my mind nevertheless."
    C "(Was Tanya actually paying me a compliment... or is this some new kind of psychological torture?)"
    "Once the half time break arrives, I march right over to Tanya with an aim to get her to tell me exactly what she's up to this time."
    C "What's your problem, Tanya?"
    "I catch Tanya taking a big gulp out of her water bottle but I know she hears me because I can see her eyes glance my way. Still, she takes her time hydrating before acknowledging me further."
    T "If you're asking why I scored two goals while you scored none, that's just because I'm a better athlete than you."
    "If I weren't also tired from all the activity on the field of play and at the moment using my stick as a crutch to rest my weary legs, I might have just smacked her over the head with it then and there."
    C "That's {b}exactly{/b} the kind of crap I'm talking about."
    "As nonchalant as ever, Tanya swipes the sweat off her brow with her body turned slightly away from me before responding once again."
    T "Better that you learn not to let your opponent take you off your game now rather than when we're playing against one of our rivals. The girls at Snipatuit High are particularly nasty."
    T "We're both Wild Roses, Clover. It's in the best interest of the team that you are playing at your best before Spring season starts."
    "I cannot deny that her little trick {b}did{/b} teach me a lesson about maintaining focus, and my vexation at her behavior {b}did{/b} make me play better as a result."
    C "So what you're saying is that all of that talk was just to make me perform better in the game?"
    T "That, and I'm still pissed about what you did to Sibyl."
    C "(There we go. {b}That's{/b} what I expected to hear.)"
    "I'm not surprised, exactly, and nor do I blame her. Privately, without ever speaking the ghastly words aloud, do I admit that Tanya was right when she warned me in advance to give up on Sibyl."
    C "(But Hell itself will freeze over before I give her the opportunity to say \"told you so\".)"
    T "Oh, and before I forget, \"I told you so\" about Sibyl. There's absolutely no way any girl would change her preferences, least of all {b}you{/b}."
    C "O-Oh— Oh, {b}yeah{/b}!?"
    "I thought I was being remarkably conciliatory in not blowing up at Tanya after everything she's done today, but this I will not endure any longer."
    C "Well, I have some news for you, Tanya. Sibyl and I {b}kissed{/b}."
    "I wasn't planning to ever tell Tanya for fear that she really does murder me one day, but she's practically asking me to throw this into her face right now, so I do."
    T "You're going to have to try better than that, Clover. "
    "The revelation I spit out at Tanya fails to land entirely. She's more interested in Miss Woolsey instructing one of our goaltenders on the other side of the gymnasium."
    C "I'm not lying. I asked her for it — for one kiss in exchange for me giving up forever — and she {b}agreed{/b}."
    C "We kissed, it was {b}amazing{/b}, and you'll never {b}ever{/b} get to know the feeling of Sibyl's lips like I do."
    "It's with a great deal of satisfaction that I spot Tanya's indifferent facade start to crumble in the face of my taunts. Her gaze edges back my way despite her attempt to appear unaffected."
    T "Sibyl is straight, a fact I know painfully well, and she doesn't like you that way. She'd never let you kiss her."
    C "You're right, I didn't kiss her. {b}She{/b} kissed {b}me{/b}."
    "I feel so delightfully devilish rubbing my kiss into Tanya's face after she's been acting so high and mighty all of practice."
    "Maybe it's the unshakeable smirk plastered on my face, or perhaps it's that Tanya knows Sibyl is too kind for her own good, but something really shakes her confidence to my benefit."
    T "Y-You're lying! She'd {b}never{/b}!"
    C "Well she {b}did{/b} so... yeah."
    "Now it's my turn to turn away slightly like I don't even care about Tanya silently fretting over my shocking admission. I still keep her in my peripheral vision just in case."
    mw "Two minutes to draw, everyone!"
    "Miss Woolsey ensures I have the last word in this particular confrontation by announcing the imminent start of the second half of the match."
    "The second half of our match is exactly the opposite of the first. While I am on top of my game, there's no doubt that Tanya is slipping."
    "When Tanya manages to snag the ball in their end of the field of play, she charges right up the field toward our goal on the attack. I fall back to help defend the goal but find her attention not on it at all, and rather locked onto me."
    T "Hrahh!"
    "All of Tanya's strength goes into the throw, launching the ball probably close to the speed of sound right between my eyes."
    C "(Oh shit)!"
    "I manage to evade the heavy lob entirely on survival instinct alone. I even manage to bounce it off my stick into the pocket of my nearby teammate, though that is entirely by lucky happenstance."
    mw "Nice block, Clover!"
    C "(It's nice and all to hear Miss Woolsey compliment my playing, but it how did she miss Tanya whipping that ball at my face?)"
    "Logically, I know that she didn't have the benefit of having locked eyes with Tanya's evil stare as she slapped the ball my way, but it still would have been nice to be acknowledged as the victim here."
    scene bg hallway with fade
    S "{b}Now{/b} what happened?"
    "When Sibyl comes to pick me and Tanya up after practice, she finds us both standing alone on opposites sides of the hallway outside the locker room."
    "More than be angry, she merely looks disheartened that her two best friends are once again on the outs with another over something she cannot possibly know or understand."
    C "Nothing's wrong. Tanya's just being a sourpuss."
    T "I {b}am not{/b}."
    S "Clover, no antagonizing her!"
    C "She started it!"
    S "Tanya?"
    "Sibyl looks right back to Tanya for her defense, and though she looks like she wants to protest my statement, she surely knows it to be accurate and stays silent."
    T "Whatever, let's go get lunch. I'm {b}starving."
    "As for the suggestion that we leave as soon as possible so that I can stuff my face all the more promptly, I have no objections. The three of us wander off toward the cafeteria with Sibyl in the middle."
    jump distancefromSibyl

label distancefromSibyl:
    scene bg black with fade
    scene bg hallway with dissolve
    "Though she appears loathe to leave me and Sibyl alone after what I told her at practice in the morning, Tanya eventually does leave us after lunch to go to her mystery Saturday afternoon activities."
    "I follow behind Sibyl as she wanders off to her own activities just as I have done just about every day since I arrived at the academy. Today we make our way through the halls and open the heavy wooden doors to the library."
    scene bg library with dissolve
    "Sibyl gets caught in a friendly conversation with the library committee on duty the moment she walks through the door, which isn't particularly uncommon at all."
    C "(What was her name? Rayna?)"
    "I give her a small wave of acknowledgment as I continue past toward the magazines. It's not that I dislike her as much as we just don't have any interests in common."
    C "(Reading and books and all that is Sibyl's passion, not mine.)"
    "The thought seems to stick in my head against my will. I try to chase it out by forcing some article from Girls' Mix through my skull, but it remains there persistently."
    "\"It's ~that~ time of year again! The season for fun fam get-togethers, wintery trips with your besties and, ofc, dreamy Valentine's dates with your beau that—\""
    C "(Ugh, seriously, what does Sibyl enjoy about this magazine?)"
    "The worst part about the whole magazine is the way it seems to be rubbing in my face how single I am right now after my first love blew up like a thermonuclear explosion in my face."
    "Almost on instinct, I look up toward the girl who occupies the darkest corner of my mind at the moment, and finally the thought niggling in the back of my head comes to the fore."
    C "(I'm in the library right now because {b}Sibyl{/b} likes the library, not because {b}I{/b} want to be here.)"
    "The library committee girl with whom Sibyl is so gleefully chatting away complements Sibyl way more than I do."
    "She shares common interests with Sibyl in such a way that they can get caught up conversing for an hour without realizing the time has passed."
    C "(Sibyl is so patient and understanding with my dumb self and also really, really cute, but would that have been enough on which to have founded a lasting relationship?)"
    "It's clear now that I was being a fool, as usual, when dealing with my first crush. I definitely let those positively delightful feelings take over my life and obscure any better judgment."
    "I've never read so much in my life as I have in the past month, and it was all to be closer to Sibyl. The books were entertaining, sure, but I only read them because Sibyl wanted me to."
    C "(I cannot stay content to be living in Sibyl's shadow. I need to have my own hobbies and find my own people.)"
    scene bg transition with fade
    scene bg transition with bedroom
    "Sunday starts with sound of bells tolling from the campus chapel."
    "On a normal Sunday the sound would merely drive me to bundle the sheets up tighter around my head and fall back into the depths of sleep none the worse, but today is different."
    "Today is March seventeenth, the Feast of Saint Patrick — the day that every single person alive pokes fun at my name."
    S "Are you sure you're feeling okay, Clover?"
    "That I haven't gotten out of bed until well into the breakfast period is normal enough, but to skip it entirely is almost unheard-of to the point of deep concern."
    C "One hundred percent fit as a fiddle, I promise. I'm just not hungry this morning."
    S "...If you say so."
    "Sibyl doesn't look at all convinced by what I say, and I probably wouldn't blame her if I were in her shoes. I don't want to make her worry about me but I also don't want to look so uncool making such a big deal about my name."
    S "After lunch Tanya and I are going to snap some reference photos of the new blooms shooting up in the flower beds outside the chapel. Would you like to come with us?"
    "Sibyl only looks mildly disappointed when I turn her down. The sight would have torn my heart in twain just a short time ago, but today I have other priorities."
    C "(Just as Spring has brought the first buds of new life to the chapel flour garden, so too shall I be reborn anew this season.)"
    "Thinking grand poetic thoughts is one thing, but actually having a plan to make this next personal metamorphosis stick after botching all the others is quite another."
    "The first step is, of course, not just doing whatever Sibyl wants to do. I need to identify what I like and make tangible plans to act on that to achieve my goals."
    C "(I like lacrosse!)"
    "I've already committed to lacrosse, mostly thanks to the hard work of Sibyl trying to snap me out of my funk when I was down in the dumps."
    "There hasn't been a single practice out of every Tuesday evening and Saturday morning session that I've missed thus far, and I plan to keep it that way."
    "My other interest and hobbies are much less easy to identify. After having abandoned most of my old, uncool passions from middle school, I don't even know myself anymore."
    C "(I like... sleeping.)"
    "This one I know is a strike out as the activity is a solo activity. A brief recollection of what happened with Vittoria and Vincenza crosses my mind but that type of \"sleeping\" doesn't count."
    C "(Eating has always been one of my favorite pastimes.)"
    "I know there are such things as professional eating contests, but somehow I don't think a club like that would fly in this dignified academy. Cooking is a related but entirely different discipline which I have yet to fully grasp."
    C "(And then there's, uhh...)"
    "The hands on Sibyl's clock spin around shockingly fast as I rack my brain trying to identify my interest and potential hobbies. A rumbling in my stomach eventually drags me out of my bed altogether in search of lunch."
    scene bg kitchen with dissolve
    "In keeping with my desire to live more for myself, I skip right to the kitchens and grab a triple bacon BLT to-go so that there's no chance of accidentally running into Sibyl and Tanya."
    scene bg dorm with dissolve
    C "(Well I know I like lacrosse, so maybe I can start there.)"
    "Now that I don't have Sibyl occupying my mind every second of the day, I can direct all of my effort to that instead. The only problem is that I already attend every practice session that Miss Woolsey organizes."
    "After enthusiastically finishing my BBBLT fast enough to get a minor stomach ache, I set off in search of Miss Woolsey while also formulating a plan in my head."
    play sound doorknock
    C "Miss Woolsey?"
    "Naturally, I start with her room in the dorm building. When I don't get a response back, I'm not too worried about it."
    C "(It's, like, three o'clock already, right? Of course she doesn't spend all day hiding away in her room like me. She has more important things to do.)"
    scene bg gymnasium with dissolve
    C "Miss Woolsey?"
    "The name echoes back to me from the depths of the silent gymnasium. Her adjacent office and the store room are empty too."
    C "(What do teachers even {b}do{/b} when classes aren't in session?)"
    scene bg hallway with dissolve
    "After leaving the gymnasium I resort to wandering the hallways in vain as my best hope of finding where Miss Woolsey has gone."
    "I would assume that there must be some kind of teachers' lounge around somewhere but I haven't the faintest idea where that would be."
    C "(A lounge, huh?)"
    "It might not be a teachers' lounge but there is a rather strange place which I've unexpectedly encountered Miss Woolsey once before."
    scene bg hallway with fade
    play sound doorknock
    C "Miss Woolsey? Are you in there?"
    "I try my student ID card at the reader but it only flashes an angry red light without letting me in."
    C "(What now?)"
    "I stand there in front of the closed for a minute or two while I attempt to come up with my next plan, when all of a sudden I hear a noise from behind it."
    C "(That sounds like... people speaking!)"
    play sound doorknock
    C "Miss Woolsey!? Are you in there?"
    "The muffled speaking goes quiet once more, and after a long minute of waiting, the door cracks open just enough for an eyeball to peak through it."
    g1 "{i}È Clover alla porta!{/i}" # It's Clover at the door!
    g2 "{i}Clover? Cosa ci fa qui?{/i}" # Clover? What is she doing here?
    C "(Oh no, what are {b}they{/b} doing here!?)"
    play sound doorclose
    "When the twins admit me to the room, I'm at first too busy trying hard not to meet their eyes that I don't even realize that both Miss Izzie and Miss Woolsey are present as well."
    O "Miss Woolsey, Clover is here to see you."
    "Being \"present\" is only a manner of speaking for how I find my teachers. Both of them sit at the low table with their legs under it, while surrounding both of them, but mostly Miss Izzie, are numerous open beer cans."
    "Having located Miss Woolsey, I now find her staring blankly into space, eyes unfocused, swaying slightly where she sits."
    H "Naomi! Snap out of it!"
    mw "Wha-ha?"
    "Miss Woolsey, visibly intoxicated, jumps suddenly to attention and stares straight at me."
    mw "Oh, Clover! To what do we owe this ple-shure? Do you want to read manga?"
    "As if it weren't obvious enough just looking at her, Miss Woolsey can also barely make it through a sentence without slurring a word, in addition to the strangeness of asking if I want to read books that are all in Japanese."
    C "Umm... hi, Miss Woolsey. No, I think I'm good. I wanted to ask you something about lacrosse, but... maybe another day."
    "Doing my best to ignore any complicated memories of encounters with the twins, I look their way for help in this situation. They provide none but do tell me how this scene came to be."
    H "Miss Izzie brought all of this beer and insisted that Miss Woolsey celebrate St. Patrick's Day with her."
    C "And did {b}you{/b}—?"
    O "We are only here to make sure they both survive to teach next week's lessons."
    mw "Good girls. Such good girls taking care of your friends!"
    "Unlike Miss Woolsey who is very much awake and conversational, Miss Izzie is out cold, face down on the table and lightly snoozing away with a contented smile."
    H "We also wouldn't miss a chance to tease Naomi while she's drunk."
    mw "I'm not drunk, I'm {b}tipsy{/b}!"
    O "Uh huh. Hey Clover, watch this."
    "Vincenza nudges Vittoria, who turns her attention away from me and back toward Miss Woolsey for some purpose I am sure to soon find out."
    H "Naomi, I'm so sorry to have to break the news to you, but the \"Secret Italian Supercat\" is not real."
    mw "W-What? {b}Nooooooooo{/b}!"
    O "It's true. As Italians ourselves we know all about it."
    mw "You just... you just don't have a h-high enough clearance to know about it. You'll see. It's {b}real{/b} and I'm going to have one!"
    "With how distraught Miss Woolsey suddenly becomes at the prospect of the giant cat from the dumb internet advertisement not being real, the twins move in to console her fears."
    O "Of course, Naomi."
    H "How foolish of us."
    "It's kind of off-putting to me how Vittoria and Vincenza keep using our teacher's first name, so when Miss Woolsey declares she's going to \"rest her eyes\" and promptly falls asleep, I ask them directly."
    C "What's up with you two, Miss Woolsey, and Miss Izzie?"
    H "We're friends of course."
    C "Don't you think it's weird to be this close friends with your teacher?"
    O "Why should it be?"
    C "Because they're your teachers! There's, like, an invisible line that you should never cross, isn't there?"
    O "Sibyl is friends with Miss Woolsey, isn't she?"
    C "Well, yeah, but... that's because they spent lots of time together when she didn't have a Vertu of her own. Do you even have anything in common with Miss Woolsey or Miss Izzie?"
    "The twins exchange a glance with one another as they typically do when I confront them both about something."
    C "(One of these days I should do some tests to find out if they really can read one another's minds.)"
    H "Did you know that Miss Woolsey was the President of the Student Council in her time at the academy?"
    "Though I wish I would forget my entire first day here at the academy, I in fact do remember all too well everything about that day — including how cringey I was acting."
    C "Yes, she told me once."
    H "Just as Miss Woolsey once held the position, now I too safeguard the secrets of the academy as the current President."
    C "What secrets?"
    H "If you wish to know the secrets, you must run for President yourself one day."
    C "There {b}are{/b} no secrets, aren't there?"
    "Maybe she has had enough of my questioning, or maybe she just doesn't care to answer anymore, but Vittoria decides to assume her princess persona and speak to her sister instead of answering me."
    H "Good heavens! Is not the young lady simply full of queries, dear sister?"
    "Vittoria mocks up fanning her face with one hand while Vincenza drops into a cool, relaxed pose with a hand pressed lightly to her temple."
    O "Assuredly so, Vittoria. Why should we be submitted to this interrogation when it is she who has intruded upon this place unsolicited?"
    C "Can you {b}please{/b} just speak normally?"
    H "Nay, Clover, if for us to drop this charade you seek, then answer us these questions two."
    O "First, enlighten us as to how it is that you have come to know of this place — itself one of the secrets which you so fervently deny existence."
    H "And second, why it is that you are here now rather than taking photos outdoors with your most treasured Sibyl?"
    "I know well enough by now that I'm not going to get anywhere with these two unless I play along sufficiently in their games. I consider just leaving instead but my curiosity wins out."
    C "Okay, fine. It's not a secret."
    C "I happened to find Miss Woolsey here one day so I know this room exists, though its purpose is still quite a mystery to me."
    C "As for Sibyl, I chose not to accompany her to gather reference photos because I have fully moved on from my crush and wish to be more independent from her."
    "I punctuate my wordy explanations with a small huff of finality to the whole ordeal, and await my chance to discover these secrets they keep holding over my head."
    C "Now that I've answer your questions, you will answer mine. First, just what {b}is{/b} this room supposed to be, and second—"
    O "Let's just stop you right there, Clover."
    H "We only agreed to stop play-acting, not to answer your questions."
    C "Are you being serious right now?"
    H "Perfectly serious. There are more secrets that this, the likes of which you can scarcely imagine, and none of them will we share with you."
    "One particularly resentful glare at the twins and they change their tune quickly enough."
    O "Okay, you win, you get {b}one{/b} question and we will answer truthfully."
    H "We're only doing this because we like you so much, Clover."
    "The twins have proven that they keep their word, so this isn't a chance to let slip away so easily."
    C "(I have so many questions about them, the academy, our teachers... How can I choose {b}one{/b}?)"
    show choice_darkness with dissolve
    menu:
        "\"Who actually {b}are{/b} both of you?\"":
            hide choice_darkness with dissolve
            C "Who actually {b}are{/b} both of you?"
            O "You caught us."
            H "We're actually alien robots from outer space."
            O "Sorry for not telling you sooner."
            "My eyes roll way up in their sockets after their answer, so I clarify further to get at what I really want to know."
            C "I meant that you're both so strange that I don't know what is real or not. I kind of doubt you're even twins."
            "Vittoria and Vincenza glance at one another in what appears to be legitimate surprise for once."
            O "Do you honestly not believe Vittoria and I are twins?"
            "After the initial shock passes, the pair of strange girls break out into giggles apparently at the absurdity of my questioning."
            O "Allow us to introduce ourselves once again."
            H "I am Vittoria Valvano."
            O "And I am Vincenza Valvano."
            H "We are from Milan, in Italy."
            O "We are identical twins..."
            H "...Though {b}I{/b} am the eldest, by eight minutes and eighteen seconds."
            C "(Vittoria is the oldest? Is that why she usually talks first when they do that weird back and forth speaking thing?)"
            O "We may like to play at roles for our own amusement, but we are no more different from you otherwise."
            C "But, like, you both do \"that stuff\" to other girls—"
            H "Sex."
            C "Y-Yeah, that... but like, you do it at the same time, together. Isn't that kinda awkward?"
            H "That's a second question, Clover."
            "Vittoria is quick to point out that only one question was the agreement, though the way they glance first toward one another, then quickly away from one another must mean... {b}something{/b}."
        "\"What is the purpose of this room, really?\"":
            hide choice_darkness with dissolve
            C "What is the purpose of this room, really?"
            O "The owner of the school stores her manga here."
            "I await further explanation, but none comes."
            C "This place is way more cozy than the average store room."
            H "She likes to read here too, when she isn't busy."
            C "Does she know that students and teachers are using her room to hang out and reading her books like this?"
            H "We only agreed to answer one question, Clover."
            "The twins smirk at me in some fashion that is difficult to determine whether it means they are friends with the mystery woman or are squatting on the private property of the owner of the school."
            C "(Suddenly I feel extra bad about being in this place where I apparently am not allowed.)"
            "Now that I've finally gotten to a point where I {b}like{/b} being at the academy, I don't want to suddenly be expelled for messing with the owners' stuff."
            C "I hope you know what you're doing."
            O "Relax, Clover. You're not in any trouble."
            H "But seriously, you're not supposed to know about this room at all so don't go blabbing about it."
        "\"How did you become friends with Miss Woolsey and Miss Izzie?\"":
            hide choice_darkness with dissolve
            C "How did you become friends with Miss Woolsey and Miss Izzie?"
            O "We share share many of the same interests, but besides that, we just enjoy their company."
            H "Miss Izzie loves hearing about our latest dalliances, and we enjoy learning from her depth of experience."
            O "Miss Woolsey is a charming woman who always tries her hardest to care for her students and support her friends."
            H "Is there any more reason needed to want to befriend these two lovely women?"
            "Vittoria motions across to my sleeping teachers, who at the moment don't seem as angelic as they say when they're both passed out drunk on the table across the room."
            C "I suppose not... I've just never known students to be so familiar with their teachers. It's nothing like that in public schools."
            "With a broad smirk, Vittoria leaves me with one final thought on the matter which is as vague as the rest of their answer."
            H "Prudence Prep simply is not like any other school."
        "\"How did you become friends with Tanya?\"":
            hide choice_darkness with dissolve
            C "How did you become friends with Tanya?"
            "Why I am wasting my one question on {b}Tanya{/b} of all people is beyond me, but I end up asking the question before I can take it back."
            H "Tanya is a very amusing girl and we share some of the same interests."
            C "You're all lesbians, I guess, but other than that?"
            O "We are all in English as a Second Language classes."
            "With how naturally Tanya speaks English, I almost forgot about that. Vittoria and Vincenza also speak English near fluently, so maybe it's just something that all foreigners have to enroll in."
            C "Oh yeah, I knew that but totally forgot since she speaks English so well."
            O "This academy has some unique properties that make it... an exciting place to enroll. Many of those students come from outside America."
            H "We have something of a little community in our ESL classes. Those of us who speak English well assist those who do not."
        "\"Was Miss Woolsey really the President of the Student Council?\"":
            hide choice_darkness with dissolve
            C "Was Miss Woolsey really the President of the Student Council?"
            O "Of course. She was the very first."
            C "Seriously?"
            H "The office of the Presidency has all the original notebooks from her administration. Many traditions we continue to this day were started by Miss Woolsey, like the Valentine's Day chocolate event."
            C "But now she's a... {b}gym teacher{/b}. How do you go from head of the class to the lowest rung of the teaching ladder?"
            "Almost like she knows we're talking about her, Miss Woolsey mumbles something incoherent in her sleep. We all turn to watch her for a moment before getting back to the conversation at hand."
            H "Her time at this academy was a turning point in her life. I'm sure she wants to help every student graduate with as many memories as she made here."
            O "You should ask her directly if you really want to know her reasons, Clover. Adults love talking about their glory days."
        "\"Do you do {b}all of those things{/b} you did with me, to every girl you play with?\"":
            hide choice_darkness with dissolve
            C "Do you do {b}all of those things{/b} you did with me, to every girl you play with?"
            H "Are you {b}jealous{/b}, Clover?"
            C "Wha—! {b}No!{/b}"
            H "I don't mind having a second go at it if you don't either. Maybe you want to do some of the touching this time?"
            C "{b}N-No, I—{/b} I just can't believe you actually do that kind of stuff all the time."
            O "Is that what you think of us, Clover? That we're a pair of floozies?"
            C "(Yeah, kinda.)"
            C "Not exactly..."
            "The pair of twins before me maintain a stern accusatory glare upon me until they eventually break down into giggles."
            O "We do act like it, though, don't we?"
            H "The sad truth, Clover, is that most girls are straight. This is something you've recently discoverd for yourself, yes?"
            "A small lump sticks in my throat as Vittoria begins to lecture me with clear reference to Sibyl, but I swallow it right away before it grows any larger."
            O "Most of our admirers like us merely because we're popular."
            H "Particularly Vincenza. Straight girls love their boy-replacements."
            C "You {b}must{/b} be lying. I mean, you did all that stuff to me so easily..."
            O "You practically begged us to, Clover. How could we resist?"
            H "You really have no idea how pretty you are, do you?"
            C "(Me? {b}Pretty?{/b} No way. All I ever heard in middle school was \"dark\" and \"gloomy\".)"
            "If the answer is that it's not common for them to go all the way with their conquests, then that must mean they have at least once before?"
            C "(They're also friends with Tanya, and I know she likes girls too. Is it possible that...)"
    "The twins may have truthfully answered my question but it still feels like they only told me half of the whole truth or avoided answering directly altogether."
    O "All that aside, we are glad to hear that you've moved on from Sibyl. Perhaps we could assist you in finding a new target for your affections who may be more receptive?"
    C "No, thanks. I'm still trying to figure out my own life right now. I only came here to speak with Miss Woolsey about lacrosse."
    "Both Miss Woolsey and Miss Izzie remain snoozing away with their legs under the low table and their faces drooling out atop it. It might be a funny sight if they weren't my teachers."
    "With my target located and determined to be incapacitated, I have no further need to stay and therefore make right for the door. The twins have other plans, however, and jump up to stand between me and the exit."
    H "Can you believe it, Vincenza? She won't even say goodbye to us when she leaves!"
    O "How rude, and after everything we did for her too!"
    C "Come on, let me out. Haven't you already had enough fun at my expense today?"
    H "But if you leave, then who will be left for us to play with?"
    C "Each other?"
    O "That doesn't count! It's no fun to tease someone who knows exactly what you're thinking."
    C "Not my problem. Bye."
    "I push right through the matched pair of girls before me without any difficulty. They doubly express their dissatisfaction with matching pouts but do not stop me from leaving any further."
    scene bg black with dissolve
    C ("Are all twins like that or is there something seriously wrong with those two in particular?")
    scene bg bedroom with dissolve
    "I'm back at my room before I know it. When I arrive, I find not only Sibyl atop her bed, but Tanya also, and spread around them dozens of instant photos."
    S "Clover, you're back! Come help us choose some photos!"
    "Stepping over, I turn my head this way and that so view each of the photos spread out haphazardly face on. Each one shows some part of the academy covered in plants just starting to emerge from their winter hibernation."
    C "(I recognize that one! That's right outside the entrance to the dorms!)"
    "I have to walk between the dormitory building and school building at least twice a day but have yet to notice the plants blooming at all. I'm always far more concerned about spending as little time in the cold as possible."
    C "These are great, Sibyl! What sort of art project are you going to use these for?"
    S "Well, we're not entirely sure yet. We were in the art store room together last week and found the most colorful stacks of tissue paper you've ever seen and wanted to work with it somehow."
    C "So you're going to cut flowers out of tissue paper?"
    S "Not exactly. We actually haven't decided how we're going to do it actually. One method is to tear the paper into little pieces and glue it on piece by piece to form the picture."
    C "And the other option?"
    T "I learned about a Mexican tissue paper art form called \"papel picado\". In this form of the craft, artists take an entire stack of tissue paper and chisel away pieces of form the image."
    S "We haven't decided which way we want to work on it yet."
    C "If you want to do it your way and Tanya wants to do it the Mexican way, just do that?"
    S "Ah, but, the thing is—"
    T "We're working on this project together, for our art club."
    S "Tanya is going to be really busy with lacrosse soon so she didn't want to get too far into a project of her own."
    "I was slightly interested in the art project that Sibyl was describing, but when Tanya mentioned lacrosse I am obviously far more interested in knowing the details."
    C "Why is lacrosse going to be busy soon?"
    T "The Spring season is starting soon, Clover."
    "Tanya tells me about the Spring season of lacrosse like it's something I know all about despite having only joined the team a few weeks ago. When it's clear I'm still in the dark, she helpfully elaborates."
    T "We've been playing sixes in the gym because of the Winter off season, but starting soon we will be playing a full season of competitive field hockey with the other local schools."
    T "You knew that we were an actual competition team when you signed up, didn't you?"
    "The exasperation in Tanya's voice sounds far too much like a condemnation of my stupidity for me to admit that I never thought too deeply about that aspect of practice."
    C "(I enjoyed playing in the gym so I signed up. I never really considered that I'd have to play against another school for real.)"
    C "Of course I did! I'm just... not sure that I'm up to the top of my game yet, that's all."
    "I remain with Sibyl and Tanya to pick through the stack of photos they took but all the while I am distracted by this new revelation about lacrosse."
    C "(Now I {b}really{/b} need to get my game play up to snuff before they kick me off the team!)"
    jump lacrosse_explainer

label lacrosse_explainer:
    scene bg transition with fade
    scene bg gym with dissolve
    "Our Tuesday evening practice session arrives with Miss Woolsey looking quite as alive and alert as she always does, probably thanks to the care of Vittoria and Vincenza."
    "We all change into our uniforms and gather in the gym as usual, but rather than checking our sticks, Miss Woolsey passes around a clipboard and pen."
    C "What's everyone doing with the clip board?"
    T "Signups for the Spring season. I told you about it the other day."
    "The husky voice of Tanya springs up right next to me when I ask the question aloud. It's a surprise considering I was mostly just talking to myself."
    C "Signups? But I'm already on the team?"
    T "You still have to officially sign up for the inter-school tournament, and Miss Woolsey needs to know what positions you would prefer to play too."
    C "What do you {b}mean{/b} what positions I'm going to play? I've been out on the field this whole time; it's not like I'm going to take up goaltending now!"
    T "No, I mean... well, maybe Miss Woolsey should help explain this all to you."
    "As every other girl on the team was around for the Autumn season of competition, I'm the only one left unsure what to do when the clipboard comes my way."
    "Tanya scribbles something next to her name then passes it my way. Reading down the list I see everyone write some combination of two letters beside the names."
    C "(\"DF\", \"MF\"... \"GK\"? \"FW\"?)"
    "None of it really makes any sense to me. Thankfully, Miss Woolsey is there to explain it all in her usual helpful manner."
    mw "For the high school lacrosse tournament starting in the Spring, we must field a team for {b}field{/b} lacrosse rather than lacrosse sixes. The letters are shorthand for which position you prefer to play."
    C "How is field lacrosse different from what we've been playing all Winter?"
    mw "Field lacrosse has a larger field of play and defined positions. In sixes, everyone on the field plays both attacking and defending roles, but in field you have to specialize."
    mw "We play sixes indoors during the winter to avoid the worst of the cold while also keeping everyone's skills sharp!"
    "Looking at the signup sheet again, suddenly the \"DF\" and \"GK\" letters make sense."
    C "(Defenders and Goalkeepers, huh? So what about the others? Fffwwwwattacker? Mmmffffattacker?)"
    C "Miss Woolsey, what positions are \"FW\" and \"MF\"?"
    mw "That would be \"forward\" and \"midfielder\". The forward is primarily concerned with scoring goals and the midfielder plays a little bit of both attacking and defending."
    mw "If you liked playing as you did in sixes, I would suggest that you request the midfielder position."
    "Miss Woolsey's advice makes sense to me, so I raise the pen toward my name to mark an \"MF\". Just as I am about to do that, however, I spy Tanya's name and the letters \"FW\" beside it."
    mw "You want to be a forward, Clover?"
    "Miss Woolsey is surprised when I hand the clipboard back to her, which is no surprise to me considering how she's praised my defensive skills a bunch and my offensive skills not even once."
    C "(So what if I don't have as many goals on my stick as the other girls? Once I start my intensive training I'll be as good as any of them!)"
    T "A forward? Do you really think you're good enough for that?"
    C "Shut your stupid face hole, Tanya! You don't get to tell me what I can and can't play, or maybe are you just {b}scared{/b} I'll score more goals than you, huh?"
    T "Maybe {b}I{/b} can't tell you what to play, but Miss Woolsey will."
    "Tanya is far too calm for my liking after my aggressive retort, so I look back to Miss Woolsey for support against her but receive only the opposite."
    mw "What Tanya means to say is that you will have to compete in tryouts with everyone else who wants to play forward, including Tanya."
    mw "We have to field a full team and there are only so many forward positions available, so anyone who doesn't make it will have to play a different position."
    "Tanya is good at playing on the attack, and even I can privately admit it to myself. It would be tough going up against her, let alone the older girls who have been playing longer."
    "Even so, I'm not about to let myself lose a single thing to Tanya, and I plan to be way better than I am now before the field lacrosse season starts anyway."
    C "Yes, I want to play forward. I know I'm not the best but that's why I tried to talk to you over the weekend."
    C "I want to train harder so I can play better and win my spot with the forwards!"
    "The fire returns to me as I tell Miss Woolsey my plans, not just because it's my new self that I'm cultivating but also because it'll mean beating Tanya at her own game for once."
    mw "You're serious about wanting to train harder, hmm?"
    C "Yes, Miss Woolsey!"
    "Miss Woolsey stares me down as she ponders my enthusiasm. Her gaze passes between me and Tanya beside me before she makes up her mind to continue on with the signups."
    mw "I have a few ideas about what you can do. See me after practice, okay?"
    C "Thank you, Miss Woolsey!"
    "Tanya waits for Miss Woolsey to move on before trying to shoot my dreams full of holes."
    T "You're better off focusing on your defensive skills, Clover. You're just not good enough to be a forward. Even {b}I{/b} might not make it through the tryouts."
    C "Whether {b}you{/b} make it through tryouts or not is none of {b}my{/b} concern. Why do you always have to tell me what I can and can't do, huh?"
    "Tanya's eyes go wide at my response and she turns away with a grimace, suddenly finding an interest in the floor tiles."
    C "(That sure showed {b}her{/b}, huh?)"
    "Why what I said was so particularly effective in shutting Tanya up is beyond me, but I'll take the win every time."
    "The signup clipboard makes its way through the rest of the team quickly enough, finally letting us get to actually playing instead of standing around."
    scene bg gym with fade
    "I truly give it my all during practice. Not just one hundred ten percent, but one hundred twenty, maybe not even one hundred thirty!"
    "That I don't manage to score a single goal isn't a problem, because Tanya doesn't either. Everyone else on the team is also giving it their all with signups so fresh on the mind."
    "When Miss Woolsey blows the whistle to en the last match of the day, most girls tiredly trudge off to the locker room to change, but not me."
    "Ignoring the aches soaking deep in my legs, I trot right up to Miss Woolsey with no delay to begin my special training."
    C "Miss Woolsey, I'm here! You said you had some ideas of how I could improve my game?"
    mw "I wonder what the girl who wasn't sure whether or not she'd even give lacrosse a try would think if she could see herself now."
    "Miss Woolsey muses on my obvious change of heart after just a couple shorts months. It's plainly obvious how happy she is that I've committed to firmly to her team."
    C "I know I wasn't sure about it at first, but I really like playing lacrosse."
    "My teacher doesn't know nor needs to know anything about my plans to use lacrosse to metamorphose myself from bitchy caterpillar Clover to sporty cute butterfly Clover."
    C "I want to do everything possible to win that spot as a forward on the team. Please help me!"
    mw "I appreciate your enthusiasm, Clover, but I'm not sure I have anything more to teach you."
    C "Huh? But you said—"
    mw "On the other hand, Miss Izzie would likely be overjoyed to have the opportunity to do some coaching again. She may have a different perspective on how you can improve your play."
    mw "You have art class tomorrow, right? Ask her about it then; I'll talk to her about it tonight so she has some time to think about it before then."
    C "O-Okay..."
    "It's not that I don't want the extra assistance causing me to have misgivings, but rather that my little art teacher, Miss Izzie, is capable of training me in any way that Miss Woolsey cannot."
    mw "Oh, and I had another idea too."
    C "Y-Yeah!?"
    "Just as I'm about to get excited for some really good improvement plan to come out of Miss Woolsey, I see her cast her sight across to the other side of the gym."
    mw "Tanya, could you come here for a moment?"
    C "(Huh?)"
    T "Miss Woolsey?"
    "Tanya jobs up beside me, again. Miss Woolsey doesn't leave me in suspense as to why she called my arch rival over."
    mw "Clover is going to ask Miss Izzie for a special training session, and I am almost positive that she will want to do it."
    mw "I'd like you to join Clover and practice together."
    T "{b}What!?{/b}"
    C "{b}Why!?{/b}"
    "Disregarding out outbursts entirely, Miss Woolsey merely smiles and replies calmly while packing away the lacrosse balls."
    mw "Clover isn't the only one who is going to have a tough time competing with the upperclassman girls in the forward tryouts, and you're both friends, aren't you?"
    C "{b}Are{/b} we!?"
    T "Miss {b}Woolsey{/b}..."
    "Despite our whining, Miss Woolsey remains resolute."
    mw "You know this is the best for both of you, now off you go!"
    "Tanya gives her a particularly pleading look of dread but Miss Woolsey only shoos us off to the locker room with a huge smile blooming across her face."
    jump izzie_lacrosse_request

label izzie_lacrosse_request:
    scene bg transition with fade
    scene bg artroom with dissolve
    S "I think it's a wonderful idea!"
    "To no one's surprise, Sibyl is very pleased with the prospect of Tanya and I training together for the lacrosse tryouts."