label study4finals:
    scene bg transition with fade
    scene bg lacrosse with dissolve
    "The very next morning after the nurse clears Tanya to return to normal life, she's back out on the track getting her laps in like she has to make up for lost time, and doing so with an obvious skip in her step."
    C "(I don't think I've ever seen her smile so brightly!)"
    "The same delight finds its way to my lips just watching my girlfriend run around the circular track like doing so is more fun the world's biggest water park and tastes sweeter than the world's sugariest candy bar."
    C "Tanya!"
    "She changes course when I call out to her, slowing to a walk upon approach and immediately starting her cool-down calf stretches by the time she stops in front of me."
    T "Good morning, Clover!"
    C "Good morning. You started without me?"
    T "Sorry, Clover, I just couldn't wait. After not being allowed to exercise for so long, and then Sierra started waking up..."
    "I watch over Tanya as she does her stretches. By the amount of sweat already sticking to her jersey, she's clearly already been out here for a while, maybe even before the sun started coming up over the horizon."
    C "(She looks super hot... and not just literally.)"
    C "It's okay. What's up with Sierra?"
    T "There's {b}too much{/b} about her. You should know that by now."
    T "She started treating me like her dream diary since I've been stuck in our room with her every morning, and I {b}Just. Don't. Care.{/b} about her dreams."
    "Tanya sighs with some small amount of frustration, and I realize that in my curiosity for what Sierra has been doing, I've already taken away some of that magical happiness she was showing before I'd interrupted her running."
    C "You looked really good running out there! Your form is as good as ever, Tanya."
    "To ease my guilty conscious, I steer the conversation away again to more enjoyable topics. Tanya herself switches her stretches to her hamstrings in an extra clean break."
    T "Thanks. I might be a little off my peak after being all but bedridden for so long, but it feels so good to be out on the track again."
    C "You know what? You did look a little rusty. I think today's the day I surpass you for good."
    "I do some of my own warm-up stretches, interlacing my fingers to stretch tall in a manner with a purposeful aloofness after such an inflammatory statement"
    T "Not if I break your legs first, Clover!"
    "From where she's on the ground stretching, Tanya lunges toward my legs with outstretched hands. I manage to jump out of the way just in time \"just in time\" from Tanya's reach, but not before releasing an embarrassing sound that is half giggle and half shriek."
    C "N-Nooo, Tanya, you {b}brute{/b}!"
    T "Get back here!"
    "Tanya scrambles back onto her feet just as I dash away, and for a good long while we chase each other around the lacrosse field, throwing taunts each way, until more girls start to show up and we both become self-conscious about flirting so openly."
    scene bg cafeteria with dissolve
    "At breakfast, Tanya tears right through her first yogurt parfait and even ventures further into a bacon and egg breakfast sandwich in such a display that Sibyl must think we'd changed places."
    S "I'm so happy to see you back to normal, Tanya! You looked absolutely {b}miserable{/b} being stuck in bed."
    C "And like a dog with one of those big poofy plastic collars digs wear to prevent them from biting themselves when you could only spectate at practices."
    "Tanya pauses from chowing down on her breakfast sandwich long enough to give me a sarcastic \"ha ha\", while I can only focus on how delicious the sandwich looks."
    C "(If Tanya herself is eating a bacon and egg sandwich, then she can't tell me off for over-eating, right?)"
    "I'm already half way to standing up and excusing myself to fetch my share of delicious breakfast meats squeezes between a fluffy biscuit when Tanya drops a bomb that sets me back into my seat."
    T "Just in time to start the last week of classes before exams too. I tried to keep up with the lessons but I think I'll need the week to get back up to speed with where we are now in time for finals."
    T "Are we going to study together all weekend again, just like we did for midterms?"
    S "You know it, study-buddy!"
    C "{b}F-Finals!?{/b}"    
    "Finally, my two friends turn their attention to the color rapidly draining from my face. All thoughts of the delicious breakfast sandwich fly away on the breeze."
    S "You're obviously welcome to study with us, Clover!"
    T "Sibyl is {b}incredible{/b} with exams, Clover. You might think you get it after seeing us study for those quizzes, but Sibyl was something else entirely at the midterm exams."
    T "I probably learned more studying with her the weekend before midterm week than I did the whole first half of the year! There's no way you can fail if you follow her process."
    C "(I wasn't worried about failing! My grades aren't {b}that{/b} bad!)"
    C "I guess I just... wasn't expecting to come up so soon. With the last few games of the season, and then Tanya's concussion, things just all sort of happened really fast."
    S "You and Tanya still have a full week of classes before we take our final exams next week, Clover."
    C "Me and Tanya?"
    "The way Sibyl words her statement strikes me as odd, so I press her on it directly."
    S "I have started my study preparations as of this morning!"
    S "I'm here at the academy on a scholarship, remember? If I don't keep top of the class, or near it anyway, I might not be able to come back for sophomore year with you and Tanya!"
    C "O-Okay..."
    "I sure don't want Sibyl to not be able to attend Prudence Prep next year, but it also seems like she's near perfect in her academics already, so starting to study hard a week plus in advance of the exam seems a little much."
    T "Maybe it doesn't hurt to stat reviewing a little bit at a time leading into the weekend. I know I'll need to catch up on what I missed too."
    S "Exactly! There's a lot of material to cover, and just one weekend won't cut it if I'm going to place first in the class."
    "Sibyl exudes confidence, so I leave her to her studies and say nothing when she surreptitiously starts flipping through flash cards while we're still chatting over the remains of our breakfast."
    scene bg classroom with dissolve
    "All throughout classes, I observe Tanya furiously writing notes on the new content while referencing copies of the past week's notes she borrowed from Sibyl."
    "Sibyl is doing something very similar. At once, she takes notes on the current lesson of the day in one notebooks, while beside that notebook is another open notebook for another subject entirely."
    "Meanwhile, I can barely keep focus as the teacher drones on about vocabulary. My lack of attention comes back to bite me when we're sprung a sudden pop quiz."
    C "(\"Assiduous\"? This can't mean, like, someone who has a really big butt?)"
    "My attention shifts to Tanya for a time, but the impossibly loud ticking of the clock and scratching of pencils around me draws my attention back to the quiz."
    C "(\"Florid: Of or relating to a flower.\" Yeah, that has to be right.)"
    "When the quizzes come back graded, I'm starting to think Sibyl is onto something by starting so early."
    C "You're very \"assiduous\", Tanya."
    T "Thanks, Clover!"
    C "You're welcome."
    scene bg bedroom night with dissolve
    "That evening, the three of us work through our new assignments and help Tanya get caught up with what she missed from the moment the bell rings to mark the end of class to the time they ring to mark curfew."
    C "The shower's free if you want to use it, Sibyl."
    "I call out to Sibyl after finishing up my nightly sleep activities, but to my surprise she's still knee deep in notebooks and textbooks on her bed."
    S "I'm almost done reviewing this chapter. Will it bother you if I keep on my clip-on book light on?"
    C "Nope. Good night, Sibyl."
    S "'Night, Clover."
    scene bg bedroom night dark with dissolve
    "Truly, Sibyl's clip-on light doesn't bother me. She's often used it before when she gets too sucked into a novel to put down for something as relatively unimportant — to her — as sleep, and I cocoon myself so tightly that no light gets in anyway."
    scene bg bedroom with fade
    "What bothers me is that when I awaken bright and early, her clip-on book light is still activated. Like the day I met her, she lies haphazardly on her side, nestled amongst the contents of her school bag."
    C "Sibyl?"
    "I call out to her faintly, unsure whether I really want to wak her or not, and ultimately just click off her lamp with the decision that she probably needs the extra sleep if she stayed up late studying."
    C "(If she sleeps in too late, Tanya and I can come fetch her well before classes begin.)"
    scene bg cafeteria with dissolve
    "It isn't until Tanya and I are busy replacing the calories we expended on another invigorating morning of exercise that Sibyl shows her face again."
    S "Good morn—"
    "A yawn interrupts her greeting as she sits down and immediately pulls a ring-bound stack of flash cards out of her bag."
    T "How late were you up studying last night, Sibyl?"
    "Tanya catches right on to the concerns I'd been keeping to myself, and isn't afraid to push them at Sibyl like I was when I woke up."
    S "Not {b}too{/b} too late. I just lost track of time a little. We covered a much broader curriculum this year than I remember."
    C "(Tell me about it.)"
    "Sibyl had very thoroughly caught me up to the rest of the class when I first transferred in, but what she crammed into my brain months ago, I'm finding, is just about gone now and making my own preparations much more difficult."
    T "You {b}need{/b} to sleep, Sibyl. You can cram al of our lessons in your brain, but if you don't give it time to rest, you won't remember any of it."
    S "I know, I know!"
    "Sibyl agrees with Tanya, though somehow also rather dismissively when she chooses to fetch a breakfast burrito with one hand still flipping through her flash cards."
    "Tanya and I share a concerned look the very moment she's gone. However, worried we might be, catching her eyes in such a way also gives me a minor thrill."
    C "(We're just like Vittoria and Vincenza. We're {b}that{/b} close already!)"
    "We both seem to agree wordlessly that something has to be done about Sibyl in the small span of time before she returns to our table."
    T "Since Clover and I don't have practice today, Sibyl, we thought we'd like to join you in the library after classes."
    S "That would be wonderful! But are you sure you don't want to spend the time together, just the two of you?"
    "I shoot a quick frown at Tanya, hoping that Sibyl doesn't catch it on the way."
    "With the lacrosse season officially over, we {b}had{/b} planned to make another evening date out of the time we'd normally have spent in lacrosse practice."
    C "I'm still slogging through review of the material I missed before transferring in, and Tanya is nearly through the stuff she missed while forbidden from attending classes."
    T "We thought... that you'd definitely be able to help us out after art club this evening!"
    C "Maybe I'll come too! Miss Izzie doesn't mind non-club visitors, right?"
    S "Art club? Oh, I'm not going this week."
    C "You're \"not going\"!?"
    "I exclaim loudly Sibyl's words back at her, and hearing an echo, turn my head aside in time with Tanya to find she mirrored my response exactly."
    S "I have too much to yet to cover before next week."
    scene bg library with dissolve
    "And so, after dreaming all week of my upcoming date with Tanya, where we'd surely get to kiss a whole lot and cuddle so closely that I'd look like a baby koala squeezing tightly to Tanya mama-koala..."
    C "\"Krebs Cycle\"? I've never heard of that in my life."
    S "It's from the unit on cellular respiration."
    "Half an hour into intensive studying with Sibyl and my brain already feels like it's going to melt in my skull and drip out my ear holes, but despite that I have to admit that I am learning a lot."
    C "Right, cellular respiration. That... produces energy for animal cells."
    S "Yes!"
    "While legitimately studying, Tanya and I also take turns having Sibyl help us with something, as I'm doing now for my biology recap. I don't know if it's helping, but we think it's better than her getting laser focused by herself."
    T "Oh, right, we read Animal Farm in English class this year. I totally forgot. What was that about, Sibyl?"
    S "Animal Farm? That's one's about farm animals who rebel against their farmer to..."
    "Tanya picks books as her choice of subject this time to get Sibyl distracted from her multitude of notebooks and on a long tangent that will prove less burdensome on her brain."
    scene bg bedroom night with dissolve
    "I think we're making good progress with giving Sibyl a little break, but she's right back to her old ways the moment we settle in after curfew."
    C "We studied a whole lot today, Sibyl. Why don't you take some well-earned rest?"
    S "I'm good to keep going, Clover."
    C "Are you sure?"
    S "Yes."
    "Her first reply was as sweet as her usual self, but her curt latter reply, while not aggressive, clearly indicates how much patience she's losing for my interruptions."
    C "Okay... get to sleep soon. We have a science lab tomorrow."
    "Even after sacrificing our date today, I still am unable to stand up to Sibyl and tell her that she needs to give herself a break. I make do by squeezing the Tanya in my dreams extra hard."
    jump sibylbreaks

label sibylbreaks:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "Sibyl never lashes out at me and Tanya, but the message becomes increasingly clear through her actions and words that she wants us to back off with bothering her during study time."
    "We have no choice but to do as she wishes, however concerned we become with her ever-increasing late arrival to breakfast and continually withdrawn sociability."
    scene bg gym with dissolve
    "It all eventually comes to a head late in the week, during gym class."
    T "Serving!"
    play sound volleyball
    "From Tanya's hands, the volleyball soars over the net to be bumped by a girl on the other side, and volleyed back our way."
    C "Got it!"
    play sound volleyball
    C "(It's definitely no lacrosse, but volleyball is pretty fun too!)"
    "Tanya and I are both in our element, jumping and diving here and there after the ball, our pent up energies that now going to lacrosse coming out in gym class."
    "Other girls are less enthusiastic. Sibyl, who normally gives gym class her best effort, is particularly low energy, and it's no surprise with how much of her energy has been going into studying lately."
    T "Going over!"
    "Tanya sets me up and I whack the ball hard over the net, leaving the girls on the other side to jump at the speeding ball, and upon making contact, leaving it to ricochet furiously back over the net."
    C "Sibyl!"
    "I shout her name as my brain uses my new geometry skills to accurately predict where the ball will fly, but it's still too slow for Sibyl or anyone else to react in time."
    "The ball catches the already unsteady Sibyl square in the face, of course, knocking her right down in her butt. Everyone rushes in quickly to pull her back on her feet."
    mw "Are you hurt, Sibyl? Let me see..."
    "Miss Woolsey arrives quickly. The other girls part ways while we support Sibyl, who clutches at her nose, pinching it together."
    S "Nose bleed..."
    "Sibyl's voice comes out nasally when she speaks. It's kind of cute to hear, and would be more if I weren't concerned for her well-being at the moment."
    "Miss Woolsey inspects her nose, offering her a handkerchief from her pocket to help stem the flow of blood, and otherwise places a hand on her forehead."
    mw "Sibyl, you're burning up!"
    scene bg nurse with dissolve
    pause 0.5
    scene bg hallway with dissolve
    "Against her objections, and most importantly with Miss Woolsey's approval, Tanya and I drag Sibyl off to the nurse to compel her to get some rest for her own good."
    nurse "Her nose isn't broken; it's just a nosebleed. She also has a light fever."
    C "She's been pushing herself too hard while studying for finals."
    T "We've been trying to get her to give it a rest, but she won't have any of it."
    nurse "Alright, calm down."
    "We plead our case to the nurse from just outside the door to the nurse's office, where Sibyl can't hear us but surely is trying to from the lone bed there."
    nurse "I'll place her on mandatory bed rest overnight. Her injuries aren't sever, but stress will only make her recovery slower."
    "The nurse pointedly looks to Tanya, who learned this fact the hard way very recently. She nods her agreement even if she knows how hard it can be to sit still like this."
    C "Thank you!"
    scene bg nurse with dissolve
    S "What's going on?"
    "I try to stifle a giggle when looking again at Sibyl, who's nose is stuffed in both nostrils with what can only best be described as \"nose tampons\"."
    nurse "You're staying here overnight to get some rest. I'll be back with some fever medicine in just a moment."
    "As soon as the nurse leaves Sibyl begs us to smuggle in her flash cards for her, to which we flatly refuse."
    T "Trust me, I {b}know{/b} how boring it can be to lay in bed doing nothing all day, but you need the rest."
    C "Our final exams are only a few days away. You want to be {b}healthy{/b} for those, don't you?"
    scene bg nurse with dissolve
    "Together with Tanya, our flawless reasoning eventually draws an reluctant agreement from Sibyl to take the night off and rest up for the upcoming weekend and exams following it."
    "Having already blown past the end of the gym class and part way through etiquette lessons, the last of the day, we decide just to stay with Sibyl until dinner, only leaving to fetch food for all three of us."
    scene bg hallway night with dissolve
    "When the shadow start to grow long, we wish Sibyl a peaceful rest and speedy recovery from her fever, then step out on our own together."
    C "I hope this whole incident proves how right we were about wanting her to take a break from studying."
    T "She's already learned her lesson, I'm sure. She's going to want to do everything possible to break the fever before exams next week."
    scene bg dorm night with dissolve
    "The two of us walk together, at some point slipping hands together without realizing it, until we reach her door at the dorms to drop Tanya off before curfew like we do every night."
    T "What'll you do without Sibyl there tonight?"
    C "I dunno. Take a bath maybe? I haven't soaked in a bath {b}once{/b} since coming here."
    T "That sounds nice. Sierra always hogs ours."
    C "You—"
    "I start to say something that flies right out of my mind, as I immediately get struck by a terrifyingly giddy realization that trembles my hand still held with Tanya's."
    C "(Tonight is the night.)"
    C "(Tonight is {b}the{/b} night.)"
    T "Clover?"
    C "S-Sibyl won't be sleeping in our room tonight, so... maybe you could come take a bath in my room..."
    "The words escape haltingly, with great effort on my part. My skeleton feels like it's going to wiggle right out of ym skin with how nervy I am."
    "Thankfully, Tanya catches on quickly to my meaning, a bright red flush growing on her face that she tries to hide by brushing her fingers through her hair with the hand not still held in mine."
    C "...I-If tonight is good for you."
    T "Yeah... tonight is good. Just let me tell Sierra."
    scene bg dorm night with dissolve
    play sound doorclose
    "I whip around away from Tanya's door the second she disappears behind it to stuff both palms into my face and stifle a little scream."
    C "(Oh my gosh. It's happening. Oh my gosh.)"
    "A whole list of things that I really wish I had time to prepare first flies through my head as I wait for Tanya to show her face again."
    C "(I shaved my legs this morning, right? Yeah. Phew.)"
    play sound doorclose
    "When she does re-appear, I try to resume my normal attitude, maybe even showing a little aloofness like I'm totally not freaking out inside."
    C "Oh, hey."
    T "Hey."
    "Tanya responds equally cooly, but I can tell that she's nervous too. She can probably see right through my charade just as well."
    "The short walk from her door to mine feels like a marathon with how fast my heart beats and time seems to slow down around me."
    scene bg black with fade
    play sound doorclose
    pause 1.0
    "The bath is small for two people, but we do not mind."
    pause 1.0
    scene cg morning_after with fade
    "Perhaps it's because the night passes like a dream that I sleep so restfully."
    "When I finally awaken, I find Tanya still snoozing peacefully in my arms. I give her a tight squeeze and revel in the feeling of her smooth skin against mine once more, as I did so much the night before."
    C "(I love her so much.)"
    "I'd been avoiding the word after using it perhaps too freely in my pursuit of Sibyl, but this time, I feel like my feelings for Tanya truly deserve it."
    C "(I love Tanya.)"
    pause 3.0
    scene bg black with fade
    jump finals

label finals:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "Sibyl recovers in time for the weekend and with enough vigor to lead me and Tanya through an in-depth workshop of every single thing I learned at the academy during the year, and the content I missed before transferring in."
    C "(Sibyl really is incredible. I'm so lucky to have her as my Vertu partner.)"
    scene bg bedroom night dark with dissolve
    "Sunday night, the last few hours before the first of a series of biggest exams of my life, finds me lying in bed wondering what the week will bring."
    "I should by all rights be at my wit's end with fear for the break of dawn, but when I clutch my pillow closer and pretend I can still smell Tanya's scent upon, the pillow, I fall right into a restful sleep."
    scene bg classroom with fade
    "Exams are administered twice a day, one in the morning and one in the afternoon from Monday through Thursday."
    "As much as I'd like to just do them all faster to get it over with, spreading them out helpfully ensures we get to focus on each individual subject."
    scene bg cafeteria with dissolve
    "Meal times become makeshift cram sessions with all of our notebooks spread out across the table, each of us taking bites between a split of the next notebook page. Not every examination is a written test, however."
    scene bg artroom with dissolve
    "Arts, athletics, and etiquette are tested as a pass/fail practical examination."
    "Having never learned the secrets necessary to produce art through close proximity to Sibyl, I'm naturally incredibly anxious about arts in particular."
    "Thankfully, Miss Izzie just plops a brick of modeling clay before each of us and tells us to go nuts with it."
    "I glance over to Tanya, who's intensely focused on finger-crafting a big crashing wave that doesn't look like it should be able to stand up but somehow does."
    "Sibyl, meanwhile, somehow turned her block of clay into a fully grown tree, complete with tons of leaves to fil the branches that she scrapes out individually with a little pointy tool."
    C "(How does she do this stuff!?)"
    "My creatively deficient mind turned my large block of gray clay into smaller blocks of gray clay. When I see Miss Izzie coming around to check on progress, I quickly stack them up like I have a real plan."
    mi "How are you doing, Clover?"
    C "Really, {b}really{/b} well, Miss Izzie! This is, as you can see, a critique on... childhood... evoking the form of common block toys to... symbolize growing up."
    "I put on my biggest grin for her, which she happily gives right back, and piles a vigorous patting of my head on top."
    mi "Who could argue with that, Clover? {b}Pass!{/b}"
    scene bg gym with dissolve
    "Perhaps the highlight of the hellish finals week is my athletics practical exam."
    mw "Congratulations, Clover! You had the best time in the hundred yard dash."
    "Immediately after the announcement, I turn to stick my tongue out at Tanya, who quickly pinches it with her fingers before I can retract it."
    C "Moy thungue!"
    T "I still placed higher than you in the long jump."
    C "Tho hwat?"
    "My tongue still captured, I blindly throw my hands out to push back at Tanya's face to force her to let go, while Sibyl looks on with equal parts humor and astonishment."
    S "Only the two of you would call this \"flirting\"."
    scene bg cafeteria with dissolve
    "It's only when it's all over that I can finally breathe a heavy sigh of relief."
    C "It's over..."
    C "Finals are done..."
    C "I'm free..."
    T "Except for that essay you have to write because you failed the etiquette practical."
    C "Shhh. Let me enjoy this before it melts."
    "The academy shares my feelings about how to appropriately celebrate the end of finals, that being by making banana splits with all the works for every student to enjoy."
    S "Half the class failed the etiquette practical. Maybe the instructor is too strict?"
    T "Some upperclassmen told me that none of the practical exams actually count for real. The essay for those who fail is just to push the students to take the class seriously."
    C "(The practicals don't count!? But I was so proud of my passing grades in art and athletics!)"
    "The make-up essay for the etiquette class is only a five hundred word reflection on what I learned. It's only a slap on the wrist for not passing the exam, but it's still a bummer to have to write it in the first place."
    C "How do you think you did, Sibyl? Good enough to keep your scholarship?"
    S "My preparations proved more than adequate. I am confident that my scholarship will remain for next year."
    "Putting down her spoon for a moment, Sibyl's expression turns a degree more earnest."
    S "Thank you both for forcing some sense into me. If you hadn't, I might have been too sick to even take the exams at all."
    C "You're welcome!"
    T "I'm sure the academy would have let you take the exams once you recovered... but I'm glad it never had to come to that at all."
    S "So am I. How did you feel after your exams, Tanya?"
    T "Great. I couldn't have done it without your study prep, Sibyl."
    C "Yeah, Sibyl, you're the best!"
    S "I am happy to have helped! You can count on me next year too!"
    C "(Next year...)"
    "Sibyl's words are a harsh reminder that the end of final examinations also means the end of the school year, but I try no to let it eat at me when I could be eating at my banana split instead."
    C "(And besides, the school year isn't over yet! There's still one more big event before we all start packing...!)"
    jump eveoflastday_part1

label eveoflastday_part1:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "The morning of the last Saturday finds me hibernating in the depths of my bed such that Tanya has to come in and drag me out of it herself."
    C "But lacrosse season's overrrr..."
    T "Proper fitness does not have a \"season\", Clover. It requires constant, thoughtful consideration to introduce activity into every day."
    "I moan and groan from the warm confines of my bed, but the combined strength of Sibyl and Tanya on each leg easily drags me right out of the sheets."
    scene bg path with dissolve
    "It's all for the best that me, my pillow, and my sheets are all rent asunder. It's a lovely day outside once my eyes blink awake into the brightness of the comfortably warm early Summer."
    S "Oh! We should have brought your lacrosse sticks!"
    C "Why?"
    S "To catch butterflies of course!"
    "The three of us prance around in the sunlit meadows away from the academy buildings. Sibyl in particular is having the time of her life running through the tall wild grasses in pursuit of butterflies."
    S "{b}Achoo!{/b}"
    "Until her hay fever gets the better of her. We make a quick stop to show her Tanya's secret refuge in the easily-climbable free where Tanya and I had our first date then head back closer to campus."
    scene bg mary with dissolve
    C "There's a lot of girls out here today."
    "I make the comment idly as we walk through the cheerful flower gardens on the way back to the academy buildings, but after saying it I actually pay attention and find it scarily accurate."
    C "Did we always have {b}this many{/b} students at the academy?"
    S "This probably isn't even all of the students. The seniors are having their graduation ceremony today in the chapel."
    T "Now that all the exams are over and club activities are finished for the year, there's nothing else for the rest of us {b}to{/b} do except roam around the campus."
    C "(We could have slept in too. Not that this is bad either of course.)"
    "Many strange faces surround me, all going about their carefree morning with a smile on their faces and surrounded by friends, just like me."
    scene bg lacrosse with dissolve
    "We continue wandering naturally to the place that the three of us have spent so much time over the past few months — the lacrosse field."
    "Coming to a particular patch of grass that is burned into my memory, I kick at the innocent green growth with a deep bitterness that I can almost taste."
    C "I still can't {b}believe{/b} I upchucked my guts right here in front of the whole school."
    "Tanya quickly breaks out into a serious case of the giggles, which is only silenced when I punch her on the arm."
    T "Sorry, it's just— you said \"upchucked my guts\" with such a serious, somber look on your face. I couldn't help it!"
    "She's still barely holding back the mirth flowing out from within, some of it leaking when she herself repeats \"upchucked my guts\". Even Sibyl is growing red to the face."
    S "I'm sorry, Clover, I'm also..."
    C "Fine, go ahead and laugh. It's just a deep emotional scar I'm going to have to live with the rest of my life, no biggie."
    "The two break out laughing when given permission, and I cannot help but join them after a while, seeing as how infectious this case of the giggles turns out to be."
    C "(It's still not a good memory, but... this one makes up for it.)"
    scene bg gym with dissolve
    "Coming in from the outside, we take a shortcut through the gymnasium. A few girls engage in some casual athletics here and there, while others hang out on the bleachers with their friends."
    "As my footsteps echo across the shiny floor, I recall the many steps I've taken throughout the year, both in athletics class and training with the lacrosse team."
    S "Oh!"
    "Breaking my own musing recollections, Sibyl interrupts with her own."
    S "I think it's okay to ask now? What animal were you, Tanya?"
    C "Animal?"
    T "Booby. What about you?"
    C "Wait, {b}what{/b}!?"
    S "That's right, it was before you arrived, Clover. We had an animal masquerade party on Halloween!"
    C "But Tanya's talking about {b}boobs{/b} now!?"
    T "A \"booby\" is a type of bird, Clover."
    C "O-Oh yeah...?"
    "I just shut right up before I make even more of a fool of myself. It kind of hurt to hear the two chat so happily about something that happened before I ever came on the scene, but I try not to let it bother me too much."
    S "I was the kangaroo!"
    "Sibyl demonstrates her knowledge of kangaroos by drawing her hands up in front of her and performing a little jump-kick like she's a young joey eager to take on the world now that she's left her mom's pouch."
    T "Ah, figures. I don't think I ran into you at all."
    S "Ah, well. Maybe next year."
    S "What animal would you like to get next year, Clover?"
    show choice_darkness with dissolve
    menu:
        "\"Dog\"":
            hide choice_darkness with dissolve
            C "I wanna be a dog."
            "The answer is out of my mouth before I really get the chance to think of it."
            S "That's a popular one! You want to be like your buddy back home, hmm?"
            S "What was his name? Ajax?"
            C "Abraxas."
            "I feel kind of stupid having chosen something so plain right off the bat, especially after Sibyl demonstrated how fun it could be to play a kangaroo, and after Tanya committed to being an animal with such a goofy name."
        "\"Raven\"":
            hide choice_darkness with dissolve
            C "Hmm, maybe a raven?"
            S "Why's that?"
            "Numerous answers come to mind, from their occult folklore as messengers between teh spiritual and physical realms, to their mysterious reputation as guardian of wisdom and secrets."
            "But I of course don't say any of that out loud. Instead, I glance across to Tanya."
            C "I've been a blonde my whole life. I want to try having sleek black feathers for a day."
        "\"Squonk\"":
            hide choice_darkness with dissolve
            C "Maybe it's not so much like \"me\" anymore, I've always kind of empathized with the squonk."
            T "What's a \"squonk\"?"
            "Though only Tanya asks the question, Sibyl is similarly puzzled."
            C "It's a mythology creature known for it's extreme ugliness. It's really shy, like me, and dissolves into a puddle of its own tears when cornered."
            C "I identified with it a lot in middle school. I even went out hunting for them once."
            T "Clover, you're {b}not{/b} ugly, by {b}any{/b} stretch of the imagination."
            C "I know, okay? I'd rather just... forget about middle school altogether, alright?'"
            S "This \"squonk\" sounds adorable actually. It totally makes you want to protect it. I wonder if we can get it added for next year's masquerade?"
            "Sibyl, thankfully, changes the topic away from me as I gow increasingly uncomfortable re-living the mistakes of years past."
    T "It's all first-come-first-served so you either have to camp out in front of the Student Council office, risk getting a random leftover, or else have leverage over Vittoria and Vincenza to sneak you the mask you want."
    C "(Leverage, eh?)"
    scene bg lockers with dissolve
    S "Ooh! So this is what the athletic teams' locker room looks like!"
    C "Oh, yeah, this is your first time in here, isn't it?"
    "Sibyl takes a opportunity of being in a new place to roam around looking at everything, like it isn't nearly an identical copy of the locker room used as necessary for the athletics classes."
    "Only Tanya seems to be brought down by the scenery, as made obvious by the dark way in which she stares at one particularly shower stall."
    C "(I'm not the only one who has made bad memories this year, am I?)"
    "While Sibyl is distracted walking down the bench in another aisle of lockers like a balance beam, I slide over to sneak my hand into hers, making her jump out of her dark trance."
    C "Hey, don't let your thoughts fester on what happened. All that darkness went down the drain there long ago."
    "A soft squeeze compacts my fingers, accompanied by a smiling glance aside from Tanya."
    T "You still have my back, just as you did then."
    C "I sure did, and I know now that you have my back... because now I'm faster than you."
    "A sound something like a half-grunt, half-snort sounds Tanya's dismissal of my retort, and like always, sh's quick to strike back at me."
    T "The exam was a {b}sprint{/b}. I'm built for {b}endurance{/b}."
    scene bg library with dissolve
    "I'm nearly about to challenge Tanya to a race right then and there, but in the end we instead follow Sibyl out of the locker room and down the hallway toward the library."
    S "Sylvia Valemont, I'm going to miss you!"
    "Like a woman departed from her beloved, Sibyl throws herself at the bookcase holding rows of her favorite novel series."
    C "(She's read those, like, minimum three times each. She'd probably be able to recite them word for word if I asked her to.)"
    "The library is rather unusually empty compared to the week before, like all the students who were studying so fervently here decided it was the last place they want to be now."
    C "Won't your local library have them too?"
    S "Oh, for sure they do, but it's not the same. Each book, no matter if they have the same words printed, each contains their own \"character\"."
    C "Really?"
    S "Really, really."
    T "Don't be silly, they're just books."
    S "Two books may have the same ISBN, but each one has a unique. Think of their deckle edge like... a fingerprint! No two are the same!"
    T "Their {b}what{/b}?"
    C "What the heck is a \"deckle\"?"
    S "It's an old papermaking tool, but a \"deckled edge\" on a book is when the paper side of the binding is all rough and uneven."
    S "On really old books in particular, this was a completely random part of the paper-making process, but now, I consider even the wear and chips books acquire to be part of their \"deckled edge\"."
    T "Only you, Sibyl."
    S "Come on, Clover, didn't you feel anything for hose books which I recommended you?"
    "Try as I might, I don't really remember anything in particular besides the stories contained within."
    C "No... they were just books to me."
    C "And honestly, I was mostly reading them because I wanted something in common with you."
    S "I figured as much. You haven't asked me to pick out a book for you in months now."
    C "Sorry. I did enjoy the ones you picked out for me, though. I'm just not much of a reader."
    "Like Tanya back in the locker room, this spontaneous trip through the memories we've accumulated through the halls of the academy have lead me to some sour lemons in the fruit bin of my brain."
    C "(How many more times am I going to wish I could go back in time and punch myself in the face? And what were Vittoria and Vincenza thinking encouraging me like that?)"
    scene bg artroom with dissolve
    "Passing the club rooms, we come next to the art room, which of course Sibyl and Tanya want to stop in to after having spent so much time here together throughout the year."
    "Having already seen the big stack of portfolios piled up in Sibyl's side of the room, it's no surprise to find that few of the students' art remained in the class."
    C "It feels kind of... sad and clinical, not seeing all of the random art strewn about the room anymore."
    "All of the little clay statues made by students for their exam remain, of course, huddled in one corner like a grand gray army of this-and-that, but otherwise, nothing."
    S "Aha! Worry not, Clover, for Miss Izzie always thinks of everything no matter how scatterbrained she may seem!"
    "As Sibyl and Tanya soon show me, the storeroom contains more than just raw material and equipment, but also a whole rack fo shelving with thick portfolios labelled by year."
    S "Here we are!"
    "Sibyl pulls our year off the shelf to leave through it out on one of the big drafting tables. Each turn reveals a new set of artwork never seen before, and that blows anything I could do completely out of the water."
    "Some of them are even Sibyl's, or Tanya's. What I don't expect whatsoever is to find any record of my time at the academy recorded in this thick volume... until the next turn of the page finds my own face staring back at me."
    T "That's hot."
    "Maybe \"glaring\" is more accurate. To her credit, Sibyl really captured the essence of my negative emotions that day of our first art class when I modeled for her."
    S "It's my {i}The Birth of Clover{/i}!"
    T "I should get this blown up and printed to hang over my bed. Or maybe make it my screensaver."
    C "You wouldn't {b}dare{/b}!"
    "Tanya yields in short order after a particularly firm shove of my shoulder into her side, but I know she's only joking. I'm actually kind of happy this will stay enshrined at the academy for future posterity."
    C "(I may have made a really big fuss and said some regretful things, but thank you so much for sending me here, Mom and Dad!)"
    scene bg aquarium with dissolve
    "Tanya doesn't want to go in, and Sibyl doesn't understand why either, but I force both of them to stop into the aquarium with me."
    C "Remember that time you found me in the aquarium, when I first came to the academy?"
    "Clutching Tanya's hand in mine, I pull her close to my side to grin bashfully in her face. I'm planning to make some sort of sappy statement of how much we've changed and come to like each other since then, but Tanya has other plans."
    T "...When I had to claw my fingernails into the palm of my hands to stop myself from holding your head underwater in the fish tanks until your arms went slack? Yeah, I remember."
    C "Wha—!? Was that a murder threat? I haven't heard one of those in {b}months{/b}!"
    T "It was a {b}past tense{/b} threat to murder you, so it doesn't count."
    C "If anyone's going to murder me, I want it to be you, Tanya."
    "Sibyl lets out a long, drawn out \"Awwwww\" as we embrace to share a kiss right there in full view of her and a few dozen glassy fish faces gawking at us from behind the glass of their tanks."
    scene bg classroom with dissolve
    C "I'm not going to miss this place."
    scene bg cafeteria with dissolve
    C "I am {b}so{/b} going to miss this place!"
    scene bg dorm with fade
    "After lunch, we say goodbye to Tanya who goes off to visit her other friends like she does every Saturday."
    S "Are you sure it's okay?"
    C "That what is okay?"
    S "That you're not spending every last hour you both have together before the summer break?"
    C "Yeah, it's fine. We plan to, hopefully, meet up over the summer, so..."
    "It does kind of feel bad to leave her now, when we are indeed quickly running of hours left to be together and I'll have to leave off for the unknown of my current home situation shortly enough."
    "We did talk about this, though. She too was concerned about leaving me alone so long on the day before I leave to go home; she wanted to bring me along to meet with her friends."
    "In the end, I convinced her that it's fine totally fine to go meet wither friends like she has been all year, and I would be uncomfortable joining in suddenly with such an established group of friends."
    C "(Even now, with how much I've grown over the past few months and with Tanya at my side, that kind of social interaction is out of my league.)"
    S "Did she... ever tell you what she's doing every Saturday?"
    "Quietly, and with a guilty look my way, Sibyl inquires about just what Tanya is always up to on Saturdays. I don't even fully get it myself, but I try to explain as best I can."
    C "She goes and geeks out with other girls in the academy who also like the kind of lesbian comics she showed us. They, like, watch anime and tak about manga they read, and stuff like that."
    S "Huh. So it's a book club, and she didn't invite {b}me{/b}?"
    C "Maybe she, umm... didn't think you've be very much interested in the stuff they read because... you know."
    S "You're probably right, but still... keeping this whole thing a secret just for that?"
    C "You shouldn't blame Tanya. It's apparently supposed to stay a secret. I probably shouldn't even have told you."
    S "I'm not angry, Clover, just... I don't know. And I won't tell, I promise!"
    scene bg lounge with dissolve
    "On our way back to our room, we stop at the lounge for the final chore of the morning."
    S "Wow, there's already a line. Maybe we should have come by earlier."
    "The line is long, but it doesn't take long before we get to the front and receive our very own copies of the class yearbook."
    "\"Prudence Preparatory Academy for Girls\""
    "My fingers trace over the letters debossed with gold in the otherwise empty pink cover. It's probably the first time I'e actually seen the full name of the school written out, and hopefully, not the last."
    jump eveoflastday_part2

label eveoflastday_part2:
    scene bg bedroom with fade
    "With Tanya away at her super secret anime club meeting, Sibyl and I return to our room to pass the time before we meet again at dinner."
    "It's clear that both of our thoughts are on home, but while I'm merely sitting on my bed cross-legged with the picture of Abraxas in my lap, Sibyl paces back and forth across the room while busy packing up her belongings."
    C "You do know they're not kicking us out right away, don't you?"
    S "I know."
    "Maybe it's because packing means accepting that I'm leaving, or just that I hate packing in general, but I've avoided it entirely up until now."
    C "(We have all morning tomorrow. She doesn't have to go this crazy right now...)"
    "Eventually, I find it more interesting to pass the time by watching her at work than doing anything else. My head rotates side to side with her activity like I'm at a tennis game."
    C "You're going to leave enough stuff out to make it through tomorrow, right?"
    S "Of course I am."
    "Compared to my side of the room, Sibyl's always looked tidy. Now that she's actually tidying up for real, my side of the room looks downright slovenly by comparison."
    