label lacrosse_anew:
    scene bg gym with dissolve
    "With my name written in bold pink letters across my back and the crosse held confidently in my hands, I envision myself as a brand new woman ready to tackle any obstacle in her path."
    C "({b}Goodbye{/b} creepy goth, angsty bitch, and love-struck loser Clover; nice to meet you, fun and sporty athlete Clover!)"
    "I haven't felt this clear-minded and energized in months, or maybe even years. I've put all the darkness both literally and metaphorical in my past, and now finally also moved out of Sibyl's shadow."
    C "(I was way too distracted for my first few weeks of lacrosse practice, but today I will kick it into high gear!)"
    "Practice starts with a paired warm up passing exercise. Overhand, underhand, even sidearm — I do them all, and well enough that Miss Woolsey is impressed by my speed in picking up the technique too."
    "After warmup we split to play shifts of {i}sixes{/i}, a type of lacrosse where two teams of five \"runners\", who play both offense and defense, and a goaltender face off in a fast-paced, non-stop lacrosse match."
    "While I wait my turn to run to play as one of the runners, I focus my energies on practicing my {i}cradle{/i} technique."
    "By moving the crosse in a semi-circular motion to produce centrifugal forces, the ball can be kept securely in the crosse even at an elevated position."
    "It's an essential skill which has been something of an issue for me in past practices, so starting today it's one of my highest priorities to get right."
    mw "Priya, swap out; Clover, you're in!"
    "Miss Woolsey calls out my name as part of substitutions for the next round of the sixes match, giving me the perfect opportunity to put my new skills to the test."
    C "Yes, ma'am!"
    "Full of confidence, I place myself forward to take the face off and hopefully win the ball to start my team off with possession."
    "As I line up with my stick on the ground before me, I narrow my focus on what actions I'm going to take to sweep the ball to my teammates. Nothing else matters in all the world but winning that little yellow rubber ball."
    "Until my opponent's stick is placed on the ground opposite me in my vision. I glance up briefly only to find the equally determined face of Tanya mere inches away from me."
    T "You're going down, Clover."
    C "(She—! She's {b}trash talking{/b} me!)"
    C "Shut your fat mouth, you... fattie!"
    T "Is that the best you've got?"
    "The coolness of Tanya's reply, and particularly the cavernous depths of smugness present on her face as she says it, really ruffles my feathers."
    "My trash talking doesn't hold a candle and I know it, but try again I must lest Tanya take away this exchange as a victory of her own."
    C "I'm going to launch that ball so hard up your butt that it comes out your mouth."
    "I catch Miss Woolsey coming over to drop the ball and start the match so I hiss my reply out quietly between my teeth. Tanya only grins at it, leaving me unsure whether it worked at all."
    "Unfortunately, I'm way late to the snap given my preoccupations with Tanya rather than watching when Miss Woolsey drops the ball, and thus lose the face off to Tanya with barely any challenge."
    C "(I played right into her head games, that bitch!)"
    "In the next millisecond after Tanya receives the ball from her teammate, I run right up to get in her face. She tries to juke to the side to pass to her teammate but I read the scoundrel's intention clearly enough."
    "With a quick flick of my stick against hers, my first ever stick check works wonderfully in popping the ball right out of her crosse and away to be scooped up by my teammate."
    mw "Great check, Clover!"
    "Miss Woolsey calls aloud to join the praises in my head for this wonderful work of stick craft, and my teammate scores the first point of the match to top it all off."
    C "(Take {b}that{/b}, Tanya!)"
    "I trot right on over to her to gloat in teh few second it takes for teh goaltender to fetch the ball and throw it back into play, but when I face her she isn't upset in the slightest."
    T "Nice take away, Clover."
    C "Uhh... thanks."
    "The interaction leaves me deflated, but when the ball sails out again over our heads, I try to push those unimportant "