label finalgame:
    scene bg transition with fade
    scene bg lockers with dissolve
    mw "This is it, girls: the last game of our season."
    "Though we are not able to play in the final game of the school year, Tanya and I still arrive to the locker room to be with the team as Miss Woolsey raises everyone's spirits before taking the field."
    mw "As we walk out there onto the field, I want you all to take a moment to think about how far you and the rest of the team have come to get to this point — every evening practice, away game, and early morning training session that has led to this moment."
    "As she finishes her thought, Miss Woolsey glances toward me and Tanya in particular with a gentle smile."
    mw "Know that you're not just playing for yourself today, but for all the tears and all the laughter we've shared to get to this point. Whatever the score may be when the whistle blows, remember that everything you've done is for each other!"
    mw "Now, let's not keep everyone waiting, ladies! Let's get out there and show them what the Wild Roses are made of!"
    C "(It must be really difficult for her to write those speeches.)"
    "Part of me believes that Miss Woolsey was speaking to me and Tanya with some of her speech, to reassure us that even if we can't join them on the grass today, we're still with them in spirit and have helped build up our teammates to what they are now."
    scene bg artroom with dissolve
    "My spirits are buoyed by our coach's speech before the game, but that's not the end of our part of the game whatsoever."
    C "Are you almost done? The first whistle is in a few minutes..."
    S "Art is not something to be rushed, Clover!"
    T "We can make it if we run..."
    S "But yes, I'm almost... done! Let's go!"
    scene bg lacrosse with dissolve
    "Sibyl displays a level of athleticism nearly matching ours as we sprint for the lacrosse field and take our places in the very first row of bleachers."
    C "(We made it! And just as the game is starting too!)"
    "Miss Woolsey spots us quickly and gives us a small wave from the sidelines. Though the spectator seating is more full than most besides the game before Prom, we're easy to pick out on account of the giant banners we're waving."
    S "{b}Prudence!{/b}"
    T "{b}Wild!{/b}"
    C "{b}Roses!{/b}"
    "Though neither of us can make it out onto the field, Tanya and I resolved to make our presence felt. Sibyl volunteered to help out any way she can too, and thus, the cheer section was born."
    mi "Give me a \"W\"!"
    C "\"{b}W{/b}\"!"
    mi "Give me an \"I\"!"
    S "\"{b}I{/b}\"!"
    mi "Give me an \"L\"!"
    T "\"{b}L{/b}\"!"
    "Miss Izzie, who tries to run the crowd hype every game no matter no many spectators from the school arrive, feeds off our energy and runs up through the aisles of the bleachers until other students join in her chanting."
    mi "Give me an \"R\"!"
    "\"{b}R{/b}\"!"
    mi "Give me an \"O\"!"
    "\"{b}O{/b}\"!"
    mi "Give me an \"S\"!"
    "\"{b}S{/b}\"!"
    mi "Give me an \"E\"!"
    "\"{b}E{/b}\"!"
    mi "Give me an \"S\"!"
    "\"{b}S{/b}\"!"
    "Our energetic arts instructor nearly topples over forward with her zeal in shouting out the letters, climaxing fully when she asks us to cheer it back to her."
    mi "{b}What does that spell!?{/b}"
    "Unfortunately, the response is rather muted and confused \"Wil...\" that starts out strong but trails off quickly."
    st "You forgot out the \"D\" miss Izzie!"
    "A student shouts back what went wrong to Miss Izzie, followed by others corroborating the issue, but Miss Izzie, as I've come to expect, just plays it off with some sort of joke that makes no sense to anyone."
    mi "Who wants to be given the \"D\" anyway? Not me! Am I right, Miss Vitolini!?"
    "I don't even realize that the twins are here watching the game at all until Miss Izzie points right to them and they both reply back as if both addressed, playing off of Miss Izzie's excuse for blanking on the last letter of \"wild\"."
    O "Right you are, Miss Izzie!"
    H "Give me a \"V\" any day of the week!"
    "Vincenza chooses to assume a relaxed, aloof posture atop the weathered seating as she shouts back to Miss Izzie, while her sister brushes a lock of her hair behind her ear as she replies in a refined, lady-like fashion with excellent posture."
    C "(Wil{b}v{/b} Roses?)"
    "As I ponder what the heck a \"wilv\" might be, Tanya snorts and mutters vaguely my direction."
    T "More like Vittoria's gonna give out her \"T\"..."
    C "{b}Wilt{/b}!? Are you trying to {b}curse{/b} our Roses!?"
    T "No, by \"T\" I meant \"tongue\"..."
    C "What are \"tongue roses\" supposed to be?"
    T "...I'll explain later, Clover."
    "Miss Izzie switches tack away from her mistake to instead lead the assembled crowd in a wave, which me, Tanya, and Sibyl naturally take the lead on ensuring is a success by any means necessary."
    scene bg lacrosse with dissolve
    "Being in the bleachers cheering on the team is fun — {b}almost{/b} as fun as actually playing in the game on the grass before us."
    C "(It still kinda stings to not be allowed to join the rest of the Wild Roses out on the field, but cheering on the team with Tanya and Sibyl is almost as good!)"
    scene bg lockers with dissolve
    "In the end, all of the whooping and hollering we do from the edge of the field does not result in our team taking the lead on points."
    "That doesn't stop the mood in the locker room when we catch up with everyone else from being anything short of celebratory and festive."
    st "We were really struggling without you there to set up the forwards, Tanya."
    T "That's what I was afraid of... but the nurse wouldn't clear me to play today."
    st "I don't think I've ever seen you so {b}loud{/b} before, Clover!"
    C "M-Me? I can be loud... I just don't want to draw attention most times."
    "Maybe it's because they're already revelled amongst themselves, but all attention turns to us when we arrive. The whole team seems to think that our cheering efforts were incredible, to the point of distracting them to from game itself."
    C "(Were we actually a {b}detriment{/b} to the team today?)"
    "It's kind of a lot even though I've known these girls for months now and like to think I've gotten over most of my fear of being put in the spotlight like this, but I make it through easily. Tanya stays by my side the whole time without fail."
    jump study4finals

label study4finals:
    scene bg transition with fade
    scene bg lacrosse with dissolve
    "The very next morning after the nurse clears Tanya to return to normal life, she's back out on the track getting her laps in like she has to make up for lost time, and doing so with an obvious skip in her step."
    C "(I don't think I've ever seen her smile so brightly!)"
    "The same delight finds its way to my lips just watching my girlfriend run around the circular track like doing so is more fun the world's biggest water park and tastes sweeter than the world's sugariest candy bar."
    C "Tanya!"
    "She changes course when I call out to her, slowing to a walk upon approach and immediately starting her cool-down calf stretches by the time she stops in front of me."
    T "Good morning, Clover!"
    C "Good morning. You started without me?"
    T "Sorry, Clover, I just couldn't wait. After not being allowed to exercise for so long, and then Sierra started waking up..."
    "I watch over Tanya as she does her stretches. By the amount of sweat already sticking to her jersey, she's clearly already been out here for a while, maybe even before the sun started coming up over the horizon."
    C "(She looks super hot... and not just literally.)"
    C "It's okay. What's up with Sierra?"
    T "There's {b}too much{/b} about her. You should know that by now."
    T "She started treating me like her dream diary since I've been stuck in our room with her every morning, and I {b}Just. Don't. Care.{/b} about her dreams."
    "Tanya sighs with some small amount of frustration, and I realize that in my curiosity for what Sierra has been doing, I've already taken away some of that magical happiness she was showing before I'd interrupted her running."
    C "You looked really good running out there! Your form is as good as ever, Tanya."
    "To ease my guilty conscious, I steer the conversation away again to more enjoyable topics. Tanya herself switches her stretches to her hamstrings in an extra clean break."
    T "Thanks. I might be a little off my peak after being all but bedridden for so long, but it feels so good to be out on the track again."
    C "You know what? You did look a little rusty. I think today's the day I surpass you for good."
    "I do some of my own warm-up stretches, interlacing my fingers to stretch tall in a manner with a purposeful aloofness after such an inflammatory statement"
    T "Not if I break your legs first, Clover!"
    "From where she's on the ground stretching, Tanya lunges toward my legs with outstretched hands. I manage to jump out of the way just in time \"just in time\" from Tanya's reach, but not before releasing an embarrassing sound that is half giggle and half shriek."
    C "N-Nooo, Tanya, you {b}brute{/b}!"
    T "Get back here!"
    "Tanya scrambles back onto her feet just as I dash away, and for a good long while we chase each other around the lacrosse field, throwing taunts each way, until more girls start to show up and we both become self-conscious about flirting so openly."
    scene bg cafeteria with dissolve
    "At breakfast, Tanya tears right through her first yogurt parfait and even ventures further into a bacon and egg breakfast sandwich in such a display that Sibyl must think we'd changed places."
    S "I'm so happy to see you back to normal, Tanya! You looked absolutely {b}miserable{/b} being stuck in bed."
    C "And like a dog with one of those big poofy plastic collars digs wear to prevent them from biting themselves when you could only spectate at practices."
    "Tanya pauses from chowing down on her breakfast sandwich long enough to give me a sarcastic \"ha ha\", while I can only focus on how delicious the sandwich looks."
    C "(If Tanya herself is eating a bacon and egg sandwich, then she can't tell me off for over-eating, right?)"
    "I'm already half way to standing up and excusing myself to fetch my share of delicious breakfast meats squeezes between a fluffy biscuit when Tanya drops a bomb that sets me back into my seat."
    T "Just in time to start the last week of classes before exams too. I tried to keep up with the lessons but I think I'll need the week to get back up to speed with where we are now in time for finals."
    T "Are we going to study together all weekend again, just like we did for midterms?"
    S "You know it, study-buddy!"
    C "{b}F-Finals!?{/b}"    
    "Finally, my two friends turn their attention to the color rapidly draining from my face. All thoughts of the delicious breakfast sandwich fly away on the breeze."
    S "You're obviously welcome to study with us, Clover!"
    T "Sibyl is {b}incredible{/b} with exams, Clover. You might think you get it after seeing us study for those quizzes, but Sibyl was something else entirely at the midterm exams."
    T "I probably learned more studying with her the weekend before midterm week than I did the whole first half of the year! There's no way you can fail if you follow her process."
    C "(I wasn't worried about failing! My grades aren't {b}that{/b} bad!)"
    C "I guess I just... wasn't expecting to come up so soon. With the last few games of the season, and then Tanya's concussion, things just all sort of happened really fast."
    S "You and Tanya still have a full week of classes before we take our final exams next week, Clover."
    C "Me and Tanya?"
    "The way Sibyl words her statement strikes me as odd, so I press her on it directly."
    S "I have started my study preparations as of this morning!"
    S "I'm here at the academy on a scholarship, remember? If I don't keep top of the class, or near it anyway, I might not be able to come back for sophomore year with you and Tanya!"
    C "O-Okay..."
    "I sure don't want Sibyl to not be able to attend Prudence Prep next year, but it also seems like she's near perfect in her academics already, so starting to study hard a week plus in advance of the exam seems a little much."
    T "Maybe it doesn't hurt to stat reviewing a little bit at a time leading into the weekend. I know I'll need to catch up on what I missed too."
    S "Exactly! There's a lot of material to cover, and just one weekend won't cut it if I'm going to place first in the class."
    "Sibyl exudes confidence, so I leave her to her studies and say nothing when she surreptitiously starts flipping through flash cards while we're still chatting over the remains of our breakfast."
    scene bg classroom with dissolve
    "All throughout classes, I observe Tanya furiously writing notes on the new content while referencing copies of the past week's notes she borrowed from Sibyl."
    "Sibyl is doing something very similar. At once, she takes notes on the current lesson of the day in one notebooks, while beside that notebook is another open notebook for another subject entirely."
    "Meanwhile, I can barely keep focus as the teacher drones on about vocabulary. My lack of attention comes back to bite me when we're sprung a sudden pop quiz."
    C "(\"Assiduous\"? This can't mean, like, someone who has a really big butt?)"
    "My attention shifts to Tanya for a time, but the impossibly loud ticking of the clock and scratching of pencils around me draws my attention back to the quiz."
    C "(\"Florid: Of or relating to a flower.\" Yeah, that has to be right.)"
    "When the quizzes come back graded, I'm starting to think Sibyl is onto something by starting so early."
    C "You're very \"assiduous\", Tanya."
    T "Thanks, Clover!"
    C "You're welcome."
    scene bg bedroom night with dissolve
    "That evening, the three of us work through our new assignments and help Tanya get caught up with what she missed from the moment the bell rings to mark the end of class to the time they ring to mark curfew."
    C "The shower's free if you want to use it, Sibyl."
    "I call out to Sibyl after finishing up my nightly sleep activities, but to my surprise she's still knee deep in notebooks and textbooks on her bed."
    S "I'm almost done reviewing this chapter. Will it bother you if I keep on my clip-on book light on?"
    C "Nope. Good night, Sibyl."
    S "'Night, Clover."
    scene bg bedroom night dark with dissolve
    "Truly, Sibyl's clip-on light doesn't bother me. She's often used it before when she gets too sucked into a novel to put down for something as relatively unimportant — to her — as sleep, and I cocoon myself so tightly that no light gets in anyway."
    scene bg bedroom with fade
    "What bothers me is that when I awaken bright and early, her clip-on book light is still activated. Like the day I met her, she lies haphazardly on her side, nestled amongst the contents of her school bag."
    C "Sibyl?"
    "I call out to her faintly, unsure whether I really want to wak her or not, and ultimately just click off her lamp with the decision that she probably needs the extra sleep if she stayed up late studying."
    C "(If she sleeps in too late, Tanya and I can come fetch her well before classes begin.)"
    scene bg cafeteria with dissolve
    "It isn't until Tanya and I are busy replacing the calories we expended on another invigorating morning of exercise that Sibyl shows her face again."
    S "Good morn—"
    "A yawn interrupts her greeting as she sits down and immediately pulls a ring-bound stack of flash cards out of her bag."
    T "How late were you up studying last night, Sibyl?"
    "Tanya catches right on to the concerns I'd been keeping to myself, and isn't afraid to push them at Sibyl like I was when I woke up."
    S "Not {b}too{/b} too late. I just lost track of time a little. We covered a much broader curriculum this year than I remember."
    C "(Tell me about it.)"
    "Sibyl had very thoroughly caught me up to the rest of the class when I first transferred in, but what she crammed into my brain months ago, I'm finding, is just about gone now and making my own preparations much more difficult."
    T "You {b}need{/b} to sleep, Sibyl. You can cram al of our lessons in your brain, but if you don't give it time to rest, you won't remember any of it."
    S "I know, I know!"
    "Sibyl agrees with Tanya, though somehow also rather dismissively when she chooses to fetch a breakfast burrito with one hand still flipping through her flash cards."
    "Tanya and I share a concerned look the very moment she's gone. However, worried we might be, catching her eyes in such a way also gives me a minor thrill."
    C "(We're just like Vittoria and Vincenza. We're {b}that{/b} close already!)"
    "We both seem to agree wordlessly that something has to be done about Sibyl in the small span of time before she returns to our table."
    T "Since Clover and I don't have practice today, Sibyl, we thought we'd like to join you in the library after classes."
    S "That would be wonderful! But are you sure you don't want to spend the time together, just the two of you?"
    "I shoot a quick frown at Tanya, hoping that Sibyl doesn't catch it on the way."
    "With the lacrosse season officially over, we {b}had{/b} planned to make another evening date out of the time we'd normally have spent in lacrosse practice."
    C "I'm still slogging through review of the material I missed before transferring in, and Tanya is nearly through the stuff she missed while forbidden from attending classes."
    T "We thought... that you'd definitely be able to help us out after art club this evening!"
    C "Maybe I'll come too! Miss Izzie doesn't mind non-club visitors, right?"
    S "Art club? Oh, I'm not going this week."
    C "You're \"not going\"!?"
    "I exclaim loudly Sibyl's words back at her, and hearing an echo, turn my head aside in time with Tanya to find she mirrored my response exactly."
    S "I have too much to yet to cover before next week."
    scene bg library with dissolve
    "And so, after dreaming all week of my upcoming date with Tanya, where we'd surely get to kiss a whole lot and cuddle so closely that I'd look like a baby koala squeezing tightly to Tanya mama-koala..."
    C "\"Krebs Cycle\"? I've never heard of that in my life."
    S "It's from the unit on cellular respiration."
    "Half an hour into intensive studying with Sibyl and my brain already feels like it's going to melt in my skull and drip out my ear holes, but despite that I have to admit that I am learning a lot."
    C "Right, cellular respiration. That... produces energy for animal cells."
    S "Yes!"
    "While legitimately studying, Tanya and I also take turns having Sibyl help us with something, as I'm doing now for my biology recap. I don't know if it's helping, but we think it's better than her getting laser focused by herself."
    T "Oh, right, we read Animal Farm in English class this year. I totally forgot. What was that about, Sibyl?"
    S "Animal Farm? That's one's about farm animals who rebel against their farmer to..."
    "Tanya picks books as her choice of subject this time to get Sibyl distracted from her multitude of notebooks and on a long tangent that will prove less burdensome on her brain."
    scene bg bedroom night with dissolve
    "I think we're making good progress with giving Sibyl a little break, but she's right back to her old ways the moment we settle in after curfew."
    C "We studied a whole lot today, Sibyl. Why don't you take some well-earned rest?"
    S "I'm good to keep going, Clover."
    C "Are you sure?"
    S "Yes."
    "Her first reply was as sweet as her usual self, but her curt latter reply, while not aggressive, clearly indicates how much patience she's losing for my interruptions."
    C "Okay... get to sleep soon. We have a science lab tomorrow."
    "Even after sacrificing our date today, I still am unable to stand up to Sibyl and tell her that she needs to give herself a break. I make do by squeezing the Tanya in my dreams extra hard."
    jump sibylbreaks

label sibylbreaks:
    scene bg transition with fade
    scene bg cafeteria with dissolve
    "Sibyl never lashes out at me and Tanya, but the message becomes increasingly clear through her actions and words that she wants us to back off with bothering her during study time."
    "We have no choice but to do as she wishes, however concerned we become with her ever-increasing late arrival to breakfast and continually withdrawn sociability."
    scene bg gym with dissolve
    "It all eventually comes to a head late in the week, during gym class."
    T "Serving!"
    play sound volleyball
    "From Tanya's hands, the volleyball soars over the net to be bumped by a girl on the other side, and volleyed back our way."
    C "Got it!"
    play sound volleyball
    C "(It's definitely no lacrosse, but volleyball is pretty fun too!)"
    "Tanya and I are both in our element, jumping and diving here and there after the ball, our pent up energies that now going to lacrosse coming out in gym class."
    "Other girls are less enthusiastic. Sibyl, who normally gives gym class her best effort, is particularly low energy, and it's no surprise with how much of her energy has been going into studying lately."
    T "Going over!"
    "Tanya sets me up and I whack the ball hard over the net, leaving the girls on the other side to jump at the speeding ball, and upon making contact, leaving it to ricochet furiously back over the net."
    C "Sibyl!"
    "I shout her name as my brain uses my new geometry skills to accurately predict where the ball will fly, but it's still too slow for Sibyl or anyone else to react in time."
    "The ball catches the already unsteady Sibyl square in the face, of course, knocking her right down in her butt. Everyone rushes in quickly to pull her back on her feet."
    mw "Are you hurt, Sibyl? Let me see..."
    "Miss Woolsey arrives quickly. The other girls part ways while we support Sibyl, who clutches at her nose, pinching it together."
    S "Nose bleed..."
    "Sibyl's voice comes out nasally when she speaks. It's kind of cute to hear, and would be more if I weren't concerned for her well-being at the moment."
    "Miss Woolsey inspects her nose, offering her a handkerchief from her pocket to help stem the flow of blood, and otherwise places a hand on her forehead."
    mw "Sibyl, you're burning up!"
    scene bg nurse with dissolve
    pause 0.5
    scene bg hallway with dissolve
    "Against her objections, and most importantly with Miss Woolsey's approval, Tanya and I drag Sibyl off to the nurse to compel her to get some rest for her own good."
    nurse "Her nose isn't broken; it's just a nosebleed. She also has a light fever."
    C "She's been pushing herself too hard while studying for finals."
    T "We've been trying to get her to give it a rest, but she won't have any of it."
    nurse "Alright, calm down."
    "We plead our case to the nurse from just outside the door to the nurse's office, where Sibyl can't hear us but surely is trying to from the lone bed there."
    nurse "I'll place her on mandatory bed rest overnight. Her injuries aren't sever, but stress will only make her recovery slower."
    "The nurse pointedly looks to Tanya, who learned this fact the hard way very recently. She nods her agreement even if she knows how hard it can be to sit still like this."
    C "Thank you!"
    scene bg nurse with dissolve
    S "What's going on?"
    "I try to stifle a giggle when looking again at Sibyl, who's nose is stuffed in both nostrils with what can only best be described as \"nose tampons\"."
    nurse "You're staying here overnight to get some rest. I'll be back with some fever medicine in just a moment."
    "As soon as the nurse leaves Sibyl begs us to smuggle in her flash cards for her, to which we flatly refuse."
    T "Trust me, I {b}know{/b} how boring it can be to lay in bed doing nothing all day, but you need the rest."
    C "Our final exams are only a few days away. You want to be {b}healthy{/b} for those, don't you?"
    scene bg nurse with dissolve
    "Together with Tanya, our flawless reasoning eventually draws an reluctant agreement from Sibyl to take the night off and rest up for the upcoming weekend and exams following it."
    "Having already blown past the end of the gym class and part way through etiquette lessons, the last of the day, we decide just to stay with Sibyl until dinner, only leaving to fetch food for all three of us."
    scene bg hallway night with dissolve
    "When the shadow start to grow long, we wish Sibyl a peaceful rest and speedy recovery from her fever, then step out on our own together."
    C "I hope this whole incident proves how right we were about wanting her to take a break from studying."
    T "She's already learned her lesson, I'm sure. She's going to want to do everything possible to break the fever before exams next week."
    scene bg dorm night with dissolve
    "The two of us walk together, at some point slipping hands together without realizing it, until we reach her door at the dorms to drop Tanya off before curfew like we do every night."
    T "What'll you do without Sibyl there tonight?"
    C "I dunno. Take a bath maybe? I haven't soaked in a bath {b}once{/b} since coming here."
    T "That sounds nice. Sierra always hogs ours."
    C "You—"
    "I start to say something that flies right out of my mind, as I immediately get struck by a terrifyingly giddy realization that trembles my hand still held with Tanya's."
    C "(Tonight is the night.)"
    C "(Tonight is {b}the{/b} night.)"
    T "Clover?"
    C "S-Sibyl won't be sleeping in our room tonight, so... maybe you could come take a bath in my room..."
    "The words escape haltingly, with great effort on my part. My skeleton feels like it's going to wiggle right out of ym skin with how nervy I am."
    "Thankfully, Tanya catches on quickly to my meaning, a bright red flush growing on her face that she tries to hide by brushing her fingers through her hair with the hand not still held in mine."
    C "...I-If tonight is good for you."
    T "Yeah... tonight is good. Just let me tell Sierra."
    scene bg dorm night with dissolve
    play sound doorclose
    "I whip around away from Tanya's door the second she disappears behind it to stuff both palms into my face and stifle a little scream."
    C "(Oh my gosh. It's happening. Oh my gosh.)"
    "A whole list of things that I really wish I had time to prepare first flies through my head as I wait for Tanya to show her face again."
    C "(I shaved my legs this morning, right? Yeah. Phew.)"
    play sound doorclose
    "When she does re-appear, I try to resume my normal attitude, maybe even showing a little aloofness like I'm totally not freaking out inside."
    C "Oh, hey."
    T "Hey."
    "Tanya responds equally cooly, but I can tell that she's nervous too. She can probably see right through my charade just as well."
    "The short walk from her door to mine feels like a marathon with how fast my heart beats and time seems to slow down around me."
    scene bg black with fade
    play sound doorclose
    pause 1.0
    "The bath is small for two people, but we do not mind."
    pause 1.0
    scene cg morning_after with fade
    "Perhaps it's because the night passes like a dream that I sleep so restfully."
    "When I finally awaken, I find Tanya still snoozing peacefully in my arms. I give her a tight squeeze and revel in the feeling of her smooth skin against mine once more, as I did so much the night before."
    C "(I love her so much.)"
    "I'd been avoiding the word after using it perhaps too freely in my pursuit of Sibyl, but this time, I feel like my feelings for Tanya truly deserve it."
    C "(I love Tanya.)"
    pause 3.0
    scene bg black with fade
    jump finals

label finals:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "Sibyl recovers in time for the weekend and with enough vigor to lead me and Tanya through an in-depth workshop of every single thing I learned at the academy during the year, and the content I missed before transferring in."
    C "(Sibyl really is incredible. I'm so lucky to have her as my Vertu partner.)"
    scene bg bedroom night dark with dissolve
    "Sunday night, the last few hours before the first of a series of biggest exams of my life, finds me lying in bed wondering what the week will bring."
    "I should by all rights be at my wit's end with fear for the break of dawn, but when I clutch my pillow closer and pretend I can still smell Tanya's scent upon, the pillow, I fall right into a restful sleep."
    scene bg classroom with fade
    "Exams are administered twice a day, one in the morning and one in the afternoon from Monday through Thursday."
    "As much as I'd like to just do them all faster to get it over with, spreading them out helpfully ensures we get to focus on each individual subject."
    scene bg cafeteria with dissolve
    "Meal times become makeshift cram sessions with all of our notebooks spread out across the table, each of us taking bites between a split of the next notebook page. Not every examination is a written test, however."
    scene bg artroom with dissolve
    "Arts, athletics, and etiquette are tested as a pass/fail practical examination."
    "Having never learned the secrets necessary to produce art through close proximity to Sibyl, I'm naturally incredibly anxious about arts in particular."
    "Thankfully, Miss Izzie just plops a brick of modeling clay before each of us and tells us to go nuts with it."
    "I glance over to Tanya, who's intensely focused on finger-crafting a big crashing wave that doesn't look like it should be able to stand up but somehow does."
    "Sibyl, meanwhile, somehow turned her block of clay into a fully grown tree, complete with tons of leaves to fil the branches that she scrapes out individually with a little pointy tool."
    C "(How does she do this stuff!?)"
    "My creatively deficient mind turned my large block of gray clay into smaller blocks of gray clay. When I see Miss Izzie coming around to check on progress, I quickly stack them up like I have a real plan."
    mi "How are you doing, Clover?"
    C "Really, {b}really{/b} well, Miss Izzie! This is, as you can see, a critique on... childhood... evoking the form of common block toys to... symbolize growing up."
    "I put on my biggest grin for her, which she happily gives right back, and piles a vigorous patting of my head on top."
    mi "Who could argue with that, Clover? {b}Pass!{/b}"
    scene bg gym with dissolve
    "Perhaps the highlight of the hellish finals week is my athletics practical exam."
    mw "Congratulations, Clover! You had the best time in the hundred yard dash."
    "Immediately after the announcement, I turn to stick my tongue out at Tanya, who quickly pinches it with her fingers before I can retract it."
    C "Moy thungue!"
    T "I still placed higher than you in the long jump."
    C "Tho hwat?"
    "My tongue still captured, I blindly throw my hands out to push back at Tanya's face to force her to let go, while Sibyl looks on with equal parts humor and astonishment."
    S "Only the two of you would call this \"flirting\"."
    scene bg cafeteria with dissolve
    "It's only when it's all over that I can finally breathe a heavy sigh of relief."
    C "It's over..."
    C "Finals are done..."
    C "I'm free..."
    T "Except for that essay you have to write because you failed the etiquette practical."
    C "Shhh. Let me enjoy this before it melts."
    "The academy shares my feelings about how to appropriately celebrate the end of finals, that being by making banana splits with all the works for every student to enjoy."
    S "Half the class failed the etiquette practical. Maybe the instructor is too strict?"
    T "Some upperclassmen told me that none of the practical exams actually count for real. The essay for those who fail is just to push the students to take the class seriously."
    C "(The practicals don't count!? But I was so proud of my passing grades in art and athletics!)"
    "The make-up essay for the etiquette class is only a five hundred word reflection on what I learned. It's only a slap on the wrist for not passing the exam, but it's still a bummer to have to write it in the first place."
    C "How do you think you did, Sibyl? Good enough to keep your scholarship?"
    S "My preparations proved more than adequate. I am confident that my scholarship will remain for next year."
    "Putting down her spoon for a moment, Sibyl's expression turns a degree more earnest."
    S "Thank you both for forcing some sense into me. If you hadn't, I might have been too sick to even take the exams at all."
    C "You're welcome!"
    T "I'm sure the academy would have let you take the exams once you recovered... but I'm glad it never had to come to that at all."
    S "So am I. How did you feel after your exams, Tanya?"
    T "Great. I couldn't have done it without your study prep, Sibyl."
    C "Yeah, Sibyl, you're the best!"
    S "I am happy to have helped! You can count on me next year too!"
    C "(Next year...)"
    "Sibyl's words are a harsh reminder that the end of final examinations also means the end of the school year, but I try no to let it eat at me when I could be eating at my banana split instead."
    C "(And besides, the school year isn't over yet! There's still one more big event before we all start packing...!)"
    jump eveoflastday_part1

label eveoflastday_part1:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "The morning of the last Saturday finds me hibernating in the depths of my bed such that Tanya has to come in and drag me out of it herself."
    C "But lacrosse season's overrrr..."
    T "Proper fitness does not have a \"season\", Clover. It requires constant, thoughtful consideration to introduce activity into every day."
    "I moan and groan from the warm confines of my bed, but the combined strength of Sibyl and Tanya on each leg easily drags me right out of the sheets."
    scene bg path with dissolve
    "It's all for the best that me, my pillow, and my sheets are all rent asunder. It's a lovely day outside once my eyes blink awake into the brightness of the comfortably warm early Summer."
    S "Oh! We should have brought your lacrosse sticks!"
    C "Why?"
    S "To catch butterflies of course!"
    "The three of us prance around in the sunlit meadows away from the academy buildings. Sibyl in particular is having the time of her life running through the tall wild grasses in pursuit of butterflies."
    S "{b}Achoo!{/b}"
    "Until her hay fever gets the better of her. We make a quick stop to show her Tanya's secret refuge in the easily-climbable free where Tanya and I had our first date then head back closer to campus."
    scene bg mary with dissolve
    C "There's a lot of girls out here today."
    "I make the comment idly as we walk through the cheerful flower gardens on the way back to the academy buildings, but after saying it I actually pay attention and find it scarily accurate."
    C "Did we always have {b}this many{/b} students at the academy?"
    S "This probably isn't even all of the students. The seniors are having their graduation ceremony today in the chapel."
    T "Now that all the exams are over and club activities are finished for the year, there's nothing else for the rest of us {b}to{/b} do except roam around the campus."
    C "(We could have slept in too. Not that this is bad either of course.)"
    "Many strange faces surround me, all going about their carefree morning with a smile on their faces and surrounded by friends, just like me."
    scene bg lacrosse with dissolve
    "We continue wandering naturally to the place that the three of us have spent so much time over the past few months — the lacrosse field."
    "Coming to a particular patch of grass that is burned into my memory, I kick at the innocent green growth with a deep bitterness that I can almost taste."
    C "I still can't {b}believe{/b} I upchucked my guts right here in front of the whole school."
    "Tanya quickly breaks out into a serious case of the giggles, which is only silenced when I punch her on the arm."
    T "Sorry, it's just— you said \"upchucked my guts\" with such a serious, somber look on your face. I couldn't help it!"
    "She's still barely holding back the mirth flowing out from within, some of it leaking when she herself repeats \"upchucked my guts\". Even Sibyl is growing red to the face."
    S "I'm sorry, Clover, I'm also..."
    C "Fine, go ahead and laugh. It's just a deep emotional scar I'm going to have to live with the rest of my life, no biggie."
    "The two break out laughing when given permission, and I cannot help but join them after a while, seeing as how infectious this case of the giggles turns out to be."
    C "(It's still not a good memory, but... this one makes up for it.)"
    scene bg gym with dissolve
    "Coming in from the outside, we take a shortcut through the gymnasium. A few girls engage in some casual athletics here and there, while others hang out on the bleachers with their friends."
    "As my footsteps echo across the shiny floor, I recall the many steps I've taken throughout the year, both in athletics class and training with the lacrosse team."
    S "Oh!"
    "Breaking my own musing recollections, Sibyl interrupts with her own."
    S "I think it's okay to ask now? What animal were you, Tanya?"
    C "Animal?"
    T "Booby. What about you?"
    C "Wait, {b}what{/b}!?"
    S "That's right, it was before you arrived, Clover. We had an animal masquerade party on Halloween!"
    C "But Tanya's talking about {b}boobs{/b} now!?"
    T "A \"booby\" is a type of bird, Clover."
    C "O-Oh yeah...?"
    "I just shut right up before I make even more of a fool of myself. It kind of hurt to hear the two chat so happily about something that happened before I ever came on the scene, but I try not to let it bother me too much."
    S "I was the kangaroo!"
    "Sibyl demonstrates her knowledge of kangaroos by drawing her hands up in front of her and performing a little jump-kick like she's a young joey eager to take on the world now that she's left her mom's pouch."
    T "Ah, figures. I don't think I ran into you at all."
    S "Ah, well. Maybe next year."
    S "What animal would you like to get next year, Clover?"
    show choice_darkness with dissolve
    menu:
        "\"Dog\"":
            hide choice_darkness with dissolve
            C "I wanna be a dog."
            "The answer is out of my mouth before I really get the chance to think of it."
            S "That's a popular one! You want to be like your buddy back home, hmm?"
            S "What was his name? Ajax?"
            C "Abraxas."
            "I feel kind of stupid having chosen something so plain right off the bat, especially after Sibyl demonstrated how fun it could be to play a kangaroo, and after Tanya committed to being an animal with such a goofy name."
        "\"Raven\"":
            hide choice_darkness with dissolve
            C "Hmm, maybe a raven?"
            S "Why's that?"
            "Numerous answers come to mind, from their occult folklore as messengers between teh spiritual and physical realms, to their mysterious reputation as guardian of wisdom and secrets."
            "But I of course don't say any of that out loud. Instead, I glance across to Tanya."
            C "I've been a blonde my whole life. I want to try having sleek black feathers for a day."
        "\"Squonk\"":
            hide choice_darkness with dissolve
            C "Maybe it's not so much like \"me\" anymore, I've always kind of empathized with the squonk."
            T "What's a \"squonk\"?"
            "Though only Tanya asks the question, Sibyl is similarly puzzled."
            C "It's a mythology creature known for it's extreme ugliness. It's really shy, like me, and dissolves into a puddle of its own tears when cornered."
            C "I identified with it a lot in middle school. I even went out hunting for them once."
            T "Clover, you're {b}not{/b} ugly, by {b}any{/b} stretch of the imagination."
            C "I know, okay? I'd rather just... forget about middle school altogether, alright?'"
            S "This \"squonk\" sounds adorable actually. It totally makes you want to protect it. I wonder if we can get it added for next year's masquerade?"
            "Sibyl, thankfully, changes the topic away from me as I gow increasingly uncomfortable re-living the mistakes of years past."
    T "It's all first-come-first-served so you either have to camp out in front of the Student Council office, risk getting a random leftover, or else have leverage over Vittoria and Vincenza to sneak you the mask you want."
    C "(Leverage, eh?)"
    scene bg lockers with dissolve
    S "Ooh! So this is what the athletic teams' locker room looks like!"
    C "Oh, yeah, this is your first time in here, isn't it?"
    "Sibyl takes a opportunity of being in a new place to roam around looking at everything, like it isn't nearly an identical copy of the locker room used as necessary for the athletics classes."
    "Only Tanya seems to be brought down by the scenery, as made obvious by the dark way in which she stares at one particularly shower stall."
    C "(I'm not the only one who has made bad memories this year, am I?)"
    "While Sibyl is distracted walking down the bench in another aisle of lockers like a balance beam, I slide over to sneak my hand into hers, making her jump out of her dark trance."
    C "Hey, don't let your thoughts fester on what happened. All that darkness went down the drain there long ago."
    "A soft squeeze compacts my fingers, accompanied by a smiling glance aside from Tanya."
    T "You still have my back, just as you did then."
    C "I sure did, and I know now that you have my back... because now I'm faster than you."
    "A sound something like a half-grunt, half-snort sounds Tanya's dismissal of my retort, and like always, sh's quick to strike back at me."
    T "The exam was a {b}sprint{/b}. I'm built for {b}endurance{/b}."
    scene bg library with dissolve
    "I'm nearly about to challenge Tanya to a race right then and there, but in the end we instead follow Sibyl out of the locker room and down the hallway toward the library."
    S "Sylvia Valemont, I'm going to miss you!"
    "Like a woman departed from her beloved, Sibyl throws herself at the bookcase holding rows of her favorite novel series."
    C "(She's read those, like, minimum three times each. She'd probably be able to recite them word for word if I asked her to.)"
    "The library is rather unusually empty compared to the week before, like all the students who were studying so fervently here decided it was the last place they want to be now."
    C "Won't your local library have them too?"
    S "Oh, for sure they do, but it's not the same. Each book, no matter if they have the same words printed, each contains their own \"character\"."
    C "Really?"
    S "Really, really."
    T "Don't be silly, they're just books."
    S "Two books may have the same ISBN, but each one has a unique. Think of their deckle edge like... a fingerprint! No two are the same!"
    T "Their {b}what{/b}?"
    C "What the heck is a \"deckle\"?"
    S "It's an old papermaking tool, but a \"deckled edge\" on a book is when the paper side of the binding is all rough and uneven."
    S "On really old books in particular, this was a completely random part of the paper-making process, but now, I consider even the wear and chips books acquire to be part of their \"deckled edge\"."
    T "Only you, Sibyl."
    S "Come on, Clover, didn't you feel anything for hose books which I recommended you?"
    "Try as I might, I don't really remember anything in particular besides the stories contained within."
    C "No... they were just books to me."
    C "And honestly, I was mostly reading them because I wanted something in common with you."
    S "I figured as much. You haven't asked me to pick out a book for you in months now."
    C "Sorry. I did enjoy the ones you picked out for me, though. I'm just not much of a reader."
    "Like Tanya back in the locker room, this spontaneous trip through the memories we've accumulated through the halls of the academy have lead me to some sour lemons in the fruit bin of my brain."
    C "(How many more times am I going to wish I could go back in time and punch myself in the face? And what were Vittoria and Vincenza thinking encouraging me like that?)"
    scene bg artroom with dissolve
    "Passing the club rooms, we come next to the art room, which of course Sibyl and Tanya want to stop in to after having spent so much time here together throughout the year."
    "Having already seen the big stack of portfolios piled up in Sibyl's side of the room, it's no surprise to find that few of the students' art remained in the class."
    C "It feels kind of... sad and clinical, not seeing all of the random art strewn about the room anymore."
    "All of the little clay statues made by students for their exam remain, of course, huddled in one corner like a grand gray army of this-and-that, but otherwise, nothing."
    S "Aha! Worry not, Clover, for Miss Izzie always thinks of everything no matter how scatterbrained she may seem!"
    "As Sibyl and Tanya soon show me, the storeroom contains more than just raw material and equipment, but also a whole rack fo shelving with thick portfolios labelled by year."
    S "Here we are!"
    "Sibyl pulls our year off the shelf to leave through it out on one of the big drafting tables. Each turn reveals a new set of artwork never seen before, and that blows anything I could do completely out of the water."
    "Some of them are even Sibyl's, or Tanya's. What I don't expect whatsoever is to find any record of my time at the academy recorded in this thick volume... until the next turn of the page finds my own face staring back at me."
    T "That's hot."
    "Maybe \"glaring\" is more accurate. To her credit, Sibyl really captured the essence of my negative emotions that day of our first art class when I modeled for her."
    S "It's my {i}The Birth of Clover{/i}!"
    T "I should get this blown up and printed to hang over my bed. Or maybe make it my screensaver."
    C "You wouldn't {b}dare{/b}!"
    "Tanya yields in short order after a particularly firm shove of my shoulder into her side, but I know she's only joking. I'm actually kind of happy this will stay enshrined at the academy for future posterity."
    C "(I may have made a really big fuss and said some regretful things, but thank you so much for sending me here, Mom and Dad!)"
    scene bg aquarium with dissolve
    "Tanya doesn't want to go in, and Sibyl doesn't understand why either, but I force both of them to stop into the aquarium with me."
    C "Remember that time you found me in the aquarium, when I first came to the academy?"
    "Clutching Tanya's hand in mine, I pull her close to my side to grin bashfully in her face. I'm planning to make some sort of sappy statement of how much we've changed and come to like each other since then, but Tanya has other plans."
    T "...When I had to claw my fingernails into the palm of my hands to stop myself from holding your head underwater in the fish tanks until your arms went slack? Yeah, I remember."
    C "Wha—!? Was that a murder threat? I haven't heard one of those in {b}months{/b}!"
    T "It was a {b}past tense{/b} threat to murder you, so it doesn't count."
    C "If anyone's going to murder me, I want it to be you, Tanya."
    "Sibyl lets out a long, drawn out \"Awwwww\" as we embrace to share a kiss right there in full view of her and a few dozen glassy fish faces gawking at us from behind the glass of their tanks."
    scene bg classroom with dissolve
    C "I'm not going to miss this place."
    scene bg cafeteria with dissolve
    C "I am {b}so{/b} going to miss this place!"
    scene bg dorm with fade
    "After lunch, we say goodbye to Tanya who goes off to visit her other friends like she does every Saturday."
    S "Are you sure it's okay?"
    C "That what is okay?"
    S "That you're not spending every last hour you both have together before the summer break?"
    C "Yeah, it's fine. We plan to, hopefully, meet up over the summer, so..."
    "It does kind of feel bad to leave her now, when we are indeed quickly running of hours left to be together and I'll have to leave off for the unknown of my current home situation shortly enough."
    "We did talk about this, though. She too was concerned about leaving me alone so long on the day before I leave to go home; she wanted to bring me along to meet with her friends."
    "In the end, I convinced her that it's fine totally fine to go meet wither friends like she has been all year, and I would be uncomfortable joining in suddenly with such an established group of friends."
    C "(Even now, with how much I've grown over the past few months and with Tanya at my side, that kind of social interaction is out of my league.)"
    S "Did she... ever tell you what she's doing every Saturday?"
    "Quietly, and with a guilty look my way, Sibyl inquires about just what Tanya is always up to on Saturdays. I don't even fully get it myself, but I try to explain as best I can."
    C "She goes and geeks out with other girls in the academy who also like the kind of lesbian comics she showed us. They, like, watch anime and tak about manga they read, and stuff like that."
    S "Huh. So it's a book club, and she didn't invite {b}me{/b}?"
    C "Maybe she, umm... didn't think you've be very much interested in the stuff they read because... you know."
    S "You're probably right, but still... keeping this whole thing a secret just for that?"
    C "You shouldn't blame Tanya. It's apparently supposed to stay a secret. I probably shouldn't even have told you."
    S "I'm not angry, Clover, just... I don't know. And I won't tell, I promise!"
    scene bg lounge with dissolve
    "On our way back to our room, we stop at the lounge for the final chore of the morning."
    S "Wow, there's already a line. Maybe we should have come by earlier."
    "The line is long, but it doesn't take long before we get to the front and receive our very own copies of the class yearbook."
    "\"Prudence Preparatory Academy for Girls\""
    "My fingers trace over the letters debossed with gold in the otherwise empty pink cover. It's probably the first time I'e actually seen the full name of the school written out, and hopefully, not the last."
    jump eveoflastday_part2

label eveoflastday_part2:
    scene bg bedroom with fade
    "With Tanya away at her super secret anime club meeting, Sibyl and I return to our room to pass the time before we meet again at dinner."
    "It's clear that both of our thoughts are on home, but while I'm merely sitting on my bed cross-legged with the picture of Abraxas in my lap, Sibyl paces back and forth across the room while busy packing up her belongings."
    C "You do know they're not kicking us out right away, don't you?"
    S "I know."
    "Maybe it's because packing means accepting that I'm leaving, or just that I hate packing in general, but I've avoided it entirely up until now."
    C "(We have all morning tomorrow. She doesn't have to go this crazy right now...)"
    "Eventually, I find it more interesting to pass the time by watching her at work than doing anything else. My head rotates side to side with her activity like I'm at a tennis game."
    C "You're going to leave enough stuff out to make it through tomorrow, right?"
    S "Of course I am."
    "Compared to my side of the room, Sibyl's always looked tidy. Now that she's actually tidying up for real, my side of the room looks downright slovenly by comparison."
    "With one eyes still watching Sibyl at work, I reach aside to pick up the new yearbook and finger over the cover again, then flip it open to peruse the pages."
    "Pages full of photos of students going about their activities wih great big smiles on their faces rub salt in my wounds when I see the autumn foliage behind them and know I wasn't there to enjoy it with them."
    "My sprits recover as I flip through to the sports team pages, and even spot myself in a few photos on the page covered in cartoon roses."
    C "Oh, there's Tanya!"
    "I chuckle to myself when I notice that I'm clearly looking at Tanya in one picture when everyone else is facing forward."
    S "What is it, Clover?"
    "The movement more than Sibyl's voice pulls my attention from the book, and soon enough I feel her plop down beside me on my bed before I can even answer."
    C "I found myself in some of the Wild Roses team photos. I didn't even know anyone was taking these photos."
    S "The yearbook club is a sneaky bunch."
    "Flipping back to the club images, we manage to spot Sibyl and Tanya here and there in the backgrounds or in groups shots, even if not the subject of any of those photos in particular."
    S "You arrived after photo day, didn't you? What did they do for your class photo?"
    "It's a good question, and one that stumps me, so I flip next to our homeroom class's page to find out."
    C "Oh, that's right. Miss Izzie pulled me aside in class to take a photo one day. I totally forgot about it."
    "Judging how how sharp the daggers I'm glaring in my photo are, it was pretty early in my time at the academy."
    "What's more, the different background compared to the other students who had their photos professionally taken makes me stand out like a sore thumb among the rest of the class."
    C "This sucks."
    S "I think it's cute. Some day, you'll look back at this and laugh."
    C "Maybe, but right {b}now{/b} it's everyone else looking at their yearbooks doing the laughing."
    S "Oh, don't think like that, Clover! It's a good photo!"
    "The bed shakes as Sibyl stands up from my bed to go dig through her stacked up belongings to find what she'd left out underneath, and returns with her own yearbook in hand."
    S "Here."
    C "Huh?"
    "Sibyl pushes her yearbook at me again expectantly, then adds an aside."
    S "Let's sign each other's yearbooks."
    C "But the yearbook signing social is tomorrow."
    S "We're Vertu partners, Clover! We should be the first to sign one another's yearbooks!"
    C "Okay, but... can I use my glitter gel pens?"
    S "Only if you let me borrow one!"
    "I select a lime green from the pack, Sibyl selects a dark blue, and we separate to our own beds for privacy while we write the words which will have to sum up our entire experience together this school year."
    pause 0.5
    "It's a comfort to me that Sibyl also seems to be deep in thought for a time after we trade yearbooks, but soon enough she's already writing in my yearbook, while I'm still stuck with cobwebs in my brain."
    C "(What does Sibyl mean to me?)"
    "The first and most obvious answer comes to mind instantly — that being my first real love."
    C "(But I'm not going to write that in her yearbook. I want it to be meaningful {b}to her{/b}.)"
    "\"Sibyl, thank you for supporting me.\""
    C "(That sounds really {b}stiff{/b}, doesn't it?)"
    "I've long known that I am even less of a writer than I am a reader, but for Sibyl, I'll keep going and hope I manage something more impactful."
    "\"It was an amazing year we had together and I'm so glad to have gotten you as my Vertu partner.\""
    "\"You've always been willing to help me, even when I didn't know that I needed it or when I did not want it at all.\""
    C "(Oh boy, isn't that an understatement?)"
    "I could very well write \"sorry I was such a bitch\" but I'm trying to keep the messaging positive."
    "\"You've helped make the academy feel like a second home to me, and even though we haven't quite left yet, I'm already counting the days until next year!\""
    C "(There we go. End on a high note. Excellent.)"
    "I set the open book aside to let the glitter gel dry and find Sibyl has already finished herself."
    S "Tradesies?"
    C "Yeah! Just be careful; the gel is still drying."
    "I didn't even write anything that strange in the book, but giving Sibyl back a piece of my feelings written down still makes me blush a little."
    "Sibyl's own heartfelt messages pop out of the otherwise blank page of my yearbook with a perfectly loopy cursive script written in sparkling deep blue that almost matches her eyes."
    "\"Can you believe the school year is already ending, Clover? It feels to me like just yesterday that I awoke out of a dream to find you in my room and in my life.\""
    "\"Time has never moved so fast as it has since you arrived at the academy. Though there might have been a few bumps in the road since then, we've only grown closer for them.\""
    "\"Thank you for being the most wonderful Vertu and enjoy your summer break! I'll be here in the next bed over, ready to wake you up early for practice again next year!\""
    C "(Darn it, how does she do that? She wrote exactly what I wanted to say but a million times better!)"
    C "Sibyl, I'm sorry."
    "I instantly apologize when I set the yearbook down and catch Sibyl's gaze once more. I don't even know what I'm apologizing for — maybe how lame my yearbook comments are in comparison to hers, or maybe for all the drama I caused earlier in the year."
    S "What are you apologizing for, Clover?"
    C "I-I don't know."
    S "Then I'm not accepting your apology."
    "With a sweet smile, Sibyl gets up from her bed to come meet me on mine and wrap her arms around me in a hug, to which I happily return the gesture."
    S "I'm proud of you, Clover. I know things were rough for you, but you've fought through it all and come out better for it."
    C "It's all thanks to you, Sibyl."
    S "No it's not. I only gave you some little nudges along the way. Everything else was all you."
    "My emotions threaten to overflow in the tender moment, but I manage to keep ym hands firmly on the reigns enough not to make a fool of myself until at last we separate."
    "As I watch Sibyl return to her packing, I cannot help but think how lonely she, who comes from such a large family, must have been before I arrived."
    "That someone like me, who grew up an only child, am already feeling so terribly lonely just thinking about spending the whole summer without the girl who became like a sister to me."
    jump yearbooks

label yearbooks:
    scene bg transition with fade
    scene bg gym with dissolve
    "Armed with my yearbook in one hand and my collection of glittery gel pens in the other, I walk in step with Sibyl and Tanya at either side into the sea of pink churning in the gymnasium."
    C "Whoa."
    S "I knew we were going to be late."
    T "It's not {b}my{/b} fault that Sierra wanted to sign my yearbook with a {b}whole page{/b} worth of her thoughts before leaving for the yearbook signing event herself."
    "Tanya isn't exaggerating even a little bit."
    "Sibyl and I stopped by her room to pick her up before heading to the gymnasium. I wanted to sign her yearbook before coming here too, but didn't have time when Sierra filled a whole blank page from top to bottom all by herself."
    C "(Now I can finally get Tanya to sign my yearbook!)"
    "I turn to Tanya and open my mouth, \"Tanya!\" is what sounds out, but it doesn't sound like my voice."
    "\"Sorry, Clover. We're stealing your girlfriend for a little bit, 'kay?\" A trio of girls emerges from the crowd and pulls Tanya into it with grasping hands each clad with a single gold ring."
    C "(Were they talking to {b}me{/b}? How do they even know my name!?)"
    "Judging at least from the direction the crowd parts away from where I last saw Tanya, they're making for where Miss Woolsey, Miss Izzie, Vittoria, and Vincenza have already camped out in one corner of the gymnasium."
    "Not very pleased to find my girlfriend immediately stolen away from me, I turn to enlist Sibyl in chasing after her, only to find that she's also already piled under yearbooks of girls I recognize from all those days dropping her off at the art club."
    C "(Seriously!? Fine, I'll go fetch Tanya myself!)"
    "Into the sea of girls I wade using the huge \"Congratulations Seniors!\" banner on either side of the basketball hoop as a north star to keep me from getting too lost and disoriented."
    "\"Clover!\""
    "The sound of my own name stops me in my tracks, finding quickly its source in a girl I've spoken to only a handful of times — the library committee girl."
    C "(What was her name? Reagan?)"
    C "Uh, I think Sibyl was back that way."
    st "Oh? I'll get her after you!"
    C "(She wants {b}me{/b} to sign her yearbook?)"
    "Thankfully, the yearbook she pushes into my hands is already full of well-wishes that address her as \"Rachel\", which sounds right to me after having read it."
    "\"Thank you for your book recommendations, Rachel. Have a good summer!\""
    C "(There. That's good, right?)"
    "It's short and sweet, but Rachel doesn't seem to mind. After thanking me she heads off in the direction I pointed out as where Sibyl might be, and I sneak a glance at what she left for me."
    "\"Have a great summer, Clover! I hope to see you and Sibyl around the library more next year!\""
    C "Hmm."
    "I'm barely three steps toward my goal when I'm stopped yet again, this time by a girl who I recognize as a classmate. She doesn't say much, but does smile shyly at me while shoving her yearbook aggressively in my hands."
    C "(What do I even write here? I talked to this girl, like, {b}once{/b} and that was while passing out worksheets.)"
    "I end up writing down a simple and plain wish for her to have a good summer, but receive much more than that in return."
    "\"I enjoyed having classes with you, Clover, even if we did not talk much. I wanted to say hello and be friends with you so much, but I didn't know how to start. You're so pretty and shine so much brighter than I—\""
    "A big scribble of crossed out words marks the end of that sentence, followed next by a simple, \"I hope you're in my class next year. I want to be friends!\""
    C "(What the heck was that? If she wanted to be friends, why didn't she just talk to me?)"
    "It's not like I don't know what it's like to be shy, and I do suppose that I had a very strong bitchy aura when I first arrived."
    C "(But even so, it's crazy to wait until the very last moment to tell me something like that, and in writing too!)"
    "Just when I think I'm finally in the clear to go and reclaim my girlfriend, I get stopped multiple times in succession with similar messages written in my notebook."
    "Often varying in particular, the most common thread seems to be that I've in fact been noticed and admired from afar this whole time, like everyone in the whole school was too afraid to come up and talk to me directly."
    "\"I was a fan of Tanya before you showed up, and I got really angry when you started butting into her life... but after Prom I suddenly changed from a Tanya fan to a Tanya&Clover fan! Wishing my favorite pair all the best!"
    C "(Is that why I'm so popular? Because I won Prom Queen with Tanya?)"
    "It explains at least a little of my popularity, and there's also that I'm apparently really cute or something. The girls who write in my notebook keep making me out to sound like some kind of ethereal stardust-based lifeform."
    C "(Oh, there's a postscript on this one.)"
    "\"P.S. If it doesn't work out with Tanya, call me! 617-555-1509 —Agnes <3\""
    C "(What the {b}heck{/b}!?)"
    "Having had just about enough of signing the yearbooks of girls I barely know, if that, I manage to trudge the rest of the way to the far corner of the gymnasium where Tanya was spirited away to."
    "It's only when I get there that I find that the circle of girls there has already collapsed under the weight of fangirls pushing to get signatures from Vittoria and Vincenza."
    mi "Girls, girls, form a line! There's {b}plenty{/b} of the twins to go around!"
    "A few half-hearted chants of \"Yes, Miss Izzie\" echo out as a whirlwind of pushing and shoving eventually tosses me around like a plastic bag in a hurricane."
    "Somehow, a proper line forms out of it, leading from half way across the gymnasium right up to where the twins sit above everyone else one step up the bleachers like the school royalty they purport to be."
    "Try as I might, I just can't find Tanya. Even standing on my tiptoes doesn't help me pick her out of the crowd. I'd need a stepladder, and maybe not even then."
    C "Where did Tanya {b}go{/b}!?"
    mi "She was talking to the twins before the wave crashed down on us."
    C "Miss Izzie!?"
    "I whirl around and come face to face with my arts teacher — or as much as that is possible given her small size."
    mi victory "In the flesh!"
    "She performs a shockingly perfect curtsy that I never would have guessed she was capable of, then snatches the yearbook right out of my hands."
    C "(I guess teachers sign yearbooks too?)"
    "While Miss Izzie is busy writing something down in my yearbook, a line has already formed up behind me nearly matching the one that formed for Vittoria and Vincenza."
    mi "Here you go!"
    "Miss Izzie returns my yearbook, and gives me a firm ruffle of the hair atop my head for good measure."
    mi "You're a good kid, Clover. I'm glad everything worked out for you."
    C "What do you mean?"
    mi "I heard about your difficult family issues, and {b}then{/b} crushing on a straight girl... That shit crushed my soul to pieces when I was your age."
    "I don't really know how to reply in the moment, and just stammer out an idiotic sounding \"uhh, yeah\"."
    mi "There really is no place in the world quite like Prudence Prep, especially for girls like us. I hope to see you in my class next year, Clover."
    C "I hope I'm in your classes next year too, Miss Izzie."
    mi "So cute!"
    scene bg gym with dissolve
    "The expression of endorsement for Miss Izzie's classes, even if I meant just being at the academy in general, earns me yet more vigorous heat-patting before my teacher pushes me off on my way to the twins' line."
    "It may have shortened some, but the line to get to talk to Vittoria and Vincenza is still long. With time to spare, I crack open my yearbook again to read what Miss Izzie wrote for me."
    "\"Art is a journey of self-discovery, and I saw so much growth in you this year. Do not become discouraged, Clover. You have only just started to draw out the wonders of your soul.\""
    "It's a definite surprise just how profound and inspiring I find the words Miss Izzie left for me, but when I think about it again, nearly every time I interact with her I leave thinking she's deeper than she acts."
    "I continue scanning the crowd for Tanya as the line progresses, but to no avail. The line dwindles one by one and in due time I'm face to face with Vittoria and Vincenza again."
    scene bg gym
    show clover
    show hime
    show ouji
    with dissolve
    H "Ah! Clover, settle something for us, would you?"
    C "Actually, I was just—"
    O "Most of the girls in our line have given their yearbook to me first."
    H "Where's the love for \"Hime-sama\", huh!?"
    O "The girls simply love their \"Ouji-kun\" more. Don't you agree, Clover?"
    H "You wanted {b}me{/b} to sign your yearbook first, isn't that right, Clover?"
    "My attempt to inform that I only got into their line so they could tell me where Tanya went never materialized, and with both of the twins bearing down on me, I feel like I have to choose."
    C "(But who do I pick?)"
    show choice_darkness with dissolve
    menu:
        "Vittoria":
            hide choice_darkness with dissolve
            jump vitt_option
        "Vincenza":
            hide choice_darkness with dissolve
            jump vinc_option
        "Neither":
            hide choice_darkness with dissolve
            C "I'm not here for either of you. I just want to know where Tanya went."
            "My answer makes the twins blink to one another in surprise, then simultaneously drop into their characters like they think annoying me will get me to participate in their game."
            H "Dearest me, sister, we have been cast aside! How merciless!"
            O "{i}Porca miseria!{/i} The beauty's tongue is sharper than any rapier."
            "Their play acting finished, both Vittoria and Vincenza out stretch an opposite hand toward me. It's clear that neither is giving up on the little contest."
            "Under normal circumstances, I am very much obstinate enough to stand here all day and refuse to play along until they give in, but right now I just want to find Tanya."
            C "Fine."
            menu:
                "Vittoria":
                    hide choice_darkness with dissolve
                    jump vitt_option
                "Vincenza":
                    hide choice_darkness with dissolve
                    jump vinc_option

label vitt_option:
    "I hold out my yearbook in offering to Vittoria, who scoops it up with a self-satisfied glance across to her sister. Vincenza surprisingly enough isn't mad but instead grins with a quiet mirth at the choice."
    O "You have triumphed over me with someone who we already knew has crushed on a \"princess\"."    
    jump yearbooks_part2

label vinc_option:
    "I hold out my yearbook in offering to Vincenza, who scoops it up with a smug grin across to her sister. Vittoria surprisingly enough isn't mad at all, but does cross her arms with faux derision."
    H "This conclusion was foregone. We knew in advance that Clover is dating a \"prince\"."
    jump yearbooks_part2

label yearbooks_part2:
    C "Umm... Can you just sign my yearbook and tell me where Tanya got to already?"
    "The half of the pair I selected — almost blindly, not that I tell them so — flips open to an empty page to start writing as the twins continue to banter back and forth."
    H "Do tell me, Vincenza, whatever might be the issue with \"princesses\"? I thought they were your preference."
    H "I had expected you to want to be the \"Hime\" persona before you laid claim to the \"Ouji\"."
    O "There is no issue at all with \"princesses\", Vittoria. But, do we not both know that you yourself prefer a \"prince\"?"
    "Finishing up, my yearbook passes from one twin to another without so much as a break in the discussion between them."
    C "(Are all Italians this strange?)"
    "Vittoria and Vincenza are still speaking English, but it's perfectly clear if only to me that they're actually speaking to one another."
    H "What of it? It is not natural for a \"princess\" to seek her \"prince\"."
    O "How the could I be anything but \"Ouji-kun\"? You are right that \"princesses\" are my preference, \"Hime-sama\"."
    # show them looking into one another's eyes
    "Vittoria and Vincenza might as well be speaking Italian for all that I am able to comprehend of what they say to one another. When they at last shut up, they remain staring into one another's eyes for a creepily long time until I disturb them."
    C "Sooo... can I have my yearbook back now?"
    "The meeting of eyes between Vittoria and Vincenza snaps like a taut cable when my words cut through it. Both turn to me, near-imperceptibly shaking off the lingering thoughts they were sharing just a moment before."
    H "I am sorry to report, Clover, but we do not know where Tanya went after leaving us."
    O "She, in fact, informed us that she was leaving in an attempt to find {b}you{/b}."
    C "Oh..."
    C "(All of {b}that{/b}, for nothing!)"
    "Taking my notebook back, I turn away to let the next girl in line finally have her turn basking in the presence of the royal twins, but not before they offer me their parting wishes."
    O "Enjoy the summer, Clover."
    H "We hope to see you next year!"
    C "Yeah, you too."
    scene bg gym with dissolve
    "I hadn't intended to specifically seek out Vittoria and Vincenza to sign my yearbook, but now that they have, it's only fair that I see what they wrote as I shuffle off aimlessly with hopes of every seeing my girlfriend again rapidly dwindling."
    "\"It was a lot of fun playing with you this year, Clover. Next year, you can help us with some of our other \"projects\"! Have a good summer!\""
    "\"Clover— I'll never forget the \'special times\' we shared this year. Here's hoping next year is just as fun! See you next autumn!\""
    C "(There sure as {b}heck{/b} not going to be any \"special times\" next year!)"
    "Both of the comments are only signed once, as \"V&V\" with each letter clearly different in handwritings, but only Vittoria would have written the second line."
    C "(And who does Vincenza think she is calling me a \"project\"!? Maybe {b}she{/b} had fun while watching me try and fail to claim Sibyl's heart, but it was {b}never-ending torment{/b} for me!)"
    "Slamming the book shut, I trudge off into the sea of girls again with my spirits at an all-time low — but not for long."
    S "There she is!"
    T "Clover!"
    "In the time it takes me to whip right around to the source of their voices, my two lost friends are suddenly right there on either side of me."
    "Even more han simply being beside me, they each hook an arm under one of my own like it's a very real possibility that we're in dangerous of being torn apart again in the midst of this madness."
    T "I've been looking {b}all over for you{/b}, Clover!"
    C "Me too!"
    S "I turned away for just one... or maybe two... minutes, and you were gone!"
    T "We have to hurry, Clover, everyone's already gathered around Miss Woolsey!"
    scene bg gym with dissolve
    "When we finally push through the gymnasium over toward where Miss Woolsey is standing, we find that just about the entirety of the Wild Roses is already there."
    "I expected to find our coach giving some sort of congratulatory speech like she always does, but what I find is an outpouring of respect and admiration for her instead."
    "\"You're the best, Coach Woolsey!\""
    "\"Every pregame speech you give gets me get totally fired up!\""
    "\"I thought I hit a plateau with my skills last year, but I'm even better this year!\""
    C "\"Thank you for giving me so many chances to succeed, Coach Woolsey!\""
    "There's no way I'm going to miss the chance  to shout out my own thanks to her after everything Miss Woolsey's done for me this year."
    "Though she's a little backed into a corner with all the affection being thrown at her so heavily, it is clear even to me how deeply she cherishes each and every one of us."
    mw "Thank you so much, girls. It's been an privilege and, honestly, the time of my life serving as your coach."
    mw "All of you worked so hard and should be proud of everything you've accomplished this year. It is not my leadership to be commended, but {b}your{/b} strength and determination."
    mw "It's true that some of our Wild Roses are graduating this year, but next year is a new opportunity to bring in new friends and teammates, so I hope to most of your faces in my gym next year!"
    "With that, Coach Woolsey puts her hand out, we all throw ours in, and the gymnasium trembles with the uproar of nearly two dozen voices shouting to the rafters — {b}Wild Roses!{/b}"
    "After delivering the speech we all desired, Miss Woolsey gets simply clobbered with all of our yearbooks. True to her kind nature, she stops to thoughtfully write in each and every one."
    C "I— I have to thank you again, Coach Woolsey."
    "Without knowing for sure that she heard the first time I shouted it to her along with all the others, I make sure to sa it again when it's my turn for her to sign my yearbook."
    C "I made a total mess of everything, like, a half dozen times at least, and you kept giving me another chance."
    "She doesn't respond in any fashion besides glances up to me with a soft smile, but that's okay because she's busy writing in my yearbook. I at least know she's hearing me while finishing up her message."
    "It's only when she's finished writing that she passes my yearbook back and respond to me personally."
    mw "Clover, it's my job to help you succeed, not to force you to give up."
    C "I know, but—"
    mw "No \"buts\". I threw you back into the thick of it every time because you were willing to put in the effort to succeed."
    mw "Everything you've accomplished this year, on and off the field, was because {b}you{/b} were willing to work hard to achieve it."
    C "You're right, Coach Woolsey. Thank you... for encouraging me to believe in myself."
    "I make way for the next student in the big tangle of yearbooks and return to Sibyl. While waiting for Tanya to finish, I check out what Miss Woolsey had to say."
    "\"Clover, it was a special delight as both your dorm mother and lacrosse coach to be able to watch just have much you've grown this year.\""
    "\"It brings me great joy to have played even a small part in helping the troubled girl who first knocked at my door bloom into such a dedicated athlete and wonderful friend to her classmates.\""
    C "(Well, friend to Sibyl and Tanya anyway. I barely spoke to anyone but them, and the other lacrosse girls too I guess.)"
    "\"I meant every word when I told you that the people you'd meet at this academy would one day become like a second family. As I've watched you, Tanya, and Sibyl over the past months, I hope you feel the same.\""
    "\"Enjoy your summer, Clover. Next year is sure to be even more special than the last!\""
    S "Miss Woolsey wrote a lot in your yearbook, didn't she? She's so thoughtful."
    C "Were you able to get your yearbook signed by Miss Izzie yet?"
    S "Oh yeah. She filled almost a third of the page all by herself."
    "Sibyl props up her yearbook to show me the long scrawling comments left by her club advisor, reaching such a length that the lines start to droop to one side as it goes on and on."
    S "She basically recapped the entire year, told me how creative I am over and over again, begged me to watch over you and Tanya, and ended by noting that I have the fluffiest hair in class."
    C "That sounds like her."
    "I try to not make my comment sound too demeaning, and luckily Sibyl doesn't take it that way."
    S "She's a wild teacher but a {b}lot{/b} of fun, and really knows her stuff. It's like she was born to be an art instructor."
    C "Yeah, I know what you mean. Miss Woolsey is a natural coach. She's the kindest and most supportive woman in the world, but she can be tough too."
    "Memories of the incident in the locker room come to mind, as well as the endless hours she spent drilling us in this very room and out in the hot sun."
    S "We're so lucky to have both of them."
    C "Did you manage to get all the signatures you wanted?"
    S "I think so. What about you?"
    C "I sill need Tanya..."
    C "(...The signature I need to get the most.)"
    "Both of us turn to glance her way, finding her now chatting at length with Miss Woolsey, her yearbook already signed. They both glance my way briefly in teh course of their discussion."
    S "I think they're talking about you."
    C "Y-You think?"
    "Just knowing that they're talking about me drives me mildly crazy, but I manage to resist the overwhelming urge to ask Tanya what Miss Woolsey had said about me when she returns and mentions nothing of it."
    T "Got all your signatures?"
    S "Yup!"
    C "I have one left."
    "It's a relief to me when Tanya doesn't reply at all, instead reaching her right hand up to brush her fingers through her hair. She knows exactly who I'm missing."
    C "(So she's also fretting about what she'll write in my yearbook.)"
    "As the bulk of the signing frenzy has settled, groups of students have retired with friends to sit in blobs on the bleachers, and so do we."
    "Tanya and I trade yearbooks, then both flip to an open page and look down toward it. Her pen clicks after only a short delay, but my pink glitter gel never gets closer than a hair's breadth from the paper."
    C "(It's hard enough to summarize everything that's happened between me and Tanya in the time I've known her, let alone knowing that this'll be the all-time {b}permanent record{/b} of this moment.)"
    "I search for some inspiration in glancing above the edge of the yearbook at Tanya. Her head is down, hand sliding back and forth across the page of my yearbook in the midst of writing."
    C "(Come {b}on{/b}, Clover! Tanya's already, like, a whole paragraph in and you haven't written a single word!)"
    "A small victory comes in writing down one word to start off with. \"Tanya\"."
    C "(It's a start!)"
    "My inspiration ends there, while I spy Tanya's deep brown eyes still trailing back and forth across my own yearbook with each line. Her sleek black hair falls down across her face in such a way that she has to pause to swipe it back over her ear."
    C "(It's not fair! I can't put everything I'm feeling into words! I can't even take my eyes off of Tanya long enough to start!)"
    T "And... done! Almost finished, Clover?"
    "Tanya's pen clicks closed. Her bright smile weighs on me, knowing that she's managed to do exactly what I'm struggling with."
    C "J-Just a moment..."
    "My eyes scan over Tanya's name glittering in pink where I wrote it. In the moment, I reach for the right words to symbolize all the days we've spent quarreling, flirting, and pushing one another forward together."
    "\"Tanya,\""
    "\"I love you.\""
    C "Here."
    "I pass the yearbook back with subtly trembling hands that I pray she cannot see, and receive my own in return."
    T "Are we... going to read them now?"
    C "If you want..."
    "A sigh forms in my chest as a physical manifestation of my half-formed belief that Tanya will surely dump me after failing to write anything good in her book. I crack my own to find her own long message."
    "\"Remember that time we started shoving each other in gym class and you fell on top of me? I thought I was going to die. Not because you were going to kill me, but because I realized just how much I liked you. I like you a whole lot, Clover. So much that I think about you every day.\""
    C "(I got so nervous I couldn't write, and Tanya was so nervous she started word vomiting. Glad I'm not the only one bad at this.)"
    "\"Sometimes I think there's—\""
    T "Clover!"
    C "Huh?"
    "I'm still only just scraping the surface of the rambling love letter Tanya left in my yearbook when I hear her call my name, and look up in just enough time to prepare myself for the force of her arms thrown around me, yearbook still in her hand."
    C "Don't crush me with your gorilla arms!"
    T "I love you too, Clover."
    "The flutter of Tanya's black obsidian hair tickles my neck, but even that cannot compare to how much her words tickle at my heart."
    C "(Seems like she enjoyed what I wrote in her yearbook. I win this one, Tanya!)"
    "The display of affection draws the attention of several students nearby us, but it's only when our lips press together that a chorus of \"ooh\"s erupt. Even Sibyl joins in with the crowd."
    "Under normal circumstances, I feel like I'd want to die, but this is no normal circumstance."
    C "(Let them watch.)"
    jump endcard

label endcard:
    stop music fadeout 0.5
    scene bg black with fade
    scene bg endcard with fade
    pause 3.0
    scene bg black with fade
    jump epilogue

label epilogue:
    scene bg path with dissolve
    T "If you don't exercise over the break, you're going to get fat."
    C "Wow, that's so {b}rude{/b}."
    "Tanya earns a push of my palm against her forehead for that remark — delivered with my left hand as my right is still held securely in her left. I let her off easy because I know it's true."
    C "I think I've eaten enough yogurt parfaits for a lifetime. I deserve a break."
    T "You didn't {b}have{/b} to eat them everyday just because I did."
    C "{b}Now{/b} you tell me!?"
    "We've already seen Sibyl off, so now it's just me, Tanya, and my big duffel at the end of the academy drive waiting for my ride to show."
    "The heat of summer bears down heavily on us even in the shade of the tall trees lining the long drive, but neither of us finds any urgency to separate our sweaty hands until the very moment my rideshare driver pulls up."
    "I shove my duffel in the trunk with a great deal of difficulty, then turn back to Tanya waiting nearby for just one more kiss."
    T "See you soon, Clover."
    C "See you soon, Tanya."
    scene bg black with fade
    "The leafy trees surrounding the academy blur together as they zoom past the windows from the back seat of my rideshare vehicle."
    "Whether a trick of the light or the heart, the lush foliage already seems to be fading from their verdant tones into the blazing hues of Autumn."
    pause 3.0
    jump end


