label lacrosse_anew:
    scene bg gym with dissolve
    "With my name written in bold pink letters across my back and the crosse held confidently in my hands, I envision myself as a brand new woman ready to tackle any obstacle in her path."
    C "({b}Goodbye{/b} creepy goth, angsty bitch, and love-struck loser Clover; nice to meet you, fun and sporty athlete Clover!)"
    "I haven't felt this clear-minded and energized in months, or maybe even years. I've put all the darkness both literally and metaphorical in my past, and now finally also moved out of Sibyl's shadow."
    C "(I was way too distracted for my first few weeks of lacrosse practice, but today I will kick it into high gear!)"
    "Saturday morning practice starts with a paired warm up passing exercise. Overhand, underhand, even sidearm — I do them all, and well enough that Miss Woolsey is impressed by my speed in picking up the technique too."
    "After warmup we split to play shifts of {i}sixes{/i}, a type of lacrosse where two teams of five \"runners\", who play both offense and defense, and a goaltender face off in a fast-paced, non-stop lacrosse match."
    "While I wait my turn to run to play as one of the runners, I focus my energies on practicing my {i}cradle{/i} technique."
    "By moving the crosse in a semi-circular motion to produce centrifugal forces, the ball can be kept securely in the crosse even at an elevated position."
    "It's an essential skill which has been something of an issue for me in past practices, so starting today it's one of my highest priorities to get right."
    mw "Priya, swap out; Clover, you're in!"
    "Miss Woolsey calls out my name as part of substitutions for the next sixes match, giving me the perfect opportunity to put my new and improved skills to the test."
    C "Yes, ma'am!"
    "Full of confidence, I place myself forward to take the draw and hopefully win the ball to start my team off with possession."
    "As I line up with my stick crossed at waist level before me, I narrow my focus on what actions I'm going to take to sweep the ball to my teammates."
    "Nothing else matters in all the world but winning that little yellow rubber ball... until my opponent arrives to place her stick right up against mine."
    T "You're going down, Clover."
    C "(She—! She's {b}trash talking{/b} me!)"
    C "Shut your fat mouth, you... fattie!"
    T "Is that the best you've got?"
    "The coolness of Tanya's reply, and particularly the cavernous depths of smugness present on her face as she says it, really ruffles my feathers."
    "My trash talking doesn't hold a candle and I know it, but try again I must lest Tanya take away this exchange as a victory of her own."
    C "(I have to really make this one count!)"
    show choice_darkness with dissolve
    menu:
        "\"I'm going to launch that ball so hard up your butt that it comes out your mouth.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the lacrosse ball between us."
            C "I'm going to launch that ball so hard up your butt that it comes out your mouth."
        "\"When I'm through with you, you'll be using your stick for crutches.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the lacrosse stick held firmly in my hands."
            C "When I'm through with you, you'll be using your lacrosse stick for crutches."
        "\"You're going to be hanging up your jersey for good after this match is through.\"":
            hide choice_darkness with dissolve
            "My mind racing to come up with something tough and punchy in a split second, I land finally on the matching uniforms on our backs."
            C "You're going to be hanging up your jersey for good after this match is through."
    "I catch a glimpse of Miss Woolsey coming over to drop the ball and start the match so I am forced to hiss my rude reply out quietly between my teeth. Tanya only grins at the abuse."
    T "You've already lost, Clover."
    C "Huh—?"
    "The ball drops in front of us and I'm way late to the snap given my preoccupations with Tanya taking precedence over watching Miss Woolsey. Tanya wins the draw and lobs the ball her side with barely any challenge."
    C "(I played right into her head games, that bitch!)"
    "In the next millisecond after Tanya receives the ball from her teammate, I run right up to get in her face. She tries to juke to the side to pass to her teammate but I read the scoundrel's intentions clearly enough."
    "With a quick flick of my stick against hers, my first ever stick check works wonderfully in popping the ball right out of her crosse pocket and away to be scooped up by my teammate."
    mw "Great check, Clover!"
    "Miss Woolsey calls aloud to join the praises in my head for this wonderful work of stick craft, and my teammate subsequently scores the first point of the match to top it all off."
    C "(Take {b}that{/b}, Tanya!)"
    "I trot right on over to her to gloat in the few second it takes for the goaltender to fetch the ball and throw it back into play, but when I face her she isn't visibly upset in the slightest."
    T "Nice take away, Clover."
    C "Uhh... thanks."
    "The interaction leaves me deflated and confused as play resumes once again. I try not to let her behavior get to me any further and keep the obtrusive thoughts at bay, but they remain there in the back of my mind nevertheless."
    C "(Was Tanya actually paying me a compliment... or is this some new kind of psychological torture?)"
    "Once the half time break arrives, I march right over to Tanya with an aim to get her to tell me exactly what she's up to this time."
    C "What's your problem, Tanya?"
    "I catch Tanya taking a big gulp out of her water bottle but I know she hears me because I can see her eyes glance my way. Still, she takes her time hydrating before acknowledging me further."
    T "If you're asking why I scored two goals while you scored none, that's just because I'm a better athlete than you."
    "If I weren't also tired from all the activity on the field of play and at the moment using my stick as a crutch to rest my weary legs, I might have just smacked her over the head with it then and there."
    C "That's {b}exactly{/b} the kind of crap I'm talking about."
    "As nonchalant as ever, Tanya swipes the sweat off her brow with her body turned slightly away from me before responding once again."
    T "Better that you learn not to let your opponent take you off your game now rather than when we're playing against one of our rivals. The girls at Snipatuit High are particularly nasty."
    T "We're both Wild Roses, Clover. It's in the best interest of the team that you are playing at your best before Spring season starts."
    "I cannot deny that her little trick {b}did{/b} teach me a lesson about maintaining focus, and my vexation at her behavior {b}did{/b} make me play better as a result."
    C "So what you're saying is that all of that talk was just to make me perform better in the game?"
    T "That, and I'm still pissed about what you did to Sibyl."
    C "(There we go. {b}That's{/b} what I expected to hear.)"
    "I'm not surprised, exactly, and nor do I blame her. Privately, without ever speaking the ghastly words aloud, do I admit that Tanya was right when she warned me in advance to give up on Sibyl."
    C "(But Hell itself will freeze over before I give her the opportunity to say \"told you so\".)"
    T "Oh, and before I forget, \"I told you so\" about Sibyl. There's absolutely no way any girl would change her preferences, least of all {b}you{/b}."
    C "O-Oh— Oh, {b}yeah{/b}!?"
    "I thought I was being remarkably conciliatory in not blowing up at Tanya after everything she's done today, but this I will not endure any longer."
    C "Well, I have some news for you, Tanya. Sibyl and I {b}kissed{/b}."
    "I wasn't planning to ever tell Tanya for fear that she really does murder me one day, but she's practically asking me to throw this into her face right now, so I do."
    T "You're going to have to try better than that, Clover. "
    "The revelation I spit out at Tanya fails to land entirely. She's more interested in Miss Woolsey instructing one of our goaltenders on the other side of the gymnasium."
    C "I'm not lying. I asked her for it — for one kiss in exchange for me giving up forever — and she {b}agreed{/b}."
    C "We kissed, it was {b}amazing{/b}, and you'll never {b}ever{/b} get to know the feeling of Sibyl's lips like I do."
    "It's with a great deal of satisfaction that I spot Tanya's indifferent facade start to crumble in the face of my taunts. Her gaze edges back my way despite her attempt to appear unaffected."
    T "Sibyl is straight, a fact I know painfully well, and she doesn't like you that way. She'd never let you kiss her."
    C "You're right, I didn't kiss her. {b}She{/b} kissed {b}me{/b}."
    "I feel so delightfully devilish rubbing my kiss into Tanya's face after she's been acting so high and mighty all of practice."
    "Maybe it's the unshakeable smirk plastered on my face, or perhaps it's that Tanya knows Sibyl is too kind for her own good, but something really shakes her confidence to my benefit."
    T "Y-You're lying! She'd {b}never{/b}!"
    C "Well she {b}did{/b} so... yeah."
    "Now it's my turn to turn away slightly like I don't even care about Tanya silently fretting over my shocking admission. I still keep her in my peripheral vision just in case."
    mw "Two minutes to draw, everyone!"
    "Miss Woolsey ensures I have the last word in this particular confrontation by announcing the imminent start of the second half of the match."
    "The second half of our match is exactly the opposite of the first. While I am on top of my game, there's no doubt that Tanya is slipping."
    "When Tanya manages to snag the ball in their end of the field of play, she charges right up the field toward our goal on the attack. I fall back to help defend the goal but find her attention not on it at all, and rather locked onto me."
    T "Hrahh!"
    "All of Tanya's strength goes into the throw, launching the ball probably close to the speed of sound right between my eyes."
    C "(Oh shit)!"
    "I manage to evade the heavy lob entirely on survival instinct alone. I even manage to bounce it off my stick into the pocket of my nearby teammate, though that is entirely by lucky happenstance."
    mw "Nice block, Clover!"
    C "(It's nice and all to hear Miss Woolsey compliment my playing, but it how did she miss Tanya whipping that ball at my face?)"
    "Logically, I know that she didn't have the benefit of having locked eyes with Tanya's evil stare as she slapped the ball my way, but it still would have been nice to be acknowledged as the victim here."
    scene bg hallway with fade
    S "{b}Now{/b} what happened?"
    "When Sibyl comes to pick me and Tanya up after practice, she finds us both standing alone on opposites sides of the hallway outside the locker room."
    "More than be angry, she merely looks disheartened that her two best friends are once again on the outs with another over something she cannot possibly know or understand."
    C "Nothing's wrong. Tanya's just being a sourpuss."
    T "I {b}am not{/b}."
    S "Clover, no antagonizing her!"
    C "She started it!"
    S "Tanya?"
    "Sibyl looks right back to Tanya for her defense, and though she looks like she wants to protest my statement, she surely knows it to be accurate and stays silent."
    T "Whatever, let's go get lunch. I'm {b}starving."
    "As for the suggestion that we leave as soon as possible so that I can stuff my face all the more promptly, I have no objections. The three of us wander off toward the cafeteria with Sibyl in the middle."
    jump saturdaywithsibyl

label saturdaywithsibyl:
    