label easter:
    scene bg black with fade
    scene bg bedroom with dissolve
    "The excitement of homecoming swiftly fades into the doldrums of passing the week-long Easter break when most students have left for home."
    S "Tanya! Gimme your threes!"
    T "Go fish."
    S "Aww..."
    "Sibyl surprised me on Sunday by attending services in the academy's chapel."
    "She told me after that she isn't religious, but that the foster family she has been with for the past few years used to take her and her foster sibling every Christmas and Easter."
    C "(She probably just went because there's nothing {b}else{/b} to do with everyone else away.)"
    "All student activities are on hold, both classes and extra-curriculars. Even the cafeteria is operating with a depressingly limited menu."
    "Sibyl and Tanya both also have chosen to stay behind, leaving the three of us to scrape the bottom of the barrel of activities to entertain us."
    T "I'll take your tens, Sibyl."
    S "Here you go!"
    "I've always gotten the impression that Sibyl genuinely likes her foster family, so why she hasn't chosen to return home is a bit of a mystery to me."
    "As the game drags on well into the afternoon, I try to think up ways I can subtly ask her about it in a manner that won't sound like I'm prying into her personal business."
    S "Clover, it's your turn."
    C "Huh? Oh, umm, Sibyl, have any nines?"
    S "Tanya {b}just{/b} took them from me. Are you feeling alright, Clover?"
    "Realizing that I must be zoning out further than I think I am, I confess to being bored with Go Fish and propose just ending the game altogether."
    "The other two accept so quickly that I almost feel like they must have been thinking of ending the game too. All three of us flop down on the bed with exaggerated malaise."
    T "I'm so glad you're staying for Easter break, Sibyl. Are you sure your foster family won't mind?"
    "After thinking how best to ask such a personal question to Sibyl, Tanya suddenly outright asks the very same thing I was wondering."
    S "It's only a week, and after seeing how stir-crazy you were after our Christmas break I couldn't do that to you again."
    "It's clear from Tanya's expression that she doesn't like this answer, and Sibyl is quick to alleviate her concerns posthaste."
    S "Really, I wanted to stay! The whole reason I applied for this scholarship is to experience all the ups and downs of living out on my own."
    T "Okay, but why is Clover still here? I thought she was finally getting along with her parents again?"
    "That Tanya asks Sibyl instead of me gets on my nerves, so despite how I don't really care to share my personal life with her, now I feel obligated."
    C "I also {b}chose{/b} to stay here this week, Tanya."
    "I've told Sibyl all about what happened with my parents' divorce, but given Tanya's dated knowledge of my situation I assume that my roommate hasn't been talking behind my back."
    "Tanya must have realized {b}something{/b} was wrong when I suddenly fell apart right before the tryouts, but she usually has enough tact not to shove her face where it doesn't belong."
    C "For your information, my parents' divorce was finalized a few weeks ago. I've accepted that it happened but that doesn't mean I'm prepared to go back to whatever will be \"home\" from now on."
    T "That sounds like you're avoiding your parents to me."
    C "Well I didn't {b}ask{/b} your opinion, did I? Why are {b}you{/b} still here?"
    T "Did you really expect me to fly all the way to Singapore and back again over a one week break?"
    C "Singa-{b}what{/b}? I thought you were Chinese?"
    T "I {b}am{/b} Chinese, but my parents and siblings all live in Singapore."
    T "We used to go back and forth living between here and there when I was little. Ever since my older brother's wife had their baby, however, everyone else in my family has remained there."
    C "Why?"
    T "Look, Clover, family as a concept is entirely different in Asia than it is here. It's better for everyone that I stay in America."
    "It's obvious that the topic is more than a little touchy for Tanya so i drop it altogether. There's no sense in aggravating Tanya, especially when Sibyl is around to tell us off."
    scene bg black with dissolve
    scene bg library with dissolve
    "After lunch we head to the library as our next means of passing the time away."
    "Sibyl gets lost in her {i}Girls' Mix{/i} back issues while I opt to flip casually through an {i}Archaeology Insights{/i} article issue about the Sumerian priestess Enheduanna."
    C "(She really liked this \"Inanna\" person, huh?)"
    "A flutter in my peripheral vision from across the table draws my attention away. It's Tanya holding her {i}Sports Annotated{/i} issue open longways from top to bottom."
    C "What are you doing to that magazine?"
    T "Nothing!"
    "Tanya quickly stammers and turns it the right way to flip to the next page, which only makes her actions all the more suspicious."
    C "Gimme that."
    T "Hey!"
    "I snatch the magazine from her hands. The cover features some woman in a bathing suit at the beach."
    C "(Maybe there's an article about surfing?)"
    "I flip through all the pages to find whatever might cause Tanya to hold it so awkwardly, and find the center pages of the magazine fit the orientation."
    C "Hmm..."
    "I first cant my head sideways, then turn the hole magazine around like Tanya did before."
    C "(I wonder if she likes blondes?)"
    "It's no surfing article but a head to toe photograph of a blonde-haired model in a bikini that made Tanya flip the whole magazine around."
    C "(No, I don't think this is surfing related at all. Or any sport for that matter.)"
    "The model is pretty, sure, but way too made up for the photoshoot in my opinion."
    S "What's up? Is there a good article in that issue?"
    C "Uh, just some new lacrosse stick models. You probably wouldn't be interested, Sibyl."
    "I quickly toss the magazine back at Tanya and earn a quiet glare, though she predictably catches it before impact."
    C "Speaking of lacrosse, when are the practices starting up again?"
    T "The first Tuesday after everyone returns from Easter break."
    S "I'm so glad that you're going to continue playing lacrosse, Clover. I just {b}know{/b} you're going to do great!"
    C "That's the plan! I can't let Tanya hog all the glory in the midfield."
    T "Maybe if you didn't gorge yourself on French toast every morning you could keep up!"
    C "I {b}told{/b} you that I need that sugar energy!"
    T "You really don't."
    C "Maybe {b}you{/b} don't!"
    S "Let's go find a book about sports nutrition, Clover! There's sure to be one around here somewhere."
    "I know that Sibyl is only trying to cut off a bigger conflict between me and Tanya before it starts but I don't hesitate to take her up on the offer."
    "Unfortunately, when we do find the book and pore through the impressively dense text, Tanya doesn't hesitate to gloat about her being right in the end."
    "Tanya thinks she has all the answers about keeping up with her athletics, and admittedly, the results are impressive. That leaves me with only one choice."
    scene bg black with dissolve
    scene bg lacrosse with dissolve
    T "What are you {b}doing{/b} here, Clover?"
    "Against my better judgement, I manage to drag myself out of the sweet caress of sleep early the next morning to ambush Tanya before she goes out on her daily run."
    C "Training. Since you have {b}all{/b} the answers, I'm gong to do everything you do."
    T "What? No!"
    C "Are you afraid that I'm going to get better than you?"
    T "{b}No{/b}, that's not going to happen. I just don't want you bothering me while I'm in the zone."
    C "Then you'd better start taking laps in your room if you don't want me around. Besides, won't the {b}team{/b} play better if {b}I{/b} play better?"
    "I make a big show of warming up to run, which coupled with my flawless arguments immediately changes Tanya's tine without any more need for discussion."
    T "Fine. It's a big field and there's plenty of room for both of us. Besides, you won't be able to keep up with me anyway."
    C "Oh yeah? We'll see about that!"
    "When Tanya starts off, I kick it into high gear to keep up to pace with her. Though she has no music in her ears or anything, she remains focused straight ahead without ever getting distracted."
    C "(Is she counting steps in her head? How does she stay so {b}focused{/b}?)"
    "I fight on valiantly, but by the time I'm huffing and puffing with each step, Tanya's still as cool and composed as when she started."
    "Tanya cleanly finishes her desired number of laps and proceeds off the field to walk a small loop in place as she checks her pulse."
    C "(Seriously, what is {b}with{/b} her!?)"
    "I make well sure to finish the exact same amount of circuits as Tanya did, just so she can't hold that over my head too."
    "With the last circuit finished, I stagger on shaky legs over to where Tanya rests and flop unceremoniously on my back into the cool grass."
    T "Your warm up was adequate but you need to {b}cool down{/b} after running too. If you don't, your muscles will tighten up and become sore."
    C "Shut up, Tanya!"
    "Despite my nearly-breathless exclamation at Tanya, I manage to scrape myself off the ground and walk a few circles around my running partner before flopping back into the grass."
    T "Here, hydrate."
    C "{b}Urk!{/b}"
    "Tanya responds to my jibe by dropping my water bottle right on top of my stomach, resulting in the rather unpleasant sounding exclamation as it impacts, but no lasting damage."
    scene bg cafeteria with dissolve
    S "I'm so proud of you, Clover!"
    "Sibyl's praise is even sweeter than the maple syrup-drizzled yogurt parfait that I struggle to shovel into my mouth with the last of my remaining energy."
    T "Today was the fastest time ever."
    S "That's great! Just last week you were telling me that you thought your times were stuck in a rut."
    "Neither of us want to admit it for our own selfish reasons, but we both know the only reason Tanya was able to break her record is because I was there to challenge her."
    "After lunch, I fall into a deep food coma and nap so long that I almost miss lunch time were it not for a timely intervention by Sibyl and Tanya."
    jump startintrigue

label startintrigue:
    scene bg transition with fade
    scene bg lacrosse with dissolve
    "I bravely flop out of bed at the crack of dawn the next morning too. Tanya is already waiting for me at the lacrosse field when I arrive."
    T "Good, you're here. I was beginning to think I broke you after pushing too hard yesterday. Warm up and grab a stick."
    "Some manner of grumbling quivers my vocal cords but produces only an unintelligible retort to Tanya's upbeat denigration."
    "The cool morning air and the reinvigorated coursing of blood through my body as a result of my warm-ups eventually returns proper English words to my speech."
    C "What are the lacrosse sticks for? Aren't we going to run laps again?"
    T "I wanted to try something a little more tough now that I have a partner. Think you can keep up with me?"
    C "Quit looking down on me, Tanya. You're no better at anything than I am; you just have a head start on training!"
    "Rather than do simple laps around the field, we both grab a stick and run in parallel up and down the length of the field, tossing and catching the ball to one another as we go."
    C "(I'm not going to let Tanya brag off to Sibyl today! This is the day that I hold my own until {b}Tanya{/b} is the one sobbing into her granola!)"
    "My desired victory ultimately fails to come to fruition, but despite the workout being doubly as intense as the day before, I manage to hold my own all the way until we call it quits."
    C "(This counts as a victory for me, right?)"
    "The twins are waiting on the sidelines to ambush us when we finally finish our jog and pass laps. As we greedily gulp down the contents of our water bottles, the President and Vice President silently circle us in opposite directions."
    "With Tanya clearly just ignoring them, I am forced the be the one who has to speak up to this strange behavior."
    C "Umm... What's happening here?"
    O "We are observing the competition."
    C "Competition?"
    T "Honestly, Clover. If you don't want to play their games, just ignore them."
    "Having been first to strike out at whatever game the twins might be playing, they take the opportunity to pounce around either side of her."
    "Vincenza stops right in front to tug softly at her necktie like something might happen if she does, while her sister Vittoria slides around back to daintily lift the back of her skort - only to realize with a pout that it is indeed a skort."
    T "What are you even doing here? Shoo, shoo."
    "As before, all it takes for Tanya to remove the twins' unwanted incursion is for her to tell them off, though she does reserve a soft flick to the forehead for Vittoria, who probably deserves it."
    O "The Easter break is almost over."
    H "Our flight was moved up at the last moment."
    "I've noticed it too — how many more girls are populating the cafeteria in the past day."
    C "Is this about the whole Homecoming thing? I'm definitely {b}not{/b} entering next you so you have nothing to worry about."
    O "Homecoming?"
    H "Oh, no no no."
    O "We mean, of course, the Student Council."
    # position the sprites moving to give the impression of them closing around C&T
    H "Who else is more suited to supplant us than the enemies from within?"
    O "The stoic ace of the lacrosse team..."
    H "...And her lush flower of a girlfriend?"
    C "{b}G-Girlfriend!?{/b}"
    T "You're both {b}way{/b} off base, as usual. I don't even {b}like{/b} Clover, let alone want to be her girlfriend."
    "Somehow, Tanya's words actually hurt me a little after all that hard training we just completed together. I feel that I must have earned at least {b}some{/b} of her respect, but apparently not."
    C "Y-Yeah, Tanya is the worst. I hate her."
    "I end up throwing what Tanya said about me back at the twins, but really it's more directed at Tanya who started it in the first place."
    H "{b}Tsun—{/b}"
    O "{b}—Dere.{/b}"
    "The twins stare down Tanya directly as they emphasize the first part of their accusatory-sounding words, then turn the spotlight on me for the second half."
    C "H-Hey, don't start speaking Italian!"
    T "You're {b}wrong{/b}!"
    "Tanya whips the equipment bag over her shoulder and storms off without another word, or even waiting for me to follow her back to return the crosse still in my hands."
    C "What was all that about?"
    O "We may have teased her a little too strongly."
    H "Tanya has something of a \"love-hate relationship\" with blondes."
    O "Worry not. We will apologize later."
    C "Let me first make one thing clear; I'm {b}not{/b} worried about Tanya."
    C "What does she have against blondes anyway?"
    O "Has she ever told you about her Vertu partner, Sierra?"
    C "Her Vertu? The girl who is apparently the human incarnation of everything bad in the world according to Tanya?"
    O "Yes, {b}that{/b} Sierra."
    "It is true that Sierra has blonde hair similar to mine, except that my large sample of secondhand knowledge about her indicates that she's way worse of a person than me even on my worst days."
    H "I believe the phrase Tanya used was \"hate-fuck\"."
    C "Like, she hates her, but wants to... you know?"
    H "Well, Sierra {b}is{/b} gorgeous, right?"
    "Rather than ask the question of me, Vittoria looks toward her sister, who nods her agreement."
    C "(It almost seems like they're implying they'd sleep with anyone who is super pretty, but that can't be true because they slept me someone like me.)"
    "A shiver unrelated to the cool early Spring air washes over me, and I try to push what happened that day completely out of my mind again."
    C "Well I'm {b}not{/b} Sierra, so if that's what's behind the {b}problem{/b} Tanya has with me, she can leave the attitude back in her dorm room."
    H "Maybe that enough gossipping for today. We did not come here {b}just{/b} to tease you both."
    O "No, we also wanted to check on you, Clover. You looked exceptionally pale at the homecoming ceremony."
    C "(So I'm just supposed to be okay with the teasing because you ask me how I'm doing after?)"
    C "Don't be concerned about me. I'm fine — never better in fact."
    "The twins before me are very obviously not satisfied with my answer given the way they look toward one another, so in the interest of getting them off my back I throw them a few scraps to nibble on."
    C "I'm not very good with being in the spotlight so Sibyl kinda coerced me and Tanya to go to the dance together and use the homecoming competition as a way for me to face those fears."
    "Rather than express any interest whatsoever in what is an admission of a deeply held fear of mine, Vittoria and Vincenza are somehow more interested in Sibyl's role in the whole affair."
    O "So it was not Tanya who asked you to the dance..."
    H "...But rather our pigtailed mutual friend who orchestrated the whole thing?"
    C "Yeah, that's what I'm saying."
    "Vittoria and Vincenza once more turn quiet to stare deeply into one another's eyes for a solid minute and a half."
    C "(This can't be good.)"
    C "I'm... going to go now. Bye."
    "The trance which came over the twins breaks just as quickly as it started when I announce my departure. Each displays a wide grin which somehow sets me ill at ease despite offering pleasant parting wishes alongside it."
    scene bg locker with dissolve
    "The door to the locker room is still swinging behind Tanya's exit by the time I return my equipment and make it back myself."
    C "(Whatever, I'll shower here if I have the whole place to myself.)"
    "The showers in the locker room are mercifully single stalls, but even so, I've been reluctant to shower here when it's just me and Tanya."
    scene bg cafeteria with dissolve
    "Tanya is already seated when I arrive at breakfast after practice. When I sit down with my own yogurt parfait adjacent from her, she mostly just ignores my presence altogether."
    "Yes, nothing at all is amiss, except that Sibyl has yet to arrive. It is quite unlike her to be late; in fact, she hasn't {b}ever{/b} beaten Tanya to the cafeteria in the whole time I've been at the academy."
    T "Did Sibyl's hair get tangled in her sleep again?"
    C "What?"
    T "The last time Sibyl missed breakfast it was because her hair was a disaster zone that she was struggling to rebuild."
    T "She wouldn't even leave her room until she felt presentable again. It took us {b}hours{/b} to unravel it all."
    "It doesn't at all come as a surprise to find out that Tanya is worrying about Sibyl in the same way I am, but I really wish she didn't have to flaunt how muh more she knows about my Vertu than I do."
    C "I don't know. I showered in the locker room."
    "I try not to look like I'm worried about what happened to Sibyl, and so too does Tanya despite both of us stealthily glancing toward the doorway every so often."
    "When Sibyl finally does show, it's with two girls on either side of her who aren't {b}us{/b} for once."
    "Vittoria and Vincenza flank her on either side, each linking an arm into hers from each flank. Sibyl apparently thinkings it is the most amusing thing ever by how brightly she's smiling."
    "The trio parts gaily at the entryway, the twins splitting off toward the kitchens together and Sibyl stepping toward our usual table in the cafeteria."
    "The pair of me and Tanya glaring her direction must be a sight to behold because her cheerful smile breaks into a surprised start when she spots us shooting daggers between her and the twins from across the room."
    S "Good mornin'! Sorry I'm late; I had an audience with the local royalty this morning."
    C "We saw."
    T "What did they want?"
    "Both of us can scarcely conceal our suspicions behind a neutral tone, but that doesn't stop Sibyl from remaining as cheerful as before."
    S "Book recommendations!"
    "It's not just me and Tanya behaving shifty. Sibyl's answer, despite being delivered in a fast and upbeat fashion, is accompanied by a roll of her away away from either of us."
    C "What did you recommend?"
    S "Anne of Green Gables, of course!"
    T "The library has only one copy, and you recommended it to both of them?"
    S "They do everything else together, so why not read together?"
    "Even with both of us trying to subtly interrogate her, Sibyl gives up nothing at all and quickly switches gears toward our plans for the rest of the day."
    C "What makes it a \"break\" if the teachers assign homework over it?"
    S "No whining, Clover! You have to keep your grades up if you want to stay on the lacrosse team."
    T "What she said."
    S "See? Tanya agrees. That's why she's going to come help you finish it up too."
    T "I didn't say {b}that{/b}! I already finished {b}my{/b} homework three days ago!"
    S "Perfect! That means you'll be well equipped to help Clover with any problems she has working through it!"
    C "But you already finished it too, and you're my Vertu partner!"
    S "Oh, I'll be there alright, but it's you two who need some off-the-field bonding!"
    C "Wasn't homecoming torture enough!?"
    jump truthordare

label truthordare:
    scene bg black with fade
    scene bg bedroom with dissolve
    "Despite having already finished the homework herself, Sibyl insists that Tanya is the one who helps me get through mine. Tanya grumbles about the whole thing but ultimately concedes to Sibyl's plans."
    C "(She has {b}one{/b} weakness and it's not something I can use against her!)"
    "To that end, she pushes both of our desks together so that we can sit side-by-side as we work through the remainder of the problems."
    T "No, no— The {b}nucleolus{/b} isn't the same as th {b}nucleus{/b}."
    C "Then why are they called the same thing!?"
    T "They {b}sound{/b} similar, but they aren't the {b}same{/b}. The nucleolus produces ribosomes and the nucleus contains genetic material."
    C "Then call them the \"ribosomus\" and \"geneticus\" so that it's obvious what they do!"
    T "Clover, do you have any dumb how stupid that sounds?"
    C "It's not \"dumb\", it's {b}logical{/b}."
    T "Yes, it's dumb, and {b}you're{/b} dumb."
    "Every single question goes much the same way, starting with me totally failing to understand a concept and ending with Tanya emphasizing how empty my head is."
    C "I'm not dumb! I'm just not good at science, or math, or English, or etiquette, or art... As a matter of fact, I'll have you know that I am perfectly good with social studies!"
    "My Vertu partner doesn't leave us alone, but neither does she micromanage our study session. She merely sits on the edge of her bed nearby, reading her book between pauses to get us back on track."
    C "(I know Sibyl wants me and Tanya to stop arguing so much, but is this really the way to do it?)"
    "The remaining questions on my science worksheet progress even worse as Tanya chooses to illustrate Punnett squares with the traits \"blonde\" and \"stupidity\"."
    S "Okay, that's enough. Let's take a break, shall we?"
    "I loose a huge sigh of relief and stand to stretch out my limbs, then flop face-first onto my bed."
    S "I had an idea for a game. Would you two like to play?"
    T "What kind of game?"
    S "Truth or Dare."
    C "Huh?"
    C "(That's a game only kids play, right?)"
    T "Fine, I'll play along if it means I can dare Clover to literally eat her homework."
    C "Whoa, hey, I didn't say I was playing!"
    S "Would you play if I let you ask me first?"
    "The offer is a good one, and eagerly do I plan to let the magic of Truth or Dare take away all my worries."
    C "Truth or Dare!"
    S "Dare!"
    C "(Exactly as planned!)"
    C "Sibyl, I dare you to do my homework for me!"
    "With a broad smile, Sibyl makes a grabby hand motion toward me. I pass her the stack of worksheets and my pencil, all for her to only fill in one bubble of a multiple-choice take-home quiz and hand it all back to me."
    C "But I said—!"
    S "I {b}did{/b} do your homework. One question of it."
    C "B-But—!"
    S "Okay, Clover, your turn."
    "Sibyl grabs the mechanical pencil I was using for my science worksheet and spins it on the desk in front of us to determine who gets to order me around."
    "When the pencil finally finished spinning, Tanya immediately glances my direction. Such evil permeates her deep brown eyes that I am forced to turn away nervously as I await whatever terrible fate is about to befall me."
    T "Truth or Dare."
    C "Tr—"
    "It's tempting to want to answer an easy Truth question, but that would only give more ammunition to my rival. My stomach has digested worse things than biology homework before."
    C "Dare."
    T "Eat. It."
    "Like a beast tearing into captured prey, I rip a corner off my science worksheet, chew up the little strip of paper, and swallow it whole."
    C "It's just a little paper. It's not going to kill me."
    "Tanya scoffs at my display of indifference to her dare. She could have asked much worse, I know, and I got off easy when she didn't even dare me to eat the whole thing."
    "The pencil turns around once more, landing this time on Sibyl who claps her hands together before her in delight."
    C "(Wow, who knew Sibyl would be this into Truth or Dare?)"
    S "Truth or Dare, Tanya!"
    T "Dare."
    S "Tanya, I dare you to tell us everything about your family situation."
    T "What? {b}Why{/b}? I've already told you some of it before, haven't I?"
    C "(Isn't that dare kind of a truth in disguise?)"
    S "Because you asked for a dare, it's my turn, and I ordered you to do it."
    C "What's up with Tanya's family? Is she hiding something about them?"
    T "Nothing is \"up\" with them. They're all happily living together in Singapore!"
    S "Yes, but... don't you think Clover would be able to understand you better if she knew about the conflicts you've had in your family life?"
    S "Clover has also had struggles in her relationship to her family, and that's one thing I just can't help her with myself. I think the two of you could help each other."
    "The reasoning for the dare is laid bare, as is probably the entire purpose of playing this game in the first place."
    T "Fine, but only because you ordered me to do it and I want to boss you around too."
    "Gritting her teeth for moment as she no doubt tries to formulate where to start, Tanya chooses to stare down Sibyl rather than look at me while re-telling her tale of family troubles."
    T "Where I come from, family is everything, and everything we do as individuals reflects on the whole family."
    C "Okay, and...?"
    T "When we picked up and moved to Singapore from America, I found I could no longer pursue certain interests of mine publicly. They were \"embarrassing\" the family, and so my parents asked me to stop."
    T "Except there are some things I can't just \"stop\" being, so eventually they sent their embarrassment of a daughter back to America half a world away."
    "She's clearly glossing over something important, but what strikes me is the similarity to my own troubles. Just like I felt like I was abandoned here, so too must Tanya feel like she's abandoned half a world away."
    C "What did they ask you not to do?"
    "Tanya send me a chilling glare when I dig for more information out of her, but it's toward SIbyl that her gaze edges when she goes to answer."
    T "That's personal and totally outside the scope of the dare."
    C "Fine, but why did your family evn move away if they were just going to send you back here anyway?"
    "This question also hits a sore point for Tanya, but surprisingly enough, she answers it anyway."
    T "Because my older brother and his wife work there. When she had their first child, my parents moved there to support them."
    T "I don't think they expected to send me back to America until they realized they had to get rid of their daughter somehow."
    C "(So her parents picked up and moved their whole lives for her brother but dumped Tanya here? How is that fair?)"
    "It's clear from the dark expression on Tanya's face that she doesn't think it's fair at all, and I can't blame her one bit."
    S "Thank you for sharing, Tanya."
    "Tanya grumbles a bit dismissively, as eager to move on as anyone asked to divulge personal history, and spins the pencil herself. The point edges her direction, bringing a small smile back to her face."
    T "Truth or Dare."
    S "Truth."
    "It takes a couple minutes, but eventually Tanya does come out with a question, and a juicy one at that."
    T "Sibyl, did you really, umm..."
    S "What is it?"
    T "...{b}Kiss{/b} Clover?"
    "The air between the three of us goes quite still as no sound but the ticking of Sibyl's clock can be heard. The question is clearly a surprise to her, obviously because that Tanya knows means that it was {b}me{/b} who must have told her."
    "That she quickly turns her head my way upon being asked only confirms it."
    S "Y-Yes, it is true. I kissed Clover."
    T "{b}Why!?{/b}"
    S "I'm sorry, that's something you should ask Clover."
    "As eager to move on from the awkward question as Tanya had been earlier, Sibyl sets the pencil spinning at a fast clip which slows upon herself."
    S "What'll it be, Clover? Truth or Dare?"
    "My stomach sinks immediately. Dread floods in to fill the space it left. I know now that this whole game is a ploy to get me and Tanya to open up to one another about our seemingly similar troubles."
    C "(Based on what she dared of Tanya, I'm probably screwed either way I let this play out.)"
    C "Dare."
    S "I dare you to tell us all about your recent issues with your parents and how they made you feel."
    "The \"dare\" is exactly what I was expecting it to be, which isn't really all that bad because I suspect that Tanya has already gleaned much of it already after months of close-ish proximity."
    C "My parents started fighting a year ago, or maybe more now actually. They've always had their problems before, but this time it just wouldn't go away."
    S "Do you know what trouble started the most recent fighting between them?"
    C "N-No, actually... I never asked..."
    C "(Should I have asked? Would I have been able to fix things before it collapsed this totally?)"
    "I've honestly never thought about it before, but as I do now, I'm all but certain neither my mother nor my father would ever have shared a thing with me."
    C "My parents might have had their issues with one another, but to me I was nothing but their most important only child. It was probably {b}me{/b} that kept them together so long..."
    C "Their most recent fight, before I came here to the academy, was the worst I've ever seen. They tried to hide it around me, but I still knew what was happening."
    C "Eventually it got so bad that they took me out of my old school one day and told me I was coming here instead. At the time I thought it was some kind of punishment or a total abandonment, but now I know they only did it out of love."
    T "Your parents abandoned you... out of love!?"
    "Tanya clearly doesn't understand what I'm talking about, and admittedly maybe it doesn't make as much sense when I say what I feel aloud as when I feel what I do inside."
    C "My parents knew that they were causing me strife with their fighting, and with some other personal struggles I was facing, they thought it was better for me to come here for a time instead."
    C "I'm still not completely over their divorce yet, but I like being here and getting to meet the people I have and experience what I have here has changed me for the better."
    C "If my parents hadn't sent me here, I'd probably be struggling even worse back home. They were right to do it, however betrayed I felt at the time."
    "No questions emerge after I finish speaking. I look up toward Sibyl, who made me say what I did, but she's only looking toward Tanya."
    "Tanya, meanwhile, is busy staring intently at the ground in front of her with a far away look in her eyes."
    C "(What... is happening?)"
    "Not wanting to be the first to slice words into the strangely tense atmosphere, I merely stay quite still until Sibyl does the work for me, quietly speaking up to Tanya."
    S "It's your turn again, Tanya. Truth or Dare."
    "Looking back up, and finding the pencil now pointing toward Sibyl, she sighs heavy and answer dispassionately, \"Truth\"."
    S "Tanya, I want you to tell us truthfully what you feel about Clover."
    C "(She just won't let up on me and Tanya, will she? What does she get out of forcing us to get along.)"
    "\"Other than having her two best friends stop bickering with one another every day\", I add in my mind as the obvious answer."
    T "I feel that Clover is a beautiful idiot with an irritating personality and decent lacrosse skills."
    "The way Tanya replies so instantly and matter-of-factly throws me off guard. Her feelings are very contradictory and I'm not sure whether I should thank her or insult her back, so merely stay awkwardly silent."
    C "A-Anyway, let's spin for you now, Sibyl."
    "I try to brush of the uncomfortable atmosphere surrounding us by keeping the game going and planning what I'm going to ask of Sibyl in my head, but unfortunately the pencil lands on Tanya instead of me."
    S "Dare!"
    T "Sibyl, I dare you to kiss me exactly like you kissed Clover before!"
    S "Okay, get ready!"
    C "H-Huh? Wait, you can't!"
    "Before either me or Tanya can prepare, Sibyl darts forward to plant a little peck against Tanya's cheek in a manner conservative even for a family member."
    T "That's not what I meant! I wanted a kiss like however you did it to Clover!"
    "With the same cheeky grin as before, Sibyl declines to give Tanya back her turn and gets away with another light dare as a result."
    "She sets the pencil spinning for my turn, which comes to a halt pointing at Tanya."
    C "It's really time that I get back to my homework."
    T "You can't just quit on your turn! That has to be against the rules!"
    S "Yeah, you have to say it when it's not your turn or else it's clearly an evasion tactic."
    "I know what Tanya would have found a way to ask of me, but I'm obviously now trying to evade whatever horrors might be spawned out of Tanya's brain."
    C "If I honesty tell Tanya what I think of her, can we end the game now?"
    S "Compromise accepted!"
    T "I didn't agree to this!"
    S "Two against one. The odds have shifted in Clover's favor. Now cough it up, Clover!"
    C "Fine, it's nothing crazy anyway. I think Tanya is a really good lacrosse player — though I'm going to be better than her eventually — who can sometimes be annoyingly clever."
    T "That's just a jumble of insults covered by compliments!"
    C "You did the same thing when Sibyl dares you to say how you feel about me!"
    T "What I said was honestly how I feel though!"
    C "Well what {b}I{/b} said is true too!"
    "Even on something so pointless, Tanya and I immediately rush right into a standoff."
    C "(I know that Sibyl wants us to get along, but surely she sees how pointless this is?)"
    T "Whatever, I'm leaving. Sibyl can help you finish the rest of your homework."
    C "I was only telling her what I thought about her, honestly!"
    "I try to explain myself to the lightly pouting Sibyl across the way, but she only remains pensive about the whole blow-up."
    jump manhuatalk

label manhuatalk:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "I still flop out of bed to meet Tanya at the crack of dawn the next morning despite our little dust up the night before. I'm not going to let a little exchange of words keep me from falling behind her."
    scene bg lockers with dissolve
    "When I step into the locker room, Tanya is still there, leaning up against the row of metal lockers with crossed arms while looking at the ground. As I enter, she looks up to me with an unreadable expression."
    C "You're still here, Tanya? Are you locked out of the equipment room?"
    T "No, I was waiting for you to arrive. There's something I have to do where no one will disturb us."
    "Either Tanya and I are about to re-enact that video I curiously opened on my smartphone while Sibyl was out of the room and quickly closed right after... or more likely, Tanya is about to beat the snot out of me."
    C "W-Wait! I'm sorry, okay!?"
    T "You're sorry?"
    "Speaking faster than I ever have in my life, I spill everything in an attempt to halt Tanya in her path of revenge."
    C "Y-Yeah, I don't think you're actually \"weapons-grade uglonium\" or \"rich in oh-mega fatty ass-ids\"! I was just trying to make Sibyl laugh, so please don't beat me up!"
    T "You said {b}what{/b}!?"
    "The flash of anger that comes to Tanya face is the first sign that she did not at all know about those things I said after she stormed out the day before."
    C "(Oh crap, I'm {b}so{/b} dead.)"
    "Before I can even begin to try to remember those prayers which I haven't recited in years, Tanya has already cooled down much to my surprise."
    T "Fine. I also don't truly think you \"have a mutation in your twenty-fourth chromosome pair\", nor that your intelligence is \"asymptotically approaching zero\"."
    C "Hey, I'm not {b}that{/b} dumb!"
    "I truly don't know what Tanya means about either description, but I know they're insults and I'm not happy about it regardless of whether I understand them or not."
    T "In fact, I actually... wanted to thank you—"
    C "So you're {b}not{/b} going to murder me?"
    T "What? No! Why would I murder you?"
    C "Because you've told me you're going to murder me a bunch of times before, and now you have me alone in the empty locker room early in the morning where no one will hear it or even find out for hours."
    T "You're {b}such{/b} an idiot, Clover. And to think I was going to say you might have some brain cells yet clinging to life in your empty skull after all!"
    C "You could say it nicer than that, you know!"
    T "I was {b}going{/b} to, but not anymore! I'm not going to hurt you, just... shut up and let me talk."
    "Tanya gives a short huff, fluffs her fingers through her bangs, and resumes staring at the point in which the lockers meet the floor in front of her. It's like whatever she's trying to say is teh most difficult thing in the world."
    T "Sibyl can be kind of a ditz sometimes, but she can also be a tricky schemer when she wants to be."
    C "(Don't I know that!)"
    T "I thought she was trying to help {b}you{/b} by making me tell you about what happened before I enrolled here, but then she made you talk about what you went through too."
    T "I just can't believe it took {b}you{/b} telling me how you resolved your own personal problems for me to resolve {b}mine{/b}!"
    "Tanya doesn't shout, but the calm manner in which she speaks belies the obvious frustration stirring behind her straight black locks of hair."
    C "I have no idea what you're talking about, Tanya!"
    C "(What is she even saying and why is she trying to tell me about whatever this is!?)"
    T "What I'm trying to tell you is that you were {b}right{/b}."
    C "Of course I was right, but about what?"
    T "God, do you {b}ever{/b} quit it?"
    T "I mean about why I was sent back to America when the rest of my family all moved to Singapore with my older brother."
    T "It's not because I was an embarrassment that had to be excised from the family, but because I can genuinely live the life I want here when I couldn't over there."
    "Now relatively confident that Tanya isn't going to break my skull open with a crosse, I take a seat on the bench running through the aisle of lockers."
    C "What were you even doing after moving back to China that started this in the first place? You were being awfully coy about that during the game."
    T "I suspect she knows already, but... I still haven't told Sibyl that I'm gay, or that I had a huge crush on her."
    C "So?"
    T "So, it was because of what I am that caused all the problems in the first place!"
    C "Is it, like, {b}illegal{/b} to be gay in China or something?"
    T "Well, no, but it can be, umm... stigmatized. It doesn't help that I was a cringey middle-schooler self-publishing cringey lesbian manhua either, but that was the only way I knew how to express myself."
    C "What's a \"manhua\"?"
    "Tanya finally looks up at me, blinking with a dumfounded expression on her face like I asked the most stupid question in the world."
    "I fully expect to be told some analogy relating how incredibly stupid I am for not knowing something so obvious, but instead she actually just tells me for once."
    T "Do you know what manga is?"
    "I nod my understanding to the question, and to my credit start to put the pieces together before she finally concludes the thought."
    T "It's like that, but Chinese. I was only self-publishing on the internet, but even then everything had to be censored."
    C "You were drawing porn? I mean, I kinda get why it was embarrassing then."
    "My reply is entirely sympathetic to Tanya's plight, having done enough cringey stuff back in middle school to make me want to jump off the nearest cliff right now."
    T "It was {b}not{/b} porn. There wasn't any sex, even implied, most of the time!"
    C "\"Most of the time\"?"
    T "You don't really understand, Clover; I couldn't even show my characters {b}kissing{/b}. Two girls merely expressing their love is \"deviant behavior\" according to the law!"
    C "Wow, that's seriously crazy!"
    "Middle school me used to be proud of being a \"deviant\", but in truth I never actually was anything more than just another weird goth kid."
    C "(While I was merely playing at being a deviant, Tanya was sincerely forced into the role by everyone around her.)"
    "This sort of terrible secret that Tanya is suddenly sharing with me would under normal circumstances be something I can use to pick on her mercilessly, but I just couldn't bring myself to be so cruel like that after everything she's told me."
    C "(Speaking of which...)"
    C "Why are you telling me all this anyway, Tanya?"
    T "Because I need to tell {b}someone{/b}. Because I thought you'd understand me better than anyone else."
    "It makes perfect sense not to divulge all these secrets to Sibyl when she has not officially come out to her yet, but I know that she's friends with the twins too, and I have first-hand knowledge of how much they also like girls."
    C "(But I guess she's right in that they wouldn't understand at all. Everything is a joke or play to them.)"
    C "I definitely know—"
    T "Phew! I feel so like in my chest. You're going to have to run extra hard today if you don't want to choke on all my dust. Don't keep me waiting."
    "My emotional sensors get whiplash from the sudden change in tone that Tanya gives off. Just a moment before she was all serious, and now she's just about back to normal herself, half way out of the locker room."
    C "H-Hey, wait, you can't just say and that and—"
    "The door is already slammed shut behind Tanya before I can even tell her off for rudely dumping her emotions on me then running off just like that."
    "Half of me suspects she's doing it on purpose to salvage some of her pride, but the other half of me wants to make her eat what remains of her tough girl act and so I change at the speed of light into my uniform before she gets too far head on the track."
    jump homeroom_queens

label homeroom_queens:
    scene bg cafeteria with dissolve
    "After running so hard in front of me on the track that I literally get the taste of the soft Spring earth in my mouth, I'm totally exhausted by the time we meet Sibyl in the cafeteria for breakfast."
    "Nothing much is said as I shovel down a whole plate of French toast as a reward, after what feels like a millennium of eating only yogurt parfaits for breakfast."
    scene bg classroom with dissolve
    "Even the saccharine embrace of fluffy French toast cannot replenish my energy enough to face the trials that soon await in homeroom, the first day back from break and after the surprise win of the homecoming court."
    st "Did you play lacrosse in your last school too?"
    T "I never picked up a crosse until the day of the academy club faire."
    "Most of the classroom surrounds the three of us before we can even get to our seats."
    "As the new school celebrities, we're now of sudden and intense interest. Sibyl whispers to me that there were even people looking our way at breakfast."
    C "U-Umm... This is my first year playing too."
    "The weight of all my classmates' attention weight heavily on me such that I try to step back in the cover of Sibyl's body, but she pushes me right back up to where Tanya composedly answers the questions."
    S "Tanya and Clovers' lacrosse skills are a testament to the power of hard work! The train every morning together!"
    "Sibyl's doesn't give me a single break, only egging the onlookers to 'ooh' and 'aah' at what she says with ever more enthusiastic interest in the new homecoming queens."
    "Without Sibyl beside me, I grip against Tanya's arm for support just like when I was on stage."
    st "The sports clubs do have a crazy practice schedule, don't they?"
    st "It's no wonder they're so close!"
    st "Are there any other couples on the lacrosse team?"
    T "Clover and I aren't a couple. We're just teammates."
    st "You don't want your feelings to get in the way of your games? That's so smart!"
    st "So you're starting as friends for now?"
    C "We're not— I don't think we're even {b}friends{/b}..."
    st "But what about the homecoming court?"
    st "And look how closely Clover is holding onto Tanya!"
    "{b}Very swiftly{/b} do I release Tanya's arm. There's no way I'm going to give anyone {b}that{/b} impression."
    "Desperately, I glance slightly back for Sibyl, but find she's entirely gone missing and left me to fend for myself."
    st "It's rude to push them to talk about their private lives. When they want to tell us, they will!"
    st "Okay, {b}Mom{/b}."
    C "(There's nothing to {b}tell{/b}!)"
    st "Your hair is so silky, Clover! What do you do to it?"
    "I'm glad that the topic of my non-existent relationship to Tanya is over, but the sudden interest in my hair and the way everyone decides to just reach out to touch it doesn't make me any more at ease."
    C "Gentle shampoos and conditioners, moisturizing hair oils, and... can you please stop touching my hair!?"
    "Even Tanya joins in to caress a lock of my hair not taken by any of the other girls, which prompts me to shift away suddenly, and stumble against a nearby desk in the process."
    C "Ow..."
    st "Sorry, it's just kind of mesmerizing, isn't it?"
    st "It's almost as shiny as Vittoria's hair!"
    st "Vincenza's hair is prettier than Vittoria's though."
    "Sweet relief washes over me when the topic at had suddenly devolves into an argument between the factions of Vittoria and Vincenza, mercifully leaves me and tanya to sneak back to our seats moments before the homeroom teacher arrives."
    T "Just ignore them. They'll find anything at all to gossip about."
    "I glance back toward Tanya, but she isn't even looking way way. Her attention lies at nothing in particular across the room while a hand brushes through her own shining black strands idly."
    C "I'm not bothered at all. I'm cool as a cucumber!"
    T "So why does my arm still sting so much?"
    "On my way to find my seat, I find Sibyl already at hers with pencils and classwork neatly arranged on her desk. She gives me a bright smile in passing which feels almost cheeky considering how she ditched me alone with Tanya."
    jump beforestormpractice

label beforestormpractice:
    scene bg transition with fade
    scene bg lacrosse with dissolve
    "The return of classes also means the return of our regular lacrosse season practices and matches."
    "Something else that also returns is the girl whose place I had been the substitute starter for while she was away. Being a practice match, we all play, but I'm still taking turns with other girls too."
    C "(Why is it still so cold out? We're a whole month into Spring already!)"
    "It's our first practice match since the whole homecoming debacle, and though I find myself \"benchwarming\" at the moment, it is anything {b}but{/b} in reality."
    "Being still the month of April, but barely, the dying grasp of Winter hasn't fully relinquished control."
    C "(I really shouldn't have shaved this morning! No one is even looking at me on the sidelines anyway.)"
    "That the skort of the team uniform exposes so much of my legs must be a great boon when full of activity in the height of summer, but not so much while I'm sitting on the sidelines in the crisp weather."
    "With how light and fine my hair is, it's practically invisible unless I'm standing in direct sunlight. If I were out on the field it might be noticeable, but not while I'm sitting out of the game."
    "As I sit there and rub my thighs together like I'm starting a fire with two sticks, I know that I were out there moving my body while playing the game I would be totally fine."
    C "(Tanya has it so good. I hate her.)"
    "The thoughts which come to mind are empty envy and I know it, but it still makes me feel a little better about myself regardless."
    "Not only is she out there on the field warming her body with activity, but just about every spectator is there for {b}her{/b}. The millisecond that she touches the ball, whoops and cheers start to sound from all sides."
    C "(So she had {b}one{/b} good game, and maybe won the homecoming queen title too? So what! {b}I'm{/b} homecoming queen too, and I'm still stuck here on the sidelines!)"
    "The worst part of it all is simply how much {b}fun{/b} Tanya looks to be having out there. She doesn't even seem to notice the crowd's adulation at all while she's out there powering through the midfield."
    "My eyes stick like glue to her more than anyone else out on the field. Not only isn't she cold, but she's even catching the angled light of the sun in a sheen of sweat covering her smooth, hairless legs."
    C "(Also she's Asian so she probably doesn't even have to shave at all!)"
    "It's all just another reason for my gaze to be glued to her thick thighs bounding from line to line. I used to think they were fat and flabby, but after seeing her run so much there's no doubt that they are actually firm with muscle."
    "Each bounding step ripples with the force of the Earth pushing back up at her, and every twist in place illuminates each muscle flexed with the slanted light of waning day."
    "It's all just so unfair."
    scene bg lockers with fade
    "Not everyone on the team, it would seem, enjoys how much attention the star freshman midfielders is getting."
    "At practice earlier in the week, Tanya suffered a few snubs from teammates during the practice match, and then some a rough brush from the side unexpectedly when she was putting her equipment back."
    "In the locker room today, the tension is thick when the whispered slights are few and glances many."
    C "(If this keeps up much longer, Tanya's going to have some real enemies. Besides me, of course.)"
    "I, for one, don't count myself among the few who give Tanya the cold shoulder about her sudden fame. As envious as I might feel, I also know that so much attention is the last thing I want."
    C "(Tanya isn't even playing into the attention at all. She's entirely ignoring it! It's not fair to blame her for other people taking it too far.)"
    "Though she looks as calm and collected as always, it's telling that she has already changed and left the door to the locker room swinging behind her before the rest of us have even half finished."
    scene bg cafeteria with fade
    "I expect to find Tanya already sitting alongside Sibyl in the cafeteria by the time I am finished in the locker room, but much to my surprise she is entirely absent."
    "When I ask Sibyl where Tanya is, she informs me that she was about to ask me the same."
    S "Maybe she forgot something in her room?"
    C "Yeah, maybe..."
    "My delightful Vertu partners smiles her brightest but concern is clearly present in her eyes. My uncertain tone definitely isn't doing anything to alleviate her worries."
    S "The preview for the latest {i}Sylvia Valemont{/i} novel was released today."
    C "What's the new one about?"
    S "The conductor aboard a luxury transcontinental train mysteriously vanishes, and Sylvia must find out what happened to him before the locomotive steams to its terminal stop."
    C "So it's a thriller, not just a mystery?"
    "Sibyl describes every little detail that the author gave away over the course of her short interview while I finish up my plate of shrimp and sausage jambalaya."
    "Then she continues right along comparing the previous novels even after I lick clean the spoon I used to eat my bananas foster, without ever moving an inch."
    "I allow Sibyl to keep chattering mindlessly about {i}Sylvia Valemont{/i} right up to when the kitchen staff comes to gently shoo the last two students out of the deserted cafeteria."
    C "She's not coming, Sibyl. We need to let the kitchen staff clean up before it gets too late."
    S "Yes, you're right..."
    scene bg mary night with dissolve
    "Sibyl is quiet most of the trip through the school building and out onto campus grounds between buildings, only finally opening up once again when the Springtime pollen in the air makes me sneeze hard enough to expel my brains through my nose."
    S "Bless you."
    C "Thanks."
    "My always-prepared Vertu picks out some facial tissues from her bag to offer me. As I attempt to expel the offending pollen from my nose, Sibyl hits me with a sudden admission."
    S "We found Tanya's sculpture smashed to pieces in art club yesterday."
    C "Was it an accident?"
    "I instinctively try to ask in such a way that implies it could have been an accident, but my phrasing makes it clear that I already know the truth of the matter."
    S "It was a dragon — the Eastern kind. She spent {b}ages{/b} carving each scale with a fettling knife."
    C "That sounds impressive."
    S "Yeah, it was."
    scene bg dorm night with dissolve
    "There's a brief moment when we reach the dorms that Sibyl seems like she's going to walk down the hallway to Tanya's door, but she must know as well as I do that she probably wanted to be alone for a reason."
    jump before_the_storm

label before_the_storm:
    scene bg transition with fade
    scene bg dorm with dissolve
    "When I step out of our room bright and early the next morning, Sibyl follows behind me."
    C "Is that new {i}Sylvia Valemont{/i} novel being released into the library today?"
    S "Hmm?"
    C "The one you were talking about yesterday."
    S "Oh! No, that will not be published for a few months yet."
    scene bg mary with dissolve
    "Finding little reason to question Sibyl's movements before breakfast, despite how unusual, I chat with her about her latest novel all the way until we run into Tanya near the entrance to the school building."
    S "Good morning!"
    T "Good morning."
    "Despite probably having skipped an entire meal yesterday, a feat which would surely leave me hangry beyond belief, Tanya acts like her normal, cool and disaffected self."
    T "Is the library getting a new {i}Sylvia Valemont{/i} novel today?"
    S "Since when are you both so interested in {i}Sylvia Valemont{/i} anyway?"
    "\"I'm not.\" Tanya and I both reply at the same time."
    C "Jinx! You owe me a cola!"
    T "No."
    C "You can't {b}refuse{/b} a jinx!"
    T "Watch me."
    "From deep within her bad, Sibyl produces a dark brown hard candy which she passes to Tanya, who then passes to me. When I pop the candy into my mouth, I find it tastes like a can of cola."
    C "Thash nawt fayr."
    "My garbled objection to this bending of the almighty rules of Jinx goes entirely disregarded as Tanya comes back around to question what were both thinking."
    T "I'm just surprised to see you this morning. Only sports club members get up this early on a week day."
    S "I wanted to come watch you and Clover practice. That's all."
    T "Oh, alright. We'll try not to be too long."
    S "Don't mind me! Just pretend I'm not even here!"
    scene bg hallway with dissolve
    pause 1.0
    scene bg lockers with dissolve
    C "(It's kind of hard to ignore her like this...)"
    "When Tanya and I reach the locker room as usual, Sibyl chooses to follow us inside rather than go around to wait where we practice."
    C "Umm... are you sure you don't want to wait outside?"
    S "Sorry, am I not allowed to be here?"
    C "I guess it's not a problem exactly, just a little awkward."
    S "Don't mind me!"
    "Sibyl turns around to stand facing the wall while we change, which only makes her being there more awkward in the end."
    C "(We change together in our room all the time. Doesn't she realize that it's simply her being there that makes it awkward?)"
    scene bg lacrosse with dissolve
    "Sibyl soon takes a seat on the bleachers while me and my arch rival begin our daily jog, both of us trying to out-pace the other while not running out of gas too early."
    "Tanya is noticeably weaker in our little competition this morning, no doubt due to having skipped a meal the night before."
    T "I concede, but only because I'm off my game today."
    C "Thank you for admitting I am the winner, Tanya."
    T "Don't get used to it, Clover. You're no match for my passing skills even on my worst day."
    "As Tanya retrieves the lacrosse ball and sticks necessary for our little game of jogging and passing back and forth, I glance back toward Sibyl, and find her missing."
    C "(Where did she—)"
    "I find her back off the bleachers, instead standing face-to-face with a trio of girls I recognize as Tanya's nascent fan club."
    C "(I {b}thought{/b} things were a little too quiet today...)"
    "They're too far away to hear what is being said, but the way that each member of the fan club stands with her arms crossed and the \"just bit into the world's most bitten lemon\" look on Sibyl's face, I can probably guess."
    T "Ignore them, Clover."
    "When my head whips back around to Tanya, I snatch the crosse out of her hands and demand answers."
    C "Did you put Sibyl up to this?"
    T "Of course not, but I did suspect that this is what she was up to when she started following us to practice and watching over us in the locker room."
    C "I don't like it."
    T "You know how Sibyl gets when she sets herself upon helping someone. She won't stop even if you tell her to, just like when she was trying everything possible to make you stop being such whiney sourpuss."
    C "What did you call me!?"
    T "A whiney sourpuss."
    C "I {b}am not{/b}!"
    T "Not {b}anymore{/b}. Now you're just {b}whiney{/b}."
    "It's only after I launch into a tirade of unflatteringly imaginative epithets for Tanya while we juggle the ball back and forth do I realize that she probably said those things to make me forget about Sibyl, and it worked just as well as she desired."
    "By the time I glance back toward my Vertu partner, she's returned to sit on the bleachers as far as possible away from the group of Tanya' fangirls."
    C "(They have {b}signs{/b} now!?)"
    T "Clover."
    C "Wha—? Ow!"
    "It's only a fleeting sting against my forehead where Tanya passes the ball, but it's her cheekiness in doing so and accuracy of the shot that really ticks me off."
    C "I'm {b}so{/b} going to get you back for that, just you wait!"
    scene bg artroom with fade
    "I hear nothing at all from Tanya nor Sibyl about the drama from earlier in the day at all until it comes time for art class, and Sibyl chooses to put her project on hold with an aim to suddenly begin something new."
    C "But what about our optical illusions project?"
    "The three of us had each taken upon ourselves to draw make an optical illusion and decide which of ours is the best."
    "I immediately set out to try drawing one of those illusory shapes where it looks like all the sides and corners should meet but never do, and somehow just end up drawing a fully realistic 3D shape."
    C "(I'd never be able to draw a real 3D shape even if I gave it my best shot, but when I {b}don't{/b} want to draw a real shape, all of a sudden it's all that comes out!)"
    "The only real competition is between Tanya's M.C. Escher-like pencil sketch of the academy buildings, and Sibyl's autostereogram collection."
    "I naturally want Sibyl to win so she can beat Tanya for me even though I can never see the images no matter how hard I squint my eyes."
    S "I will finish it during club if I have to, but there's something I want to make before the next lacrosse game."
    C "(Before our next game?)"
    "I know instinctively that this can only mean trouble with everything that has happened recently, and my intuition is confirmed when she explains in further detail."
    S "I want to make the biggest, most flashiest banner to take to your next game, and use it to wish {b}all{/b} of our Wild Roses the best of luck."
    T "I know you just want to help, Sibyl, but acknowledging my fans is only going to make it worse. I only want to focus on the game and ignore everything else."
    T "Besides, they're just some dumb fangirls chasing after my fifteen minutes of fame. They will forget me and be following around someone else in another week and everything will go back to normal."
    S "I know, but it's hard to just sit here and do nothing."
    C "You don't give Tanya enough credit for how tough she is. I've feared for my life, like, {b}five{/b} time since I've known her."
    "My comment is wholly serious but Sibyl's burst of giggles indicate she must have mistaken it for a joke."
    C "(As long as Sibyl isn't worried, I'll just ignore how much of a terrifying brute Tanya can be sometimes.)"
    C "And here's one more thing! If you want someone to cheer for, cheer for {b}me{/b}! Miss Woolsey told me to be prepared to play next game!"
    S "You're starting in the next game, Clover? This is big news!"
    C "Well, no, I'm not starting in the game, but she is going to substitute me in!"
    "Though the girls who earned their roles in tryouts play most of the time, Miss Woolsey does swap in substitute players like me for part of the game. With all of the backups on our roster, I didn't get any time in the last game."
    C "I'm not going to let this chance slip by again. I'm going to show Miss Woolsey and everyone else how much I have to offer for our team."
    jump gametwo:

label gametwo:
    scene bg transition with fade
    scene bg dorm with dissolve
    "The hour of the starting whistle to the Wild Roses' second game arrives quickly at the start of the weekend."
    "Nowhere near as many spectators show up for this match as there were for the homecoming game, but I'm still willfully trying to ignore the cheers that do erupt from the bleachers while I await the signal to take the field."
    C "(Ignore them. Focus on the game. Watch the state of the field. See where our game is lacking so you can patch it up when called upon.)"
    "Naturally, I watch the midfielders play for most of the game as that is where I will be substituting in."
    "Tanya seems to be dominating in the midfield again like she did the previous game, but unlike the team we faced before, this team moves much more quickly from end to end."
    C "(Our advantage of a strong midfield is nullified if they only pass quickly through it.)"
    "Tanya is doing her best but it's tough to always be running from one end of the field to the other so much, even with her strength and stamina."
    # hide clover, show naomi
    mw "Nolan, Ipswich, McLeod— you're up!"
    # hide naomi, show clover
    C "(That's me!)"
    "I almost totally forget that I'd be playing in this game until I hear Miss Woolsey call my name out."
    # hide clover
    "The entire first half passed in a total nailbiter of a game, with our Wild Roses and the other school trading leads back and forth."
    "After we swap in for the three most tired girls leaving the field, Miss Woolsey gives the rest of us a little pep talk with the remaining intermission minutes."
    # show everyone show naomi talk with dd
    mw "Wachusett High may have brought their A-game today, but that doesn't mean we're going to roll over and let them beat our win streak, does it?"
    "\"No!\""
    "We all respond back to Miss Woolsey in unison and huddle up together as she starts to disseminate game plans to each part of the field."
    mw "They're passing long through the center, so we won't be able to keep up the play to play pressure that we normally do."
    mw "I want to see the midfield run less and remain open more. Stay in your zones and put yourself in the middle of the passing lanes."
    mw "If you have the chance to get up close and personal, take it, but otherwise I want to see you making them work to move down the field by putting yourself between your mark and her target."
    mw "Now, are you all ready to get back out there and send them packing?"
    "\"Yes, Coach Woolsey!\""
    mw "Hands in!"
    "All together, we push one arm forward to intermingle with every other member of the team, then raise it out together alongside a loud \"Fight, Wild Roses!\" scream."
    "The forwards jog off to their stations, as do the defensive players, while me and the rest of the center section trot much more nearby into the middle of the grassy rectangle."
    C "(Let's go, Clover, show 'em all what you're made of!)"
    "With a slap on my thighs and a few hops in place to get my blood flowing, I hype myself up in my own mind while also shutting out everything else but me and the players on the other side of the field."
    "It works almost too well, in fact, as I totally hearing my name spoken beside me until Tanya's face spins around right around in front of me to drag me back into reality."
    C "What are you doing?"
    T "What am {b}I{/b} doing? You're the one spacing out while I'm trying to talk to you. Are you feeling alright?"
    "I can see a curious concern in Tanya's face, as well as note the little step back like she's afraid I might suddenly up-chuck all over her if she stands too close."
    C "(Doesn't she know that {b}reminding me{/b} about the crowd is only going to make me feel worse?)"
    "Even having been reminded that I'm out on the field being watched by the crowd from the bleachers, I somehow still feel pretty okay, and chalk it up to a result of Sibyl's homecoming dance theatrics."
    C "What, are you worried that I'm going to overshadow you now that we're on the field together, huh?"
    "The tension visibly leaves Tanya's shoulders and she goes to wipe a forearm at her brow, which I now find is incredibly sweaty, like like everything else about her."
    T "If you were to play half as good as you boast about yourself, we'd all be grateful. Wachusett has us running ragged."
    C "You heard what Coach Woolsey said. They know that's how we play and they're specifically trying to tire you out."
    "Tanya's morale doesn't seem to be any more lifted by what I repeat from the huddle just before, and that's clearly because it flies entirely against the skills she possesses which made her suc a star last game."
    C "So, hmm, listen to this maybe— Coach Woolsey wants us to stay in formation more and roam less. We both have different strengths, so all we need to do is play them up."
    C "I'm better defensively, and you're better supporting the forwards, so we should each take up a position on either side of the green."
    C "If they get down the field I'll be able to challenge them before our defense, and if we get up the field, you can power the last step with the forwards."
    T "You've had a lot of time to think about this from the bench, huh?"
    "Tanya probably sees my dark expression at her question right away, because she's instantly re-phrasing what she said just a moment before."
    T "What I mean is— you've clearly been giving this a lot of thought. I'll try it your way."
    C "Just you watch. Soon {b}I'll{/b} have the crowd of adoring fans!"
    "My advice is basically just what Miss Woolsey said combined with what is obvious watching the first half of the game, but I'm not above trying to pull a personal win over Tanya's head."
    # whistle sound from official whistle
    pause 1.0
    "At the sound of the official's whistle, Tanya and I job off to opposite ends of the field. One of our new substitutes takes the toss at the center and play begins once more."
    "Without the benefit of blending in with Tanya by my side, I am initially more cognizant of the students and teachers watching and cheering from the side of the field, but as the game progresses, everything else starts to fade away."
    "Now that I'm on the field myself, Wachusett High is even tougher than it looked from the benches, but our new style of play seems to be working better than the pressure we tried in the first half."
    C "(We just need to stop them from being able to move the ball from one end of the field to the other.)"
    "It's not just Tanya who will have ot adjust her play style — I'm also struggling to suppress the desire to run up and check the girl cradling the little yellow ball."
    "Instead, I hang back a few paces away with only a few quick glances back to see where my opponent's teammates may be. When I see her eyes lock onto someone behind me, I swiftly move to an intercept path and wave my crosse over my head to block."
    "It works out swell the first few times, but after a while they too adjust, and fake out more often, even if it means sometimes missing their intended passing targets."
    C "(If they want to get tricky, let's get tricky!)"
    "I've stared down Tanya's gloating face enough times for such simple ruses to throw me off my guard now."
    "When one player on the other team comes into my part of the field, I follow her jukes right along with her until she's got no choice but to try to run with the ball rather than pass, at which points I make my move."
    C "(I've gotcha now!)"
    "I almost yell it out loud, which would have been super embarrassing if I weren't so in the zone to be consciously thinking about it. My mind is set upon that little yellow ball in her crosse."
    "With my opponent caught out of her usual play, she's an easy target for my own strength — a swift stick check which knocks the ball free just as planned."
    "By mere fortune, it pops up cleanly enough that I can swipe it right out of the air, and pivoting on one foot while my opponent recovers, look back up field toward our forwards for my girl."
    C "Tanya!"
    "It's a long pass across the field to where Tanya remains stationed further up, but we do it a hundred times every day in the early morning."
    "There's no time to wait, so I drop into a big wind up and launch the ball way back up the field before the girl I took possession from and find her footing to check me back."
    "The ball seems to hang in the air for way too long as I watch it sail over the head dotting the center field. Everyone remains incredibly still watching it travel, except Tanya, who darts forward to collect it with ease."
    T "Got it!"
    "Our forwards, and the other team's defense, start up the chase instantly, but Tanya is faster."
    "She's already powered half a dozen paces forward and whipped the ball to one of our forwards before any of the defenders can catch up to her, and the ball is in the back of their net just as quickly."
    "The cheers erupt from the sidelines immediately, and while Tanya gets plenty of praise from the forwards for her starring role, so too do the other midfielders run by to praise my perfect stick check and pass."
    C "T-Thanks!"
    "I can feel the heat of embarrassment creep up through my cheeks at the sudden attention paid to me by my teammates, but rather than weight me down and make me sick, I simply bask in the warmth of it all."
    scene bg black with fade
    scene bg lacrosse with dissolve
    "We ultimately lose the game, but it was close enough that no one is too upset about the outcome. The person most devastated by the loss is Miss Izzie, who dramatically collapses into the grass at the final whistle."
    "While our most fervent supporter might be down about the results, our coach, Miss Woolsey, only praises us for our play during the post-game huddle."
    mw "They came here thinking they could read our play book, but we showed them just how adaptable our team can be."
    "While Tanya and the forwards remain the stars of the game, Miss Woolsey does praise the defense, and me by name, in the review too."
    scene bg lockers with fade
    "The mood is suitably celebratory as we return to the lockers despite the loss."
    "I look to Tanya to allow her to shower upon my praises for executing that perfect pass across the field in the second half, but find her already rushing off to the showers way ahead of everyone else."
    C "(Being popular sure is tough, huh?)"
    "Tanya's detractors have been causing her trouble, I know, I so try not to blame her for the speedy turn around and go about my own business, until a shriek and sudden commotion rips through the lazy locker room atmosphere."
    st "Look at that cutting board!"
    st "Thunder thighs!"
    "Like everyone else in the locker room, I whip my head around toward the raised voices to find the usual detractors by the shower stalls. One holds the shower curtain open by force while the other two throw pieces of a uniform into the running water."
    st "Not so perfect {b}now{/b}, are you!?"
    "I don't have to catch glimpses of the sleek black hair or firm thighs of the girl struggling to pull the shower curtain closed while also attempting to cover her naked self up to know it's Tanya."
    "Everyone else in the locker room is frozen as solid with surprise as I am, but despite that, the rage still builds inside me that these three girls should be treating any member of our tea in such a way."
    "Before I can even yell out at them, however, a far more terrifying sound emerges from the doorway."
    mw "You three, my office, {b}now{/b}!"
    mw "The rest of you, get changed and leave at once."
    "Everyone, and I mean everyone this time, goes silent at the tempered ferocity that surely no one thought Miss Woolsey was capable of, and quickly follows her orders."
    "While the three miscreants slink out of the locker room with Miss Woolsey, the rest of us quickly don our uniform and get out of there with all haste, the only sound that of whimpers muffled by running water."
    scene bg black with fade
    pause 1.0
    scene bg hallway with dissolve
    "After the rest of the team disperses from the locker room, I remain behind in the hallway to wait for Sibyl to come pick me and Tanya up like she always does."
    S "Hi, Clover. Where's Tanya?"
    C "..."
    scene bg black with fade
    "Sibyl is none too happy when I tell the whole story, and two times I have to nearly prevent her from barging into the locker room."
    "The first immediately after I finish the retelling, and the second is after the trio of culprits eventually emerge from the locker room with gigantic scowls on their faces."
    "The death stare which Sibyl gives those three is definitely the most frightening thing I've seen since coming to the academy."
    "After yet more waiting, Tanya herself finally emerges from the locker room. Sibyl immediately launches herself to wrap her arms into a big hug around the former, who looks almost surprised to see us at all."
    C "(Did she really think Sibyl wouldn't have waited here no matter how long it would take?)"
    S "Clover told me everything— Tanya, I'm so sorry!"
    T "Don't be. You had nothing to do with it."
    "Tanya tries to coolly play the whole thing off to Sibyl despite her blatantly obvious red, swollen eyes."
    S "How are you feeling? Do you want to get a late lunch while we still can?"
    T "I've been better, thanks. I think I will to skip lunch today."
    S "Oh that's right, you have your Saturday afternoon thing today, don't you?"
    "Tanya herself must have forgotten, because she turns her head away and replies pensively."
    T "I'm going to skip today. They'll understand."
    "While Sibyl is busy fussing over her friend, I myself hang back without any idea of what I should say."
    "I may not have been directly involved in what happened today at all, but some part of what went down does eat at me a little enough to speak up regretfully."
    C "Tanya, I... wish I could have legs as strong as you."
    "Sibyl may be clueless as to why I'm saying such things now, but Tanya at least seems to understand that it's my way of apologizing for the jibes about her thighs what feels like so long ago now, but really wasn't."
    T "You'll get there. Cut out all that sugar and eat more protein."
    scene bg dorm with dissolve
    "It's for the best that we don't go to the cafeteria after all."
    "Tanya might have had the small benefit of getting an extra long shower, but her uniform is a total wrinkled wreck after clearly being hastily dried out."
    "I'm not looking so hot either, having hastily thrown my uniform back on without having had a chance to clean up after the game in the morning."
    "Sibyl drops Tanya off at her room solemnly, then walks me back to our room before taking her leave with a promise to bring back some lunch from the cafeteria while I get myself clean."
    jump easter

label easter:
    scene bg transition with fade
    scene bg chapel with dissolve