label easter:
    scene bg black with fade
    scene bg bedroom with dissolve
    "The excitement of homecoming swiftly fades into the doldrums of passing the week-long Easter break when most students have left for home."
    S "Tanya! Gimme your threes!"
    T "Go fish."
    S "Aww..."
    "Sibyl surprised me on Sunday by attending services in the academy's chapel."
    "She told me after that she isn't religious, but that the foster family she has been with for the past few years used to take her and her foster sibling every Christmas and Easter."
    C "(She probably just went because there's nothing {b}else{/b} to do with everyone else away.)"
    "All student activities are on hold, both classes and extra-curriculars. Even the cafeteria is operating with a depressingly limited menu."
    "Sibyl and Tanya both also have chosen to stay behind, leaving the three of us to scrape the bottom of the barrel of activities to entertain us."
    T "I'll take your tens, Sibyl."
    S "Here you go!"
    "I've always gotten the impression that Sibyl genuinely likes her foster family, so why she hasn't chosen to return home is a bit of a mystery to me."
    "As the game drags on well into the afternoon, I try to think up ways I can subtly ask her about it in a manner that won't sound like I'm prying into her personal business."
    S "Clover, it's your turn."
    C "Huh? Oh, umm, Sibyl, have any nines?"
    S "Tanya {b}just{/b} took them from me. Are you feeling alright, Clover?"
    "Realizing that I must be zoning out further than I think I am, I confess to being bored with Go Fish and propose just ending the game altogether."
    "The other two accept so quickly that I almost feel like they must have been thinking of ending the game too. All three of us flop down on the bed with exaggerated malaise."
    T "I'm so glad you're staying for Easter break, Sibyl. Are you sure your foster family won't mind?"
    "After thinking how best to ask such a personal question to Sibyl, Tanya suddenly outright asks the very same thing I was wondering."
    S "It's only a week, and after seeing how stir-crazy you were after our Christmas break I couldn't do that to you again."
    "It's clear from Tanya's expression that she doesn't like this answer, and Sibyl is quick to alleviate her concerns posthaste."
    S "Really, I wanted to stay! The whole reason I applied for this scholarship is to experience all the ups and downs of living out on my own."
    T "Okay, but why is Clover still here? I thought she was finally getting along with her parents again?"
    "That Tanya asks Sibyl instead of me gets on my nerves, so despite how I don't really care to share my personal life with her, now I feel obligated."
    C "I also {b}chose{/b} to stay here this week, Tanya."
    "I've told Sibyl all about what happened with my parents' divorce, but given Tanya's dated knowledge of my situation I assume that my roommate hasn't been talking behind my back."
    "Tanya must have realized {b}something{/b} was wrong when I suddenly fell apart right before the tryouts, but she usually has enough tact not to shove her face where it doesn't belong."
    C "For your information, my parents' divorce was finalized a few weeks ago. I've accepted that it happened but that doesn't mean I'm prepared to go back to whatever will be \"home\" from now on."
    T "That sounds like you're avoiding your parents to me."
    C "Well I didn't {b}ask{/b} your opinion, did I? Why are {b}you{/b} still here?"
    