label cincodemmayo:
    scene bg transition with fade
    scene bg bedroom with dissolve
    S "Do you really have to run her this hard so early in the morning?"
    T "This much is just to keep her skills sharp until her probation is over."
    S "But she looks like a fish lying on a dry pier."
    "From my vantage spread out on my back in the grass gasping for air, I probably do look like a fish out of water."
    "Determined to ease Sibyl's mind, and to get her to cease giving me such a pitying look, I manage to scrape myself back up onto aching legs once again."
    C "She's right, Sibyl. I can't allow myself to get complacent. I need to be on top of my game when probation expires, so it's hard training and clean, whole foods every day for me from here on out!"
    scene bg cafeteria with dissolve
    T "\"Clean, whole foods\", Clover. You promised."
    C "B-But..."
    S "Oh, just give her this one day, won't you, Tanya? She's literally been talking about them in her sleep."
    "Luckily for me, Tanya is just as weak to Sibyl's demands as I am, so I manage to get a full helping of crisp, warm, delicious churros despite Tanya's protests."
    C "Every day should be Cinco de Mayo."
    "THe kitchen staff has made churros a number of times before, but they go all out today with a special dish of {i}chilaquiles{/i} as the highlight of breakfast and even freshly made {i}horchata{/i} too."
    S "Look how happy she is! Doesn't she look like a rabbit, Tanya?"
    "The way that I attempt to savor the amount of churros I've allotted for myself by making lots of tny nibbles evidently just makes me an amusing sight for everyone else."
    "When I look up from my delicious fried treat, I catch a glimpse of even a small grin touching the corner of Tanya's lips."
    C "(Whatever. I'm not going to let looking a little funny get in the way of enjoying this Mexican feast to the fullest.)"
    scene bg classroom with dissolve
    "The sugar crash lands hard during the very first period after homeroom, but the lecture on quadratic equations is probably just as much at fault as the churros."
    "Sibyl manages to keep me at attention for most of the lecture, and when I start daydreaming about what Mexican food will be served during French lessons, Tanya doesn't hesitate to prod me in the back with her mechanical pencil."
    scene bg gym with dissolve
    S "Maybe Tanya was right. You should have something more wholesome for lunch, Clover."
    C "Nonsense! If I work hard enough in gym class, I can eat whatever I want at lunch with a clean conscience!"
    T "Even if you will burn enough calories to make up for eating churros at three meals in the same day, that much sugar just plain isn't good for you."
    C "Don't you worry, I feel great! Check this out! I'm burning that big breakfast off right now to make room for lunch!"
    "Not only to do I show off jogging in place, but I do it a the same time as a carefully bounce a badminton shuttlecock up and down with my racket at the same time."
    "It's honestly only an accident when it takes an odd bounce off my racket and smacks Tanya right on her forehead."
    C "Sorry. Accident."
    "Sibyl takes a worried glance between me and Tanya, but rather than get angry, Tanya merely picks the shuttlecock off the ground and whips it right back at my face in return."
    T "Watch it, you dullard."
    C "Make me, you brute!"
    "Though we trade bards much as we have always done in the past, the malice just isn't there like it had been before. Even Sibyl is comfortable enough with the exchange now to smile through it."
    T "Watch it, or I will!"
    "We both trade throws pelting each other with the light plastic shuttlecock as Sibyl looks on until Miss Woolsey gives us a stern glare from across the gymnasium as if to say \"quick goofing off and get back to the lesson at hand\"."
    C "So anyway, Tanya, we still need to work on a plan to present to Miss Woolsey by the end of next week."
    T "I know, I've been thinking about it already. I have art club with Sibyl tomorrow, so maybe we can do some brainstorming on Friday?"
    C "Yeah, let's do that!"
    "A distracting motion catches the corner of my eye, which I find to be Sibyl nearby, silently twirling her racket in her hands as Tanya and I talk to one another. When I look her way, she shows me an encouraging smile that wasn't there a moment before."
    C "...And maybe we should do it in the library. Maybe Sibyl can find some books for us to reference."
    S "I'd be very happy to help if I can!"
    "It's at this mention that Sibyl step forward, the small smile now a full grin spread across her face."
    T "Miss Woolsey never said we couldn't enlist some outside help. Besides, you're basically part of the team anyway with how you're always spectating our practices and cheering on our games."
    S "That is exactly right!"
    "We quickly pick back up with our casual volley of the shuttlecock over the net stretched across the gym floor before Miss Woolsey catches us talking again, but all the while my thoughts are left on Sibyl."
    C "(Is she feeling... left out?)"
    "It's no overstatement to say that I'm maybe spending more time with Tanya now than I am with Sibyl, not counting the time we spend asleep in the same room."
    "It was Sibyl who encouraged me to join the lacrosse team and get closer to Tanya, and I don't think she is showing any regrets about that, but it also must be tough for her to have her two best friends share a hobby in which she cannot participate."
    jump twinsinterlude

label twinsinterlude:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "With Sibyl and Tanya at their art club on Thursday, I occupy the hours until meal time with the homework that's been piling up on my desk."
    "A fill-in-the-blank worksheet from science class sticks out among the rest, and I'm actually not that bad with biology, so it's with aplomb that I re-shuffle that sheet to the top of the stack to get to work."
    C "(Lipids. Mitochondria. Chloroplast.)"
    "Things go nice and smooth until I get deeper into the worksheet, to parts of lessons for which I may have been distracted with other drama in my life to remember all that well."
    C "(Cell cycle. I can do this. That's \"interphase\", \"mitosis\", \"telekinesis\"...)"
    "I happily flourish my pencil along the last letter of the last answer, but it becomes clear when checking over my work that maybe I have been more distracted lately than is good for me."
    C "(No, that's not right. Where are my notes on the cell cycle?)"
    "As I flip through my notebook, I fail to find any note about that lesson at all, and resort to having to open my textbook to find the right answers."
    C "(How did I manage to smash \"telophase\" and \"cytokinesis\" together?)"
    "With one worksheet finished and trigonometry peeking out behind it, I take the opportunity to stretch my legs instead with the excuse that sitting in one place too long is probably bad for my health after all."
    scene bg dorm with dissolve
    "Where I am going is anyone's guess. After appreciating the warm rays of sun shining through the large dorm windows for a few minutes, I make off down the hallway in an equally aimless manner."
    scene bg mary with dissolve
    "My feet mindlessly lead me out the doors of the dormitory and, as best as I can tell, toward the school building likely in pursuit of where I know Sibyl and Tanya remain."
    "\"Psst. Clover.\""
    "I never make it far enough to reach the school building, however. A quiet summons snaps the background hum of outdoor activity on the academy's grounds, though I cannot find the source."
    "There's a moment when I turn my head toward the large statue in the garden where I think I must have instead fallen asleep rather than go for a walk, but realize it's the girl in pink uniform sitting at the base calling to me and not the Virgin Mary."
    C "What are {b}you{/b} doing here?"
    "A queer sensation comes over me as I approach Vincenza sitting under the statue's watchful vigil, which I quickly realize is because there isn't another girl sitting right beside her."
    C "(Is this some kind of trap? Is Vittoria going to jump me from the shadows?)"
    "I lean aside to peer around the back of the statue to find only yet more cheerfully colorful flowers smiling up at me from their earthen beds."
    C "Where's the other one?"
    O "Not even months of watching over you and one unforgettable afternoon together is enough for you to treat your {i}senpai{/i} with proper respect?"
    show choice_darkness with dissolve
    menu:
        "\"My {b}what{/b}?\"":
            hide choice_darkness with dissolve
            C "My {b}what{/b}?"
            O "All I'm saying is, even Tanya calls me \"Ouji-onee-sama\" and it only took a tiny amount of blackmail."
            C "Vincenza, I have {b}no idea{/b} what you're saying."
            O "I just wish you were nicer to me and my sister, Clover. Is that so much to ask?"
            C "But you're both always so {b}irritating{/b} with that \"Prince and Princess\" thing you do. I think I deserve to be able to fight back."
            "I expect Vincenza to object, but surprisingly actually giggles at my questionable logic."
            O "So your response to our little playacting is to yourself play the part of the irascible {b}tsundere{/b}? How adorable."
            C "{b}Stop{/b} using words I don't understand!"
        "\"What \'unforgettable afternoon\'? I don't know what you're talking about.\"":
            hide choice_darkness with dissolve
            C "What \"unforgettable afternoon\"? I don't know what you're talking about."
            O "Don't try to play ignorant now, Clover. You may try to pretend that day never happened, but the next girl you kiss will only make you remember that it was {b}me{/b} who took your first."
            C "You're wrong! You {b}weren't{/b} my first kiss!"
            "Smugly, I refute Vincenza in triumph, only for her to smile just as smugly right back at me."
            O "So you {b}do{/b} remember now, huh?"
            C "N-No, I just..."
            C "Okay, fine, but {b}I{/b} didn't touch you or your sister like that; it was only you two doing stuff. And it doesn't count anyway because I don't {b}love{/b} either of you."
            O "Well if that's how it works, we're both pure virgin maidens then, aren't we?"
            C "(Is she seriously saying she's never been in love? Or just that she's never done {b}that{/b} with her?)"
            "My expression softens as I puzzle through the hidden meanings behind the joke, which appears like jovial when viewed from deep within Vincenza's eyes."
        "\"You're not \'watching over me\' at all! I'm just another pawn in you and your sister's games!":
            hide choice_darkness with dissolve
            C "You're not \"watching over me\" at all! I'm just another pawn in you and your sister's games!"
            O "Now, Clover, that I must protest! You are not a \"pawn\" of any kind, nor do Vittoria and I play \"games\"."
            O "There are students here at Prudence Prep who require more attention than most, and those often require a unique approach that we are most well suited to provide. You are one such case in both respects."
            O "Please rest assured that, no matter how much you may fail to understand our methods, my sister and I are {b}on your side{/b}."
            "A small snort blows through my nostrils at this comically farcical statement, to which Vincenza takes a minor degree of offense."
            C "I don't believe you."
            "Though even as I say it, I do consciously remember with how much respect Sibyl treats Vincenza and her sister Vittoria despite how little she also cares for their theatrics."
    C "A-Anyway, where {b}is{/b} your sister? It feels weird seeing you alone like this."
    O "Vittoria is resting in the nurse's office with a lightly strained ankle."
    C "And you're not there with her? You're not going to wither if you stay apart from one another too long?"
    O "She sent me away."
    C "That's not going to do you any favors with your fans, \"Prince\". Shouldn't you be guarding her door or something?"
    O "Oh, I played the part all right. Our whole athletics class saw me princess carry her out of the gymnasium, even if they didn't see my legs go all wobbly just outside the door before we both ended up on the floor."
    O "No, Vittoria thinks she knows best because she's the older twin between us, like she thinks a minute longer makes her more mature than me."
    O "Today, that means sending me away because she doesn't want me to be stuck sitting around in the nurse's office too."
    C "And... how do you feel about that?"
    "It might be a probing question, but Vincenza seems like she's in the mood to unload a little of her emotions, and I am certainly getting more than a little interested in their relationship now."
    C "(I thought the two of them were of the exact same mind before, or close enough to it, but they might actually be two different people after all.)"
    O "I want to stay by her side. I don't care if it's boring in the nurse's office or about whatever the student council has happening."
    C "I'm sure she has her reasons. I mean, if you're both close enough to have sex together with another girl... Well, I don't know exactly what to say about that, but you probably understand."
    O "Vittoria doesn't like to say \"have sex together\". She prefers \"have sex with the same girl\"."
    C "What's the difference?"
    O "Less guilt about us enjoying intimacy together."
    C "I don't get it. Just don't have sex with someone like me if you're going to feel guilty about it."
    O "...Look, Clover, the point is that Vittoria doesn't like people asking those kinds of questions, and you shouldn't be asking them either way."
    C "So if I go ask her about it right now..."
    O "I'm not joking, Clover. You {b}won't{/b}, right?"
    C "I'm hearing you loud and clear, Vincenza."
    "Maybe it's because English is her second language, but she doesn't even pick up that my response was entirely absent of any promises to do a she asks."
    C "Well, I should be going to pick up Sibyl and Tanya soon I think."
    O "Tanya? I won't keep you waiting. Go get her!"
    C "What do you mean? Their club hasn't even let out yet?"
    "I turn away from Vincenza off toward the school building. Though I tell Vincenza that I am going to pick up Sibyl and Tanya from their club meeting, but it's the nurse's office that is foremost in my mind."
    scene bg nurse hallway with dissolve
    "When I arrive at my destination, I find at least a half dozen students crowd around the door to the nurse's office, all eager to sneak peek through the glass window to the inside."
    C "Umm... excuse me."
    "The crowd parts when I push myself through them toward the door. Their looks range from surprised to indignant."
    C "(How do Vittoria and Vincenza put up with their fan clubs?"
    "This kind of attention sent Tanya spiraling into depression and would probably outright kill me."
    scene bg nurse with dissolve
    C "I-I'm here to see Vittoria."
    nurse "If you are not injured, please wait outside!"
    "The nurse is all over me when I first step into the room. Her words might be polite, but the frazzled way she says them as she simultaneously tries to herd me out the door tells of another story entirely."
    H "Is that Clover? I'd like to speak to her."
    "The nurse sighs dejectedly but does not fight Vittoria's wishes. Instead, she steps aside to allow me past her toward the bed where Vittoria lies pensively."
    nurse "Very well. It's about time that the others disperse from outside my office, however."
    "The nurse slips past me and out the door while I take a seat conveniently placed next to Vittoria's bedside."
    H "Let me guess: you need some help with Tanya. Don't worry, I'll make sure everything works out between you both!"
    C "What? No, I don't have any problems with Tanya. We haven't even fought once since what happened the other day."
    H "Is that so? Well, that's a start. What are you doing here if it's not to get advice about Tanya?"
    C "I ran into Vincenza outside and she told me that you were in here."
    H "So you came running to check on me? What wonderful juniors I have!"
    C "Y-Yeah..."
    "I really did intend to come in here and ask her the questions that Vincenza told me not to ask, but now that she's giving me this unintentional guilt trip it's hard to come out with it."
    C "She said something about your ankle?"
    H "Yes. We simply chased after the same tennis ball at the same time and ran right into one another! I took an odd step and this was the result."
    H "It is quite a minor injury. I will be back to my student council duties shortly, and in the mean time I have instructed Vincenza on how to fill in for me."
    C "So your normal student council work is moping under the statue out in the garden?"
    "There's a moment where Vittoria processes what I'm saying, upon which her expression turns sour."
    H "I gave Vincenza {b}specific{/b} instructions!"
    C "Well, she's not following them. She's just kind of upset about how you kicked her out of the nurse's office."
    H "God knows I would rather be out there with her and not lying in the nurse's office, but {b}someone{/b} has to do our nightly rounds!"
    "I shrug my shoulders casually. Whatever their duties as President and Vice President entail, it's not my concern whatsoever, and I'm not volunteering to help out with them. I came here for a different reason."
    C "Why did you and Vincenza have sex with me together?"
    H "This again? Clover, you {b}literally begged us{/b} to do it. Don't go regretting it now after we tried to warn you."
    C "I didn't say I {b}regret{/b} it, okay?"
    H "So what? Did you come here because you want to go again? You picked the absolute worst day to suddenly show an interest again, Clover."
    "Vittoria takes what I'm asking a completely different direction than what I intended, but it's hard to just come out and tell her that's not what I meant when just the mere suggestion turned her gloomy expression into such a bright, blushing grin."
    H "If Vincenza were here and I weren't stricken lame, we'd definitely—"
    "I cover my eyes to muffle the sounds of whatever shocking things Vittoria says she wants to do to me, but I can still see her lips move and vaguely make out some of the details."
    "When she finally finishes speaking, I release my ears, at which points she tacks on an additional offer for me to consider."
    H "Maybe this time you want to try it on us too. Don't worry, I can teach you exactly how to do it just perfectly, and Vincenza won't mind playing test subject!"
    C "U-Umm, actually, Vittoria, that's not what I was asking..."
    H "Eh?"
    "The thought of maybe going another round with Vittoria and Vincenza does kind of excite me at some level, but my memory of the hollow feeling which came after the lascivious high eclipsed sours the expectations."
    C "I mean, like, why you do it {b}with your sister{/b}. You didn't even entertain the thought of doing \"it\" without Vincenza with you. She said I shouldn't ask you about it, but I never promised her not to."
    "Vittoria quickly turns more beet red to the face than when she was actively detailing how she and Vincenza were going to go about {i}bleep{/i}ing my {i}bleep{/i} and other such lewd acts."
    H "W-We don't— I mean, when we get in the mood, it's better that there's... another girl in the middle, right?"
    "Vittoria stumbles over her word in rapid succession in a way that I've never seen out of her before. It's rewarding to see someone who usually teases me so mercilessly fumbling over herself, even if I have no idea what she's rambling on about."
    "She does eventually collect herself enough to try to reply in a more coherent way which sounds more diplomatic and less emotional than her last."
    H "Listen, Clover, I don't know what Vincenza told you, but she and I are twin sisters, and things which may not seem normal to normal sisters do not feel so strange when we have been so close by one another our whole lives."
    C "So... what you're saying is that it's not that awkward between you when you do it?"
    "With a heavy sigh, Vittoria merely says \"yes\", and repeats it again right after."
    H "Yes. When we make love to another girl at the same time, there's nothing awkward about it at all. If that's all you were wondering about, I'm glad that was cleared up, Clover."
    "I've always thought Vittoria was the maybe slightly less weird of the two, but Vincenza was right that something about it really set her off into the loco zone."
    C "Huh. Okay."
    H "But if things don't work out with Tanya, the offer stills stands for us to..."
    C "Tanya? What about her? Are you and Vincenza doing {b}that stuff{/b} with her too?"
    H "I meant between {b}you{/b} and Tanya. We heard from her that you finally apologized so—"
    C "What do you mean, {b}finally{/b}? She apologized to {b}me{/b} too!"
    H "If I know both of you, I do not doubt both of you had a lot to apologize for."
    H "Now that you both {b}have{/b} apologized, however, it is the perfect opportunity to take your friendship to the next level, don't you think?"
    C "Yeah, we are?"
    H "You {b}are{/b}!? She didn't tell us that!"
    C "Yeah. We've more or less stopped fighting and we're going to be working together on drafting plans to re-work the Wild Roses' midfield strategies tomorrow in the library."
    H "Oh, yeah?"
    "Vittoria's tone falls flat as she droops back into the nurse's office cot."
    C "Yeah. Me, Tanya, and Sibyl are going to meet in the library tomorrow after class to start brainstorming."
    H "Hmm..."
    "The door suddenly clicks back open, and in walks the nurse again, who looks just as frazzled as when she left but now pushes along a wheelchair before her."
    H "Please excuse me, Clover. Nurse Hamilton has graciously offered to wheel me back to my room in the absence of my sister."
    C "R-Right... I have to go meet Sibyl and Tanya anyway."
    scene bg hallway with dissolve
    "I actually don't have to meet them at all. The plan was for me to spend all afternoon working on my homework and then they'd come pick me up before dinner, but I've already wasted the entire afternoon and am near their club anyway."
    jump brainstorming

label brainstorming:
    scene bg transition with fade
    scene bg classroom with dissolve
    "When at last we are finally dismissed from the last lesson of the day on Friday, I'm the first to hop out of my seat."
    C "Hurry up, we only have three hours before the opening of the cafeteria for dinner!"
    "No, it's not that I am rushing to get to the cafeteria three hours early, but that I'm just so full of ideas for how to manage our lacrosse team's midfield that I want to get started as quickly as possible."
    C "(And end as close to on time as possible we so don't get stuck with the leftover in the cafeteria, of course!)"
    T "Relax, Clover, we have plenty of time today, and all of this weekend, not to mention the entire next week too."
    "After successfully pulling Sibyl out of her seat by her hands, I turn to prance around Tanya impatiently while she seemingly goes extra slow on my account."
    S "What a reversal this is! You looked on the verge of death itself during our etiquette lessons, and now you're too giddy for your galoshes!"
    C "I've been working on plans in my head for days now! I don't think I'll be able to cram any more math and science in there until I get them out!"
    "At that moment, Tanya finishes packing up her things and steps over to join us with a perfectly prepared quip at my expense."
    T "So you {b}do{/b} have something in your head? I could have sworn it was empty!"
    "Sibyl gives Tanya a light rebuke in the form of a small disapproving glare, but I don't really care about what Tanya has to say about my brain at all."
    C "(Once she hears my plans, there'll never call me stupid ever again!)"
    scene bg hallway with dissolve
    "I quickly proceed to nearly drag Sibyl and Tanya to the library with the pace I set going forward, but get stopped on the route there by a pair of roadblocks rather resolutely set in our way."
    S "Good Heavens! What has happened to you, Vittoria?"
    H "Do not worry on my behalf, Sibyl. It is merely a small sprain which will heal in a few days' time."
    O "Everyone's favorite princess will be safely in my care until her injuries have healed."
    "Vittoria, supported on one side by a crutch, takes the opportunity of their grandiose speech to lean aside against her sister to clutch an arm to her chest."
    "The gaggle of girls watching from just down the hallway erupt into a quiet murmur at the action, which was no doubt intended to set their fancies ablaze more than the three of us here."
    S "Of course. Where would a princess be without her prince?"
    "I know Sibyl doesn't actually believe their act to be real either, but she still replies in kind with a slight glance toward the twins' admirers grouped just away."
    C "(How can those girls seriously believe any of this act is real? It's so {b}cheesy{/b}.)"
    T "I don't know what scheme you're up to right now, but I'm not playing it right now."
    "Addressing the twins, Tanya chooses to break the mood and get right down to whatever business she thinks there must be happening here."
    O "You have no need to fear, Tanya. Today we are here for Sibyl."
    S "Me?"
    H "Yes. The library has suddenly found need of an {b}immediate{/b} re-cataloguing, and we would like to request your help."
    T "The library? But that's where we were going to do our brainstorming!"
    S "Re-cataloguing? I wasn't aware of anything like that."
    O "I'm afraid so. But not to worry, Clover. We have already arrange for you and Tanya to use Miss Izzie's art room for your plans this evening."
    T "Miss Izzie?"
    C "Umm... okay, I get the library is important, but Sibyl was going to help us with our planning today."
    H "I'm afraid it's dreadfully important, right Sibyl?"
    S "Hmm?"
    O "That you leave Clover and Tanya alone, while you come with us to assist with the emergency re-cataloguing of the library."
    S "Oh. Oh! Yes, of course!"
    "Turning to face me and Tanya, she places her hands together as if begging which she explains that she actually totally forgot about the emergency re-cataloguing and that she definitely needs to help right away."
    S "So, actually, there was a new library system that was published the other day, the... Doo-wop Decimal System. It's real cutting edge stuff, and you'd probably hate it, so go along with Tanya. We'll catch up at meal time!"
    C "There's {b}another{/b} one! But I just finally learned {i}Dewey{/i}!"
    "Perhaps equally exasperated with the sudden need to learn and entirely new library organization system, Tanya punctuates my exclamation with a heavy sigh of her own."
    T "Come on, Clover, let's just go. We're out-numbered here."
    "Tanya yanks me away by one of the straps on my skirt before we can even say good bye to Sibyl."
    scene bg artroom with dissolve
    "When we first enter the art room, the calming sounds of smooth jazz shuffle pleasantly through my ear drums, and then Tanya breaks the ambiance to draw my attention elsewhere."
    T "What's with the candles? Are you trying to summon a succubus again, Izzie?"
    mi "No! And it would have worked too if Nao-chan didn't chicken out!"
    "All the desks save one with a chair on either side have been moved to the back of the art room, and around the double seated desk lie five candles in a circle around them, of varying colors."
    C "This is a pentagram ritual, not a summoning circe, and barely even that. The blue candle needs to be where the orange candle is, and where that would leave the orange candle needs to be replaced with a white candle."
    "Having participated in my share of pentagram rituals, this much is obvious to me as first glance, but I only realize how crazy I must sound when I notice both Tanya and Miss Izzie staring at me in stunned silence."
    C "(Dang it, Clover, that stuff was supposed to stay buried in your past!)"
    C "...Or something. I read a book about it once."
    mi "Can I borrow Clover next time we try it, Tanya?"
    T "Why are you asking {b}me{/b}? I don't own her."
    T "And I see what you're trying to do here, by the way. I {b}told{/b} you all that it's not like that."
    mi "What {b}I'm{/b} doing? Why, I am helpfully providing a place for two of my students to work on their extra-curriculars at the request of the Student Council!"
    "Nevermind whatever Tanya and Miss Izzie seem to be arguing about, I get right to work unpacking my bag, prompting Tanya to do the same after some feet dragging."
    C "Come here and brainstorm with us, Miss Izzie! I'm sure you have lots of good ideas too!"
    "I'm totally confident in my plans, but it doesn't hurt to have someone with experience on your side, and Miss Izzie is probably the most fanatic supporter of the team out of anyone."
    "She looks like she wants to yank a chair right up the table with us, but with a bite to her lower lip she only tells us that she has other matters to attend to and cannot join in."
    mi "I have a very important staff meeting starting exactly {b}right now{/b}."
    T "How convenient."
    "Miss Izzie's shadow has already left disappeared from the doorway before Tanya even finishes her rebuttal."
    C "Miss Izzie sure is strange."
    T "You don't know the half of it."
    C "I guess you do see a lot of her from the arts club, huh?"
    T "Yeah, I see her a lot in the arts club."
    "After confirming exactly what I though, Tanya goes about extinguishing the candles,a nd is about to shut off the smooth jazz before I stop her."
    C "Keep it on. I like background music when I'm thinking."
    "Without being able to bring my smartphone with me outside the bedroom, I am unable to play my music while studying. Even when I'm at my desk in my room, I still don't put it on speaker like I used to out of respect for Sibyl."
    C "(Sibyl probably wouldn't appreciate the louder screamo bands I was fond of in middle school. It's probably time that I get into more adult music like jazz.)"
    C "So here, take a lok at this."
    "When Tanya finally reaches her seat opposite mine at the desk, I pull out a pen and flip to a blank page in my notebook to illustrate the plans I've been cultivating in my head."
    C "Before that last game, we've been mostly playing two-way midfield all the way through, right? But in that match, we switched to an offensive and defensive setup which worked well."
    T "Uh huh."
    "As I scribble my thoughts out onto the crude sketch of a lacrosse field, I suddenly realize that what is in my brain isn't all that well visualized by the mad scribbles coming out of my pen."
    C "I think we should keep at it. We keep one offensive midfielder and station here {b}here{/b}, one defensive midfielder stationed here, and we keep one two-way in the middle."
    T "To cover the OM and DM on either side of the field."
    C "Exactly!"
    T "And the DM gets the long stick?"
    C "Of course!"
    "Happily enough, Tanya appears to be following me step for step even with my sub-par drawing skills."
    C "(Is this how Vittoria and Vincenza feel with on another all the time?)"
    T "It's a good plan, Clover. I assume you put yourself into the DM position here?"
    C "Yeah. I was thinking you'd play well in the two-way role."
    T "Even though I'm the best shot taker in our midfield lineup?"
    C "Well, that's true, but... you're also the strongest player we have when it comes to having the stamina to play two-way the full sixty minutes."
    C "Even if you won't be able to get so many shots in, I think the two-way is the most important player on he field since she's covering for the OM and DM on pressure, as well as keeping herself open to intercept passes or advance the ball."
    "Tanya's marble-like brown eyes flicker over the scribbles between us as she pauses to think in silence. After a moment she reaches out to tap my hand, which confuses me until I realize she just wants my pen."
    T "You have us more or less lined up in the midfield. What if we put two OMs up font in parallel with the DM in back, forming a triangle like this?"
    "Dreadful memories of geometry class return to me as Tanya scribbles a triangle over my earlier scribbles, but it's something else entirely that captures my attention."
    C "You smell good."
    T "What?"
    "With Tanya having leaned closer to me over the desk to draw on my notebook, I get a pleasant whiff of something earthy and floral radiating off of her. I have to lean in slightly further just to catch it again."
    T "S-Stop that!"
    C "Lavender and... something. Is that your shampoo?"
    T "Lavender and rosemary! It's my SPF moisturizer."
    T "You should be wearing some too, Clover. It's more important than ever to take care of your skin as we approach Summer and we're spending more time outside."
    C "You're probably right. My neck was that kind of red that goes white when you press on it after the last game."
    T "That's {b}sunburn{/b}, Clover!"
    C "But it din't hurt. It was just kind of red."
    T "You really need to go down to the academy store and buy some sunscreen. It's a miracle your skin has remained so firm and unblemished when you mistreat it as much as you do."
    C "(She's complimenting me! {b}Tanya{/b} is complimenting me.)"
    "I let myself soak into the rare moment of praise from Tanya. Even if it is delivered by way of chastisement, I know that she only means well in wanting me to take care of my skin better."
    C "(There's no way I can tell her that my skin only stayed so fair because I used to carry around that all-black, lace-trimmed parasol around with me.)"
    "Tanya eventually drags me back to the scribbles on the sheet of paper between us and the task at hand."
    C "Oh, yeah, I guess that you could do that, but then there'd be a big gap in the middle of the field and the DM won't have any support."
    T "If you're able to throw accurate, long distance passes like you did during the last game, moving the ball up through the dead zone won't be a problem."
    C "Maybe, but I'm not personally even a starting player, remember? And if most of our midfield is pushed so ar forward, it makes it easier for the other team to pass around the DM and into the defensive zone."
    "It takes another half dozen pages full of wavy scribbles, long arcing arrows, and labelled circles for us to come to an agreement."
    "Despite how much back and forth we do, it actually doesn't take all that long. Izzie returns before long to check on how we're doing, but we're already done."
    mi "Ooh, show me what ya got!"
    "Tanya takes the lead lying out our plan while I try to point to each piece in the most sane set of doodle in my notebook."
    scene bg cafeteria with dissolve
    "By the time we get to the cafeteria, Sibyl is already there to meet us."
    S "How did the lacrosse brainstorming session go?"
    T "Well. I've never seen Clover so well-prepared and insightful before."
    "Nodding my head to agree with Tanya appraisal, I give my own thoughts to Sibyl."
    C "Tanya didn't threaten physical violence even once. And even Miss Izzie approved of our lacrosse plans."
    S "I am happy that you both worked so well together, I think."
    C "Sorry that you couldn't be there to help us, though, Sibyl. Did everything go well with the emergency in the library?"
    S "Emer—? Oh, yeah, well, you see... we actually decided that we were going to stick with Dewey after all, so no emergency re-cataloging ever took place!"
    C "Really? That's such a relief."
    T "Clover, you are {b}such{/b} a moron. You're lucky you have the looks to counteract your mental deficiencies."
    C "Hey, that was uncalled-for!"
    "I look to Sibyl to back me up, but she only smiles back sweetly my way. I take it to mean she agrees with me, even if she doesn't feel the need to say it out loud."
    C "Still, it's too bad that you couldn't work with me and Tanya. I feel like we haven't spent as much time together since I started going so hard on lacrosse."
    S "We will have all day to be together tomorrow, Clover. I'm just happy that you and Tanya are getting along so much better."
    C "Yeah, I guess we are."
    "I turn to look at Tanya with the expectation that she'll say the same, but her attention is focused solely on Sibyl, with a steely gaze that could crack even the toughest nut."
    jump practicewatching2

label practicewatching2
    scene bg transition with fade
    scene bg gym lacrosse with dissolve
    "For some reason, I expected that watching the lacrosse team's practice session from the bleachers would be much the same as watching from the sidelines."
    C "From even just this little increase in height, I can see much better how each side are sticking to their formations and game plans."
    S "I feel like I've learned so much merely from watching all of the practices and games that you and Tanya take part in."
    "With the weekend just ramping up into what will turn out to be a beautiful Spring day, it should be no surprise that it's just me and Sibyl sitting by ourselves to spectate the lacrosse team practice in the gymnasium today."
    C "Maybe you should join the team, then? It must be boring sitting up here the whole time with nothing to do."
    S "It's not boring at all, and I do it because I want to support you and Tanya."
    S "Besides, I only come watch on days that I don't have art club. And on the other days, Miss Izzie often sits with me too. She is {b}not{/b} someone you could ever call \"boring\", to be sure."
    "I honestly still am terribly lacking in artistic talent, but Miss Izzie always somehow finds something positive to say about whatever the end result of my efforts may be."
    C "No, I suppose not. I should thank her for looking after my Vertu when I cannot."
    S "She would like that. And if I know her at all, probably make some kind of joke about it too. She's allergic to sincere moments."
    "Sibyl goes quiet as I get drawn into a particularly competitive battle for control of the midfield, but after which she suddenly sparks up conversation again just as Miss Woolsey's whistle blows play to a halt."
    S "You've really changed, haven't you, Clover?"
    C "What do you mean, \"changed\"? I haven't changed at all; I'm still just me, \"Clover\"."
    S "Yes, you're still Clover, but the \"Clover\" I knew months ago would not have sat here with me like this, let alone talk about thanking teachers or anything like that."
    show choice_darkness with dissolve
    menu:
        "\"I {b}so too{/b}\ would have sat with you here!\"":
            hide choice_darkness with dissolve
            C "I {b}so too{/b}\ would have sat with you here!"
            S "Clover, I had to {b}drag{/b} you to sit with me for the first practice session you spectated."
            C "O-Okay, yeah, so maybe I was a little stubborn."
            S "A {b}little{/b} stubborn?"
            C "Okay, fine. Maybe I was a {b}lot{/b} stubborn, {b}sometimes{/b}."
            "Sibyl turns herself near fully to face me, all to give me that look which screams \"be serious now, Clover\"."
        "\"That's not true. I've always liked you, Sibyl!\"":
            hide choice_darkness with dissolve
            C "That's not true. I've always liked you, Sibyl."
            "The moment the words leave my mouth, I feel the sudden need to immediately try to correct myself, but only end up digging a deeper hole."
            C "I mean, like, \"like as a person\", not {b}like{/b}, like, right?"
            C "Because I don't anymore, \"like\" you, I mean."
            S "Clover—"
            C "That's not what I— I {b}do{/b} like you, Sibyl, but not like {b}that{/b} anymore!"
            S "Clover, I understand! Stop worrying so much!"
            S "Besides, you know you're \"not my type\", and there are other girls out there who are way cooler than me."
            "I feel like she's trying to hint something to me with the way she leaves her last thought, but before I can find out about any cool new friends Sibyl may have made, she brings the conversation right back around."
    S "Face it, Clover, you {b}have{/b} changed a lot since you got here."
    C "(Have I really though? Aren't I still the same ex-goth outcast with a messed up personal life?)"
    "I still cringe internally when I remember how hard I tried to re-invent myself, and how spectacularly I failed in that endeavor."
    "The ex-goth part of me may never go away, and the sting of my parents' divorce still feels as sharp as ever, but it's true that I have so much more now."
    "I have my friends, Sibyl and Tanya, and I have lacrosse, the hobby which has rapidly consumed most of my life."
    C "(So maybe I'm a little better off now than I was before, but I can't really have changed all that much in only a few months!)"
    "With the sudden realization that I'm still staring at Sibyl while zoning out in my own head, I turn away from her to face back toward the field of play below."
    C "(I've learned I like girls, for starters. I sure went crazy over Sibyl, huh?)"
    "That's one {b}big{/b} change. And then there's how Sibyl helped me join the Wild Roses, and how she pushed for me to work past my issues with being in the public spotlight too."
    C "(I really owe Sibyl so much, don't I? If I've changed at all, it's only because of {b}her{/b}.)"
    "The attribution feels right when I think it, but as my eyes settle upon the familiar shadow prowling up and down the length of the midfield before me, it suddenly doesn't sit quite so right anymore."
    C "(I didn't even know what my feelings for Sibyl were until Tanya told me.)"
    "Though Sibyl may have taken me to my spectate my first lacrosse practice, but when I was on the verge of dropping out of the team altogether, Sibyl couldn't make me see reason."
    C "(It was Tanya who slapped some sense back into me back then. If it weren't for her, I probably wouldn't be part of the Wild Roses at al right now.)"
    "And back during the whole homecoming debacle, it may have been Sibyl who set us up for it, but it wasn't her there on the stage with me sharing in the spotlight."
    C "(If Tanya wasn't there to hold my hand, I definitely would have perished and been half way to the Great Beyond before my body hit the stage.)"
    "While I'm still nowhere near totally comfortable being the center fo attention and still suffer greatly at the mere thought of presenting in front of the class, it's undeniable that I handle those encounters much better now than before."
    "It' also thanks to Tanya that I'm eating healthier and am unafraid of looking at myself in teh bathroom mirror anymore."
    C "(Tanya has been helping me change for the better this while time, even as she was insulting my intelligence every single day and after declaring her intent to murder me several times.)"
    "It's a tough pill to swallow, but a bit easier after the recent warming of relations following the cessation of our personal Cold War."
    S "She really {b}does{/b} dominate the midfield, huh?"
    C "Huh?"
    "Out of my reverie I'm pulled by the sound of Sibyl's voice next to me. When I turn to look at her, a bright and cheerful grin greets me."
    S "Tanya. You've been following her with your eyes for the last five minutes."
    C "Have I? I was just thinking how... lucky we are to have her on our team. She's a great asset to our team."
    S "Yeah, she does have a great ass, doesn't she?"
    "I nearly choke on my own spit when I hear what I think I hear Sibyl say, and it must show on my face by the way she can barely hold in the giggles pouring out from her lips."
    S "For girls who like that sort of thing, I mean. I totally get it, in a way. She's got a lot of muscle in her legs and glutes."
    "What Vincenza and Tanya once told me about how straight girls might see them as \"boy replacements\" returns to my mind, but the thought that maybe Sibyl might be fooled by it too is new."
    C "Don't tell me you're starting to think that way about girls {b}now{/b}, Sibyl!"
    S "No, no, I'm not! All I'm saying is that I think she's a good catch who will make some lucky girl very happy."
    "Sibyl gives me a little shove of her shoulder against mine to lighten my spirits, having suddenly myself found them to be dropped to dangerously low levels without warning and for no good reason."
    C "(Why should I feel so bad even if Sibyl was interested in Tanya anyway? I'm already over the feelings I had for her!)"
    "Perhaps sensing my distress, as she always seems to be able to do so easily, Sibyl tries again to cheer me up."
    S "Say, Tanya's going to be going to do her usual Saturday thing, so it'll just be the two of us this afternoon."
    S "Shall we go to the library together, just like old times? It feels like it's been ages since we've last passed the time away there without a mound of homework set before us."
    C "Yeah, let's go. After practice is finished."
    "Today might just be practice for the Wild Roses, but tomorrow is a real away game."
    "It leaves a bitter taste in my mouth to have to stay behind while the team goes to face another team without me, but knowing that Sibyl will remain here with me is some consolation."
    jump gymclass

label gymclass:
    scene bg transition with fade
    scene bg gym with dissolve
    C "Stop looking over there and put more of your weight on my ankles!"
    T "You don't know Sierra like I do, Clover."
    "When Miss Woolsey paired me and Tanya for stretching exercises to start our athletics lesson, she also put our Vertu partners together."
    C "After hearing you talk about her every morning? I think I know her well enough."
    "I take a quick glance back toward Sibyl when I finish my first set of sit-ups just to check on her, just in case."
    C "See? Nothing she can't handle."
    "On the face of my Vertu is an expression of utmost evenness and glassy, zoned out eyes as she holds Sierra's ankles firmly to the floor of the gymnasium."
    "Tanya's Vertu, meanwhile, jabbers away about something we can't hear and does absolutely no sit-ups whatsoever."
    T "She hasn't built up a \"Sierra immunity\" like I have."
    "having barely finished my last set of sit-ups without my core giving out, I take the opportunity to switch off with Tanya, who completely outdoes my count without even seeming like she's trying."
    C "(So she's got good core muscles too...)"
    "Nonchalantly, so as to distract myself from pondering just how toned Tanya's abdominals must be, I try to bring conversation up again."
    C "I think this is the first time I've been partnered with you for stretches. You're way better at this than Sibyl. Lately, I've gotten used to being the one to show off."
    T "I'm not \"showing off\", I just have better developed core strength than you do."
    "Tanya barely even seems to be breathing harder when she finishes her first set and replies to me. She just brushes a hand across her forehead and glances back to Sibyl like I'm not even worth consideration."
    C "Sibyl is {b}fine{/b}! Stop worrying about her and pay attention to your exercise partner."
    T "What's gotten into you, Clover?"
    C "What do you mean, \"what's gotten into\" me? You're the one ignoring me while I'm right in front of your face."
    "I have to wait for a reply while Tanya finishes another set of sit-ups. Though she doesn't say anything while in the middle of her exercises, I can tell she's thinking quite a few things, and that only makes me more annoyed when she refuses to elaborate."
    T "I'm done, switch."
    "While I'm still in the middle of my first set, Tanya finally hits me with whatever was bouncing around her brain now that she's the one right-side-up."
    T "Clover, have Vittoria or Vincenza... talked to you about anything strange lately?"
    C "What do you mean? They're {b}always{/b} being strange."
    "I reply naturally between sit-ups but it's only once I finish my first set and oxygen returns to the blood circulating through my brain that I remember I have indeed exchanged some very odd words lately with them."
    C "(There's no way Tanya knows about what happened {b}that evening{/b}, right? No way! Unless they told her...?)"
    C "Why are you asking? They didn't... mention anything about me and them... did they?"
    "With both of us being so unusually vague and evasive in out language, it's no surprise that for the next few moments we both simply stare at one another, as if it were possible to divine thoughts in such a manner."
    T "Why, did they do something to you?"
    C "N-No, nothing at all! They've been keeping their hands to themselves even since that day!"
    T "The day you first arrived? I heard about that."
    C "Yeah, that's the day I'm talking about..."
    "Once again, I launch into a newly re-invigorated set of sit-ups to silence my mouth before I accidentally spill any more beans out of it."
    T "Clover, you're kind of slow on the uptake, so I think it's only fair that I tell you this..."
    T "I think Vittoria and Vincenza, and Sibyl too, are trying to... push us together. In fact, I know so."
    T "Miss Izzie is also complicit, and Miss Woolsey too. In fact, I'm pretty sure that's why she put us together on the lacrosse project and in athletics class today."
    C "No duh, I mean, Sibyl's been trying to get us to stop fighting since the day I got here."
    C "And Miss Woolsey has seen for herself how well we play together on the field when we're not at each other's throats."
    T "No, Clover, you're not getting it! Just... stop for a moment and listen to me, okay?"
    C "Uh, okay?"
    "At Tanya's bidding, I lay back to take well-deserved break from my core strength exercises to hear whatever has gotten her panties in a twist."
    T "They're trying to {b}set us up{/b} together, Clover."
    C "What do you mean? Like, to take the fall for a crime, or something?"
    T "No, {b}romantically{/b}! Honesty, Clover, {b}what{/b} is wrong with your brain!?"
    C "Shut up, there's nothing wrong with my brain!"
    "Finding that Tanya has nothing sensible to say, I resume my exercises, but not without continuing my casual thoughts as they come in."
    C "Besides, trying to set us up that way doesn't make any sense."
    T "That's what I told them!"
    C "Right? Why would I ever want to go out with {b}you{/b}?"
    "The weight around my ankles suddenly vanishes just as I'm reclining back from a sit-up, leaving me terribly off-balance without my feet being grounded to the floor and sending the rest of my body into an awkward backwards cartwheel."
    "When I finally get myself turned right-side-up onto my knees, I whip the hair out of my face and let my exercise partner have it with a light push against her shoulders and some choice words."
    C "What the {b}frick{/b} did you do {b}that{/b} for?"
    T "Is there something so {b}wrong{/b} with me, huh?"
    C "But you were just {b}agreeing{/b} with me!"
    T "I know that!"
    "The the little pushes escalate with each verbal jab back and forth until the flurry of shoves and uniform grabbing sends us both tipping over together sideways onto the floor in a tangle of failing limbs."
    T "Get off me!"
    C "Quit pushing at me!"
    T "Then get {b}off{/b} me!"
    C "I'm {b}trying{/b}!"
    "By virtue of her formidable strength and size, Tanya quickly enough extricates herself from my arms enough to push me on my back against the floor, leaving herself over top of me on her hands and knees."
    C "(Dang it, I could have taken her! And she {b}started{/b} it too!)"
    "It was a clean little scuffle, and I'm not so much angry at Tanya as I am annoyed at how easily she's gotten the better of me, so when it all comes to an end I merely give up and pant ot catch my breath."
    "Tanya does the same. She doesn't look angry as I stare up at her flushed cheeks and fixed gaze staring back down at me — nor does she she even look haughty for having come out the victor."
    C "(Just what is she thinking?)"
    "I never find out."
    mw "Girls, {b}girls{/b}! What is {b}going on{/b} here!?"
    "The sound of Miss Woolsey's raised voice makes us both freeze in place, not even daring to breathe behind our wide eyes."
    "Simultaneously, we both scramble away from one another and back onto our feet in front of our teacher."
    C "N-Nothing happened. I'm sorry!"
    mw "If nothing happened, then why are you sorry?"
    C "(Urgh! She's got me there!)"
    T "We had a little disagreement and it got out of hand. It won't happen again."
    "With how precarious my position on the Wild Roses is already, the last thing I need to do is disrupting my coach's regular lessons with petty fights involving my teammates."
    "But just as I'm about to roll out another round of apologies for being a disruption, I finally catch on to just how many eyes in the gymnasium are turned me way — namely, {b}all of them{/b}."
    C "(Gyeep!)"
    "My arm reaches out instinctively to clutch at Tanya's beside me just in time for my lungs to construct down to the size of walnuts."
    T "Clover?"
    "Tanya is surprised, as she probably should be for the death grip I have against her arm, but Miss Woolsey also takes note. Turning around to face the class, she dismisses them all suddenly."
    mw "That's enough for warm-ups today, everyone please partner up and gather around the volleyball net. I will be there in a moment."
    "I catch only one set of comforting eyes, Sibyl's, as the rest of my classmates wander off to the other side of the gym as instructed."
    "With the source of my anxieties abated, I release Tanya's arm and find that, suddenly, I'm all better once again. The effects of my affliction which I so feared never really materialized."
    C "(It's all in my head. It's {b}always{/b} all been in my head, but it is not more than ever.)"
    mw "Are you all right, Clover?"
    C "(Did she dismiss everyone on purpose, for me? How does she know that about me?)"
    C "Y-Yeah. Thanks, Miss Woolsey."
    mw "I won't have any trouble with the two of you again, will I?"
    "I give Miss Woolsey my utmost promise, and even swear on my lacrosse stick that it'll never happen again, but it's Tanya whom she seems to be most serious in hearing answer her."
    T "I know it may not look very good on the surface, but you have nothing to worry about between me and Clover."
    mw "Are you sure? Did we push you—?"
    T "Naomi, stop. This is just how Clover and I {b}are{/b}. It's nothing you or anyone else did."
    T "But yeah, maybe you and the others could cut it out. It's getting kind of annoying."
    mw "I can talk to Izzie, but you know how the Royals can be."
    T "And I'm pretty sure they've brought Sibyl over to their side too..."
    C "I don't understand a single thing you're saying. Are we in trouble or not!?"
    "Both Tanya and Miss Woolsey glance my way at my outburst, after which Miss Woolsey excuses herself without explaining any further."
    C "So is that it? We got off without even a warning? What was all that about?"
    T "That's it. Come on, let's hurry up and rejoin the class."
    C "Hey, don't ignore me!"
    "Tanya remains rather tight-lipped throughout the rest of our athletics lesson, though admittedly I do entirely forget all about the weird conversation she had with Miss Woolsey as soon as we get into the volleyball game."
    "By the time the lesson is over, I think no more about the little scuffle I had with Tanya than I do about how big of a bruise I have on my wrist from underhand serving the volleyball."
    jump rejoinlacrosse

label rejoinlacrosse:
    "Just as we'd promised Miss Woolsey, Tanya and I come to no more fisticuffs as the week progresses. We fall instead into a rather comfortable routine of early morning practices together, meal times, with Sibyl, and homework all together after class.
    "