label cincodemmayo:
    scene bg transition with fade
    scene bg bedroom with dissolve
    S "Do you really have to run her this hard so early in the morning?"
    T "This much is just to keep her skills sharp until her probation is over."
    S "But she looks like a fish lying on a dry pier."
    "From my vantage spread out on my back in the grass gasping for air, I probably do look like a fish out of water."
    "Determined to ease Sibyl's mind, and to get her to cease giving me such a pitying look, I manage to scrape myself back up onto aching legs once again."
    C "She's right, Sibyl. I can't allow myself to get complacent. I need to be on top of my game when probation expires, so it's hard training and clean, whole foods every day for me from here on out!"
    scene bg cafeteria with dissolve
    T "\"Clean, whole foods\", Clover. You promised."
    C "B-But..."
    S "Oh, just give her this one day, won't you, Tanya? She's literally been talking about them in her sleep."
    "Luckily for me, Tanya is just as weak to Sibyl's demands as I am, so I manage to get a full helping of crisp, warm, delicious churros despite Tanya's protests."
    C "Every day should be Cinco de Mayo."
    "THe kitchen staff has made churros a number of times before, but they go all out today with a special dish of {i}chilaquiles{/i} as the highlight of breakfast and even freshly made {i}horchata{/i} too."
    S "Look how happy she is! Doesn't she look like a rabbit, Tanya?"
    "The way that I attempt to savor the amount of churros I've allotted for myself by making lots of tny nibbles evidently just makes me an amusing sight for everyone else."
    "When I look up from my delicious fried treat, I catch a glimpse of even a small grin touching the corner of Tanya's lips."
    C "(Whatever. I'm not going to let looking a little funny get in the way of enjoying this Mexican feast to the fullest.)"
    scene bg classroom with dissolve
    "The sugar crash lands hard during the very first period after homeroom, but the lecture on quadratic equations is probably just as much at fault as the churros."
    "Sibyl manages to keep me at attention for most of the lecture, and when I start daydreaming about what Mexican food will be served during French lessons, Tanya doesn't hesitate to prod me in the back with her mechanical pencil."
    scene bg gym with dissolve
    S "Maybe Tanya was right. You should have something more wholesome for lunch, Clover."
    C "Nonsense! If I work hard enough in gym class, I can eat whatever I want at lunch with a clean conscience!"
    T "Even if you will burn enough calories to make up for eating churros at three meals in the same day, that much sugar just plain isn't good for you."
    C "Don't you worry, I feel great! Check this out! I'm burning that big breakfast off right now to make room for lunch!"
    "Not only to do I show off jogging in place, but I do it a the same time as a carefully bounce a badminton shuttlecock up and down with my racket at the same time."
    "It's honestly only an accident when it takes an odd bounce off my racket and smacks Tanya right on her forehead."
    C "Sorry. Accident."
    "Sibyl takes a worried glance between me and Tanya, but rather than get angry, Tanya merely picks the shuttlecock off the ground and whips it right back at my face in return."
    T "Watch it, you dullard."
    C "Make me, you brute!"
    "Though we trade bards much as we have always done in the past, the malice just isn't there like it had been before. Even Sibyl is comfortable enough with the exchange now to smile through it."
    T "Watch it, or I will!"
    "We both trade throws pelting each other with the light plastic shuttlecock as Sibyl looks on until Miss Woolsey gives us a stern glare from across the gymnasium as if to say \"quick goofing off and get back to the lesson at hand\"."
    C "So anyway, Tanya, we still need to work on a plan to present to Miss Woolsey by the end of next week."
    T "I know, I've been thinking about it already. I have art club with Sibyl tomorrow, so maybe we can do some brainstorming on Friday?"
    C "Yeah, let's do that!"
    "A distracting motion catches the corner of my eye, which I find to be Sibyl nearby, silently twirling her racket in her hands as Tanya and I talk to one another. When I look her way, she shows me an encouraging smile that wasn't there a moment before."
    C "...And maybe we should do it in the library. Maybe Sibyl can find some books for us to reference."
    S "I'd be very happy to help if I can!"
    "It's at this mention that Sibyl step forward, the small smile now a full grin spread across her face."
    T "Miss Woolsey never said we couldn't enlist some outside help. Besides, you're basically part of the team anyway with how you're always spectating our practices and cheering on our games."
    S "That is exactly right!"
    "We quickly pick back up with our casual volley of the shuttlecock over the net stretched across the gym floor before Miss Woolsey catches us talking again, but all the while my thoughts are left on Sibyl."
    C "(Is she feeling... left out?)"
    "It's no overstatement to say that I'm maybe spending more time with Tanya now than I am with Sibyl, not counting the time we spend asleep in the same room."
    "It was Sibyl who encouraged me to join the lacrosse team and get closer to Tanya, and I don't think she is showing any regrets about that, but it also must be tough for her to have her two best friends share a hobby in which she cannot participate."
    jump twinsinterlude

label twinsinterlude:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "With Sibyl and Tanya at their art club on Thursday, I occupy the hours until meal time with the homework that's been piling up on my desk."
    "A fill-in-the-blank worksheet from science class sticks out among the rest, and I'm actually not that bad with biology, so it's with aplomb that I re-shuffle that sheet to the top of the stack to get to work."
    C "(Lipids. Mitochondria. Chloroplast.)"
    "Things go nice and smooth until I get deeper into the worksheet, to parts of lessons for which I may have been distracted with other drama in my life to remember all that well."
    C "(Cell cycle. I can do this. That's \"interphase\", \"mitosis\", \"telekinesis\"...)"
    "I happily flourish my pencil along the last letter of the last answer, but it becomes clear when checking over my work that maybe I have been more distracted lately than is good for me."
    C "(No, that's not right. Where are my notes on the cell cycle?)"
    "As I flip through my notebook, I fail to find any note about that lesson at all, and resort to having to open my textbook to find the right answers."
    C "(How did I manage to smash \"telophase\" and \"cytokinesis\" together?)"
    "With one worksheet finished and trigonometry peeking out behind it, I take the opportunity to stretch my legs instead with the excuse that sitting in one place too long is probably bad for my health after all."
    scene bg dorm with dissolve
    "Where I am going is anyone's guess. After appreciating the warm rays of sun shining through the large dorm windows for a few minutes, I make off down the hallway in an equally aimless manner."
    scene bg mary with dissolve
    "My feet mindlessly lead me out the doors of the dormitory and, as best as I can tell, toward the school building likely in pursuit of where I know Sibyl and Tanya remain."
    "\"Psst. Clover.\""
    "I never make it far enough to reach the school building, however. A quiet summons snaps the background hum of outdoor activity on the academy's grounds, though I cannot find the source."
    "There's a moment when I turn my head toward the large statue in the garden where I think I must have instead fallen asleep rather than go for a walk, but realize it's the girl in pink uniform sitting at the base calling to me and not the Virgin Mary."
    C "What are {b}you{/b} doing here?"
    "A queer sensation comes over me as I approach Vincenza sitting under the statue's watchful vigil, which I quickly realize is because there isn't another girl sitting right beside her."
    C "(Is this some kind of trap? Is Vittoria going to jump me from the shadows?)"
    "I lean aside to peer around the back of the statue to find only yet more cheerfully colorful flowers smiling up at me from their earthen beds."
    C "Where's the other one?"
    O "Not even months of watching over you and one unforgettable afternoon together is enough for you to treat your {i}senpai{/i} with proper respect?"
    show choice_darkness with dissolve
    menu:
        "\"My {b}what{/b}?\"":
            hide choice_darkness with dissolve
            C "My {b}what{/b}?"
            O "All I'm saying is, even Tanya calls me \"Ouji-onee-sama\" and it only took a tiny amount of blackmail."
            C "Vincenza, I have {b}no idea{/b} what you're saying."
            O "I just wish you were nicer to me and my sister, Clover. Is that so much to ask?"
            C "But you're both always so {b}irritating{/b} with that \"Prince and Princess\" thing you do. I think I deserve to be able to fight back."
            "I expect Vincenza to object, but surprisingly actually giggles at my questionable logic."
            O "So your response to our little playacting is to yourself play the part of the irascible {b}tsundere{/b}? How adorable."
            C "{b}Stop{/b} using words I don't understand!"
        "\"What \'unforgettable afternoon\'? I don't know what you're talking about.\"":
            hide choice_darkness with dissolve
            C "What \"unforgettable afternoon\"? I don't know what you're talking about."
            O "Don't try to play ignorant now, Clover. You may try to pretend that day never happened, but the next girl you kiss will only make you remember that it was {b}me{/b} who took your first."
            C "You're wrong! You {b}weren't{/b} my first kiss!"
            "Smugly, I refute Vincenza in triumph, only for her to smile just as smugly right back at me."
            O "So you {b}do{/b} remember now, huh?"
            C "N-No, I just..."
            C "Okay, fine, but {b}I{/b} didn't touch you or your sister like that; it was only you two doing stuff. And it doesn't count anyway because I don't {b}love{/b} either of you."
            O "Well if that's how it works, we're both pure virgin maidens then, aren't we?"
            C "(Is she seriously saying she's never been in love? Or just that she's never done {b}that{/b} with her?)"
            "My expression softens as I puzzle through the hidden meanings behind the joke, which appears like jovial when viewed from deep within Vincenza's eyes."
        "\"You're not \'watching over me\' at all! I'm just another pawn in you and your sister's games!":
            hide choice_darkness with dissolve
            C "You're not \"watching over me\" at all! I'm just another pawn in you and your sister's games!"
            O "Now, Clover, that I must protest! You are not a \"pawn\" of any kind, nor do Vittoria and I play \"games\"."
            O "There are students here at Prudence Prep who require more attention than most, and those often require a unique approach that we are most well suited to provide. You are one such case in both respects."
            O "Please rest assured that, no matter how much you may fail to understand our methods, my sister and I are {b}on your side{/b}."
            "A small snort blows through my nostrils at this comically farcical statement, to which Vincenza takes a minor degree of offense."
            C "I don't believe you."
            "Though even as I say it, I do consciously remember with how much respect Sibyl treats Vincenza and her sister Vittoria despite how little she also cares for their theatrics."
    C "A-Anyway, where {b}is{/b} your sister? It feels weird seeing you alone like this."
    O "Vittoria is resting in the nurse's office with a lightly strained ankle."
    C "And you're not there with her? You're not going to wither if you stay apart from one another too long?"
    O "She sent me away."
    C "That's not going to do you any favors with your fans, \"Prince\". Shouldn't you be guarding her door or something?"
    O "Oh, I played the part all right. Our whole athletics class saw me princess carry her out of the gymnasium, even if they didn't see my legs go all wobbly just outside the door before we both ended up on the floor."
    O "No, Vittoria thinks she knows best because she's the older twin between us, like she thinks a minute longer makes her more mature than me."
    O "Today, that means sending me away because she doesn't want me to be stuck sitting around in the nurse's office too."
    C "And... how do you feel about that?"
    "It might be a probing question, but Vincenza seems like she's in the mood to unload a little of her emotions, and I am certainly getting more than a little interested in their relationship now."
    C "(I thought the two of them were of the exact same mind before, or close enough to it, but they might actually be two different people after all.)"
    O "I want to stay by her side. I don't care if it's boring in the nurse's office or about whatever the student council has happening."
    C "I'm sure she has her reasons. I mean, if you're both close enough to have sex together with another girl... Well, I don't know exactly what to say about that, but you probably understand."
    O "Vittoria doesn't like to say \"have sex together\". She prefers \"have sex with the same girl\"."
    C "What's the difference?"
    O "Less guilt about us enjoying intimacy together."
    C "I don't get it. Just don't have sex with someone like me if you're going to feel guilty about it."
    O "...Look, Clover, the point is that Vittoria doesn't like people asking those kinds of questions, and you shouldn't be asking them either way."
    C "So if I go ask her about it right now..."
    O "I'm not joking, Clover. You {b}won't{/b}, right?"
    C "I'm hearing you loud and clear, Vincenza."
    "Maybe it's because English is her second language, but she doesn't even pick up that my response was entirely absent of any promises to do a she asks."
    C "Well, I should be going to pick up Sibyl and Tanya soon I think."
    O "Tanya? I won't keep you waiting. Go get her!"
    C "What do you mean? Their club hasn't even let out yet?"
    "I turn away from Vincenza off toward the school building. Though I tell Vincenza that I am going to pick up Sibyl and Tanya from their club meeting, but it's the nurse's office that is foremost in my mind."
    scene bg nurse hallway with dissolve
    "When I arrive at my destination, I find at least a half dozen students crowd around the door to the nurse's office, all eager to sneak peek through the glass window to the inside."
    C "Umm... excuse me."
    "The crowd parts when I push myself through them toward the door. Their looks range from surprised to indignant."
    C "(How do Vittoria and Vincenza put up with their fan clubs?"
    "This kind of attention sent Tanya spiraling into depression and would probably outright kill me."
    scene bg nurse with dissolve
    C "I-I'm here to see Vittoria."
    nurse "If you are not injured, please wait outside!"
    "The nurse is all over me when I first step into the room. Her words might be polite, but the frazzled way she says them as she simultaneously tries to herd me out the door tells of another story entirely."
    H "Is that Clover? I'd like to speak to her."
    "The nurse sighs dejectedly but does not fight Vittoria's wishes. Instead, she steps aside to allow me past her toward the bed where Vittoria lies pensively."
    nurse "Very well. It's about time that the others disperse from outside my office, however."
    "The nurse slips past me and out the door while I take a seat conveniently placed next to Vittoria's bedside."
    H "Let me guess: you need some help with Tanya. Don't worry, I'll make sure everything works out between you both!"
    C "What? No, I don't have any problems with Tanya. We haven't even fought once since what happened the other day."
    H "Is that so? Well, that's a start. What are you doing here if it's not to get advice about Tanya?"
    C "I ran into Vincenza outside and she told me that you were in here."
    H "So you came running to check on me? What wonderful juniors I have!"
    C "Y-Yeah..."
    "I really did intend to come in here and ask her the questions that Vincenza told me not to ask, but now that she's giving me this unintentional guilt trip it's hard to come out with it."
    C "She said something about your ankle?"
    H "Yes. We simply chased after the same tennis ball at the same time and ran right into one another! I took an odd step and this was the result."
    H "It is quite a minor injury. I will be back to my student council duties shortly, and in the mean time I have instructed Vincenza on how to fill in for me."
    C "So your normal student council work is moping under the statue out in the garden?"
    "There's a moment where Vittoria processes what I'm saying, upon which her expression turns sour."
    H "I gave Vincenza {b}specific{/b} instructions!"
    C "Well, she's not following them. She's just kind of upset about how you kicked her out of the nurse's office."
    H "God knows I would rather be out there with her and not lying in the nurse's office, but {b}someone{/b} has to do our nightly rounds!"
    "I shrug my shoulders casually. Whatever their duties as President and Vice President entail, it's not my concern whatsoever, and I'm not volunteering to help out with them. I came here for a different reason."
    C "Why did you and Vincenza have sex with me together?"
    H "This again? Clover, you {b}literally begged us{/b} to do it. Don't go regretting it now after we tried to warn you."
    C "I didn't say I {b}regret{/b} it, okay?"
    H "So what? Did you come here because you want to go again? You picked the absolute worst day to suddenly show an interest again, Clover."
    "Vittoria takes what I'm asking a completely different direction than what I intended, but it's hard to just come out and tell her that's not what I meant when just the mere suggestion turned her gloomy expression into such a bright, blushing grin."
    H "If Vincenza were here and I weren't stricken lame, we'd definitely—"
    "I cover my eyes to muffle the sounds of whatever shocking things Vittoria says she wants to do to me, but I can still see her lips move and vaguely make out some of the details."
    "When she finally finishes speaking, I release my ears, at which points she tacks on an additional offer for me to consider."
    H "Maybe this time you want to try it on us too. Don't worry, I can teach you exactly how to do it just perfectly, and Vincenza won't mind playing test subject!"
    C "U-Umm, actually, Vittoria, that's not what I was asking..."
    H "Eh?"
    "The thought of maybe going another round with Vittoria and Vincenza does kind of excite me at some level, but my memory of the hollow feeling which came after the lascivious high eclipsed sours the expectations."
    C "I mean, like, why you do it {b}with your sister{/b}. You didn't even entertain the thought of doing \"it\" without Vincenza with you. She said I shouldn't ask you about it, but I never promised her not to."
    "Vittoria quickly turns more beet red to the face than when she was actively detailing how she and Vincenza were going to go about {i}bleep{/i}ing my {i}bleep{/i} and other such lewd acts."
    H "W-We don't— I mean, when we get in the mood, it's better that there's... another girl in the middle, right?"
    "Vittoria stumbles over her word in rapid succession in a way that I've never seen out of her before. It's rewarding to see someone who usually teases me so mercilessly fumbling over herself, even if I have no idea what she's rambling on about."
    "She does eventually collect herself enough to try to reply in a more coherent way which sounds more diplomatic and less emotional than her last."
    H "Listen, Clover, I don't know what Vincenza told you, but she and I are twin sisters, and things which may not seem normal to normal sisters do not feel so strange when we have been so close by one another our whole lives."
    C "So... what you're saying is that it's not that awkward between you when you do it?"
    "With a heavy sigh, Vittoria merely says \"yes\", and repeats it again right after."
    H "Yes. When we make love to another girl at the same time, there's nothing awkward about it at all. If that's all you were wondering about, I'm glad that was cleared up, Clover."
    "I've always thought Vittoria was the maybe slightly less weird of the two, but Vincenza was right that something about it really set her off into the loco zone."
    C "Huh. Okay."
    H "But if things don't work out with Tanya, the offer stills stands for us to..."
    C "Tanya? What about her? Are you and Vincenza doing {b}that stuff{/b} with her too?"
    H "I meant between {b}you{/b} and Tanya. We heard from her that you finally apologized so—"
    C "What do you mean, {b}finally{/b}? She apologized to {b}me{/b} too!"
    H "If I know both of you, I do not doubt both of you had a lot to apologize for."
    H "Now that you both {b}have{/b} apologized, however, it is the perfect opportunity to take your friendship to the next level, don't you think?"
    C "Yeah, we are?"
    H "You {b}are{/b}!? She didn't tell us that!"
    C "Yeah. We've more or less stopped fighting and we're going to be working together on drafting plans to re-work the Wild Roses' midfield strategies tomorrow in the library."
    H "Oh, yeah?"
    "Vittoria's tone falls flat as she droops back into the nurse's office cot."
    C "Yeah. Me, Tanya, and Sibyl are going to meet in the library tomorrow after class to start brainstorming."
    H "Hmm..."
    "The door suddenly clicks back open, and in walks the nurse again, who looks just as frazzled as when she left but now pushes along a wheelchair before her."
    H "Please excuse me, Clover. Nurse Hamilton has graciously offered to wheel me back to my room in the absence of my sister."
    C "R-Right... I have to go meet Sibyl and Tanya anyway."
    scene bg hallway with dissolve
    "I actually don't have to meet them at all. The plan was for me to spend all afternoon working on my homework and then they'd come pick me up before dinner, but I've already wasted the entire afternoon and am near their club anyway."
    jump brainstorming

label brainstorming:
    scene bg transition with fade
    scene bg classroom with dissolve
    "When at last we are finally dismissed from the last lesson of the day on Friday, I'm the first to hop out of my seat."
    C "Hurry up, we only have three hours before the opening of the cafeteria for dinner!"
    "No, it's not that I am rushing to get to the cafeteria three hours early, but that I'm just so full of ideas for how to manage our lacrosse team's midfield that I want to get started as quickly as possible."
    C "(And end as close to on time as possible we so don't get stuck with the leftover in the cafeteria, of course!)"
    T "Relax, Clover, we have plenty of time today, and all of this weekend, not to mention the entire next week too."
    "After successfully pulling Sibyl out of her seat by her hands, I turn to prance around Tanya impatiently while she seemingly goes extra slow on my account."
    S "What a reversal this is! You looked on the verge of death itself during our etiquette lessons, and now you're too giddy for your galoshes!"
    C "I've been working on plans in my head for days now! I don't think I'll be able to cram any more math and science in there until I get them out!"
    "At that moment, Tanya finishes packing up her things and steps over to join us with a perfectly prepared quip at my expense."
    T "So you {b}do{/b} have something in your head? I could have sworn it was empty!"
    "Sibyl gives Tanya a light rebuke in the form of a small disapproving glare, but I don't really care about what Tanya has to say about my brain at all."
    C "(Once she hears my plans, there'll never call me stupid ever again!)"
    scene bg hallway with dissolve
    "I quickly proceed to nearly drag Sibyl and Tanya to the library with the pace I set going forward, but get stopped on the route there by a pair of roadblocks rather resolutely set in our way."
    S "Good Heavens! What has happened to you, Vittoria?"
    H "Do not worry on my behalf, Sibyl. It is merely a small sprain which will heal in a few days' time."
    O "Everyone's favorite princess will be safely in my care until her injuries have healed."
    "Vittoria, supported on one side by a crutch, takes the opportunity of their grandiose speech to lean aside against her sister to clutch an arm to her chest."
    "The gaggle of girls watching from just down the hallway erupt into a quiet murmur at the action, which was no doubt intended to set their fancies ablaze more than the three of us here."
    S "Of course. Where would a princess be without her prince?"
    "I know Sibyl doesn't actually believe their act to be real either, but she still replies in kind with a slight glance toward the twins' admirers grouped just away."
    C "(How can those girls seriously believe any of this act is real? It's so {b}cheesy{/b}.)"
    T "I don't know what scheme you're up to right now, but I'm not playing it right now."
    "Addressing the twins, Tanya chooses to break the mood and get right down to whatever business she thinks there must be happening here."
    O "You have no need to fear, Tanya. Today we are here for Sibyl."
    S "Me?"
    H "Yes. The library has suddenly found need of an {b}immediate{/b} re-cataloguing, and we would like to request your help."
    T "The library? But that's where we were going to do our brainstorming!"
    S "Re-cataloguing? I wasn't aware of anything like that."
    O "I'm afraid so. But not to worry, Clover. We have already arrange for you and Tanya to use Miss Izzie's art room for your plans this evening."
    T "Miss Izzie?"
    C "Umm... okay, I get the library is important, but Sibyl was going to help us with our planning today."
    H "I'm afraid it's dreadfully important, right Sibyl?"
    S "Hmm?"
    O "That you leave Clover and Tanya alone, while you come with us to assist with the emergency re-cataloguing of the library."
    S "Oh. Oh! Yes, of course!"
    "Turning to face me and Tanya, she places her hands together as if begging which she explains that she actually totally forgot about the emergency re-cataloguing and that she definitely needs to help right away."
    S "So, actually, there was a new library system that was published the other day, the... Doo-wop Decimal System. It's real cutting edge stuff, and you'd probably hate it, so go along with Tanya. We'll catch up at meal time!"
    C "There's {b}another{/b} one! But I just finally learned {i}Dewey{/i}!"
    "Perhaps equally exasperated with the sudden need to learn and entirely new library organization system, Tanya punctuates my exclamation with a heavy sigh of her own."
    T "Come on, Clover, let's just go. We're out-numbered here."
    "Tanya yanks me away by one of the straps on my skirt before we can even say good bye to Sibyl."
    scene bg artroom with dissolve
    "When we first enter the art room, the calming sounds of smooth jazz shuffle pleasantly through my ear drums, and then Tanya breaks the ambiance to draw my attention elsewhere."
    T "What's with the candles? Are you trying to summon a succubus again, Izzie?"
    mi "No! And it would have worked too if Nao-chan didn't chicken out!"
    "All the desks save one with a chair on either side have been moved to the back of the art room, and around the double seated desk lie five candles in a circle around them, of varying colors."
    C "This is a pentagram ritual, not a summoning circe, and barely even that. The blue candle needs to be where the orange candle is, and where that would leave the orange candle needs to be replaced with a white candle."
    "Having participated in my share of pentagram rituals, this much is obvious to me as first glance, but I only realize how crazy I must sound when I notice both Tanya and Miss Izzie staring at me in stunned silence."
    C "(Dang it, Clover, that stuff was supposed to stay buried in your past!)"
    C "...Or something. I read a book about it once."
    mi "Can I borrow Clover next time we try it, Tanya?"
    T "Why are you asking {b}me{/b}? I don't own her."
    T "And I see what you're trying to do here, by the way. I {b}told{/b} you all that it's not like that."
    mi "What {b}I'm{/b} doing? Why, I am helpfully providing a place for two of my students to work on their extra-curriculars at the request of the Student Council!"
    "Nevermind whatever Tanya and Miss Izzie seem to be arguing about, I get right to work unpacking my bag, prompting Tanya to do the same after some feet dragging."
    C "Come here and brainstorm with us, Miss Izzie! I'm sure you have lots of good ideas too!"
    "I'm totally confident in my plans, but it doesn't hurt to have someone with experience on your side, and Miss Izzie is probably the most fanatic supporter of the team out of anyone."
    "She looks like she wants to yank a chair right up the table with us, but with a bite to her lower lip she only tells us that she has other matters to attend to and cannot join in."
    mi "I have a very important staff meeting starting exactly {b}right now{/b}."
    T "How convenient."
    "Miss Izzie's shadow has already left disappeared from the doorway before Tanya even finishes her rebuttal."
    C "Miss Izzie sure is strange."
    T "You don't know the half of it."
    C "I guess you do see a lot of her from the arts club, huh?"
    T "Yeah, I see her a lot in the arts club."
    "After confirming exactly what I though, Tanya goes about extinguishing the candles,a nd is about to shut off the smooth jazz before I stop her."
    C "Keep it on. I like background music when I'm thinking."
    "Without being able to bring my smartphone with me outside the bedroom, I am unable to play my music while studying. Even when I'm at my desk in my room, I still don't put it on speaker like I used to out of respect for Sibyl."
    C "(Sibyl probably wouldn't appreciate the louder screamo bands I was fond of in middle school. It's probably time that I get into more adult music like jazz.)"
    C "So here, take a lok at this."
    "When Tanya finally reaches her seat opposite mine at the desk, I pull out a pen and flip to a blank page in my notebook to illustrate the plans I've been cultivating in my head."
    C "Before that last game, we've been mostly playing two-way midfield all the way through, right? But in that match, we switched to an offensive and defensive setup which worked well."
    T "Uh huh."
    "As I scribble my thoughts out onto the crude sketch of a lacrosse field, I suddenly realize that what is in my brain isn't all that well visualized by the mad scribbles coming out of my pen."
    C "I think we should keep at it. We keep one offensive midfielder and station here {b}here{/b}, one defensive midfielder stationed here, and we keep one two-way in the middle."
    T "To cover the OM and DM on either side of the field."
    C "Exactly!"
    T "And the DM gets the long stick?"
    C "Of course!"
    "Happily enough, Tanya appears to be following me step for step even with my sub-par drawing skills."
    C "(Is this how Vittoria and Vincenza feel with on another all the time?)"
    T "It's a good plan, Clover. I assume you put yourself into the DM position here?"
    C "Yeah. I was thinking you'd play well in the two-way role."
    T "Even though I'm the best shot taker in our midfield lineup?"
    C "Well, that's true, but... you're also the strongest player we have when it comes to having the stamina to play two-way the full sixty minutes."
    C "Even if you won't be able to get so many shots in, I think the two-way is the most important player on he field since she's covering for the OM and DM on pressure, as well as keeping herself open to intercept passes or advance the ball."
    "Tanya's marble-like brown eyes flicker over the scribbles between us as she pauses to think in silence. After a moment she reaches out to tap my hand, which confuses me until I realize she just wants my pen."
    T "You have us more or less lined up in the midfield. What if we put two OMs up font in parallel with the DM in back, forming a triangle like this?"
    "Dreadful memories of geometry class return to me as Tanya scribbles a triangle over my earlier scribbles, but it's something else entirely that captures my attention."
    C "You smell good."
    T "What?"
    "With Tanya having leaned closer to me over the desk to draw on my notebook, I get a pleasant whiff of something earthy and floral radiating off of her. I have to lean in slightly further just to catch it again."
    T "S-Stop that!"
    C "Lavender and... something. Is that your shampoo?"
    T "Lavender and rosemary! It's my SPF moisturizer."
    T "You should be wearing some too, Clover. It's more important than ever to take care of your skin as we approach Summer and we're spending more time outside."
    C "You're probably right. My neck was that kind of red that goes white when you press on it after the last game."
    T "That's {b}sunburn{/b}, Clover!"
    C "But it din't hurt. It was just kind of red."
    T "You really need to go down to the academy store and buy some sunscreen. It's a miracle your skin has remained so firm and unblemished when you mistreat it as much as you do."
    C "(She's complimenting me! {b}Tanya{/b} is complimenting me.)"
    "I let myself soak into the rare moment of praise from Tanya. Even if it is delivered by way of chastisement, I know that she only means well in wanting me to take care of my skin better."
    C "(There's no way I can tell her that my skin only stayed so fair because I used to carry around that all-black, lace-trimmed parasol around with me.)"
    "Tanya eventually drags me back to the scribbles on the sheet of paper between us and the task at hand."
    C "Oh, yeah, I guess that you could do that, but then there'd be a big gap in the middle of the field and the DM won't have any support."
    T "If you're able to throw accurate, long distance passes like you did during the last game, moving the ball up through the dead zone won't be a problem."
    C "Maybe, but I'm not personally even a starting player, remember? And if most of our midfield is pushed so ar forward, it makes it easier for the other team to pass around the DM and into the defensive zone."
    "It takes another half dozen pages full of wavy scribbles, long arcing arrows, and labelled circles for us to come to an agreement."
    "Despite how much back and forth we do, it actually doesn't take all that long. Izzie returns before long to check on how we're doing, but we're already done."
    mi "Ooh, show me what ya got!"
    "Tanya takes the lead lying out our plan while I try to point to each piece in the most sane set of doodle in my notebook."
    scene bg cafeteria with dissolve
    "By the time we get to the cafeteria, Sibyl is already there to meet us."
    S "How did the lacrosse brainstorming session go?"
    T "Well. I've never seen Clover so well-prepared and insightful before."
    "Nodding my head to agree with Tanya appraisal, I give my own thoughts to Sibyl."
    C "Tanya didn't threaten physical violence even once. And even Miss Izzie approved of our lacrosse plans."
    S "I am happy that you both worked so well together, I think."
    C "Sorry that you couldn't be there to help us, though, Sibyl. Did everything go well with the emergency in the library?"
    S "Emer—? Oh, yeah, well, you see... we actually decided that we were going to stick with Dewey after all, so no emergency re-cataloging ever took place!"
    C "Really? That's such a relief."
    T "Clover, you are {b}such{/b} a moron. You're lucky you have the looks to counteract your mental deficiencies."
    C "Hey, that was uncalled-for!"
    "I look to Sibyl to back me up, but she only smiles back sweetly my way. I take it to mean she agrees with me, even if she doesn't feel the need to say it out loud."
    C "Still, it's too bad that you couldn't work with me and Tanya. I feel like we haven't spent as much time together since I started going so hard on lacrosse."
    S "We will have all day to be together tomorrow, Clover. I'm just happy that you and Tanya are getting along so much better."
    C "Yeah, I guess we are."
    "I turn to look at Tanya with the expectation that she'll say the same, but her attention is focused solely on Sibyl, with a steely gaze that could crack a tough nut."
    jump practicewatching2

label practicewatching2
    scene bg transition with fade
    scene bg gym lacrosse with dissolve
    