label sunday_after_date:
    scene bg transition with fade
    scene bg black with dissolve
    "The day after our first date, Sunday, starts not at all goes as it normally does."
    scene bg bedroom night with dissolve
    "To begin with, I expected to have some really wild dreams after the really wild day I had with Tanya, but they all turned out to be extremely normal. All I dreamed about was laughing and climbing trees with Tanya."
    C "(I don't remember anything about what me and dream-Tanya talked about, but I remember I felt like I was having a good, and I think I she taught me how to climb trees for real...)"
    scene bg hallway with dissolve
    "My overactive imagination suddenly being normal-active was just the first oddity. Now, as I stand in the hallway outside the locker room waiting for Tanya to arrive for our customary morning training session, she isn't showing her face."
    C "(The birds are all flying from left to right! I hope Tanya is okay.)"
    "I turn away from the windows before I catch and glimpses of further bad omens, just to be safe."
    C "(She's probably just embarrassed to be seen after what happened yesterday. Yeah.)"
    "Thankfully, I see Tanya come walking down the hallway towards me soon enough, though easily over 20 minutes later than our usual meeting time. I run right up to her without delay."
    C "You're {b}late{/b}, Tanya! Is everything okay!?"
    T "I texted you this morning?"
    C "You did!?"
    T "Yeah."
    C "Guess I didn't see it."
    T "Everything is fine, Clover, and..."
    C "...And?"
    "Tanya suddenly goes quiet, eyes darting back down the hall then toward me, clearly anxious about something."
    C "(What is it? Is she being followed? Is there a ghost!?)"
    "My question is answered quickly enough, as Tanya darts forward to press a peck of a kiss to my surprised lips amidst a deep flush of bashfulness."
    T "Good morning."
    C "(What. Was. {b}That?{/b})"
    "Grabbing Tanya's shoulders, I shake her about a little just to be sure the image before me is real and corporeal."
    C "Where is the {b}real{/b} Tanya!? What have you done with her, skinwalker!?"
    "I feel around \"Tanya\"'s bewildered face for any seams or telltale signs that the Tanya I know has been replaced with this absurdly cute creature, but find only her flawless skin well-attached to her correctly-oriented skull."
    T "Clover, get ahold of yourself before I slap some sense into you!"
    C "(Whoa, false alarm! It's the real Tanya after all!)"
    C "Sorry, it's just... the birds were all flying left to right and you didn't show up on time..."
    T "What are you yammering about!? Was my kiss {b}so bad{/b} that you needed to freak out at me!?"
    C "No the kiss wasn't— Just forget I said anything about birds."
    C "Your kiss was nice, but, umm... unexpected. I wasn't ready for it."
    T "Are you... ready for it {b}now{/b}?"
    "I nod silently, and after a quick glance down the hallway to be sure no one is looking, we share another quick kiss that I can actually appreciate this time."
    C "(Who new a casual \"good morning\" kiss could be so electrifying?)"
    C "So... why were you late this morning anyway?"
    T "I, uhh, went to the chapel to offer thanks to God."
    C "You did!? What for!?"
    T "I recently realized that God has been using this extremely irritating but super hot girl to test my resolve, and that getting to make out with her recently must be my reward for putting up with all her bullshit."
    C "{b}Tanya!{/b} What the heck!?"
    "I turn and give her a soft punch to her shoulder as we slowly make our way to the locker rooms, which Tanya quickly mimics in tone with my name and punches me right back."
    C "I don't sound like that!"
    T "You {b}so{/b} do."
    scene bg lockers with dissolve
    "The good mood carried through as my badge into the athletic clubs' locker room, only to stop when we spot someone sitting out on the bench in what should normally be an empty locker room, clearly waiting for us."
    H "Good morning, Tanya."
    T "Ugh."
    "Tanya's displeasure at seeing Vittoria is clear. Just as I'm wondering where Vincenza might be, the sound of the door closing firmly shut behind us rings out, followed by her voice coming up behind Tanya."
    O "Did you think you could give us the slip that easily?"
    T "How did you even get in here? This locker room is only for sports club members."
    H "We have our ways..."
    O "More importantly, why didn't you {b}tell{/b} us you were going out with Clover?"
    "The twins slowly circle Tanya like sharks, taking turns addressing her sharply, while for her part, Tanya mostly takes it in stride with dismissive annoyance."
    C "(Is this {b}bullying{/b}? I thought they were friends!)"
    T "It's none of your business, Vincenza, or yours, Vittoria."
    O "That's \"Ouji-onee-sama\" to {b}you{/b}, Tanya."
    H "And don't forget your \"Hime-onee-sama\" either."
    C "(What the heck are they saying?)"
    H "You {b}knew{/b} we were trying to set you and Clover up."
    O "We {b}saw{/b} the {i}bacio alla francese{/i} yesterday."
    C "(Huh?)"
    H "How long have you and Clover been dating?"
    O "And why have you been keeping it from us?"
    "Having had quite enough of this grilling, I step forward to confront the twins."
    C "Back off! Tanya hasn't been keeping {b}anything{/b} from you; that was our {b}first{/b} date!"
    "Both Vittoria and Vincenza step back from Tanya in surprise, turning their attention with renewed interest toward me instead."
    C "(Oops.)"
    O "That was your {b}first{/b} date?"
    H "{b}Cataglottism{/b} so quickly?"
    C "(Why are they always throwing out weird foreign words around me!?)"
    "Thankfully, Tanya hits right back at them, drawing the twins' scrutiny once again."
    T "I know for a {b}fact{/b} that you've both done much more than French kissing without {b}any{/b} dates."
    H "We're only having a little fun when we do it."
    O "It's different when you have real feelings."
    H "You {b}do{/b} have real feelings for her, right?"
    "Perhaps catching on to what the twins are saying, I offer up myself as bait to take the heat off of Tanya, even if it means having the pressure placed back on me."
    C "I-I was the one who wanted to kiss, so stop being so mean to Tanya!"
    O "{b}Clover{/b} initiated it?"
    T "You can't honestly blame me. When a girl {b}that{/b} beautiful {b}asks{/b} for it, how could I possibly refuse her?"
    "The twins both glance my direction with a knowing smile, but thankfully do not say anything more to Tanya about what happened that day after Sibyl rejected me."
    H "Truly, it is impossible."
    O "We understand completely."
    C "Okay, so maybe I'm not ugly or anything, but I'm not really {b}that{/b} gorgeous, am I?"
    "All three of the girls in front of me exchange glances in complete silence, completely unable to meet my questioning scan of their faces."
    C "Are you saying all I have to do is flirt a {b}little bit{/b} and you'll all do {b}anything{/b} I ask?"
    T "...Maybe not {b}anything{/b}."
    "Tanya might be trying to downplay this new revelation, but the twins are less circumspect."
    H "Heavens forgive us."
    O "We've created a monster."
    "The twins quit circling Tanya and assume their standard posture side-by-side one another in a more casual stance. They even apologize to Tanya for assuming that she had been keeping them in the dark about an ongoing relationship between me and her."
    T "I wanted our relationship to develop at our own pace — {b}without{/b} any outside interference. We would have told you when the time was right."
    C "See!? Tanya had good reason not to have told you about our first date beforehand!"
    H "Did you really expect us to interfere with your date?"
    O "After how much we've been trying to push you toward one another?"
    T "You {b}did{/b} interfere with our date, didn't you?"
    "There's a certain sharpness to her accusation, clearly demonstrating how Tanya is still bothered by what happened while we were kissing on the tree limb."
    O "You never showed up to the meeting. We were honestly just trying to find out what happened to you."
    O "The Grand Macaron said we should give you both privacy when we did finally find you and Clover."
    C "Who?"
    "The twins, and most annoyingly, Tanya as well, just keep right on ignoring me. I don't try very hard to force myself into the conversation while I think this is all still part of their apologies, but I do get a little irked at teh behavior."
    C "(I feel like I deserve an apology too, considering I was also interrupted!)"
    H "But there really is no stopping Izzie when she's set in her mind."
    T "She's almost as bad as both of you."
    H "Oh, {b}please{/b}. Get her to tell you some of the tales from her heyday."
    O "So basically what we are saying is that it's not {b}our{/b} fault at all."
    T "What do you think, Clover? Should we accept their apology?"
    "Tanya finally sees fit to drag me back into the conversation — both by her question toward me and literally by pulling my arm to shift my body closer to her side."
    C "Maybe... on one condition."
    "The gears start spinning delightfully in my head trying to come up with all the terribly satisfying things I could make the twins do, but rather than eventually grind to a halt they just keep spinning without ever finding an answer."
    C "(I need more time to think about this!)"
    H "Might I suggest \"sexual favors\"?"
    "Vittoria is clearly smiling directly at me when she offers her suggestion. Vincenza counters with another, directed at Tanya."
    O "How about... \"humiliating my bullies\"?"
    "The prospect of really sticking it to the girls who bullied Tanya does seem to interest her, but she instead chooses the higher road while I'm still stuck myself."
    T "...Let's just say you owe us one, and that you'll promise not to interfere with oru relationship unless we {b}ask{/b} you to do something."
    H "Deal!"
    scene bg lockers with dissolve
    "With that arrangement now settled, the twins next start to ask us questions about how our date went, claiming that it's not \"interfering\ so much as \"catching up with friends\"."
    "Tanya is quick to shoo them out of the locker room whatever the case may be, citing our rapidly dwindling time allotted to morning training before we have to meet Sibyl for breakfast."
    "In the end, we really did lose so much time between Tanya'a tardiness and the twins' mischief that we just sit and chat until it's time to start off toward the cafeteria."
    scene bg cafeteria with dissolve
    S "How was training today?"
    "Tanya and I exchange a quick glance — much in the way that the twins do to my chagrin."
    T "Light."
    "That much is true, but I try to expand upon things a little bit for Sibyl's benefit, and speak around the truth a bit while I'm at it."
    C "We have an away game this afternoon so we don't want to wear ourselves out before then."
    S "You do? It's too bad I can't come along and cheer for our team."
    C "Maybe it's something you could bring up to the Student Council?"
    "Gears start turning in my head again, but they're soon stilled when I watch Tanya pop the strawberry off the top of her yogurt parfait for Sibyl to snap out of her fingers with her teeth."
    C "(Don't get jealous. Don't get jealous. They do this every day. Don't get jealous.)"
    "Though the chants echo in my head, an unwanted flutter still tightens my chest as I stare down the oblivious Tanya."
    "Whipping the strawberry off the top of my own yogurt parfait, I cheerfully hold it out to Sibyl, who eagerly snaps it off my fingers just the same."
    S "Two strawberries in one day! Yum!"
    "To my deplorable delight, Tanya shoots a gaze full of complex emotions my way."
    C "(You don't even {b}like{/b} strawberries!)"
    "I mentally ask Tanya, \"See how I feel?\", but choose not to meet her eyes in any way so that my actions remain innocent."
    "Sibyl remains content and happily oblivious throughout the short exchange, and fortunately it seems Tanya gets over her bout of jealousy as quickly as I do."
    scene bg hallway with dissolve
    "When we pass Miss Woolsey in the hallway between classes, she gives us a meek apologetic smile that I presume is to atone for her role in the interruption of our date."
    "With a particularly heavy-looking plastic bin in her hands, she does not stop to chat, but other girls do. One small group catches the three of us changing classrooms and stops to apologetically chat up Tanya."
    C "(Are those the same girls who were there when Miss Izzie interrupted our kiss?)"
    T "Go ahead, I'll catch up before class starts."
    S "Gotcha!"
    "It's only when we're safely out of earshot that Sibyl questions me about what all that might be about."
    C "I'll... tell you later."
    scene bg artroom with dissolve
    "I thought the worst fallout would be when it came to art class, but after setting us all up with what we need to continue our projects just Miss Izzie goes about her normal routine of hopping around each cluster of students to check on their work."
    C "Can I have a sheet of the green, Sibyl?"
    S "Here ya go!"
    "For a group project, me, Tanya, and Sibyl are all cutting shapes out to semi-transparent tissue paper which we plan to layer on top of one another."
    C "(It was Sibyl's idea, and I know way better than to question her about art stuff, but won't it all the colors just combine to be brown?)"
    "Everything goes exceedingly smoothly. We chat about classes and upcoming lacrosse games as usual while cutting out delicate colorful shapes, and I completely forget about Miss Izzie until she suddenly jumps in between us."
    mi "{b}-N-G!{/b}"
    "All three of us jump at the unexpected exclamation which cuts right through our casual conversation."
    mi "I'm sorry, I just had to finish it!"
    T "You never had to {b}start{/b} it in the first place."
    mi "Seriously, sorry, Tanya, and you too Clover. But when I saw you both... and in a tree too..."
    "Tanya and I both share a very slightly contemptuous look for Miss Izzie's apology, but settle with telling her to not do it again, to which she exaggeratedly swears on the Virgin Mary herself."
    S "Your entrance gave me quite a jump, Miss Izzie, and as you can see we're all holding scissors too."
    mi "Pshaw, these dull old things? Only good for cutting tissue paper!"
    mi "Trust me, I'm an {b}expert{/b} at scissoring!"
    "Now Sibyl has a turn to display her disapproval to Izzie, who shrugs her eccentric behavior off as she always does, with a round of heat pats for all us and a speedy exit toward the next group of students to check in with."
    S "What was that all about?"
    T "Miss Izzie being Miss Izzie."
    S "I meant when she was talking to you and Clover about a tree. What did she mean by that?"
    "Sibyl glances between me and Tanya while waiting patiently for an explanation. Given all the random apologies she's borne witness to today, we both quietly fill her in on exactly what happened in the tree during our date."
    "Much to my surprise and betrayal, Sibyl ends up being on Miss Izzie's side of the argument."
    S "If I say two of my friends kissing in a tree, I don't think I could hold myself back either!"
    jump datepart2

label datepart2:
    scene bg transition with fade
    scene bg bedroom with dissolve
    "With a big test to study for after dinner on Monday and lacrosse practice to attend after class on Tuesday, it isn't until a couple days later on Wednesday that Tanya and I get to part two of our first date."
    C "(So this is the part where we share the dark days of middle school with one another, huh?)"
    "It's still a terrifying prospect, to dig up and break open the casket of my middle school years which I thought I had buried for good, but if it's to get closer with Tanya I'll do it."
    C "(And I'm kinda curious about her drawings too...)"
    play sound doorknock
    S "Oh! There's Tanya!"
    play sound doorclose
    "I jump up from my bed to greet Tanya as she enters. We both pause in front of one another like we want to share a quick peck of a kiss like we did that morning after our date, but with Sibyl right there I feel it's too awkward, and maybe Tanya does too."
    S "Were you able to smuggle your smartphone here without any issue?"
    C "It's just down the hall, Sibyl..."
    "Before we even decided to meet up today, Tanya and I both agreed that we wanted Sibyl to be a part of this phase of our date."
    "Though we both want to have time for ourselves, we also don't want Sibyl to feel excluded now that we're dating."
    C "(Sibyl already knows about my dark past, but Tanya said she's never shared these drawings with anyone else here before.)"
    "I think of it as a display of how much we both appreciate and trust Sibyl, and how much we both still want her in our lives."
    C "Rock."
    T "Paper."
    C "Scissors."
    T "Shoot!"
    "I try to argue my case, but both Tanya and Sibyl firmly deny my assertion that rock totally beats paper because it can sit on top and pin it down."
    "My defeat assured, I pull my big box of shame out from under my bed and join my friends already gathered atop it."
    C "So, umm, I guess we'll start with this..."
    S "Ah, the {i}pièce de résistance{/i}! I've been wanting to get a good look at that!"
    "Sibyl, who has already caught a glimpse of the cringey photo of me and my friends from middle school once before, giddily claps her hands together. Her excitement only furthers Tanya's anticipation and fuel my apprehension."
    "Turning the photo frame around, I push it out in front of me and turn my head away, squinting my eyes against the coming ridicule."
    "None comes, however. Sibyl only giggles, while Tanya takes it out of my hands to inspect further."
    T "Which one is you?"
    C "You can't tell!?"
    S "Look, she's this one!"
    "Even after Sibyl leans over to point me out in the photo, Tanya still has to take several looks up at the current me and back down at the hideous past me."
    "Eventually I just snap and snatch the photo right out of her hand to bury deep in the box again, and replace it with the framed photo of Abraxas."
    C "That's enough photo time! Here, look at my dog Abraxas instead!"
    T "H-Hey, I wasn't done committing \"emo Clover\" to permanent memory!"
    C "I wasn't {b}emo{/b}, I was {b}goth{/b}! There's a {b}big{/b} difference!"
    "With as emphatically as I shout something so ridiculous back to Tanya, I should be thankful that only Sibyl breaks out into giggles and that the girl I'm trying to date manages to take me seriously."
    C "Besides, that \"me\" is long gone and is never coming back. I'd rather you just now know about it in the first place, but I promised to show you."
    T "Oh, stop— \"goth Clover\" is totally cute."
    S "Totally cute!"
    C "You were {b}just{/b} laughing at me, Sibyl!"
    S "Well, yeah, you did look goofy, but that's what makes it cute."
    "The frown on my face curls so hard I think I might end up permanently disfigured. Sibyl reaches out to mush my cheeks back into a normal shape before it sticks that way."
    T "Seriously, your middle school photo is cute. Maybe you've out-grown it since starting high school, but I think one day you'll look back and laugh fondly at the memories."
    C "No way! I'd sooner lobotomize the part of my brain storing those memories."
    T "I understand how you feel, but—"
    C "You can't have any idea how I feel unless {b}you{/b} had an equally mortifying middle school experience."
    T "I— I did."
    C "You did?"
    "Perhaps speaking too fast and suddenly regretting it, Tanya looks suddenly away, brushes a hand through her bangs, and leans back slightly away. Sibyl and I lean closer in response."
    T "I was a fat kid."
    C "What?"
    T "You heard me. I was {b}fat{/b} in middle school, so I know how it feels to want to forget big chunks of your past."
    S "I can hardly imagine it."
    T "Y-Yeah... but as painful as it is to remember how I was back then, I don't want to forget it because it makes me proud to see the results of all my hard work at the gym to get where I am now."
    C "So {b}that's{/b} how you got so strong!"
    T "I was really into dietary programs and strength training before I enrolled at Prudence Prep. There's no proper fitness center here so I mostly do calisthenics in addition to my training for lacrosse."
    "As I stare at Tanya as hard as I can but I just can't picture her any other way but the way she is now."
    C "Do you have any photos?"
    T "No!"
    C "Why not? I thought you were proud of how hard you've worked to change yourself."
    T "I am, but, you know, I don't want the girl I just started dating to see me looking so unpleasant."
    S "That's {b}so{/b} sweet!"
    "I have to agree with Sibyl. Tanya's words easily sweep all the hard feelings out of my heart and leave it mushy with her saccharine feelings."
    C "O-Okay, but you're still going to show me your manhua, right?"
    "Tanya nods her assent, and glad to be off the topic of her traumatic middle school years, fiddles with her smartphone while Sibyl and I gather closely around either side so we can see her screen better."
    T "S-So... this is the last manhua I worked on. It's probably the best, or at least, it's the one which was made when my art skills were the best."
    C "(Tanya is so cute when she's so anxious and on edge!)"
    S "What's it about?"
    "As the images load on her smartphone, we're greeted with a big title graphic that only Tanya among us can read."
    C "Let's start with what it's {b}called{/b}!"
    T "The title is {i}Heavy Love{/i}."
    T "The main character's name is Qiuyue. This is her—"
    "Past the title page, Tanya scrolls down to the first panel where we get a frame of the protagonist, who I presume to be a Chinese girl by her name and short, jet black hair."
    S "She's cute!"
    "I have to agree with Sibyl, and I do so aloud so that Tanya can hear it, as well as complement her artistic skills which are of course way above mine."
    C "So it's not a book? It's all this really long scrolly thing?"
    T "Yes. This is how most digital manhua is arranged."
    C "So I guess all the big white spaces between the frames is like a new page or something?"
    "Tanya continues scrolling through the first chapter, narrating text where necessary, though it is fairly easy to follow since it's just an introduction of the main character."
    "Qiuyue is a normal girl just starting out a new year at school. As she's getting dressed in the morning the day of the entrance ceremony, she pinches her chubby stomach with displeasure and swears to be skinny like a model."
    T "—And here's Clara. She's, umm, well, I did warn you that this was a baihe manhua, right?"
    "Clara is pretty foreign transfer student with wavy blonde hair and sapphire blue eyes. The frame when she first enters makes it quite clear that everyone, Qiuyue included, thinks she's just about the most beautiful person ever."
    C "(Maybe Sibyl can do {b}my{/b} hair that way too?)"
    S "Wow, she's all over her, huh?"
    T "Clara? Yeah, it's basically love at first sight for her. Qiuyue is {b}exactly{/b} her type."
    "The blonde foreign student shown immediate infatuation with the protagonist, to the point of getting way too close for strangers at her desk in front of the whole class."
    C "(Tanya really went all out with drawing those \"beauty sparkles\" around her!)"
    "As Tanya continues through the first chapter, it becomes clear why. Clara, a celebrity model from Norway is in China for a short term artistic residency, and is on a strict diet to kep her impossibly slim figure."
    "But, as Clara is quick to explain while following Qiuyue to where she intends to eat her lunch alone, she really loves soft chubby girls, and wants to feed Qiuyue all the foods she wishes she could eat."
    T "The main story of the work is how Qiuyue desperately wants to slim down while Clara conversely keeps pushing food on her."
    S "But, like, they're also lesbians?"
    "That much should be clear, I think, from the way Clara is shown squeezing Qiuyue's chubby thighs way too high up what is already a dizzyingly short skirt."
    T "Oh, yeah, they kiss and stuff later, but you probably don't want to see it."
    "Tanya quickly squeezes the side button of her smartphone to darken the screen as we finish the first chapter like she doesn't intend to go on to the second."
    S "I want to see it, Tanya! I've never seen you make any kind of artwork like this before."
    T "Even if there's a lot of kissing and other stuff?"
    S "I'm {b}fourteen years old{/b}, Tanya. I think I'll be fine seeing a drawing of cartoon characters kissing."
    T "R-Right..."
    "Tanya certainly doesn't look very sure at all about showing Sibyl more of {i}Heavy Love{/i}, but she gives in almost instantly when Sibyl pressures her for more."
    S "{b}After{/b} a quick break! Wait for me, please!"
    "Sibyl dashes off to the adjoining bathroom, leaving Tanya alone with me in a way that suddenly feels kind of awkward. Wanting to ease the mood, I dredge up something to break the silence."
    C "So... is Sibyl going to be okay with the \"other stuff\" in the later chapters?"
    "For just a moment, Tanya stares blankly at me with her mouth half open, obviously unsure how to answer my question."
    T "She might not even realize what's happening...?"
    C "So they do {b}that kind of thing{/b} with each other!?"
    T "They do it {b}a lot{/b}, after a few chapters. We might not even get that far."
    C "They do it, {b}a lot{/b}!?"
    T "I needed an outlet for my own frustrations, okay?"
    "With some amusement do I realize exactly what Tanya means while she's so aggressively defending her artistic work."
    T "But because of the weird rules about publishing this kind of thing in China, it's no graphic at all and actually drawn very... {b}metaphorically{/b}."
    C "Metaphorically?"
    T "Can we just drop it for now? I want to hear more about what you were like as a goth."
    "Like she's desperate to drop the conversation, Tanya quickly reaches for my box and digs around to pull out something random from within it to ask me about."
    T "What's this?"
    "Luckily for her, I am willing to wait until it's my turn to get her to show me whatever smutty stuff she drew in middle school."
    C "That's my oujia board!"
    T "What do you... do with it?"
    C "It lets you communicate with spirits of the dead. Here, I'll show you!"
    T "Thanks, but no. I don't need to hear my ancestors asking me why I haven't been married yet."
    C "That's never happened to me before."
    T "{b}You're{/b} not Chinese."
    C "I thought you {b}wanted{/b} to know what I was like in middle school?"
    "Tanya's resistance falls away quickly after I hit her with that unfair one liner, and the two of us sit on either side of the board from one another."
    "With our hands together on either side  and our heads turned down with respect for the dead, I start us off."
    C "Spirits near and far: the most kind and gentle among ye, we humbly solicit to speak."
    "After raising our heads, we release each others' hands only to each place one upon the planchette atop the board."
    C "So all we have to do is ask questions and the spirits will answer!"
    T "With the board?"
    C "Yeah, the planchette will move letter by letter to reveal the spirit's answer."
    T "Uhh, okay... you start."
    "Putting on a bit of a theatrical voice, I ask of the first spirit to speak to us."
    C "Come, gentle soul, and tell us your name!"
    "Both Tanya and I watch intensely at the planchette under our fingers as it begins to drift slightly between us."
    T "R... A... L... C... O..."
    C "Carol! Your name is Carol!"
    T "What?"
    C "R - A - L - C - O... It's an anagram!"
    T "The spirit is dyslexic?"
    "If I were back in middle school, I would totally be annoyed by how little Tanya \"gets\" the appeal of the ouija board, but now I only think her dry disbelief is amusing and totally \"Tanya\"."
    C "Now you try, Tanya. Ask her a question!"
    T "What should I ask her?"
    C "Just think of something easy."
    T "Oh, Spirit, tell us your favorite color!"
    "After Tanya asks the question aloud, we both concentrate on the planchette again, which moves once more to answer our questions."
    C "R... E... D... E..."
    C "Wait, you must mean \"red\"!"
    "I grin across to Tanya, but I can tell by the blank expression returned that I'm quickly losing her interest."
    C "(Give me a little helping hand here, \"Carol\"!)"
    C "I call upon ye, red-favored spirit of Carol, what must I do to to make Tanya a believer?"
    "This time, I help \"Carol\" along a little bit with a bit of subtle pushing."
    C "K... I... S..."
    C "I wonder what she's trying to say?"
    C "S... M... E..."
    "With an artificial gasp, I quickly look up to Tanya while continuing to play up the spooky encounter."
    C "What she's telling us... should we do it!?"
    T "\"KISS MEN\"? I {b}told{/b} you this would happen!"
    C "Huh?"
    "Looking back down to the board, the tricksy Carol must not like me interfering in her answer at all and played a trick on me by moving it again toward the \"N\"."
    C "No, no, she's not finished, see?"
    "Quickly, I nudge the planchette against toward the \"O\" and \"W\"."
    C "She says, \"KISS ME NOW\"! She wants to you to kiss me!"
    "From where my fingers rest next to Tanya's on the planchette, I crawl them up her fingers and onto her hand as I lean close to her over the ouija board."
    T "It sounds more like the spirit wants me to kiss \"her\", not \"you\"."
    "Much to my pleasure, Tanya doesn't dwell \"Carol's\" choice of words and instead happily meets my smooch. The plush meeting of our lips makes me feel just as electric and tingly as before."
    "Before I know it, I've become fully enraptured and fall ever deeper into Tanya."
    "The kiss never breaks but only gets more intense. I don't know exactly which of us starts it, but one second we're just smooching and the next we're full-on making out."
    "Without even opening my eyes, I carelessly brush aside the ouija board between us so that I can get even closer to Tanya, gripping her arm on one side, and bracing myself against her shoulder on the other."
    T "C-Clover..."
    "Hearing my name brush off Tanya's lips only stokes my fire to even greater intensity. A swift shift in equilibrium carries me fully horizontal without making any conscious effort to do so."
    "I think, with some small part of my mind not currently crammed full of Tanya, that it must have knocked her over with how far over the board when I was leaning into her."
    "The way Tanya next wraps her arms around my neck halts any such thoughts. Her strong arms rest heavily upon my back, locking me closely to her as he melt into one another."
    C "Mng, Ta... nya!"
    "My heart feels like's it's going to burst out of my chest with very passing moment."
    "I feel as though I might even faint, though that could be due to my paltry oxygen intake and not the way Tanya's chest brushes against mine or the way our legs entwine together to the detriment of how carefully I mad my sheets that morning."
    play sound doorclose
    S "I'm back, sorry that took so—"
    "The sound of Sibyl's voice is enough to make both of us currently getting tied closer together by the second suddenly freeze up."
    play sound doorclose
    "By the time we both extricate our faces far enough from each other to whip our heads toward the bathroom door, Sibyl's brown curls are already bounding back into the bathroom with a heavy slam of the door behind them."
    "..."
    T "You forgot about Sibyl!"
    "The heavy arms drop from my back to push up on my shoulders instead, keeping me atop Tanya at a safe distance for her to firmly accuse me of wrongdoing."
    C "{b}I{/b} forgot about Sibyl? {b}You{/b} pulled me down!"
    T "It was {b}you{/b} you started kissing me in the first place!"
    C "Nuh uh, that was {b}Carol{/b}, remember?"
    "Whoever might be at fault here, both of us scramble off the bed and line up outside the door to the bathroom to apologize to Sibyl and try to coax her out."
    S "S-Sorry... you can... ignore me..."
    "Her voice is terribly quiet even from behind the thick wooden door, which only makes Tanya and I all the more insistent that she comes out."
    "She does eventually, after some more pleading, and looking a bit warmer to her cheeks than usual. The awkwardness fades slowly but surely, and seen enough all three of us are laughing on my bed once again while I show off my tarot cards."
    scene bg bedroom night with dissolve
    "Tanya and I never do get back to what we started, however much I want desperately to be wrapped up in her arms once again."
    "It's not until I rest my head and close my eyes that my wishes are fulfilled by a very titillating dream which, upon waking suddenly, leaves me only wanting to have yet more of Tanya all to myself."
    jump after_date1

label after_date1:
    scene bg hallway with dissolve
    scene bg transition with fade
    scene bg black with dissolve
    "I meet Tanya for our morning training session the next day, memories of the taste and sensation of Tanya's lips still foremost in my mind."
    T "Good morning, Clover."
    "Tanya sneaks a quick glance this way and that before giving me a quick peck to the lips. It's become a part of our morning routine, and as much as I like it, it now only makes me restlessly want more from her."
    scene bg lockers with dissolve
    "I do not many any attempt to push her down like I want to, however, and we both continue to the locker room to change into our uniforms for our customary morning training session."
    scene bg lacrosse with dissolve
    "The lust bubbling up inside me fades as we push ourselves to the limit of our athletic abilities."
    C "Tanya's going hard this morning. Where did she {b}get{/b} this energy!?"
    "Not only do we double the amount of jogging around the track, but we also do ground ball drills, partner passing, parallel running toss all in the same morning."
    "I practically have to beg her to stop before we are forced to skip breakfast just to get to homeroom on time."
    scene bg lockers with dissolve
    "Just stepping into the locker room is enough to make my heart race increase after having just let it reduce following all our exercise."
    C "You've done this a bajillion times before, Clover. Don't be a creep."
    "Facing my locker, I stiffly withdraw my clothes while trying to push away the memories of how amazing it felt to have Tanya in my arms."
    "Still, I find myself peeking behind me, and catching a full glimpse of Tanya's reverse in all her sweaty, post-workout glory."
    C "(Tanya makes athletic underwear look {b}way{/b} too sexy.)"
    "Pulling myself around facing toward my own locker, I quickly change back into my uniform lest the absolute tragedy of missing breakfast should occur."
    "I feel like a complete and utter fool being so self-conscious around Tanya all of a sudden, but try as I might to fight it, I never win."
    C "(Is it because she's Chinese? Are they less weird about public semi-nudity there?)"
    "I feel like there are probably public baths there, and for that matter, Vittoria and Vincenza are probably used to that sort of thing too."
    C "{b}Those{/b} two probably parade around butt naked at gym class just for the heck of it..."
    "Having finished, I close the locker and spin around to tell Tanya I'm ready to go."
    C "All done! Ready to go, Ta—"
    "My speech pause mid-sentence when I notice Tanya leaning back against her locker, watching me as I turn to face her."
    T "Took you long enough."
    "She kicks off her locker and heads toward the door. I follow along, gears still turning in my mind."
    scene bg hallway with dissolve
    play sound doorclose
    C "(No, there's no way she was watching me...)"
    "The door opens, and as I walk through it, Tanya speaks up once again."
    T "You've been wearing cuter underwear lately."
    C "(So she {b}was{/b} watching!)"
    "I'm so flabbergasted that I don't even know what to say in response to that smirk she's showing me. I wish I could find something smooth or edgy to throw back at her an outright refusal."
    C "It's not like I'm doing it for you!"
    "I totally am more conscious about what I'm wearing lately, of course, so you might actually say I {b}am{/b} doing it for her."
    C "(But Tanya doesn't need to know that!)"
    C "I deserve French toast this morning, don't you think?"
    "I'm only teasing Tanya and fully expect her to lecture me about eating healthy as she normally does, but instead she simply agrees to what I say."
    T "You gave it your all out there this morning. You deserve it."
    C "Are you, \"gasp\", going {b}soft{/b} on me, Tanya? A little tongue and you'll agree to anything I want?"
    "Tanya gives me a slight sideways shove, which I pass right back around to her."
    T "Not a chance, but our calorie expenditure was way higher than normal this morning. You can afford to eat that French toast."
    C "Yeah, what's with that, anyway? You don't normally push us that hard."
    "We take a few more steps down the hallway toward the cafeteria in silence, while with each step Tanya looks off in the distance while playing with her hair."
    T "I had a lot of pent up energy this morning that I needed to get out of my system."
    scene bg cafeteria with dissolve
    pause 1.0
    scene bg classroom with dissolve
    C "(\"In triangle ABC, suppose D, E, and F are the midpoints of BC, CA, and AB, respectively. Prove that AD, BE, CF are concurrent.\")"
    C "(What the {b}heck{/b} does that even {b}mean{/b}!?)"
    "Half of math class vanishes into notebook three pages of triangles with lines drawn all through them and lots of capitalized letters all over, without me getting any closer to understanding what I'm supposed to be taught."
    "I know full well that Sibyl will teach me later in a manner much easier to understand, so it's without any surprise that I fall willingly right back into the warm fuzzies of remembering my time together with Tanya."
    T "I'm not made of sugar, Clover."
    C "W-Wha-!?"
    "Tanya's confusing whispers spoken across the desks startle me away from my daydreams and into the reality of my depressingly blank sheet of geometric proofs."
    "I don't even realize that Sibyl has momentarily walked away from our desk cluster until I look aside and no longer find her sitting next to me."
    T "You've been staring at me like you do your French toast on cheat day, for the last {b}fifteen minutes{/b}!"
    "I have since caught on to Tanya's mannerisms, so when she turns away and starts fiddling with her hair, I know she's feeling very bashful about my gaze upon her. Even if I wasn't aware I was gazing upon her at all."
    "After our little mishap with the ouija board the last time Sibyl stepped away we both promised to play it extra cool while she's nearby, but the opportunity to sneak in a little bit of whispered flirting is difficult to resist."
    show choice_darkness with dissolve
    menu:
        "\"You're sweeter than any French toast, Tanya.\"":
            hide choice_darkness with dissolve
            C "You're sweeter than any French toast, Tanya."
            T "I've {b}seen{/b} how you drench your French toast in maple syrup, Clover. I'm worried about your pancreas."
            "She might hide it behind snark, but know better now than before just how concerned Tanya probably actually is about my health."
            C "(If she didn't care, she wouldn't even pay it any mind.)"
            "It's like how yesterday morning she gave me that cute little kiss when we met in the morning, then immediately asked me if I was out of face wash because my pores were \"more clogged than her shower drain after Sierra is done with it\"."
            C "(If someone didn't know her, she might just come across as mean, but she took the time to walk me to the school store to pick up more face wash that same day.)"
            C "First you take my heart, and now you're worried about my pancreas!?"
        "\"I'm imagining devouring you like I do my French toast.\"":
            hide choice_darkness with dissolve
            C "I'm imagining devouring you like I do my French toast."
            "It's a risky gambit, to be going for something daringly suggestive, but I am most pleased to find Tanya react more with surprise at my unexpected reply than shock at how bawdy the thoughts are which have been occupying my mind."
            T "Did you not get enough yesterday? Clover, you glutton!"
            C "I'm following {b}your{/b} diet, remember?"
            T "Perhaps it's time to add a daily supplement of Vitamin T into your diet then. I wouldn't want you to become malnourished, Clover."
        "\"That's 'cause you're bread... a-and I'm gonna... beat you with eggs...\"":
            hide choice_darkness with dissolve
            C "That's 'cause you're bread... a-and I'm gonna... beat you with eggs..."
            "Whatever suave thing I thought I was trying to say never comes out quite right. I shut my mouth right up, but that doesn't stop Tanya from firing right back."
            T "Have I ever told you how moronic you sound sometimes?"
            C "Uhh, maybe like one or two... {b}hundred{/b} times!"
            C "But if anyone's to blame, it would be {b}you{/b}, Tanya."
            T "Me?"
            C "Yeah, you! Whenever I look at you, I'm struck totally dumb!"
            "By the way Tanya laughs off my comeback means it must have worked, so I mentally pat myself on the back for recovering after the initial stumbles."
            T "I may lose fifteen IQ points every time I'm near you, Clover, but I wouldn't have it any other way."
    "The mood between the two of us is good. {b}Really{/b} good. We both abandon our worksheets to lean on our arms toward each other across the desks, eyes locked onto one another."
    "A soft pressure brushes against my ankle under the desk and I move my leg aside instinctively, only for it to happen once again and continue to linger."
    C "(Ohhh!)"
    "A spark of recognition light up my brain when I realize what's happening. I'd tried to play footsie before with Sibyl during the time period I was trying to foolishly court her, and now it was being done to me."
    "I twist my ankle in response to press more of my foot flat against hers, but Tanya isn't going easy on me whatsoever. She quickly changes tack, instead brushing the front side of her shoe slowly up my calf."
    "This small contact initiated by Tanya is enough to send a shiver of excitement racing up my spine, or maybe it's the way her eyes bore into me half-lidded, and her lips curl into a transient grin when she spots my reaction."
    show sibyl talking with dd
    S "Three worksheets for homework, and they're {b}all{/b} proofs."
    "Sibyl returns from wherever she had disappeared off to, which was apparently to fetch our math homework."
    "In one respect, I'm glad to find that she also hates these proofs as much as I do, but in another I really wish she had noticed the mood happening between me and Tanya rather than disturb us."
    C "We'll {b}never{/b} have the time for another date if we keep getting this much homework!"
    "The exasperated exclamation is loose before I remember that I didn't want to talk about it publicly. Thankfully, Sibyl doesn't seem to mind all that much, and I don't care what anyone else in my class thinks even if they did overhear."
    T "It's not just classes, but we're just about the peak of the lacrosse season and I have art club too."
    S "Maybe you could quit art club so you can spend Thursday after class with Clover? I won't be around so you won't even have to be concerned about me at all."
    "Despite being the one to bring up the suggestion, Sibyl sports a terribly sour face as she glances between us after speaking it. The dark expression fades quickly when we both tell her that we both think Tanya should stay in art club."
    C "(I couldn't do that to Sibyl, and it wouldn't be fair to Tanya either.)"
    S "What about this Monday?"
    T "Oh, right, we'll have off all day, don't we?"
    C "Huh? There are no classes on Monday?"
    S "Monday is Memorial Day."
    "Glorious thoughts about sleeping in late and eating my breakfast in bed flood into my mind right away, but are soon enough chased out by a sudden and shocking revelation."
    C "M- {b}Memorial Day{/b}!? It's {b}Memorial Day{/b} already!?"
    T "Yeah...?"
    "Both Tanya and Sibyl apparently fail to understand what is causing me suc alarm given how alarmed their faces are in response to my alarm about the rapidly approaching \"unofficial first day of summer\"."
    C "Well, because..."
    "I want to blurt right out every last thing that is wrong with this and make them understand, but the anxiety about how they both don't feel the same as I do keeps me quietly brooding on the inside."
    scene bg dorm with fade
    "I keep quiet all through the rest of classes, the homework session together in the library, and through a late dinner, but the angst of the impending holiday remains niggling in the back of my mind throughout."
    C "Umm, Sibyl, I'm going to talk to Miss Woolsey real quick. I'll catch up with you back in the room?"
    S "Oh? Okay, I'll hop in the shower first while you're gone."
    "This is totally something that Sibyl would want to tag along for normally, but she must have noticed the quiet distress in my entire being despite having been trying to hide it."
    scene bg dorm with dissolve
    play sound doorknock
    mw "One minute!"
    "The sound of my teacher's voice rings out from behind her door, and though I expect to have sixty seconds to compose my thoughts, she instead swings open the door to her room in about five."
    mw "Clover! What can I do for you?"
    if secret_lilies_romance == "blanche":
        "Miss Woolsey arrives to her door, smartphone held aloft in one hand and the other clutching a stuffed orange cat plushie to her chest. She neither steps out nor invites me in."
        C "Umm, I just had a small question for you. Is now a good time?"
        mw "I always have time for my students, Clover! What's up?"
        "The plushie is delicately tossed back onto her bed and the phone moved behind her back, Miss Woolsey positioning herself in such a manner to prove she's ready to hear me out."
        C "Sibyl told me that we don't have any classes on Monday for Memorial Day."
        mw "Yup, it's a school holiday."
        "Miss Woolsey clearly expects this reply to lighten my face, but instead I only sink deeper into despair. I don't want to hear the answer to my next question, but it's something that I need to know."
        C "And... when does the school year end?"
        "With a certain degree of trepidation no doubt caused by my forboding demeanor, Miss Woolsey informs me how classes end in just about a month's time from today."
        C "(One month. Four weeks. Thirty days.)"
        mw "Is something wrong, Clover? I have the time to listen to whatever you need to say, I promise."
        "I want to stamp my feet and scream out in agony that there's absolutely no way I can possible leave the academy and my friends behind now, but not in front of Miss Woolsey after making such a scene to her about not wanting to be here at all on my first day."
        "My eyes glue to the ground in front of me, my feet resolutely planted in a clear sign that I'm not done yet. I stumble to start a few times but end up finding the strength to spit out the heart of the matter."
        C "But I only {b}just{/b} started dating Tanya..."
        "Silence reigns in the dormitory hallway for several long moments. I never specifically asked a question of Miss Woolsey, but the meaning of my statement is clear enough."
        phone "This sounds serious, Naomi. You can call me back later."
        "A woman's voice sounds softly through the electrical haze of the smartphone behind Miss Woolsey's back. The volume is quiet enough that she's clearly not on speaker, but loud enough that we both can hear her."
        mw "Blanche? You can hear us?"
        phone "It is quiet, but yes."
        "Miss Woolsey draws the phone back in front of herself, staring down at it with surprise and toggling speakerphone mode to prove it was off the whole time."
        mw "I'm sorry, Clover, I was talking to my girlfriend when you knocked and—"

    if secret_lilies_romance == "veronika":
        "Miss Woolsey arrives to her door, smartphone held aloft in one hand and the other clutching a stuffed orange cat plushie to her chest. She neither steps out nor invites me in."
        C "Umm, I just had a small question for you. Is now a good time?"
        mw "I always have time for my students, Clover! What's up?"
        "The plushie is delicately tossed back onto her bed and the phone moved behind her back, Miss Woolsey positioning herself in such a manner to prove she's ready to hear me out."
        C "Sibyl told me that we don't have any classes on Monday for Memorial Day."
        mw "Yup, it's a school holiday."
        "Miss Woolsey clearly expects this reply to lighten my face, but instead I only sink deeper into despair. I don't want to hear the answer to my next question, but it's something that I need to know."
        C "And... when does the school year end?"
        "With a certain degree of trepidation no doubt caused by my forboding demeanor, Miss Woolsey informs me how classes end in just about a month's time from today."
        C "(One month. Four weeks. Thirty days.)"
        mw "Is something wrong, Clover? I have the time to listen to whatever you need to say, I promise."
        "I want to stamp my feet and scream out in agony that there's absolutely no way I can possible leave the academy and my friends behind now, but not in front of Miss Woolsey after making such a scene to her about not wanting to be here at all on my first day."
        "My eyes glue to the ground in front of me, my feet resolutely planted in a clear sign that I'm not done yet. I stumble to start a few times but end up finding the strength to spit out the heart of the matter."
        C "But I only {b}just{/b} started dating Tanya..."
        "Silence reigns in the dormitory hallway for several long moments. I never specifically asked a question of Miss Woolsey, but the meaning of my statement is clear enough."
        phone "{b}The end of the school year doesn't have to be the end of your love! We're proof that long distance can work!{/b}"
        "A woman's voice sounds loudly through the electrical distortion of the smartphone behind Miss Woolsey's back. The volume is quiet enough that she's clearly not on speaker, but loud enough that she is definitely shouting on her end."
        mw "Veronika? You can hear us?"
        phone "Sure can! It's real quiet though."
        "Miss Woolsey draws the phone back in front of herself, staring down at it with surprise and toggling speakerphone mode to prove it was off the whole time."
        mw "I'm sorry, Clover, I was talking to my girlfriend when you knocked and—"
        phone "I've got this, Naomi! Put me on speaker so I can talk to her!"
        "Miss Woolsey nervously glances my way, but I nod my acceptance to hearing out her girlfriend. After all, it is precisely romantic troubles which I am having at the moment, and some reassurance would be welcome even if it's from a stranger."
        phone "Am I on speakerphone? Can you hear me?"
        mw "We can hear you, Veronika. You don't need to shout."

    if secret_lilies_romance == "izzie":
        "Miss Woolsey arrives to her door, clutching a stuffed orange cat plushie to her chest. She neither steps out nor invites me in."
        mi "Is that Clover? Your bed is big enough for a third."
        "Leaning slightly around my teacher at the door, I spot Miss Izzie lounging on Miss Woolsey's bed with a smug grin on her face which is soon smacked right off by a flying plushie direct to her face."
        mw "Ahhh, L'il Nika, I'm so sorry!"
        "Miss Woolsey immediately steps back toward the bed, but stops when Miss Izzie holds up the plush out to her."
        mi "Look, she's fine. Honestly, Nao-chan, who do you love more, Li'l Nika or {b}me{/b}?"
        "No answer is given, as apparently it is well known between them. Miss Izzie simply sets the plushie aside on the bed then hops off it to join us at the doorway."
        mi "Don't mind me."
        mw "Don't mind her. What's up, Clover?"
        C "Sibyl told me that we don't have any classes on Monday for Memorial Day."
        mw "Yup, it's a school holiday."
        "Miss Woolsey clearly expects this reply to lighten my face, but instead I only sink deeper into despair. I don't want to hear the answer to my next question, but it's something that I need to know."
        C "And... when does the school year end?"
        "With a certain degree of trepidation no doubt caused by my forboding demeanor, Miss Woolsey informs me how classes end in just about a month's time from today."
        C "(One month. Four weeks. Thirty days.)"
        mw "Is something wrong, Clover? I have the time to listen to whatever you need to say, I promise."
        "I want to stamp my feet and scream out in agony that there's absolutely no way I can possible leave the academy and my friends behind now, but not in front of Miss Woolsey after making such a scene to her about not wanting to be here at all on my first day."
        "My eyes glue to the ground in front of me, my feet resolutely planted in a clear sign that I'm not done yet. I stumble to start a few times but end up finding the strength to spit out the heart of the matter."
        C "But I only {b}just{/b} started dating Tanya..."
        "Silence reigns in the dormitory hallway for several long moments. I never specifically asked a question of Miss Woolsey, but the meaning of my statement is clear enough."
