label sunday_after_date:
    scene bg transition with fade
    scene bg black with dissolve
    "The day after our first date, Sunday, starts not at all goes as it normally does."
    scene bg bedroom night with dissolve
    "To begin with, I expected to have some really wild dreams after the really wild day I had with Tanya, but they all turned out to be extremely normal. All I dreamed about was laughing and climbing trees with Tanya."
    C "(I don't remember anything about what me and dream-Tanya talked about, but I remember I felt like I was having a good, and I think I she taught me how to climb trees for real...)"
    scene bg hallway with dissolve
    "My overactive imagination suddenly being normal-active was just the first oddity. Now, as I stand in the hallway outside the locker room waiting for Tanya to arrive for our customary morning training session, she isn't showing her face."
    C "(The birds are all flying from left to right! I hope Tanya is okay.)"
    "I turn away from the windows before I catch and glimpses of further bad omens, just to be safe."
    C "(She's probably just embarrassed to be seen after what happened yesterday. Yeah.)"
    "Thankfully, I see Tanya come walking down the hallway towards me soon enough, though easily over 20 minutes later than our usual meeting time. I run right up to her without delay."
    C "You're {b}late{/b}, Tanya! Is everything okay!?"
    T "I texted you this morning?"
    C "You did!?"
    T "Yeah."
    C "Guess I didn't see it."
    T "Everything is fine, Clover, and..."
    C "...And?"
    "Tanya suddenly goes quiet, eyes darting back down the hall then toward me, clearly anxious about something."
    C "(What is it? Is she being followed? Is there a ghost!?)"
    "My question is answered quickly enough, as Tanya darts forward to press a peck of a kiss to my surprised lips amidst a deep flush of bashfulness."
    T "Good morning."
    C "(What. Was. {b}That?{/b})"
    "Grabbing Tanya's shoulders, I shake her about a little just to be sure the image before me is real and corporeal."
    C "Where is the {b}real{/b} Tanya!? What have you done with her, skinwalker!?"
    "I feel around \"Tanya\"'s bewildered face for any seams or telltale signs that the Tanya I know has been replaced with this absurdly cute creature, but find only her flawless skin well-attached to her correctly-oriented skull."
    T "Clover, get ahold of yourself before I slap some sense into you!"
    C "(Whoa, false alarm! It's the real Tanya after all!)"
    C "Sorry, it's just... the birds were all flying left to right and you didn't show up on time..."
    T "What are you yammering about!? Was my kiss {b}so bad{/b} that you needed to freak out at me!?"
    C "No the kiss wasn't— Just forget I said anything about birds."
    C "Your kiss was nice, but, umm... unexpected. I wasn't ready for it."
    T "Are you... ready for it {b}now{/b}?"
    "I nod silently, and after a quick glance down the hallway to be sure no one is looking, we share another quick kiss that I can actually appreciate this time."
    C "(Who new a casual \"good morning\" kiss could be so electrifying?)"
    C "So... why were you late this morning anyway?"
    T "I, uhh, went to the chapel to offer thanks to God."
    C "You did!? What for!?"
    T "I recently realized that God has been using this extremely irritating but super hot girl to test my resolve, and that getting to make out with her recently must be my reward for putting up with all her bullshit."
    C "{b}Tanya!{/b} What the heck!?"
    "I turn and give her a soft punch to her shoulder as we slowly make our way to the locker rooms, which Tanya quickly mimics in tone with my name and punches me right back."
    C "I don't sound like that!"
    T "You {b}so{/b} do."
    scene bg lockers with dissolve
    "The good mood carried through as my badge into the athletic clubs' locker room, only to stop when we spot someone sitting out on the bench in what should normally be an empty locker room, clearly waiting for us."
    H "Good morning, Tanya."
    T "Ugh."
    "Tanya's displeasure at seeing Vittoria is clear. Just as I'm wondering where Vincenza might be, the sound of the door closing firmly shut behind us rings out, followed by her voice coming up behind Tanya."
    O "Did you think you could give us the slip that easily?"
    T "How did you even get in here? This locker room is only for sports club members."
    H "We have our ways..."
    O "More importantly, why didn't you {b}tell{/b} us you were going out with Clover?"
    "The twins slowly circle Tanya like sharks, taking turns addressing her sharply, while for her part, Tanya mostly takes it in stride with dismissive annoyance."
    C "(Is this {b}bullying{/b}? I thought they were friends!)"
    T "It's none of your business, Vincenza, or yours, Vittoria."
    O "That's \"Ouji-onee-sama\" to {b}you{/b}, Tanya."
    H "And don't forget your \"Hime-onee-sama\" either."
    C "(What the heck are they saying?)"
    H "You {b}knew{/b} we were trying to set you and Clover up."
    O "We {b}saw{/b} the {i}bacio alla francese{/i} yesterday."
    C "(Huh?)"
    H "How long have you and Clover been dating?"
    O "And why have you been keeping it from us?"
    "Having had quite enough of this grilling, I step forward to confront the twins."
    C "Back off! Tanya hasn't been keeping {b}anything{/b} from you; that was our {b}first{/b} date!"
    "Both Vittoria and Vincenza step back from Tanya in surprise, turning their attention with renewed interest toward me instead."
    C "(Oops.)"
    O "That was your {b}first{/b} date?"
    H "{b}Cataglottism{/b} so quickly?"
    C "(Why are they always throwing out weird foreign words around me!?)"
    "Thankfully, Tanya hits right back at them, drawing the twins' scrutiny once again."
    T "I know for a {b}fact{/b} that you've both done much more than French kissing without {b}any{/b} dates."
    H "We're only having a little fun when we do it."
    O "It's different when you have real feelings."
    H "You {b}do{/b} have real feelings for her, right?"
    "Perhaps catching on to what the twins are saying, I offer up myself as bait to take the heat off of Tanya, even if it means having the pressure placed back on me."
    C "I-I was the one who wanted to kiss, so stop being so mean to Tanya!"
    O "{b}Clover{/b} initiated it?"
    T "You can't honestly blame me. When a girl {b}that{/b} beautiful {b}asks{/b} for it, how could I possibly refuse her?"
    "The twins both glance my direction with a knowing smile, but thankfully do not say anything more to Tanya about what happened that day after Sibyl rejected me."
    H "Truly, it is impossible."
    O "We understand completely."
    C "Okay, so maybe I'm not ugly or anything, but I'm not really {b}that{/b} gorgeous, am I?"
    "All three of the girls in front of me exchange glances in complete silence, completely unable to meet my questioning scan of their faces."
    C "Are you saying all I have to do is flirt a {b}little bit{/b} and you'll all do {b}anything{/b} I ask?"
    T "...Maybe not {b}anything{/b}."
    "Tanya might be trying to downplay this new revelation, but the twins are less circumspect."
    H "Heavens forgive us."
    O "We've created a monster."
    "The twins quit circling Tanya and assume their standard posture side-by-side one another in a more casual stance. They even apologize to Tanya for assuming that she had been keeping them in the dark about an ongoing relationship between me and her."
    T "I wanted our relationship to develop at our own pace — {b}without{/b} any outside interference. We would have told you when the time was right."
    C "See!? Tanya had good reason not to have told you about our first date beforehand!"
    H "Did you really expect us to interfere with your date?"
    O "After how much we've been trying to push you toward one another?"
    T "You {b}did{/b} interfere with our date, didn't you?"
    "There's a certain sharpness to her accusation, clearly demonstrating how Tanya is still bothered by what happened while we were kissing on the tree limb."
    O "You never showed up to the meeting. We were honestly just trying to find out what happened to you."
    O "The Grand Macaron said we should give you both privacy when we did finally find you and Clover."
    C "Who?"
    "The twins, and most annoyingly, Tanya as well, just keep right on ignoring me. I don't try very hard to force myself into the conversation while I think this is all still part of their apologies, but I do get a little irked at teh behavior."
    C "(I feel like I deserve an apology too, considering I was also interrupted!)"
    H "But there really is no stopping Izzie when she's set in her mind."
    T "She's almost as bad as both of you."
    H "Oh, {b}please{/b}. Get her to tell you some of the tales from her heyday."
    O "So basically what we are saying is that it's not {b}our{/b} fault at all."
    T "What do you think, Clover? Should we accept their apology?"
    "Tanya finally sees fit to drag me back into the conversation — both by her question toward me and literally by pulling my arm to shift my body closer to her side."
    C "Maybe... one one condition."
    "The "